### ISSUE TITLE
Templates that require a structure.xml do not work

### ISSUE THREAD

**Issue by 2martens** [phpDocumentor/phpDocumentor#1000]
Whenever I try to use a template that has a structure.xml line in it's template.xml, the transformation stops with this message:

```
[DOMException]           
Invalid Character Error  
```

If I change to a template without a structure.xml line it does work like a charm.
I have tried it with abstract (with structure.xml) and responsive-twig (without).

**Comment by blackdrago** [comment]
I've been experiencing this with php 2.9, too. I know that my files are all UTF-8 encoded, yet nearly every template fails (except responsive-twig, and clean). I can't get the logging <paths> settings to work (though the level setting does) and I can't find where phpdoc sends its log files (not in /tmp/ for example).  Even when running phpdoc -v, I can't really tell what's happening. 

However, I believe this may not be related to character encoding at all, but instead related to XML's name requirements (namely, they cannot be/start with a number, among other things). I can't be 100% certain, but I thought I'd mention the possibility just in case.

Below is the output I could gather with phpdoc -v.

...
Execute transformation using writer "xml"

  [DOMException]
  Invalid Character Error

Exception trace:
 () at /usr/share/pear/phpDocumentor/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php:218
 DOMElement->__construct() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php:218
 phpDocumentor\Plugin\Core\Transformer\Writer\Xml->buildFile() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php:142
 phpDocumentor\Plugin\Core\Transformer\Writer\Xml->transform() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Transformer/Transformer.php:312
 phpDocumentor\Transformer\Transformer->applyTransformationToProject() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Transformer/Transformer.php:275
 phpDocumentor\Transformer\Transformer->transformProject() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Transformer/Transformer.php:141
 phpDocumentor\Transformer\Transformer->execute() at n/a:n/a
 call_user_func_array() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Console/Output/Output.php:59
 phpDocumentor\Console\Output\Output->writeTimedLog() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Transformer/Command/Project/TransformCommand.php:206
 phpDocumentor\Transformer\Command\Project\TransformCommand->execute() at /usr/share/pear/phpDocumentor/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Command/Project/RunCommand.php:275
 phpDocumentor\Command\Project\RunCommand->execute() at /usr/share/pear/phpDocumentor/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /usr/share/pear/phpDocumentor/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/pear/phpDocumentor/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /usr/share/pear/phpDocumentor/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /usr/share/pear/phpDocumentor/src/phpDocumentor/Application.php:183
 phpDocumentor\Application->run() at /usr/bin/phpdoc:24

**Comment by mvriel** [comment]
In phpDocumentor 3 we have removed the XML based templates in favour of a new 'default' template; I recommend trying it out!
