### ISSUE TITLE
Read more specific object class names from function/method signature

### ISSUE THREAD

**Issue by cweiske** [phpDocumentor/phpDocumentor#1060]
Some class names are really long, e.g. `Companyname_Project_Package_Extension_Model_Foo_List`. Putting them in `@param` makes the docblock unreadable.

I suggest that it should be possible to simply use `object` as type in the docblock, and phpdoc reads real class name from the method/function signature:

```
/**
 * Does something
 *
 * @param object $bar A Bar object
 *
 * @return void
 */
function foo(Bar $bar)
{
}
```

phpdoc should show `$bar` to be of type `Bar`.

This should only happend when `@param` is of type `object` and the type in the method signature is a specific class name.

**Comment by jaapio** [comment]
I think this is not relevant anymore, if somebody wants to have this feature anno 2024, please create a new ticket
