### ISSUE TITLE
No markdown except in template "clean"

### ISSUE THREAD

**Issue by fi5er** [phpDocumentor/phpDocumentor#1064]
Using the phar file (version 2.1.0), markdown formatting seems to be ignored everywhere, except in the "clean" template.

I _could_ use the "clean" template, but there are other issues with it:
- it seems to rely on Ajax, even for local files
- there is no file list

The lack of a file list is a problem for us, because without it, we cannot document stand-alone scripts (like build scripts, init scripts, config files, etc). Scripts like that usually only have the file-level doc block and maybe some constants or functions. Apparently a script _must_ contain a class, or the file-level doc block won't be accessible with the "clean" template.

Other templates (like "zend" or "new-black") do have file lists, but no markdown, in addition to other errors which are probably already known.

**Comment by mvriel** [comment]
With phpDocumentor 3, we have abandoned all XSL based templates. All existing templates now support markdown
