### ISSUE TITLE
Feature request: @method support for referencing magic methods

### ISSUE THREAD

**Issue by aimfeld** [phpDocumentor/phpDocumentor#1085]
After doing some research and asking on stackoverflow for a [way to reference magic methods](http://stackoverflow.com/questions/20189400/how-can-i-reference-magic-methods-with-phpdocumentor), and this seems currently not possible.

PHP frameworks use a lot of magic methods which poses a problem for IDEs since they have no easy way of linking method calls to the magic method implementation.

In ZF2 for example, controller plugins and view helpers are implemented with __invoke. These magic methods are documented with the `@method` tag (e.g. [view helpers](https://github.com/zendframework/zf2/blob/master/library/Zend/View/Renderer/PhpRenderer.php)). However, IDEs like PHPStorm can only link the method calls to the `@method` tag, but not to the magic method __invoke directly.

Instead of documenting a viewhelper like BasePath like this

```
@method \Zend\View\Helper\BasePath basePath($file = null)
```

I think it would be helpful to be able to document it like this

```
@method basePath \Zend\View\Helper\BasePath::__invoke
```

Return types and parameters of the basePath() function could be determined from the __invoke method's phpdoc directly without repeating them in the `@method` tag. Also, it would be easier for IDEs to directly link to the magic method. Maybe it would be better to introduce a new tag instead of supporting an alternative usage for the `@method` tag?

Any thoughts on this idea?

**Comment by TomasVotruba** [comment]
This is probably already resolved, right?

**Comment by Artistan** [comment]
if this is resolved, how do you handle magic static method calls to non-static methods of an instance of another class?  this happens a lot in laravel.

**Comment by TheColorRed** [comment]
I am not sure if this has been resolved, or if there has been any discussion on it

Here is what I think would be a nice way for describing a method.

As seen here, we describe how the method should be called. In this example it should be called without the prefixed `scope`.

```php
class A extends ClassWithMagic {
    
    /**
     * @called MyMethod
     */
    public function scopeMyMethod() {}
}
```

Just an example of what the the extended class might look like:
```php
class ClassWithMagic {
    public function __call($name, $args){
        $func = 'scope' . $name;
        $this->$func($args);
    }
}
```
