### ISSUE TITLE
The new website looks awesome! one hope for the 'creating templates' section that's still in development..

### ISSUE THREAD

**Issue by arkadianriver** [phpDocumentor/phpDocumentor#1091]
I love the 'clean' template and plan to modify it for my CakePHP project, which doesn't use namespaces, only folders. So, I'd like to change the long unsorted list on the left and organize it to expand/collapse based on the MVC folders of the CakePHP project.

The thing I hope to learn when reading the documentation about templates is where the data for the Twig files comes from so that I can determine what I have to work with as I tweak things.

**Comment by mvriel** [comment]
We have a complete project dedicated to improving the documentation; this will also include new features in phpDocumentor 3 regarding the new `.phpdoc` folder where you can override specific twig templates instead of having to create your own. Due to this separate effort, I am closing this issue
