### ISSUE TITLE
Changes in Twig templates and copies have no effects

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#1114]
When I tried to modify the "clean" template I noticed that all changes in Twig templates ("clean" and "responsive-twig") have no effects, while changes in "responsive" (I guess the other XSL templates, too) works fine.

When I copy a template and make the changes in this copy, they have no effects, neither with Twig nor with XSL templates.

I'm using phpDocumentor 2.2.0 on Windows, installed via PEAR.

"clean" is a very nice template, by the way! Just some little changes and it'd be perfect for me ... :)

**Comment by nelson6e65** [comment]
If I update my custom template via composer the cached copy in the templates folders is refreshed? https://github.com/phpDocumentor/phpDocumentor2/issues/1257#issuecomment-43334148
