### ISSUE TITLE
Error while applying responsive template

### ISSUE THREAD

**Issue by sthitamishra1987** [phpDocumentor/phpDocumentor#1149]
Hi,

I am trying to use responsive template by the following command

phpdoc -d "project_directory path" -t "output_path" --template="responsive"

I get the following error : [phpDocumentor\Plugin\Core\Exception]  
  Specified DOMDocument lacks documentElement, cannot transform.  
  Apparently an error occurred with reading the structure.xml file, the reported error was "Extra content at the end of the document" on  
  line 76107 

But when I try with phpdoc -d "project_directory path" -t "output_path" it by default uses responsive-twig template and woks fine

Thanks & Regards,
Sthitaprajna Mishra

**Comment by jaapio** [comment]
We dropped xml support, so this issue can be closed. Not relavant anymore for v3.
