### ISSUE TITLE
annotation not properly displayed

### ISSUE THREAD

**Issue by flip111** [phpDocumentor/phpDocumentor#1150]
I'm using this annotation

```
 * @AccessorOrder("custom", custom = {
 *      "id",
 *      "type",
 *      "selectedAttributes"
 * })
```

from here: http://jmsyst.com/libs/serializer/master/reference/annotations

and in the documentation it looks like this:
![image](https://f.cloud.github.com/assets/2244480/2435739/7682ca12-adce-11e3-9a23-7f2826f0dbd3.png)

**Comment by jaapio** [comment]
This has been resolved in v3.
