### ISSUE TITLE
Documentation left sidebar navigation does not retain state

### ISSUE THREAD

**Issue by flip111** [phpDocumentor/phpDocumentor#1151]
When expanding left sidebar navigation and then clicking one item the whole sidebar is retracted again on the next page.

Two possible solutions:
1. catch the click even with javascript and append a query to the URL that stores information about the state of the menu. Then use this information on the next page to recreate the menu state.
2. use sessionStorage https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#sessionStorage

**Comment by mvriel** [comment]
No longer relevant in phpDocumentor 3; the TOC no longer uses javascript nor does it contain all elements in the project. This makes the sidebar less complex, all files faster to render and reduce the amount of diskspace needed significantly
