### ISSUE TITLE
Regular text incorrectly parsed as Markdown

### ISSUE THREAD

**Issue by Kapeli** [phpDocumentor/phpDocumentor#1198]
Something like this:

``` php
/**
 * Sets the bubbling behavior.
 *
 * @param  Boolean $bubble true means that this handler allows bubbling.
 *                         false means that bubbling is not permitted.
 * @return self
 */
```

Gets generated to:

![screen shot 2014-04-04 at 17 28 34](https://cloud.githubusercontent.com/assets/1445635/2616332/6d3264c8-bc05-11e3-8660-d18fe35d7fdb.png)

I think the Markdown parser thinks the whitespaces before the `false` are meant to define a code block in Markdown.

**Comment by dipakmdhrm** [comment]
So, this is still an issue.

What is everyone's thoughts on completely preserving everything in the text comment.
i.e. no markdown parsing, no php parsing. Just displaying it as it is.

**Comment by dipakmdhrm** [comment]
Umm... Now that I think about it, it will probably never display as it is. 
The comment in code editor will be displayed using a monospace font, whereas in documentation it will be displayed using a normal font and thus will look different.

**Comment by jaapio** [comment]
This issue has been resolved, not sure when :-) 

Tested with 3.4
