### ISSUE TITLE
Code block incorrectly recognised

### ISSUE THREAD

**Issue by Kapeli** [phpDocumentor/phpDocumentor#1205]
A comment like the one from https://github.com/jadb/cakephp-monolog/blob/master/Lib/Log/Handler/CakeEmailHandler.php#L5-L23, turns into:

![screen shot 2014-04-05 at 15 22 38](https://cloud.githubusercontent.com/assets/1445635/2622608/3428d5fa-bcbd-11e3-884d-603fc26a586e.png)

Some things to consider:
1. Might be worth allowing only fenced code blocks and stop identifying code blocks based on the number of whitespaces
2. Only allow code blocks if they're separated by a new line at the top (GitHub does this afaik).

The problem with both approaches is that if you stop identifying the code block, everything gets to be on one single line (no `<br>`'s are added)

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
