### ISSUE TITLE
Command-line option defaultpackagename

### ISSUE THREAD

**Issue by toxalot** [phpDocumentor/phpDocumentor#1210]
Does this option do anything at all at the moment? It doesn't seem to affect the output of any template. Its value does not appear to be written to structure.xml.

What is it supposed to do? I've read the docs, but don't really understand what affect this should have.

> This option changes the name of your ‘default’, or nameless, package to that of your preference. This way you can, for example, change the default package name to the name of your application.

I think I am going to design my own template because I need a combo of features from several different templates. I can think of a few things that the default package name might be useful for.

It could be used as the name of the "top level" package in a template based on responsive-twig. It could be used in place of the "global" package in a template based on abstract. In both those cases, it would need to be set to something that is not already used as a package name.

But then it could also be set to a package name that already exists, and that could be the first page that loads.

I'm in the process of removing `@subpackage` from my DocBlocks and using a delimited `@package` value. Depending on how the _defaultpackagename_ option is supposed to be used, I may decide to use a different naming scheme.

**Comment by jaapio** [comment]
Is there, works like expected.
