### ISSUE TITLE
Inline @see and @link tags not working

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#1213]
@FlorianWolters wrote:

Neither inline `@see` nor inline `@link` are working with the `responsive` template in v2.4.0. The documentation states:

> The effects of the inline version of this [**@link**] tag are not yet fully implemented in PhpDocumentor2. There’s only URI support (i.e. no support for Structural Elements), and even that is available only in long descriptions. This is a known issue that is sure to be fixed before the final release of PhpDocumentor 2.0.

So I would recommend to re-open this issue. A simple `{@see ClassName}` isn't rendered in the output.

**Comment by ksimka** [comment]
According to this issue 'see' tag has inline syntax, but there's nothing about this feature in docs  http://www.phpdoc.org/docs/latest/references/phpdoc/tags/see.html

If I get it right, guys from the PhpStorm team are still waiting for official docs to support inline 'see' tag — https://youtrack.jetbrains.com/issue/WI-24525 . So could you please update the docs so we can force those guys to implement inline 'see'?)

**Comment by Flexo013** [comment]
@mvriel 
Giving this another bump as inline `{@see ...}` should really just work as it does in the description.

**Comment by yoosefi** [comment]
I have to agree with @Flexo013 , inline should work regardless of where it appears (summary or not).

**Comment by jaapio** [comment]
Please note that you are replying on a issue that has been closed for years, and reported on phpdocumentor v2.6 which is not maintained anymore. 
I would highly recommend you to give the v3-rc a try, and open a new issue if the issue is still present. So we can have a look when needed.

**Comment by thebigb** [comment]
Can confirm this is still an issue with v3.0.0-rc.
