### ISSUE TITLE
responsive-twig does not work with non-classes

### ISSUE THREAD

**Issue by oshh** [phpDocumentor/phpDocumentor#1216]
Once again I have troubles with the responsive-twig template.

I have a file "mylib.php". For the first time, this file does not have a class inside, but is simply a collection of some useful helper functions.

``` php
<?
/**
* mylib
* @package lib
*/

/**
* this function does nothing  <= this line I can see
* and this line already is dropped and never shows up anywhere
* @param int bar  <= unfortunately, this gets dropped as well
* @return int
*/
function foo($bar) {
 return ++$bar;
}
```

If I go to the packages page (/classes/packages/lib.html), I do not find mylib.php as a file there inside the package lib, but all functions are already displayed in a list. This is not very nice, but I could cope with it.
But nowhere, the items @ param or @ return are displayed. I can cklick the function name (here: foo) but nothing at all happens. In other words: besides the very first line, all text gets dropped/hidden/ignored.

Since the behaviour of the template responive is much more behaving as I would expect it, I assume this is not a feature inside responsive-twig, but a bug.

**Comment by jaapio** [comment]
Support for responsive template has been dropped.
