### ISSUE TITLE
Please document the templates

### ISSUE THREAD

**Issue by bskendig** [phpDocumentor/phpDocumentor#1217]
It would be helpful if the documentation listed what templates are available, provided screenshots for what each one looks like, and explained the difference between them (because I understand some provide HTML while others output XML, and they differ in the kind of code they handle?).

http://www.phpdoc.org/templates has some screenshots, but doesn't even say what template each screenshot represents.

**Comment by bmartinGithub** [comment]
I see updates have been long to come, are there plans to release a PHP 7 stable build soon?

**Comment by benlk** [comment]
@bmartinGithub version 3 appears to be in the works with support for PHP 7: https://github.com/phpDocumentor/phpDocumentor2/releases

**Comment by jaapio** [comment]
Yes we are working on a new version of phpdocumentor. But due limited time the team has on the project we are not making progress as fast as we wanted to.

**Comment by mvriel** [comment]
phpDocumentor 3 is released; the docs still need some love but we have a separate project in Github to deal with that

**Comment by benlk** [comment]
Is that docs project https://github.com/phpDocumentor/phpdoc.org or something else?

**Comment by mvriel** [comment]
I track that at the organisation level, here: https://github.com/orgs/phpDocumentor/projects/5
