### ISSUE TITLE
Template Navigation Issues

### ISSUE THREAD

**Issue by space-mvc** [phpDocumentor/phpDocumentor#1221]
Firstly on the new Clean theme the left side navigation menu does not retain its position after you click an menu item.

When you click a link from the left menu the page changes and tree shrinks back to the default loosing you position in the menu tree, which is very annoying for big projects like mine.

Secondly on the same Clean Theme the packages menu seems to stay flat, and does not show any heirachy of package contents...

This is worthless like this, without the heirachy whats the point?

I have searched for hours to find an old original template working but cannot find it anywhere, just lots of half way there templates advertised on the phpdocs and github.

**Comment by jaapio** [comment]
The new template shipped with phpdoc v3 is worth trying.
