### ISSUE TITLE
Duplicate class names

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#1277]
I have several classes with the same name in my project. When phpdoc is generated, it links to only one file, with one class. 

I'm having the following comment blocks in the PHP file:

```
/**
 * Portal 
 *
 * Portal for admins
 *
 * @package Portal
 * @author  DirtyDutch
 * @copyright Copyright (c) 2014
 * @version     Version 1.0
 */

/**
 * Users Admin Controller
 *
 * This class facilitates the overview of users
 *
 * @package Portal\Users
 * @category Controllers
 * @version Version 1.0
 */

 class Admin extends MY_Controller {}
```

It links every class to the file 'Admin.html'. But it only displays one class in it.. Even when providing different package names

**Comment by jaapio** [comment]
Closing as this is not an issue we can solve.
