### ISSUE TITLE
Make making and debugging a Twig template easier

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#1279]
Currently Twig templates are cached for performance. This is good when running in production but causes confusion if you are developing a twig template because you don't see your changes unless you empty the cache folder.

When developing a template it should be made easier to enable a debug modus where the cache generation is disabled, the Twig Debug Extension is loaded and the `dump` Twig filter is enabled by enabling Twig's Debug option.

There is already code doing this in the Twig writer but it still causes a lot of confusion and should be simpler to enable

**Comment by brutalcrozt** [comment]
Somehow I (as a consumer) expect that when we use `--force` i will get immediate changes. At this time it not happen. Let me know if my perspective is wrong.

**Comment by jaapio** [comment]
We disabled twig cache, it doesn't have much impact on our speed.
