### ISSUE TITLE
Source Code View in "clean" template buggy

### ISSUE THREAD

**Issue by drakej** [phpDocumentor/phpDocumentor#1297]
I noticed that when I view source code output generated with the "clean" template that the result is a syntax highlighted file, however the line numbers are always cut off at 2.

So you see line 1 which is the <?php tag usually, and then line 2 which includes everything else. This makes the source code view half as useful since it doesn't include proper line numbers.

**Comment by jaapio** [comment]
fixed in phpdoc v3.
