### ISSUE TITLE
No source for functions not in namespace on "clean" template

### ISSUE THREAD

**Issue by drakej** [phpDocumentor/phpDocumentor#1298]
Another issue with the clean template. It generates source code buttons for globally namespaced functions that were parsed in the generation yet the buttons are dead. When you attempt to view the source nothing happens. I'm guessing this is a side effect of the fact that they are global functions and it can't figure out which file they came from. So it's a special case but assumptions of explicit namespacing and class encapsulation seems a bit dangerous.

**Comment by DaveWP** [comment]
I've looked at the problem and it seems the node collection associated with each function, constant does not contain the associated file name.  This leads to "blank" File entries when viewing the default namespace.

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
