### ISSUE TITLE
Zend template content div get pushed down

### ISSUE THREAD

**Issue by rockymontana** [phpDocumentor/phpDocumentor#1310]
![screenshot from 2014-06-04 13 26 19](https://cloud.githubusercontent.com/assets/330839/3172869/8eae4688-ebdc-11e3-93a6-45df4d63ce97.png)

The main content div get pushed down from the sidebar. 
I talked about this with mvriel on IRC a couple minutes ago.

**Comment by jaapio** [comment]
We dropped the support for the zend template after so many years. 

This issue is not relevant anymore.
