### ISSUE TITLE
global function not rendered/clickable in responsive-twig

### ISSUE THREAD

**Issue by gimler** [phpDocumentor/phpDocumentor#1346]
The function exists but is not clickable also no param and only one line of the comments are visible.

version 2.6.1

command

```
./bin/phpdoc project:run -f test.php -t test --template="responsive-twig" --title="Test" --force -vvv
```

example

``` php
/**
  * Counts the number of items in the provided array.
  *
  * @param mixed[] $items Array structure to count the elements of.
  *
  * @return int Returns the number of elements.
  */
 function count(array $items)
 {
 }
```

see also #1027

**Comment by jack126guy** [comment]
In v2.8.5 it works, but only on a namespace page, not a package page.

**Comment by jaapio** [comment]
Phpdocumentor v3 brings a lot of improvements. This is one of them with the new template
