### ISSUE TITLE
Invalid paths about source files

### ISSUE THREAD

**Issue by Surfoo** [phpDocumentor/phpDocumentor#1390]
I have an issue with the version 2.6.1, the path of my source files are wrong

**wrong path** : `docs/files/Api%2FAbstractGeocachingApi.php.txt`
and I fixed it by creating the directory "Api" and move the file :
**right path** : `docs/files/Api.AbstractGeocachingApi.php.txt`

You can reproduce the bug with this repository: https://github.com/Surfoo/geocaching-api

**Comment by soyuka** [comment]
Same error here, the @L3CC code doesn't fix it.

**Comment by Hrusdik** [comment]
Any updates on this issue ?

**Comment by SteveJobzniak** [comment]
This is still a problem. The `.txt` files with source code for classes get generated. But the `clean` template doesn't link properly to them. :-(

**Comment by SteveJobzniak** [comment]
Nevermind, I found the problem by looking in the JavaScript Console:

`XMLHttpRequest cannot load file:///home/foo/docs/output/files/Utilities.php.txt. Cross origin requests are only supported for HTTP.`

So I started a small http-server and tried the source code links again. It works. Excellent! Sorry for the wrong report above. I hope my tip helps others too.

**Comment by jaapio** [comment]
should be fixed https://github.com/phpDocumentor/phpDocumentor/pull/2919
