### ISSUE TITLE
v2.7.0 ignores default-package-name configuration setting

### ISSUE THREAD

**Issue by dleffler** [phpDocumentor/phpDocumentor#1402]
I compile using .xml configuration and with v2.7.0 the default package name is 'Default' instead of what I have set in the configuration file.  This was working back in v2.4.0 (skipped over other versions to get to 2.7.0)

**Comment by mvriel** [comment]
Unless I am mistaken this issue has already been fixed but apparently I didn't discover that this specific ticket should be closed.
