### ISSUE TITLE
referenced parameters not recognized

### ISSUE THREAD

**Issue by flack** [phpDocumentor/phpDocumentor#1406]
I have a docblock looking like this:

``` php
/**
 * Summary
 *
 * @param array &$args Parameter description
 */
public function test(array &$args)
```

This produces an error in the log to the effect that no documentation for `$args` was found. Also, in the rendered documentation (at least in `clean` and `responsive` themes) the `&` sign is not rendered in the signature, so that by reading the API doc you have no idea that this is a reference.

**Comment by samlev** [comment]
I agree with @flack - documentation should be explicit, and should allow `@param array &$var` (or similar).

**Comment by jaapio** [comment]
Fixed in v3 release:
![image](https://user-images.githubusercontent.com/1060433/144123849-8743a4ec-54e1-423c-8189-6a518c6c782e.png)
