### ISSUE TITLE
Consider adding a sniff command

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#1421]
phpDocumentor2 has the ability to act as a PHP_DocSniffer (the documentation variant of PHP_CodeSniffer) where we detect how well your project is documented and what to improve. It might be a good thing to make this more obvious by introducing a new Sniff command that would provide the user with the ability to just scan for issues and output any error found, or output it to a checkstyle XML files.
- [ ] Add new 'sniff' command
- [ ] Re-use output style 
- [ ] Add same command line options from PHP_CodeSniffer
- [ ] Add support for 'ruleset.xml' configuration files that contain standard definitions
- [ ] Exit with exit code 1 if an error is found

> Please note: in #40 we have added support for Rules and Rulesets

**Comment by GaryJones** [comment]
PHPCS and related packages already have some standards / sniffs that focus on DocBlocks and comments.

Would it not be better to let PHPCS sniff the code (Docs), and let phpDocumentor generate the documentation?

**Comment by jaapio** [comment]
Closing, we will not address this in phpDocumentor
