### ISSUE TITLE
filesource issue: failed to open stream: No such file or directory in pear\PhpDocumentor\src\phpDocumentor\Descriptor\Example\Finder.php on line 125

### ISSUE THREAD

**Issue by tobiaspm** [phpDocumentor/phpDocumentor#1438]
Dear developers,

I got the warning message below when I run the phpdoc and I can see Loading… when I open the source on my documentation.
I used the phpdoc 2.7.0

failed to open stream: No such file or directory in pear\PhpDocumentor\src\phpDocumentor\Descriptor\Example\Finder.php on line 125

**Comment by mvriel** [comment]
Hi @tobiaspm, have you been able to test this?

**Comment by jaapio** [comment]
Closing because this issue is quite old. 
phpDocumentor has been changed a lot.
