### ISSUE TITLE
Markers output unusable with default configuration

### ISSUE THREAD

**Issue by hschletz** [phpDocumentor/phpDocumentor#1443]
According to the documentation, the "TODO" and "FIXME" keywords should be interpreted as markers by default. However, if I don't explicitly configure any keywords, _every_ inline comment ("// ...") shows up in the "Markers" section (using "Clean" template), regardless of content.

When I set markers explicitly via the -m command line option, output is as expected.

**Comment by turbo2ltr** [comment]
This is still seems to be an issue with 2.9.0
Every single comment that starts with //, even if it follows code on the same line, shows up in the marker report.
Had to manually add to my `phpdoc.xml` file:
```
<markers>
	<item>TODO</item>
	<item>FIXME</item>
</markers>
```
