### ISSUE TITLE
Argument $[varname] is missing from the Docblock of [methodname]

### ISSUE THREAD

**Issue by nikita240** [phpDocumentor/phpDocumentor#1460]
I get the following errors with 2.8.0:

```
Parsing /var/www/app/controllers/Controller.php
  Only one @package tag is allowed
  Argument $action is missing from the Docblock of __construct
  Argument $model_loc is missing from the Docblock of requireModel
```

The `@package` bug is already well documented [here](https://github.com/phpDocumentor/phpDocumentor2/issues/1339).

Here is the [source code](https://gist.github.com/Nikita240/fc460428155f0fb55401) of the php file I am using for reference.

It seems that phpdoc doesn't "see" the first `@param` tag in a DocBlock. For example, let's take a look at my constructor:

```
/**
 * Constructor simply initializes the class properties.
 * 
 * @param string $action The name of the action to be executed.
 * @param array $get_vars Array of urlencoded GET variables (usually just the $_GET array).
 */
public function __construct($action, $get_vars)
```

Phpdoc has no complaints about the `$get_vars @param` tag, yet the `$action @param` tag (the first `@param` tag) is invisible to it. 

I downgraded phpdoc to 2.7.0 and it did **not** have this problem. This is strictly a 2.8.0 issue.

**Comment by thefeldkircher** [comment]
I downloaded 2.8.1 this week and this problem still exists, what do I need to do?

**Comment by JacobCZ** [comment]
@thefeldkircher Well, you can use the workaround i "invented" :D (Remove the line beginning asterisks, like this)

```
/**    
  The <b>main</b> method, that actually changes the name's suffix.
  @param string $name Name you want to process.
  @param string $gender Gender of the name (male|female|neutral(default)).
*/
```

But that's temporary... I'm waiting for the fix as well...

**Comment by tschallacka** [comment]
Same here. So its the asterisks here eh.

**Comment by JacobCZ** [comment]
Srsly guys, you should fix this finally...

**Comment by mvriel** [comment]
@JacobCZ I understand your frustrations but due to personal circumstances I have had to reduce the amount of work that I can do on phpDocumentor. My apologies for the delays and kind regards

**Comment by rivets** [comment]
Quick fix 
In IsArgumentInDocBlockValidator.php change the line

$index = $value->index;

to say

$index = $value->index == '' ? 0 : $value->index;

**Comment by clonemeagain** [comment]
@rivets Thanks!

**Comment by JacobCZ** [comment]
@rivets Do you think you could create a pull request and convince the author to use the fix? :wink:

**Comment by trasher** [comment]
:+1: @JacobCZ  that would be great to have this one fixed :)

ping @rivets @mvriel

**Comment by JacobCZ** [comment]
:+1:

**Comment by chrizz1001** [comment]
Fix from @rivets works for this. When it will be implemented?
I use the (last) tarball version of documentor

**Comment by jaapio** [comment]
If you are able to create a PR for this issue I can have a look

**Comment by trasher** [comment]
PR opened with verbatim original fix proposal:
https://github.com/phpDocumentor/phpDocumentor2/pull/1814

**Comment by navii1991** [comment]
still getting the error in version 2.9.0

**Comment by paragajency** [comment]
Still getting the error with v 2.9.0 Argument $args is missing from the Docblock of functionaname

**Comment by navii1991** [comment]
@paragajency  yes i m getting the error in v2.9.0

**Comment by dtoro** [comment]
Still getting the error in v2.9.0

**Comment by mattiasghodsian** [comment]
I also have the error in v2.9.0

**Comment by gweller22** [comment]
I also have the error in v2.9.0

**Comment by leeIco3** [comment]
I also have the error in v2.9.0

**Comment by hansworschd** [comment]
I also have the error in v2.9.0
