### ISSUE TITLE
problem with phpdoc in Symfony2 and Ant

### ISSUE THREAD

**Issue by duderion** [phpDocumentor/phpDocumentor#1464]
hi Guys,

i installed PHPdoc via Pear, as described on the Webpage
and in every directory, it seems to work beside the root folder of my Symfony2 folder, where i wanted to use it together with Ant to generate my php documentation. There seems to be a namespace confusion or similar.

the failure is:

:/var/cache/git/sf2$ phpdoc
/usr/share/php/phpDocumentor/src/phpDocumentor/Bootstrap.phpPHP Fatal error:  Class 'phpDocumentor\Application' not found in /usr/share/php/phpDocumentor/src/phpDocumentor/Bootstrap.php on line 63

in a randomly different folder, it works:
/var/cache/git/sf2/output$ phpdoc
/usr/share/php/phpDocumentor/src/phpDocumentor/Bootstrap.phpCollecting files .. OK
Initializing parser .. OK
Parsing files
[Exception]
No parsable files were found, did you specify any using the -f or -d parameter?

Any ideas ?

Greets
Adrian

**Comment by port22** [comment]
I also have the same problem, installed via PEAR.

```
Fatal error: Uncaught Error: Class 'phpDocumentor\Application' not found in /usr/local/lib/php/phpDocumentor/src/phpDocumentor/Bootstrap.php:63
Stack trace:
#0 /usr/local/bin/phpdoc(23): phpDocumentor\Bootstrap->initialize()
#1 {main}
 thrown in /usr/local/lib/php/phpDocumentor/src/phpDocumentor/Bootstrap.php on line 63
```
although:

```
ls -al /usr/local/lib/php/phpDocumentor/src/phpDocumentor
total 80
drwxr-sr-x 13 root staff 4096 Aug 28 08:09 .
drwxr-sr-x 4 root staff 4096 Aug 28 08:09 ..
-rw-r--r-- 1 root staff 9692 Aug 28 08:09 Application.php
```

> I'd look at include_path

Can you explain where to set what? Why can't the pear package handle that I wonder ...

**Comment by Anubarak** [comment]
Is there any solution on this? I have the same issue

**Comment by jaapio** [comment]
Not by installing phpdocumentor via pear. You can install phpdocumentor via composer or download the phar or zip file from github
