### ISSUE TITLE
Responsive Template's Public API Methods links incorrect

### ISSUE THREAD

**Issue by MarqD** [phpDocumentor/phpDocumentor#1488]
I get a 404 error message in my browser when I click on any of the side bar links for Public API methods on the index.html in the Responsive Template. 

Error message:
"Firefox can't find the file at /phpDocumentor2/output/classes/ArgvInput.html#__construct."

![screenshot_linkincorrect](https://cloud.githubusercontent.com/assets/9897258/5154427/390ef30a-725d-11e4-8752-8bd25c2702f2.png)

**Comment by jaapio** [comment]
We decided to drop the support for this template.
V3 will get a new template that supports all new features. With better customization options to create the skin you like. 

Feel free to contact us at any time when you have any questions or issues with phpdocumentor.
