### ISSUE TITLE
Template 'responsive-twing' not getting the child class DocBlock

### ISSUE THREAD

**Issue by kunalbhagawati** [phpDocumentor/phpDocumentor#1496]
Hi, I'm facing a weird problem, 'responsive-twig' seems to inherit only the parent class DocBlock and discards the child class DocBlock.

``` php
abstract Class Model {

    /**
     * Constructor for core\Model()
     *
     * Inititalizes
     * - Instance of RDBMS engine class
     * - Instance of Document Oriented DB engine class
     *
     * @see $_instanceRdbms
     * @see $_instanceDocument
     */
    function __construct(){
        $this->_instanceRdbms      =   StorageFactory::getInstance("RDBMS"); 
        $this->_instanceDocument   =   StorageFactory::getInstance("DOCUMENT"); 
    }
}


/**
 * Model for the others/locale submodule 
 */
class LocaleModel extends core\Model {

    /**
     * Initializes the class with instances of models\ValidateFields(), models\BusinessLogic(), models\DB(), models\Cache() and models\MQ()
     *
     * @see models\ValidateFields
     * @see models\BusinessLogic
     * @see models\DB
     * @see models\Cache
     * @see models\MQ
     * @return bool returns true 
     *
     */
    function __construct(){
        parent::__construct();
        $this->InstValidate = new models\ValidateFields();
        $this->InstBusinessLogic = new models\BusinessLogic();
        $this->InstDB = new models\DB();
        $this->InstCache = new models\Cache();
        $this->InstMQ = new models\MQ();
        return true;
    }
}
```

So when I run phpdoc this happens :
![2014-12-11-130028_1366x768_scrot](https://cloud.githubusercontent.com/assets/8683984/5390733/70821780-8136-11e4-9835-8fd678d7c9d2.png)

In case the writing is not clear, the model is 'others\locale\LocaleModel' but it only shows the DocBlock for 'core\Model'.
This is not the case with the 'clean' template, where it shows both the parent and the child DocBlock mixed together.

I attempted to find a way to shut down the inheritance but the official docs point to a dead link and the switches in phpdoc don't mention anything either. Am i missing someting?

In any case, thanks for this beautiful tool and keep up the awesome work!

**Comment by jaapio** [comment]
Template isn't supported anymore
