### ISSUE TITLE
Source Code Viewer Does Not Scroll To Method

### ISSUE THREAD

**Issue by axiom82** [phpDocumentor/phpDocumentor#1504]
Using the clean template, when opening the source code viewer for a class method, the viewer does not automatically scroll to the part of the script where the class method is located.  We are having to scroll down each time, which isn't as we expected.

**Comment by ezk84** [comment]
+1

**Comment by jaapio** [comment]
fix in the new default template https://github.com/phpDocumentor/phpDocumentor/pull/2919
