### ISSUE TITLE
PHP Warning:  array_shift() expects parameter 1 to be array, null given 

### ISSUE THREAD

**Issue by dogstarTest** [phpDocumentor/phpDocumentor#1533]
hi, i got this when i try to generate docs, here is the detail:

PHP Warning:  array_shift() expects parameter 1 to be array, null given in phar:///usr/bin/phpdoc/vendor/phpdocumentor/reflection-docblock/src/phpDocumentor/Reflection/DocBlock.php on line 204
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpdoc:0
PHP   2. require() /usr/bin/phpdoc:10
PHP   3. phpDocumentor\Application->run() phar:///usr/bin/phpdoc/bin/phpdoc:23
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/bin/phpdoc/src/phpDocumentor/Application.php:183
PHP   5. Symfony\Component\Console\Application->doRun() phar:///usr/bin/phpdoc/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/bin/phpdoc/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   7. Symfony\Component\Console\Command\Command->run() phar:///usr/bin/phpdoc/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   8. phpDocumentor\Command\Project\RunCommand->execute() phar:///usr/bin/phpdoc/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   9. Symfony\Component\Console\Command\Command->run() phar:///usr/bin/phpdoc/src/phpDocumentor/Command/Project/RunCommand.php:260
PHP  10. phpDocumentor\Parser\Command\Project\ParseCommand->execute() phar:///usr/bin/phpdoc/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP  11. phpDocumentor\Parser\Parser->parse() phar:///usr/bin/phpdoc/src/phpDocumentor/Parser/Command/Project/ParseCommand.php:224
PHP  12. phpDocumentor\Parser\Parser->parseFileIntoDescriptor() phar:///usr/bin/phpdoc/src/phpDocumentor/Parser/Parser.php:319
PHP  13. phpDocumentor\Parser\File->parse() phar:///usr/bin/phpdoc/src/phpDocumentor/Parser/Parser.php:359
PHP  14. phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildFileUsingSourceData() phar:///usr/bin/phpdoc/src/phpDocumentor/Parser/File.php:67
PHP  15. phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() phar:///usr/bin/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:111
PHP  16. phpDocumentor\Descriptor\Builder\Reflector\FileAssembler->create() phar:///usr/bin/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:142
PHP  17. phpDocumentor\Descriptor\Builder\Reflector\FileAssembler->addClasses() phar:///usr/bin/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php:65
PHP  18. phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() phar:///usr/bin/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php:137
PHP  19. phpDocumentor\Descriptor\Builder\Reflector\ClassAssembler->create() phar:///usr/bin/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:142
PHP  20. phpDocumentor\Reflection\BaseReflector->getDocBlock() phar:///usr/bin/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/ClassAssembler.php:56
PHP  21. phpDocumentor\Reflection\BaseReflector->extractDocBlock() phar:///usr/bin/phpdoc/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php:112
PHP  22. phpDocumentor\Reflection\DocBlock->__construct() phar:///usr/bin/phpdoc/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php:132
PHP  23. phpDocumentor\Reflection\DocBlock->splitDocBlock() phar:///usr/bin/phpdoc/vendor/phpdocumentor/reflection-docblock/src/phpDocumentor/Reflection/DocBlock.php:90
PHP  24. array_shift() phar:///usr/bin/phpdoc/vendor/phpdocumentor/reflection-docblock/src/phpDocumentor/Reflection/DocBlock.php:204

**Comment by jaapio** [comment]
Closing this, the bug itself might have been solved. But there is so much changed in 5 years that I do not think it is worth the effort to investigate this.
