### ISSUE TITLE
Class hierarchy diagram does not show on IE 11

### ISSUE THREAD

**Issue by kaloyan-raev** [phpDocumentor/phpDocumentor#1607]
The class hierarchy diagram is not displayed on Internet Explorer 11. The reason is that the version of JQuery iViewer bundled with phpDocumentor has an issue displaying SVG images on IE 11. The latest version of JQuery iViewer does not have this problem.

**Comment by kaloyan-raev** [comment]
Actually I was wrong. The issue also exists in the latest version of jQuery.iviewer: https://github.com/can3p/iviewer/issues/74

**Comment by jaapio** [comment]
IE11 is EOL
