### ISSUE TITLE
Bad path names for source code in WAMP

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#1649]
I have been running phpdoc 2.8.5 on my WAMP site and getting good results.

However, the source code links return a 403 error. When checking the paths that were produced, they include incorrect slashes and references to the drive letter and colon, which is encoded in the files/folders.

![capture](https://cloud.githubusercontent.com/assets/7675185/10035418/fac933cc-61ed-11e5-81ae-c9eb6312df34.PNG)

The path names in the various documents are like this:
`<pre data-src="../files/C:\wamp\www\site1\app\controllers\about.php.txt" class="language-php line-numbers"></pre>`

phpDocumentor was launched from within the C:\wamp\www\site1\api folder with the following command: 
`php ..\..\phpDocumentor-2.8.5\bin\phpdoc --sourcecode -d ..\ -t .\ --cache-folder .\cache`
Note I have also used the phar file with the same results.

Can these path names be corrected when executing on a Windows platform?

**Comment by AnrDaemon** [comment]
This is still an issue for 2.9.0.
`data-src` attributes are generated with backslashes.

**Comment by AnrDaemon** [comment]
This should fix the problem in 2.9.0.
[0001-Fixes-backslashes-in-data-src-source-references.txt](https://github.com/phpDocumentor/phpDocumentor2/files/1439608/0001-Fixes-backslashes-in-data-src-source-references.txt)

**Comment by jaapio** [comment]
phpDoc v3 has fully changed the file handling.
