### ISSUE TITLE
Double package tag on globals functions in files with a file docblock 

### ISSUE THREAD

**Issue by marcimat** [phpDocumentor/phpDocumentor#1675]
Hi, with phpdocumentor 2.8.5, there is sometimes 2 same packages found for 1 function in this case : 
- have a file  (with or without namespace) with a file docblok (with ou without package tag)
- have a global function into this file with a package tag.

Example : 

``` php
<?php
/**
 * file
 */

/** 
 * function test
 * 
 * @package demo
 */
function test() {}
```

The package is writen 2 times in the generated template for this function.
Without the file docblock, it is correct.

Maybe related with #1339

**Comment by mvriel** [comment]
Thanks for reporting this issue; this is a bug that should be solved

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
