### ISSUE TITLE
How would we document the return type of array_keys() ?

### ISSUE THREAD

**Issue by donquixote** [phpDocumentor/phpDocumentor#1737]
Array keys in PHP can be integer or string. And it can only be a string that does _not_ look like an integer.
In fact, PHP does some type conversion for array keys. Every array key that "looks like" an integer, be it `'1'` or `1.2` will be cast to integer.
I personally think this is stupid (for `1.2` at least), but here I just mention it as a side note..

The question is, how do we correctly document the type of those array keys with phpDocumentor? Sure, we can say `int|string`. But what if we want to append `[]`?
Should we introduce some kind of meta-type?

Example:

```
/**
 * @param array $array
 *
 * @return string[]|int[]|mixed[]
 */
function arrayGetKeys(array $array) {
  return array_keys($array);
}

var_export(arrayGetKeys(array(1 => 'one', '2' => 'two', 1.2 => 'one point two')));
```

`@return string[]` and `@return int[]` would both be wrong, because it can contain a mixture of strings and integers. `(int|string)[]` is currently not supported, afaik. `scalar[]` can also contain booleans and floats.

Any ideas?

**Comment by jaapio** [comment]
According to the PSR-5 draft document your suggestion of `(int|string)[]` is correct. However we will not at this as a new feature to phpdocumentor 2. I think we can support it in phpdocumentor 3. 

For now an description is required to the @return tag. to explain to the user that the return type can be mixed. 

I totally agree with you that mixing the return types is kind of strange. You might consider to cast everything back to a string? 

Sorry for the inconvenient answer. We are working hard to get phpdocumentor 3 at a acceptable level for its first release. But due limited resources this will take some time.

**Comment by donquixote** [comment]
Thanks for the reply.

I am always torn whether I should comment here on phpDocumentor, or on php-fig.
Imo, there is a need for documentation standards beyond just generating external documentation. The more important thing is (imo) code analysis by the IDE.
E.g. http://stackoverflow.com/questions/17445392/whats-the-best-way-to-document-intentional-switch-fall-through/17456155?noredirect=1#comment58481512_17456155 is something that has no place in phpDocumentor, but is still worth discussing.
On the other hand, not everything needs to go into a PSR immediately.

**Comment by donquixote** [comment]
And a new meta-type "key" would have a stronger meaning than just "int|string".
"int|string" also includes strings like "1", which can never occur as array keys.

**Comment by jaapio** [comment]
phpDocumentor v3 has been released since the last comment. And the world has changed. phpstan and psalm have introduced some extra types. I think we do not need this issue anymore.
