### ISSUE TITLE
PHPDoc returns 0 status even if it finds missing documentation when parsing files

### ISSUE THREAD

**Issue by julenpardo** [phpDocumentor/phpDocumentor#1748]
First of all, thanks for developing such an useful software engineering tool.

I've introduced PHPDoc in my build process, with the purpose of mark the build as failed if it founds errors like missing descriptions, or whatever. But I've noticed that doesn't return non-zero status even if it finds those errors.

I was wondering if this is the expected behaviour and, in that case, if it exists a way to determine these errors in an automated build process?

Kind regards,
Julen

**Comment by jaapio** [comment]
I like your suggestion, thanks for pointing that out. I would like to schedule this for phpdocumentor 3. Which will be backwards compatible. Since it will be very hard to integrate this in phpdocumentor 2.

**Comment by thomascorthals** [comment]
I'm trying to integrate phpDocumentor in a workflow as a Github action and I ran into the same issue. Even when errors are reported, the build step is marked as successful.

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
