### ISSUE TITLE
Best template to use?

### ISSUE THREAD

**Issue by kaysond** [phpDocumentor/phpDocumentor#1819]
I'm trying to find a template that doesn't have any issues... but no luck so far.

Abstract: Lists files, great, but is missing some class properties that show up in other templates. Also missing all "@see" tags.

Clean: Doesn't list files anywhere, which is needed for the file summaries for test scripts. Also has problems showing the source (either it complains about includes not existing or the file itself not existing).

new-black: same as abstract

old-ocean: same as abstract

responsive: no file summaries, also missing properties and @see tags

responsive-twig: same as responsive

zend: same as abstract

For all templates, I get no errors anywhere and checkstyle is empty...
I'm happy to help sort through things at some point, but am currently short on time and it would be nice to have something that works out of the box.

**Comment by mvriel** [comment]
There have been efforts to improve on the templates but this is a significant effort and we have limited resources, unfortunately; I have marked your suggestions as improvements to be made on the templates.

The default template, Clean, is currently the template with the largest feature set aside from the missing files listing. This is something we are aware of and agree that it should be added.

**Comment by mvriel** [comment]
In phpDocumentor 3, `default` is the new template that is meant to replace the rest. This template is actively maintained by the core team while the rest is on community support or best effort.
