### ISSUE TITLE
Fatal error - Uncaught TypeError thrown on initial start

### ISSUE THREAD

**Issue by MDT-FGI** [phpDocumentor/phpDocumentor#1857]
I am new to phpDocumentor and installed v2.9.0 via "PEAR". I followed the official introduction to install phpDocumentor. Installation ended successfully but when I want to generate the documentation, I get the following error:

> Load cache                                                         ..    2.205s
Preparing template "clean"                                         ..    0.174s
Preparing 17 transformations                                       ..    0.000s
Build "elements" index                                             ..    0.024s
Replace textual FQCNs with object aliases                          ..    0.136s
Resolve @link and @see tags in descriptions                        ..    0.013s
Enriches inline example tags with their sources                    ..    0.013s
Build "packages" index                                             ..    0.061s
Build "namespaces" index and add namespaces to "elements"          ..    0.002s
Collect all markers embedded in tags                               ..    0.003s
Transform analyzed project into artifacts                          ..
Applying 17 transformations
  Initialize writer "phpDocumentor\Plugin\Core\Transformer\Writer\FileIo"
  Initialize writer "phpDocumentor\Plugin\Twig\Writer\Twig"
  Initialize writer "phpDocumentor\Plugin\Graphs\Writer\Graph"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "twig"
[2017-06-13 14:32:06] phpDocumentor.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in H:\UwAmp\bin\php\pear\pear\phpDocumentor\vendor\monolog\monolog\src\Monolog\ErrorHandler.php:122 Stack trace: #0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error)) #1 {main}   thrown {"file":"H:\\UwAmp\\bin\\php\\pear\\pear\\phpDocumentor\\vendor\\monolog\\monolog\\src\\Monolog\\ErrorHandler.php","line":122} []
[.. LOADS OF LINES OF HTML ...]
Fatal error: Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in H:\UwAmp\bin\php\pear\pear\phpDocumentor\vendor\monolog\monolog\src\Monolog\ErrorHandler.php:122
Stack trace:
#0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in H:\UwAmp\bin\php\pear\pear\phpDocumentor\vendor\monolog\monolog\src\Monolog\ErrorHandler.php on line 122

The error appears when the final generation starts and all the HTML-stuff is shown on the cmd.
I used this command to initialize:
> phpdoc -d H:\UwAmp\www\ -t H:\UwAmp\www\Documentation

Please let me know what else I can provide in order to help you on tracking this issue.

**Comment by mark-101** [comment]
I am getting what seems to be exactly the same error on a new PEAR install of phpDocumentor 2.9.0
The environment is IIS 8.5 on Windows server 2012 r2 running PHP 7.0.19

**Comment by jaapio** [comment]
Can you try the installation via the phar file? And report back if you have any issues with that as well.

**Comment by mark-101** [comment]
Thank you, it works with the phar file installation.

**Comment by jaapio** [comment]
@mvriel think we need to repack the pear build. There was some Dependency mismatch in the past.

**Comment by BramVer** [comment]
Just ran into the same issue (PHP 7.1.10, Arch Linux) and I was about to look for a different library until I came across this.
Running the .phar file works for me.

Perhaps mention this in the documentation, even if it's only a temporary issue, since most users will follow the recommended install via Pear.

**Comment by oliveratgithub** [comment]
Same issue here – when do you think a fixed version will be available via pear?

**Comment by oleg-kosarev** [comment]
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Linux DESKTOP-4UOV9JE 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux (debian)

Applying 17 transformations
  Initialize writer "phpDocumentor\Plugin\Core\Transformer\Writer\FileIo"
  Initialize writer "phpDocumentor\Plugin\Twig\Writer\Twig"
  Initialize writer "phpDocumentor\Plugin\Graphs\Writer\Graph"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "FileIo"
  Execute transformation using writer "twig"
PHP Notice:  Array to string conversion in /usr/share/php/phpDocumentor/vendor/erusev/parsedown/Parsedown.php on line 894
PHP Notice:  Undefined property: Parsedown::$Array in /usr/share/php/phpDocumentor/vendor/erusev/parsedown/Parsedown.php on line 894
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /usr/share/php/phpDocumentor/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:122
Stack trace:
#0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in /usr/share/php/phpDocumentor/vendor/monolog/monolog/src/Monolog/ErrorHandler.php on line 122
[2018-07-29 08:04:20] phpDocumentor.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /usr/share/php/phpDocumentor/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:122 Stack trace: #0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error)) #1 {main}   thrown {"file":"/usr/share/php/phpDocumentor/vendor/monolog/monolog/src/Monolog/ErrorHandler.php","line":122} []

**Comment by jaapio** [comment]
Closing this, as we dropped support for phpDocumentor v2.
