### ISSUE TITLE
Tag @uses not creating link or generating @used-by for receiving method

### ISSUE THREAD

**Issue by jasonetwork** [phpDocumentor/phpDocumentor#1871]
I'm using the latest .phar to generate documentation. I am trying to utilize the @uses tag to link to a method located within the same class. When I generate the documentation, the method appears under the "Uses" heading, but does not contain any link. Also, no @used-by tag is generated for the receiving method. I've tried every combination to refer to the receiving method (generateToken(), self::generateToken(), AccessTokens::generateToke(), \Core\OAuth2\AccessTokens::generateToken(), etc.), but none of them are successful. 

Here is a sample of my code:

```
namespace Core\OAuth2;

class AccessTokens {
/**
 * Create a new access token
 * @param  UserInterface    $user        User Object
 * @param  ClientInterface  $client      Client Object
 * @param  DateTime 	    $expiration Timestamp of access token expiration.
 * @return array                        Returns an array with id and access_token keys
 * @uses Core\OAuth2\AccessTokens::generateToken() to generate the token string
 */
public function create(UserInterface $user, ClientInterface $client, DateTime $expiration){ }

/**
 * Generates a valid access token
 * @return string                        Returns access token string
 */
public function generateToken() { }

}
```
Is there a bug that is causing the link to not appear? It works fine if I'm using the @see tag (link is generated), but not with @uses. Any ideas?

**Comment by mbed67** [comment]
Hello! See also this issue: #920. I will pick this up soon.

**Comment by alien999999999** [comment]
So, i do see a proper link in @uses to the used method; but i do not see a used-by reference back...

**Comment by alien999999999** [comment]
after adding "@usedby Class::method() description" manually, it does show in the tags section, but no link to the original @uses is there (i think it's handling is much like an unknown tag; even the method is in the same p tag as the description.
