### ISSUE TITLE
Problems with pass by ref

### ISSUE THREAD

**Issue by donbidon** [phpDocumentor/phpDocumentor#1878]
```php
/**
 * @param int   &$arg Some arg
 * @return void 
 */
function foo(&$arg)
{
}
```
isn't rendered correctly. "Some arg" dissapears, no & symbol.

**Comment by jaapio** [comment]
Fixed in v3 default template:

![image](https://user-images.githubusercontent.com/1060433/144123970-01cd66fd-1813-4343-acbb-6146ace8f417.png)
