### ISSUE TITLE
Website (documentation) seems to be down

### ISSUE THREAD

**Issue by Erutan409** [phpDocumentor/phpDocumentor#1885]
Getting a bunch of 404's.  Just tried navigating to what was in my history from yesterday and I'm getting 404's this morning.

**Comment by mvriel** [comment]
I have migrated the website yesterday and our rollback failed; I am now working on restoring all functionality. I will update this issue once done

**Comment by mvriel** [comment]
We have made a replacement available at https://docs.phpdoc.org/; we need to fix some of the links in the website but at least the docs are available now
