### ISSUE TITLE
Allow to use files for templates and transformation, outside the PhpDoc tree

### ISSUE THREAD

**Issue by laurentj** [phpDocumentor/phpDocumentor#1886]
In old versions of PhpDocumentor, it was possible to indicate a directory where templates were stored (with the `-tb` option). 

I don't see such option in recent versions. So, the template we want to create should be stored inside the PhpDocumentor directory, which is difficult to do (No, I don't want to open and recreate the phar to include my template :) )

Same issue in `<transformation>`elements of configuration: the source attribute can refer only files inside the PhpDocumentor source code... So, in practice, [the example you give in the documentation](https://docs.phpdoc.org/getting-started/changing-the-look-and-feel.html#creating-your-own-look-and-feel) doesn't work.

**Comment by jaapio** [comment]
I think it should work when you provide an absolute path.

**Comment by laurentj** [comment]
Providing an absolute path is not a solution. Neither I nor contributors of my projects, and moreover nor any Continus Integration system,  should have to change the configuration file each time we install the source code and we want to generate the documentation. PhpDoc should support relative path for transformation and templates.

In a project, I would like to provide the xml files, a directory where there is a template for my project, and running phpdoc should be done without changing configurations.

And this is not a question, this is a feature request ;-)

**Comment by quasipickle** [comment]
I believe I'm encountering this issue as well.  Using the PHAR, I'm getting errors when specifying a directory for the template option - both using `--template` and in the configuration XML.  I am using absolute paths, and I get this error:

```
[Symfony\Component\Filesystem\Exception\IOException]
  Failed to create phar:///var/www/htdocs/point/app/libraries/phpdoc/phpDocumentor.phar/src/phpDocumentor/Transformer/../../../data/templates/template.clean
```

I realize "clean" is built-in, but I wanted to make some improvements and can't find any way to make phpDocumentor use my template.

**Comment by mvriel** [comment]
@quasipickle apologies for the late reply, we have been understaffed and only now ramping up again. You are encountering issues that we have with the design of templates; what happens is that they are copied into phpDocumentor's templates folder but with a phar this cannot be done.

This has been reported in https://github.com/phpDocumentor/phpDocumentor/issues/2117 too and I am now reworking the template mechanism to no longer depend on this mechanism. This does mean a significant rework but we intend to have this done by the next alpha release

**Comment by mvriel** [comment]
> In a project, I would like to provide the xml files, a directory where there is a template for my project, and running phpdoc should be done without changing configurations.

With the new templating mechanism I am working on relative paths should work too; but I am going to keep this open to remind me to check this as soon as it is done.

**Comment by mvriel** [comment]
Once finished, build https://github.com/phpDocumentor/phpDocumentor/actions/runs/31776448 will contain a PHAR file that should support external templates. I definitely need to do some more testing but hope you are able to help me there so that I can focus on solving more/other bugs in the meantime. So just to prepare you, it is entirely possible that you encounter another bug.

My initial tests have shown positive results; but I know I need more time to test this through in detail.

**Comment by jaapio** [comment]
This issue should be fixed in v3-rc. but it requires some testing. It would be very helpful if someone else rather than the core team could to a test.

**Comment by jaapio** [comment]
Tested and fixed in master branch
