### ISSUE TITLE
Version 2.9.0 on PEAR is corrupted: files version mismatch

### ISSUE THREAD

**Issue by cardonr** [phpDocumentor/phpDocumentor#1887]
Hi,

I just installed the version 2.9.0 of PhpDocumentor via PEAR:
pear channel-discover pear.phpdoc.org
pear install phpdoc/phpDocumentor

When I tried to execute phpdoc on my PHP project, I received such error:
Warning: require_once(C:\server\htdocs\MyProject\vendor/dompdf/dompdf/dompdf_config.inc.php): failed to open stream: No such file or directory in C:\server\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 178
...

But... this bug was solved in version 2.8.4
https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v2.8.4
"Removed DOMPDF"

So I compared the files in GitHub and PEAR
- GitHub: https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor-2.9.0.tgz
- PEAR: http://pear.phpdoc.org/get/phpDocumentor-2.9.0.tgz

The src/phpDocumentor/Bootstrap.php are not the same on PEAR and GitHub:
- GitHub: 5.855 bytes
- PEAR: 6.611 bytes, still contains 'dompdf' code.

Conclusion: the version 2.9.0 on PEAR is curently corrupted!

Please also note that the http://phpdoc.org is currently down (error HTTP 500).

**Comment by cardonr** [comment]
The following issue is related but was badly closed: https://github.com/phpDocumentor/phpDocumentor2/issues/1859

**Comment by cardonr** [comment]
Workaround to install with PEAR but using the archive on GitHub:
1) download https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor-2.9.0.tgz
2) launch PEAR from the command line with the downloaded package: 
pear install phpDocumentor-2.9.0.tgz

(Thanks to the comment of miken32 on this issue: https://github.com/phpDocumentor/phpDocumentor2/issues/1764)

**Comment by jaapio** [comment]
I have to be honest, we are not going to fix this anymore. 

phpDocumentor has moved forward in the past years. And we are not doing any maintenance anymore in v2.
