### ISSUE TITLE
Structure.xml file was not found in the target directory (using PHAR release)

### ISSUE THREAD

**Issue by AnrDaemon** [phpDocumentor/phpDocumentor#1912]
I'm trying various templates to find one that is usable.

`template:list` shows
```
Available templates:
* abstract (Errors out)
* checkstyle (Works, but… well…)
* clean (Works, but far from "clean", more like "pompous".)
* new-black (Errors out)
* old-ocean (Errors out)
* responsive (Errors out)
* responsive-twig (Works, but worse than "clean".)
* xml (Errors out)
* zend (Errors out)
```

Full error text:
```
  [RuntimeException]
  Structure.xml file was not found in the target directory, is the XML writer missing from the template definition?
```

There IS A `structure.xml` (note the small "s") in the target directory. And each time it is the same file generated, no differences.

This all happens on a symlinked UNC path. If I try to render into a local directory, slightly more files are generated, but no actual documentation, and the error message is different:
```
PHP Warning:  XSLTProcessor::transformToUri(): No stylesheet associated to this object in phar://C:/usr/sbin/php-tools/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xsl.php on line 307
```

Rendering directly to an UNC path fails miserably because of [PHP's is_writable bug](https://bugs.php.net/bug.php?id=68926#1480720239).

**Comment by jaapio** [comment]
We dropped xml support, so this issue can be closed. Not relevant anymore for v3.
