### ISSUE TITLE
Ignore files for lint errors, but keep them in the documentation

### ISSUE THREAD

**Issue by robertmain** [phpDocumentor/phpDocumentor#1947]
There should be a way to configure phpdoc so that I can include PSR standards from packagist in my documentation, but not get yelled at by the linter because they aren't documented "properly"

## Expected Behavior
I set the `ignoreErrorReportsFrom` or similar variable in my phpdoc config meaning that any lint error reports from those files(or directories) will be silently swallowed

## Actual Behavior
Currently, I get error reports in my generated documentation referring to things in `vendor/`. It would be nice if I could include the files from vendor so I can link to interfaces in my docs, but ignore the errors that it produces(since I can't do anything about them within my code base)

## Steps to Reproduce the Problem

  1. `composer require psr/cache`
  2. Create a PHP class that extends `Psr\Cache\CacheItemInterface` or similar
  3. You will see lint errors referring to `vendor\psr\cache\src\CacheItemInterface.php` etc. in your docs

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 2.x
* Install method: Composer
* php version: 7.0
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10
* Link to your project: https://github.com/robertmain/uniformcache

**Comment by jaapio** [comment]
closing as phpDocumentor v3 does not have validation anymore, so this should not be an issue in v3.
