### ISSUE TITLE
Long classes cause the sidebar to obscure the documentation

### ISSUE THREAD

**Issue by robertmain** [phpDocumentor/phpDocumentor#1953]
If a set of documentation proves to be longer than the sidebar, the sidebar ends up covering up the documentation

## Expected Behavior
The sidebar should remain to the right of the documentation

## Actual Behavior
It's currently in the middle of the generated documentation obscuring it and making it impossible to read

![image](https://user-images.githubusercontent.com/537684/35982981-0d962324-0cbf-11e8-87b9-cfdfead3abbf.png)

## Steps to Reproduce the Problem

Not actually sure, but I can reproduce it pretty reliably with my repo(https://github.com/robertmain/codeigniter-starter)

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: dev-master
* Install method: composer
* php version: 7.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10
* Link to your project: https://github.com/robertmain/codeigniter-starter

**Comment by robertmain** [comment]
Update: Found the root cause of this. If you have one class extending another, and the child class has `@return array<object>` it causes this behaviour.

Here's my example:

```php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Model Class
 *
 * @package		CodeIgniter
 * @subpackage	Libraries
 * @category	Libraries
 * @author		EllisLab Dev Team
 * @link		https://codeigniter.com/user_guide/libraries/config.html
 */
class CI_Model {

	/**
	 * Class constructor
	 *
	 * @link	https://github.com/bcit-ci/CodeIgniter/issues/5332
	 * @return	void
	 */
	public function __construct() {}

	/**
	 * __get magic
	 *
	 * Allows models to access CI's loaded classes using the same
	 * syntax as controllers.
	 *
	 * @param	string	$key
	 */
	public function __get($key)
	{
		return get_instance()->$key;
	}

}
```


```php
<?php

namespace App\Core;

use CI_Model;

/**
 * Abstract Base Model
 *
 * Abstract database model. Adds additional functionality such as created/updated/deleted timestamps, etc.
 */
abstract class Model extends CI_Model
{

    /**
     * Retrieve all records for a particular model
     *
     * @param bool $include_deleted Include deleted records in the result set (defaults to false)
     *
     * @return array<object> An array of objects representing the records in the database
     */
    public function get_all($include_deleted = false) : array
    {
		return [
			(object)['foo'   => 'bar'],
			(object)['fubar' => 'baz']
		];
    }
}
```

**Comment by mvriel** [comment]
Many of these issues should be resolved in phpDocumentor v3; the new `default` template addresses many of the shortcomings of our other templates. To be able to focus on the best experience possible; we have put the other templates on community-support / best effort. Pull requests are most welcome but otherwise I would like to invite you to try out our new default template
