### ISSUE TITLE
phpDocumentor does not recognize a composer installation when using a custom vendor directory.

### ISSUE THREAD

**Issue by kwvanderlinde** [phpDocumentor/phpDocumentor#1954]
## Expected Behavior

When a custom `"vendor-dir"` is set in `composer.json` to a sub-directory, phpDocumentor should be able recognized that it was installed via composer.

## Actual Behavior

phpDocumetor looks for `composer.json` in the parent directory of the vendor directory, regardless of whether a custom vendor directory is set. When `"vendor-dir"` does not have the same parent as `composer.json`, we get the following error:
```
PHP Fatal error:  Uncaught RuntimeException: phpDocumentor expected to find an autoloader at "<redacted>/example/untracked/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/../../vendor/autoload.php" but it was not there. Usually this is because the "composer install" command has not been ran yet. If this is not the case, please open an issue at http://github.com/phpDocumentor/phpDocumentor2 detailing what installation method you used, which path is mentioned in this error message and any other relevant information. in <redacted>/example/untracked/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php:101
Stack trace:
#0 <redacted>/example/untracked/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php(60): phpDocumentor\Bootstrap->createAutoloader('<redacted>...')
#1 <redacted>/example/untracked/vendor/phpdocumentor/phpdocumentor/bin/phpdoc(23): phpDocumentor\Bootstrap->initialize()
#2 {main}
   in <redacted>/example/untracked/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php on line 101
```

## Steps to Reproduce the Problem

1. Create an empty directory and `cd` into it.
2. Create a `composer.json` file with these contents:
```
{
	"require-dev": {
		"phpdocumentor/phpdocumentor": "^2.0"
	},
	"config": {
		"vendor-dir": "untracked/vendor"
	}
}
```
3. Run `composer install`
5. Run `./untracked/vendor/bin/phpdoc`

## Your environment

<dl>
<dt>phpDocumentor version</dt><dd>2.9</dd>
<dt>Installation method</dt><dd>composer</dd>
<dt>PHP version</dt><dd>7.0</dd>
<dt>Operating system</dt><dd>Ubuntu 16.04</dd>
</dl>

I gave all these details to be complete, but this is clearly an issue with the assumptions behind `phpDocumentor\Bootstrap::findVendorPath()`.

**Comment by jaapio** [comment]
Thanks for reporting. Please note that we do not recommend using phpdocumentor via the composer install method because there are more issues with this way of installing phpdocumentor. 

Currently all time we have is spend on phpdoc v3. But we are open for PR's for this issue.

**Comment by kwvanderlinde** [comment]
Then the composer install method should probably be removed from the front page of the site. Or at least a warning should be put there.

**Comment by kwvanderlinde** [comment]
I have an idea on how to solve this particular issue, so I can look into it (I have very little time, though, so no promises on a PR).

**Comment by iAmiAdam** [comment]
@kwvanderlinde Having the same issue with a custom vendor path, in my case it is /public/vendor/. Issue seems to be that phpdocumentor only searches five directories above itself in findVendorPath in Bootstrap.php

Trying to think of a logical solution that searches a couple of directories above but stops at the root drive.

**Comment by iAmiAdam** [comment]
See my commit here; https://github.com/iAmiAdam/phpDocumentor2/commit/ec98f146bce42838c1b1a23ad10c2aabdea1a685

Read the contribution guidelines after I'd made the change so I'll make the changes properly for 2.x later when I can.

**Comment by jaapio** [comment]
We are not working on phpDoc v2 anymore, users will have to move forward to run phpDocumentor. 

we do support old project code, back to php5, however phpDocumentor itself requires php 8.1 to run. This can be done using docker.
