### ISSUE TITLE
Using packages hierarchy in clean template

### ISSUE THREAD

**Issue by sabat24** [phpDocumentor/phpDocumentor#1958]
I know that clean template doesn't support packages hierarchy etc. However the new-black does so it's possible to have got 2 hierarchy (logical and functional) in one template - which wasn't available in 2014 when I saw discussion about it. To be honest the clean template is great and as I know it's main template for phpDocumentor. Why there is no support for packages hierarchy in clean template, if it's supported by almost every another template, including both hierarchies in new-black?

**Comment by mvriel** [comment]
The new default template of phpDocumentor 3 has support again for this feature and is the active maintained template; all other templates are now community-maintained / best effort templates so that we can focus on making the application itself even more awesome :)
