### ISSUE TITLE
Public/private/protected constants not supported

### ISSUE THREAD

**Issue by gruntaway** [phpDocumentor/phpDocumentor#1962]
I get a syntax error if I define public/private/protected constants within a namespace class. This is something that got supported in PHP 7.1, but PHPDocumentor2 does not yet seem to support the use of these constants.

## Expected Behavior
No syntax errors. :)

## Actual Behavior
```
Parsing /src/Library/Config.php
Parse Error: Syntax error, unexpected '[', expecting '(' on line 64  No summary was found for this file
```

## Steps to Reproduce the Problem
Simply try to define the following, and use it later on.
```

  public static $Db;

  public const Db = [
    'production' => [
      'username' => 'something',
      'password' => '',
      'host' => '127.0.0.1',
      'database' => 'mydb'
    ],
    'staging' => [
      'username' => 'something',
      'password' => '',
      'host' => '127.0.0.1',
      'database' => 'mydb_staging'
    ],
    'development' => [
      'username' => 'something',
      'password' => '',
      'host' => '127.0.0.1',
      'database' => 'mydb_development'
    ]
  ];

  public static function setDatabase(string $environment) {
    if(!isset(self::Db[$environment])) { throw new \Exception('No configuration set for environment ('.$environment.').'); }

    self::$Db = self::Db[$environment];
  }
```

Here, the `!isset(self::Db[$environment])` also seems to be throwing an error. But most importantly, the syntax error happens a the first attempt of defining a scoped constant.

## Your environment
* Version used: 3.0.0-alpha1
* Install method: Composer
* php version: 7.2.2
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS High Sierra

**Comment by gruntaway** [comment]
This issue is related to #1964

**Comment by gruntaway** [comment]
Just a quick note and a question regarding this issue.

Note: The bug seems to be related to using constants as arrays (something that is supported in PHP 7.2).

Question: When can we expect a fix? I know you're busy, but we are currently building a project in PHP 7.2 and sort of need a functional generator for it before the end of the month, so it would just be nice to know if we need to find another solution before then. :) I hope PHPDoc can do it though, as it's by far the best one out there - with the exception of 7.2 support. :)

**Comment by gruntaway** [comment]
Any updates? :)

**Comment by gruntaway** [comment]
? : )

**Comment by jaapio** [comment]
Should be part of phpdoc3 alpha2

**Comment by gruntaway** [comment]
Awesome. I'll be excited to test it out when it's released. :)

**Comment by jaapio** [comment]
This is implemented in the current master branch. Will be part of a upcommig release.

**Comment by nelson6e65** [comment]
> 
> 
> This is implemented in the current master branch. Will be part of a upcommig release.

Nice! Thanks! 😃
