### ISSUE TITLE
Free function don't get documented properly

### ISSUE THREAD

**Issue by LupusMichaelis** [phpDocumentor/phpDocumentor#1969]
In a PHP file with free functions (eg: function out of any class), the docblock isn't properly parsed when a description isn't provided. At least the first argument tag is not detected, and processed as the description.

It is possible to force phpDocumentor to generate properly by explicitly writing a description (at least a dot).

## Expected Behavior
@param tag to be processed accordingly.

## Actual Behavior

@param tag is embeded in description, and an error is logged by phpDocumentor that the arguments are not documented.

## Steps to Reproduce the Problem

Example can be found here: https://github.com/LupusMichaelis/phpdoc-freefn

## Your environment

* Version used: 2.9.0
* php version: 5.6.33
* Microsoft Windows 7 SP1 (Cygwin)
* Files are saved as Unix files with Vim (passing them to Windows format doesn't seem to affect the issue)

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
