### ISSUE TITLE
Resolving globs in --filename param doesn't work

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#1979]
@thelounge-zz commented on Mar 27 in #1960 

first it don't understand things like "--filename="/www/phpincludes/global*.php" any longer
Warning: file_get_contents(/www/phpincludes/global*.php): failed to open stream: No such file or directory in phar:///mnt/data/www/thelounge.net/contentlounge/updateservice/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/File/LocalFile.php on line 44

second the following call also leads in empty docs as described in this bugreport

/usr/bin/time -f "%E" php -d "extension=tokenizer.so" "$CMS_UPDATE_SERVICE_LOCATION/phpDocumentor.phar" run --force --progressbar --cache-folder="/tmp" --encoding="ISO-8859-1" --directory="$CMS_UPDATE_SERVICE_LOCATION/package" --filename="/www/phpincludes/newsletter.php" --ignore="modules/blog/tagcloud.php" --target="$CMS_UPDATE_SERVICE_LOCATION/documentation/code-referenzen/contentlounge" --title="ContentLounge - Technische Referenz" --defaultpackagename="ContentLounge" --template="clean"

**Comment by mvriel** [comment]
As discussed: closing it
