### ISSUE TITLE
Bootstrap.php cannot find path to composer.json to get autoload.php

### ISSUE THREAD

**Issue by MrSuit** [phpDocumentor/phpDocumentor#2002]
Bootstrap.php cannot find path to composer.json caused on line :138 in Bootstrap.php

## Expected Behavior

Generating documentation via lib/vendor/bin/phpdoc -p -d crud_core/ -t doc/

## Actual Behavior

> lib/vendor/bin/phpdoc -p -d crud_core/ -t doc/
PHP Fatal error:  Uncaught RuntimeException: phpDocumentor expected to find an autoloader at "/home/mr/devel/git/crud_core/lib/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/../../vendor/autoload.php" but it was not there. Usually this is because the "composer install" command has not been ran yet. If this is not the case, please open an issue at http://github.com/phpDocumentor/phpDocumentor2 detailing what installation method you used, which path is mentioned in this error message and any other relevant information. in /home/mr/devel/git/crud_core/lib/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php:101
Stack trace:
#0 /home/mr/devel/git/crud_core/lib/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php(60): phpDocumentor\Bootstrap->createAutoloader('/home/mr/devel/...')
#1 /home/mr/devel/git/crud_core/lib/vendor/phpdocumentor/phpdocumentor/bin/phpdoc(23): phpDocumentor\Bootstrap->initialize()
#2 {main}
  thrown in /home/mr/devel/git/crud_core/lib/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php on line 101
Script lib/vendor/bin/phpdoc -p -d crud_core/ -t doc/ handling the cdoc event returned with error code 255

## Steps to Reproduce the Problem

  1. change vendor-dir in composer configuration to lib/vendor for example
  2. composer install
  3. php lib/vendor/bin/phpdoc OR make script in composer.json and run composer phpdoc

## Your environment

Rather than doing something like on line :131 use for example getenv('DOCUMENT_ROOT').
Everytime user run script in location where composer.json is this cause that all will work fine and you can have vendor everywhere. Please try it and apologize me and my English. This is my first bug report.

project_folder ->
  [here i am running the script via composer cdoc]
  - composer.json
  - public_html
  - lib
    - vendor

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 2.9.0
* Install method: composer
* php version 7.0.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Debian Stretch (actual)
* Link to your project:
* ...
* ...

**Comment by MrSuit** [comment]
update: my mistake, getenv('DOCUMENT_ROOT') => empry string

**Comment by asmundstavdahl** [comment]
Looks like Bootstrap->findVendorPath() requires the vendor-dir to be on the same directory depth as composer.json.

**Comment by MrSuit** [comment]
Sry guys but i do not have much time right now. 

asmundstavdahl hits the core of problem.
