### ISSUE TITLE
Use GPG signing of PHAR

### ISSUE THREAD

**Issue by filips123** [phpDocumentor/phpDocumentor#2028]
Use GPG signing instead of OpenSSL signing of PHAR. This would allow users to install phpDocumentor (v3) with tools like [PHIVE](https://phar.io/) and better security (see infection/infection#134).

> On the other hand: After all these years the openssl signature stuff exists in ext\phar I'm still not sure why anyone would want to use this mechanism. Imho, it's completely pointless: The only thing this method verifies is that the phar has not been modified since the signature had been made with an unknown private key accompanying the given public key. Since chances are I can simply replace the pubkey file if I have permissions to modify the phar, I fail to see where the (security) benefit in openssl signing the phar lies. Particularly since the neither the used private key nor the public key contain any means of identifying the signer.

**Comment by jaapio** [comment]
This is work in progress for us. I already implemented a workflow to improve our release process. Using a GPG key is part of that. However there is an issue with the created phar that I need to check.

**Comment by filips123** [comment]
@jaapio I have one more thing that is not really related to GPG signing but to releases and repository in general.

New version is 3.x. However, repository is still called `phpDocumentor2`. Shouldn't it be renamed to `phpDocumentor3` or even better just `phpDocumentor`? I think that Github will handle most of redirects o new URL automatically so there shouldn't be much problem.

**Comment by jaapio** [comment]
it should, but I didn't have time yet to fix this :-)

**Comment by jaapio** [comment]
This one is ready with the release of v3 beta. 
Please let me know it there are any issues.
