### ISSUE TITLE
Template "xml" can create an invalid structure.xml

### ISSUE THREAD

**Issue by fi5er** [phpDocumentor/phpDocumentor#2045]
Not all Unicode characters are legal in XML documents, for example `0x1B` (decimal 27, ESC). A PHP source document may reasonably contain these characters, for example:

```php
class Broken
{
    /** Escape character. */
    const ESC_CHAR = "\x1B";
}
```
The "xml" template writes this character into the `structure.xml` file as-is, leading to an invalid document. Most tools (like PHP's `DOMDocument` class or `xmllint`) will refuse to handle such a document.

Possible solutions would be to replace all characters outside the [valid ranges](https://www.w3.org/TR/REC-xml/#charsets) with a replacement character (�), or to remove them.

* Version used: v3.0.x-dev@ee92b8f
* Install method: cloned "develop" branch
* php version: 7.2.10
* Operating system and version: Kubuntu 18.04

**Comment by jaapio** [comment]
We dropped xml support, so this issue can be closed. Not relavant anymore for v3.
