### ISSUE TITLE
phpDocumentor is not parsing correctly the name of the static method 'new' from the Atlas class

### ISSUE THREAD

**Issue by andrewscaya** [phpDocumentor/phpDocumentor#2057]
When parsing a file containing a call to the Atlas::new() static method, phpDocumentor fails and does not include the source file in generated html output.

 ## Expected Behavior

Should parse correctly.

## Actual Behavior

File is ignored.

## Steps to Reproduce the Problem

  1. Use the Atlas::new() static method in code
  2. Try to parse phpDocumentor annotations

## Your environment
* PHP 7.1.24
* File is Unix LF, UTF-8
* Code running in a standard Unix environment

* Version used: Current phar file : http://www.phpdoc.org/phpDocumentor.phar
* Install method: running phar file through a Composer script
* php version: 7.1.24
* Operating system and version: Linux with glibc 2.24 and gcc 6.2.0

Linked issue: https://github.com/atlasphp/Atlas.Orm/issues/101

**Comment by mvriel** [comment]
@andrewscaya we are aware that when keywords are used as the name for methods or properties that a fatal error occurs. We need to investigate this issue but at the same time I can recommend avoiding PHP keywords as names for methods and properties; there is no guarantee that in future PHP versions this will work or that this will work properly in other tools that do static analysis.

**Comment by jaapio** [comment]
I just confirmed that this issue has been resolved in our nightly build: https://github.com/phpDocumentor/phpDocumentor#nightly-builds

Feel free to create a new issue when you have issues with the new build.
