### ISSUE TITLE
v3 argument default value in quotes if string

### ISSUE THREAD

**Issue by NesCafe62** [phpDocumentor/phpDocumentor#2084]
I'm making template based on cvuorinen/phpdoc-markdown-public. Method signatures generated very good, except string argument default values not surrounded with quotes. So, maybe modify `getDefault` to return quoted result for strings (as it was in version 2), or make different method to determine that default value is a string (defaultIsString for example)?
...first I thought about checking for argument type == 'string', but there can be many types, and if one of them is string, not always default value will be string.

**Comment by NesCafe62** [comment]
The same is actual for constants, their default value can also be string or not.

**Comment by mvriel** [comment]
In a moment I will be pushing a new version to master that will solve this

![image](https://user-images.githubusercontent.com/193704/73165773-bae52a00-40f4-11ea-85f1-9c3b6d2ac383.png)

If you want to test this you need to grab a PHAR from Github Actions (see the top navigation). This fix will be included in the next alpha
