### ISSUE TITLE
How i can install phpDocumentor2 with Mint 19.2 and PHP 7.2 ?

### ISSUE THREAD

**Issue by ZerooCool** [phpDocumentor/phpDocumentor#2113]
pear channel-discover pear.phpdoc.org

Error: Unable to create XML parser
Discovering channel pear.phpdoc.org over http:// failed with message: channel-add: invalid channel.xml file
Trying to discover channel pear.phpdoc.org over https:// instead
Error: Unable to create XML parser
Discovery of channel "pear.phpdoc.org" failed (channel-add: invalid channel.xml file)

**Comment by ZerooCool** [comment]
Then, that's my way. It's ok ?

```
wget https://pear.phpdoc.org/channel.xml
pear channel-add ./channel.xml
```

```
pear install http://pear.phpdoc.org/get/phpDocumentor-2.9.0.tgz
wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar
sudo mv phpDocumentor.phar /usr/local/bin/phpdoc
sudo chmod +x /usr/local/bin/phpdoc
```

```
phpdoc --version
phpDocumentor version 2.9.0
```

```
# Pour tout le projet :
php /usr/local/bin/phpdoc -d "." -t "./docs"
php /usr/local/bin/phpdoc -d "." -t "./docs" --template="responsive-twig"
```

```
# Pour un seul fichier :
php /usr/local/bin/phpdoc -f "sample1.php" -t "./docs"
```

```
# Consulter le rendu :
http://localhost/docs/
```

**# La page Class Hierarchy Diagram n'affiche rien.** <----- :/

**Comment by ZerooCool** [comment]
```
# Pour générer la Class Hierarchy Diagram, installer le paquet graphviz :
apt install graphviz
```

I forget something to properly install the documentation generator?

For now, it seems to work like this.

I would like to see how to use other templates.

**Comment by jaapio** [comment]
phpDocumentor has a number of commands that could help you. 

`phpdoc template:list` returns a list of the available templates.
you can run `phpdoc run  --template=clean` for the clean template.

**Comment by ZerooCool** [comment]
Ok for this command :

phpdoc template:list
Available templates:
* abstract
* checkstyle
* clean
* new-black
* old-ocean
* responsive
* responsive-twig
* xml
* zend

**Comment by jaapio** [comment]
Closing because we improved the readme with installation steps

**Comment by aadhar41** [comment]
> Then, that's my way. It's ok ?
> 
> ```
> wget https://pear.phpdoc.org/channel.xml
> pear channel-add ./channel.xml
> ```
> 
> ```
> pear install http://pear.phpdoc.org/get/phpDocumentor-2.9.0.tgz
> wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar
> sudo mv phpDocumentor.phar /usr/local/bin/phpdoc
> sudo chmod +x /usr/local/bin/phpdoc
> ```
> 
> ```
> phpdoc --version
> phpDocumentor version 2.9.0
> ```
> 
> ```
> # Pour tout le projet :
> php /usr/local/bin/phpdoc -d "." -t "./docs"
> php /usr/local/bin/phpdoc -d "." -t "./docs" --template="responsive-twig"
> ```
> 
> ```
> # Pour un seul fichier :
> php /usr/local/bin/phpdoc -f "sample1.php" -t "./docs"
> ```
> 
> ```
> # Consulter le rendu :
> http://localhost/docs/
> ```
> 
> **# La page Class Hierarchy Diagram n'affiche rien.** <----- :/

Thank You very much I was looking for this solution for such a long time.
