### ISSUE TITLE
Broken link in @see reference on root page

### ISSUE THREAD

**Issue by WoodrowShigeru** [phpDocumentor/phpDocumentor#2115]
The @see reference tag is missing a subpath from the output directory in a very specific situation:

```
// broken link:
http://dev.mysite.local/classes/Project.L10n.html#method_find

// should use:
http://dev.mysite.local/docs/classes/Project.L10n.html#method_find

// this is how I generate the phpdoc:
$ vendor/manually/phpDocumentor/2.9.0/bin/phpdoc -d www/code/ -t www/docs/

// This text is referencing the method.
See {@see \Project\L10n::find() L10n::find()} method for more info.
```

The referencing file is a global include file with tools for system-wide needs. That's why it doesn't define a namespace. In the phpdoc it appears under `\` (root). If I enter http://dev.mysite.local/docs/ in the browser, this root page with the global functions is the first thing I see. Now the link is broken.

However, if I navigate a bit through the phpdoc space (i.e. click on "\Project" and pick the "\Project\L10n" class, which has a namespace defined), and then click on root again, the link is fixed.

The source code uses `<a href="../classes/Project.L10n.html#method_find">L10n::find()</a>` in both cases, but it never references correctly when I directly request the output directory.

## Your environment
* Ubuntu 18.04.2
* LAMP, Server version: Apache/2.4.29 (Ubuntu), Server built: 2019-07-16T18:14:45
* PHP 7.2.19
* phpDocumentor 2.9.0, installed manually by downloading the tar-ball from the releases tab of this github.

**Comment by jaapio** [comment]
It would be very nice if someone could verify this issue with the nightly builds of phpDocumentor v3.

**Comment by jaapio** [comment]
Checked this with the latest build of v3, this is fixed now in the nightly builds
