### ISSUE TITLE
Add support for generic / template types.

### ISSUE THREAD

**Issue by ADmad** [phpDocumentor/phpDocumentor#2122]
Prominent static analyzers like [psalm](https://psalm.dev/docs/annotating_code/templated_annotations/) and [phan](https://github.com/phan/phan/wiki/Generic-Types) already support it and support for [phpstan](https://arnaud.le-blanc.net/post/phpstan-generics.html) is also WIP.

**Comment by martinatseequent** [comment]
:+1:

**Comment by jaapio** [comment]
Some news on this, phpDocumentor does support parts of generics now. However, we are not handling the templates.
