### ISSUE TITLE
Responsive theme does not work

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#2123]
But using the `responsive` template doesn't generate any html files, just a bunch of folders with css and js files.

_Originally posted by @ADmad in https://github.com/phpDocumentor/phpDocumentor2/issues/2114#issuecomment-524851700_

**Comment by ADmad** [comment]
As you mentioned [here](https://github.com/phpDocumentor/phpDocumentor2/issues/2114#issuecomment-524956532) I did have `php-xsl` missing. A warning about the missing extension would have been nice.

But even after installing the required extension still don't get any html files. There are numbers errors like this:
```
[2019-08-27 00:30:57] php.WARNING: Warning: XSLTProcessor::transformToUri(): No stylesheet associated to this object {"exception":"[object] (ErrorException(code: 0): Warning: XSLTProcessor::transformToUri(): No stylesheet associated to this object at phar:///srv/sites/cake-apps/cakephp/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Xsl.php:291)"} []
```

**Comment by jaapio** [comment]
The warning should be in. I will check why you didn't get it.
It looks like the phar is failing to write or fetch a file. but that needs more time from my side. I will have a look. And report when I got something. 

Thanks again for creating an issue.

**Comment by jaapio** [comment]
We decided to drop support for xsl templates. Because they are hard to maintain. And we need to reduce the amount of maintenance time.
So closing this issue.
