### ISSUE TITLE
[question] How to use @see to point to a DocBlock on a class declaration?

### ISSUE THREAD

**Issue by o-alquimista** [phpDocumentor/phpDocumentor#2152]
The DocBlock is on top of a class declaration:
```
/**
 * DocBlock (...)
 */
class ExampleClass
{}
```

I need to point another method in another namespace to the DocBlock above.

Would it be `@see App\Example\ExampleClass`?

**Comment by jaapio** [comment]
Yes, you can reference every element using its full qualified element name.

To reference a method you can add ::method() after the class name
