### ISSUE TITLE
Could not specifiy a type for array

### ISSUE THREAD

**Issue by OskarStark** [phpDocumentor/phpDocumentor#2158]
## Expected Behavior
No error 🤔 

## Actual Behavior

> In FileLoader.php line 180:
>
> A type is missing in a collection expression in . (which is being imported from "/dev/backend/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.
>
> In TypeResolver.php line 263:
>
> A type is missing in a collection expression

## Steps to Reproduce the Problem

I added a type to a property:
```diff
    /**
     * @ORM\Column(name = "extra_data", type = "json", nullable = false)
     * @Serial\Groups({
     *     "audit_log_collection_output",
     *     "audit_log_item_output",
     * })
     *
-    * @var array
+    * @var array<string, string|array<string, string>>
     */
    private $extraData = [];
```

## Your environment

PHP 7.3
api-platform/core                   v2.5.3

phpdocumentor/reflection-common     2.0.0
phpdocumentor/reflection-docblock   4.3.2
phpdocumentor/type-resolver         1.0.1

symfony/asset                       v4.4.1  Symfony Asset Component
symfony/browser-kit                 v4.4.1  Symfony BrowserKit Component
symfony/cache                       v5.0.1  Symfony Cache component with ...
symfony/cache-contracts             v2.0.1  Generic abstractions related ...
symfony/config                      v4.4.1  Symfony Config Component
symfony/console                     v4.4.1  Symfony Console Component
symfony/css-selector                v4.4.1  Symfony CssSelector Component
symfony/debug                       v4.4.1  Symfony Debug Component
symfony/debug-bundle                v4.4.1  Symfony DebugBundle
symfony/debug-pack                  v1.0.7  A debug pack for Symfony proj...
symfony/dependency-injection        v4.4.1  Symfony DependencyInjection C...
symfony/doctrine-bridge             v4.4.1  Symfony Doctrine Bridge
symfony/dom-crawler                 v4.4.1  Symfony DomCrawler Component
symfony/dotenv                      v4.4.1  Registers environment variabl...
symfony/error-handler               v4.4.1  Symfony ErrorHandler Component
symfony/event-dispatcher            v4.4.1  Symfony EventDispatcher Compo...
symfony/event-dispatcher-contracts  v1.1.7  Generic abstractions related ...
symfony/expression-language         v4.4.1  Symfony ExpressionLanguage Co...
symfony/filesystem                  v4.4.1  Symfony Filesystem Component
symfony/finder                      v4.4.1  Symfony Finder Component
symfony/flex                        v1.5.3  Composer plugin for Symfony
symfony/form                        v4.4.1  Symfony Form Component
symfony/framework-bundle            v4.4.1  Symfony FrameworkBundle
symfony/http-client                 v4.4.1  Symfony HttpClient component
symfony/http-client-contracts       v2.0.1  Generic abstractions related ...
symfony/http-foundation             v4.4.1  Symfony HttpFoundation Component
symfony/http-kernel                 v4.4.1  Symfony HttpKernel Component
symfony/inflector                   v5.0.1  Symfony Inflector Component
symfony/intl                        v4.4.1  A PHP replacement layer for t...
symfony/ldap                        v4.4.1  An abstraction in front of PH...
symfony/maker-bundle                v1.14.3 Symfony Maker helps you creat...
symfony/messenger                   v4.4.1  Symfony Messenger Component
symfony/mime                        v4.4.1  A library to manipulate MIME ...
symfony/monolog-bridge              v4.4.1  Symfony Monolog Bridge
symfony/monolog-bundle              v3.5.0  Symfony MonologBundle
symfony/options-resolver            v4.4.1  Symfony OptionsResolver Compo...
symfony/orm-pack                    v1.0.7  A pack for the Doctrine ORM
symfony/phpunit-bridge              v5.0.1  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu           v1.13.1 Symfony polyfill for intl's I...
symfony/polyfill-intl-idn           v1.13.1 Symfony polyfill for intl's i...
symfony/polyfill-mbstring           v1.13.1 Symfony polyfill for the Mbst...
symfony/process                     v4.4.1  Symfony Process Component
symfony/profiler-pack               v1.0.4  A pack for the Symfony web pr...
symfony/property-access             v4.4.1  Symfony PropertyAccess Component
symfony/property-info               v4.4.1  Symfony Property Info Component
symfony/routing                     v4.4.1  Symfony Routing Component
symfony/security-bundle             v4.4.1  Symfony SecurityBundle
symfony/security-core               v4.4.1  Symfony Security Component - ...
symfony/security-csrf               v5.0.1  Symfony Security Component - ...
symfony/security-guard              v4.4.1  Symfony Security Component - ...
symfony/security-http               v4.4.1  Symfony Security Component - ...
symfony/serializer                  v4.4.1  Symfony Serializer Component
symfony/serializer-pack             v1.0.2  A pack for the Symfony serial...
symfony/service-contracts           v2.0.1  Generic abstractions related ...
symfony/stopwatch                   v4.4.1  Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.4.0  Symfony SwiftmailerBundle
symfony/templating                  v4.4.1  Symfony Templating Component
symfony/test-pack                   v1.0.6  A pack for functional and end...
symfony/translation                 v4.4.1  Symfony Translation Component
symfony/translation-contracts       v2.0.1  Generic abstractions related ...
symfony/twig-bridge                 v4.4.1  Symfony Twig Bridge
symfony/twig-bundle                 v4.4.1  Symfony TwigBundle
symfony/validator                   v4.4.1  Symfony Validator Component
symfony/var-dumper                  v5.0.1  Symfony mechanism for explori...
symfony/var-exporter                v5.0.1  A blend of var_export() + ser...
symfony/web-link                    v4.4.1  Symfony WebLink Component
symfony/web-profiler-bundle         v4.4.1  Symfony WebProfilerBundle
symfony/workflow                    v4.4.1  Symfony Workflow Component
symfony/yaml                        v4.4.1  Symfony Yaml Component

**Comment by jaapio** [comment]
Thanks for your report. Currently our typeresolver doesn't support the extended version of type hints introduced by phpstan and psalm.
We focused on the specs that were written in prs-5, because both were written at the same time.
At this point I would highly recommend you to start using the type templates of psalm which are now also supported by phpstan.
Improving the type resolver with the new formats does not have our attention atm. However it would be very nice if we could integrate the type detection of all tools at some point. Which was our intention with prs-5

**Comment by mvriel** [comment]
To add, assistance with this is _much_ appreciated! Jaap and I are currently focusing on phpDocumentor 3 and this means we can have less focus on the surrounding libraries at the moment. This does not mean we don't want or value these features; we just don't know where to find the time :)

**Comment by jaapio** [comment]
Generic notations are now properly supported in our libraries. I'm closing this because I do not expect any issues regarding this report.
