### ISSUE TITLE
Phar does need to be writable to be used

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#2161]
MFG!!!!

If `phar.readonly = On`, it runs just fine.
If `phar.readonly = Off`, the output is as shown in the logs, and it actually tries to write to the .phar, and damages it!

_Originally posted by @AnrDaemon in https://github.com/phpDocumentor/phpDocumentor/issues/2130#issuecomment-565835656_

**Comment by jrfnl** [comment]
@jaapio Don't you mean _needs to be readonly_ ?

**Comment by jaapio** [comment]
Yes, it should be readonly, but currently it is not... so that's the issue ;-)

**Comment by jaapio** [comment]
Ok, I was confused by the inversed logic here. 
When `phar.readonly` is false. The phar is writable. And phpdoc's phar will try to write data to the phar. This means possibly that symfony is trying to warm the cache again? 

If the phar is not writable. phpDocumentor will work as expected since the cache is already included in phpdoc. 

It is recommended anyway to have `phar.readonly = on` by default unless you are doing something which phar creation. But in any case phpdocumentor should keep working. We need to check if there is a way to by pass the behavior when `readonly` is `off`

**Comment by jaapio** [comment]
digging into this issue, I found out that the compression of humbug/box is omitting some file contents. I don't have a good reason for that but without the compression the phar just works without the warnings. I got when using compression and readonly=off. 

This means that we are missing classes in the compressed phars.
