### ISSUE TITLE
Documentation pages (single page CMS/Wiki)

### ISSUE THREAD

**Issue by gruntaway** [phpDocumentor/phpDocumentor#2177]
I have tried everything from using .pkg-files (tag-format) to various @package structures, but I cannot seem to find out how to insert single page content.

PHPDocumentor often writes that you have to write the documentation for developers and users alike, and so it would make sense to e.g. be able to define content for the "index" page of the documentation, as well as separate single pages which are not necessary "comments of a specific file, code etc.".

How would I achieve this? I would love to e.g. specify some content on the index page, to provide a good overview of the application, as well as a few separate pages like "Getting started", "How to do *this*", "Simple example of doing *this*".

I hope it makes sense.

**Comment by jaapio** [comment]
At the moment we cannot process user guides, I think that is what you are trying to accomplish? But it is a demand from use as maintainers for a very long time to have such a feature.

The good news is that we are experimenting with some libraries to get this kind of docs rendered together with the api docs we are currently rendering. The first results do look very promising.
The bad news is that we had to delay this feature again to get phpdoc v3 out as soon as possible. But this is definitely on our roadmap.

Thanks for reaching out.

**Comment by gruntaway** [comment]
Awesome. Just glad it's in the pipeline, as that really seems to be the last remaining feature to make complete documentation that can be used for both development, production and as wiki/guide for usage of the software.

Amazing - Keep up the good work on V3. Merry Xmas.

**Comment by mvriel** [comment]
Thank you! You too happy holidays and enjoy these times!

(Because this feature is on the roadmap I will be closing this issue)
