### ISSUE TITLE
[Documentation] Graphviz Link Update

### ISSUE THREAD

**Issue by firrae** [phpDocumentor/phpDocumentor#2203]
## Expected Behavior

Click the Graphviz link in the docs [here](https://docs.phpdoc.org/getting-started/installing.html#using-pear) and have it bring me to the downloads section OR direct link to the appropriate version.

## Actual Behavior

Currently the link is pointed at what looks like an old Downloads page, said downloads page appears as a file to download and contains HTML saying that the page has moved. The correct new URL to the downloads page is: [http://graphviz.org/download/](http://graphviz.org/download/).

## Steps to Reproduce the Problem

  1. Head to [https://docs.phpdoc.org/getting-started/installing.html#using-pear](https://docs.phpdoc.org/getting-started/installing.html#using-pear)
  2. Click the Graphviz link ([this](https://graphviz.org/Download..php))
  3. Download the file, if prompted, and look at the contents for the message described above.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpful if you link to your project
or add any code that is involved in to the issue.

* Version used: Not required.
* Install method: Pear
* php version: 7.2
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Mac

**Comment by jrfnl** [comment]
Additional suggestion:

Add links to the Readme for Graphviz:

> This will require Graphviz to be installed on the machine running phpDocumentor. Graphviz is optional, and warnings about missing Graphviz can be ignored.

**Comment by mvriel** [comment]
@jrfnl I ave updated the README to include links to the GraphViz downloads page and a couple of rewordings

**Comment by mvriel** [comment]
@firrae thank you for your report; with it, I noticed that our build pipeline for pushing documentation live was broken; we are fixing this now and then we can fix this typo :)

**Comment by mvriel** [comment]
The link has been updated; thank you for reporting this

**Comment by jrfnl** [comment]
@mvriel Thanks for the quick turn around!

**Comment by firrae** [comment]
@mvriel @jrfnl Thanks for updating quickly. 2 issues fixed with 1 ticket is always the best 😄
