### ISSUE TITLE
Reflection\DocBlock\Description::render() must be of the type string, bool returned

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#2205]
Next, I've done a test run with the project which is not yet online and unfortunately, I'm running into an error there, but I think that's unrelated to the issue being discussed here:
```
# phpdoc3 run
PHP 7.3.12 (cli) (built: Nov 19 2019 14:00:18) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies

phpDocumentor 7632766

Parsing files
 28/28 [============================] 100%01:13:33 WARNING   [php] Warning: vsprintf(): Too few arguments ["exception" => ErrorException { …}]
Fatal error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Return value of phpDocumentor\Reflection\DocBlock\Description::render() must be of the type string, bool returned in phar://C:/path/to/phars/phpDocumentor-3.0.0-alpha4d.phar/src/phpDocumentor/Descriptor/Builder/Reflector/AssemblerAbstract.php on line 0
01:13:33 CRITICAL  [php] Fatal Error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Return value of phpDocumentor\Reflection\DocBlock\Description::render() must be of the type string, bool returned ["exception" => Symfony\Component\ErrorHandler\Error\FatalError^ { …}]
01:13:33 CRITICAL  [php] Fatal Error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Return value of phpDocumentor\Reflection\DocBlock\Description::render() must be of the type string, bool returned ["exception" => Symfony\Component\ErrorHandler\Error\FatalError^ { …}]

In AssemblerAbstract.php line n/a:

  Error: Method phpDocumentor\Reflection\DocBlock\Description::__toString() must not throw an exception, caught TypeError: Return value of phpDocumentor\
  Reflection\DocBlock\Description::render() must be of the type string, bool returned


project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>


Exit code is 255
```

**Edit**: running over the other project with the git clone install gives the same results without any additional debug information.

_Originally posted by @jrfnl in https://github.com/phpDocumentor/phpDocumentor/issues/2130#issuecomment-573255067_

**Comment by jaapio** [comment]
I remember this issue. This should be addressed in https://github.com/phpDocumentor/ReflectionDocBlock/pull/198. 

The problem is that the `__toString` method returns an invalid value, because one of the tags inside a description is invalid. 

From what we have seen in the wild this is mostly regarding the `@see` tag. Which is abused very often to target parameters like this `@see $paramName`  which is invalid according to the specs of `@see` you should either provide an element name or a link.

**Comment by jrfnl** [comment]
@jaapio I'll see if I can find the offender. Is there any way I can get more information about, for instance, the file in which the offending `@see` tag was found ?

Or could the error potential be caught and ignored for the purposes of generating the docs and then be added to the "Error" Report in the generated documentation ?

That way it doesn't break the run and provides useful info for people to solve the issue in their docs.

**Comment by mvriel** [comment]
The PR that Jaap has made includes the possibility for such by generating an 'InvalidTag' object that also contains the exception that was thrown. With this, we can check for it in phpDocumentor and provide reporting on this.

**Comment by jrfnl** [comment]
@mvriel Excellent! Sounds like a great stepping stone to fixing this issue :+1:
