### ISSUE TITLE
Fix @covers and @use statements in tests

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2214]
For phpDocumentor, we want to be more strict in how our code coverage is reported. This will enable us to be more thorough writing tests and provide better feedback for contributors on what to test and if they are successful.

To do this, the `beStrictAboutCoversAnnotation` setting should be enabled in `phpunit.dist.xml` and every warning reported by PHPUnit should be fixed by adding the respective `@covers` and `@uses` annotations to each test.

**Comment by jaapio** [comment]
phpunit is changing on this field. I do not want to add this for now.
