### ISSUE TITLE
Change string class names in tests to `MyClass::class` notation

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2215]
Parts of the phpDocumentor test suite was written prior to the introduction of the `::class` feature of PHP. To improve the quality of our test suite we want to replace the class names that are written out as string to this `::class` notation.

Example:

    `m::mock('\phpDocumentor\Reflection\Fqsen')` should become `m::mock(Fqsen::class)`

**Comment by orklah** [comment]
This can be closed I believe

**Comment by mvriel** [comment]
Yes it can! Thanks!
