### ISSUE TITLE
Move from phpstan level 5 to level 6

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2216]
In the past few months, phpDocumentor has been pushing to upgrade the quality of the codebase by introducing tools such as phpstan. We have made enough fixes to get to phpstan level 5 and would like help to get to phpstan 6, and eventually to max level.

This specific ticket is for getting to phpstan level 6.

**Comment by orklah** [comment]
This has been solved, it could be closed :)
