### ISSUE TITLE
Generate blank documentation (skeleton) in laravel

### ISSUE THREAD

**Issue by Camelia2020** [phpDocumentor/phpDocumentor#2219]
When use phpDocumentor for generate document for laravel's project, result is skeleton and document's files are empty. 

Project Terms: 
- Laravel 6
- Latest version of phpDocumentor 

Has this been viewed in the new version? Is there a solution?

**Comment by jaapio** [comment]
Hi @Camelia2020 

Thanks for reaching out and welcome to our project.

The current alpha release has some issues. Especially on windows. You might want to try our latest version on master. Therefore we do provide a nightly build. In the readme you can find some information about the nightly builds. 

But for your convenience here is a link you might want to try: https://github.com/phpDocumentor/phpDocumentor/suites/416830103/artifacts/1302184

Please let me know if this works for you or if you have any problems. I'm here to help.

**Comment by Camelia2020** [comment]
I have an error : 

```
In Description.php line 96:

  Return value of phpDocumentor\Reflection\DocBlock\Description::render() mus
  t be of the type string, bool returned
```

**Comment by mvriel** [comment]
That's wonderful to hear; we are ramping up to a new alpha release so an official release will follow soon. Since your problem seems to be resolved in the meantime I will be closing this issue. Thank you for your report and please do let us know if you have any other questions or concerns
