### ISSUE TITLE
Escape / Tidy HTML descriptions before parsing it with Markdown

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2233]
While testing the new `default` template, I found that including a `<select>` opening tag without a closing tag will gobble up the rest of the description and show an empty select:

![image](https://user-images.githubusercontent.com/193704/73168021-4b256e00-40f9-11ea-87de-d8527424c8de.png)

**Comment by jaapio** [comment]
I fixed this by escaping all html, using parsedown's buildin `saveMode`
