### ISSUE TITLE
v2.9.1 Runs with Error: Uncaught Exception Error: "Class 'Webmozart\Assert\Assert' not found"

### ISSUE THREAD

**Issue by wpx** [phpDocumentor/phpDocumentor#2237]
phpDocumentor v2.9.1 runs with Error: Uncaught Exception Error: "Class 'Webmozart\Assert\Assert' not found"

## Expected Behavior

v2.9.1 to run successfully like v2.9.0 did but issue for #1914 fixed.

## Actual Behavior

I get the following error:

```
[2020-01-27 19:13:25] phpDocumentor.ERROR: Uncaught Exception Error: "Class 'Webmozart\Assert\Assert' not found" at phar://C:/code/repos/github/dhurlburtusa/wtf-component/v0/tools/phpDocumentor/v2.9.1/phpDocumentor.phar/src/phpDocumentor/Plugin/Scrybe/Template/Factory.php line 55 {"exception":"[object] (Error(code: 0): Class 'Webmozart\\Assert\\Assert' not found at phar://C:/code/repos/github/dhurlburtusa/wtf-component/v0/tools/phpDocumentor/v2.9.1/phpDocumentor.phar/src/phpDocumentor/Plugin/Scrybe/Template/Factory.php:55)"} []
Script php ./tools/phpDocumentor/v2.9.1/phpDocumentor.phar run -d src -t docs/api handling the docs:api event returned with error code 255
```

## Your environment

* Version used: 2.9.1
* Install method: PHAR
* php version: 7.3.5
* Operating system and version: Windows 10

**Comment by mvriel** [comment]
:thinking: 

I am quite sure I tested this before releasing. I wonder what went wrong. We'll investigate, thanks!

**Comment by tyranron** [comment]
@mvriel `v2.9.1/phpDocumentor.phar` somehow just misses `vendor/webmozart/` dir. I cannot understand why, because running `composer install` on `v2.9.1` Git tag adds it to `vendor/`. And I also cannot find any CI logs related to this release (not on GitHub Actions, nor on Travis).

**Comment by mvriel** [comment]
In the box.json I need to specify each vendor folder to include when building the PHAR; this must then not be included and I did not see this when testing. I will fix it this evening; I am now at work

**Comment by tyranron** [comment]
@mvriel oh, I see. Would it be a new patch version release, or you're going to update the `v2.9.1` tag?

**Comment by mvriel** [comment]
Since it is a failure in producing the PHAR and nothing in the code itself; I will be replacing the PHAR of 2.9.1

**Comment by mvriel** [comment]
Okay, I just uploaded a new PHAR file. Can you retry it?

**Comment by tyranron** [comment]
@mvriel confirming that it's OK now.

**Comment by mvriel** [comment]
Thanks for verifying it!
