### ISSUE TITLE
v3.0.0-beta: Unable to parse file "admin/imagemeta_to_artikeldownload.php", an error was detected: trim() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor#2254]
happily it now no longer breaks everything but i don't get what can't be parsed here

it's in fact the comment block no matter what and if there is any code
https://pastebin.com/He1vtmdu

**Comment by mvriel** [comment]
At first glance, neither do I see what is wrong. We'd need to dig deeper. As such, I have categorised this issue as a bug to be investigated for v3.0. Thanks for reporting

**Comment by thelounge-zz** [comment]
looks like you don't surivive german umlats (üöä) in ISO-8859-1 comments

**Comment by mvriel** [comment]
@thelounge-zz can you re-run with `-v` and attach the stacktrace? With the provided example I cannot reproduce the issue. 

Can you also attach an example as a php source file to this issue? It may be UTF8 related and pastebin has converted your example to UTF-8; causing my tests to be in the UTF-8 encoding while the issue may be that your files are not in UTF-8 encoding and our conversion process fails.

**Comment by mvriel** [comment]
Ah, I found a way to simulate this seconds after posting my message :) Got it and looking into it

**Comment by mvriel** [comment]
Okay, the issue I found is two-fold:

- Re-encoding support became unavailable during migration from local filesystems to a FlySystem based integration; this needs to be restored

    > phpDocumentor assumes that the contents of files are UTF-8 and otherwise it is recommended for the user to supply the encoding to use since encoding detection is unreliable and messy.

- The DocBlockFactory is the one who fails to parse the DocBlock since it expects Unicode (the 'u' regex modifier is used to properly support non-ascii characters); this failure should be caught and a proper exception emitted instead of trim failing

I will focus on reintroducing encoding conversions; this can take a while to fix however

**Comment by thelounge-zz** [comment]
well, i burnt them with fire in deplyoed codebase long ago, that was customer specific code dating back to 2003 which says a lot about the backward compatibility of my codebase and frameworks :-)

**Comment by thelounge-zz** [comment]
> otherwise it is recommended for the user to supply the encoding

while i "fixed" the code already i wanted to add the encondig and well, it's already there in my default-command likely for ages - seems to be ignored!

PHPDOC_DEFAULT_PARAMS="run --force --quiet --no-debug --cache-folder=/tmp/phpdoc-cache --encoding=ISO-8859-1"

**Comment by mvriel** [comment]
As mentioned above; that is indeed broken in the beta; I am working on the fix :)

**Comment by thelounge-zz** [comment]
ah, i understood it in a way that automatic detection is not available and i am supposed to use the param

however: depsite my rant last year the shape of 3.0.0-beta is pretty good! congratulations!

see my other repots, mostly minor issues including the shebang-one while that's the most annyoing because i can't remove it from shell-scripts, but well, so we have a "Default" package for now :-)

**Comment by mvriel** [comment]
The issue should now be resolved on master; I have done various tests and there is a unit test covering the middleware that covers this behaviour. I want to add a functional test with an actual iso-8859-1 encoded file; but we are migrating away from behat to phpunit for our unit tests so I need to postpone that for a while.
