### ISSUE TITLE
v3.0.0-beta: files with shebang ignores @package

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor#2259]
3.0.0-beta with some love to the docblocks becomes nearly perfect

one remaining issue is that i have a ton files without classes, mostly boilerplate-code with some functions for cronjobs/administration

the files all have their clean docblock with "@package   Serveradministration-Spamfilter" or similar but instead "Home -> Serveradministration -> Spamfilter" they are ending in "Default" with teir functions

as far as i can see it seems that files with "#!/usr/bin/php" before <?php are affected which indicates that shebangs should be removed internally before processing

**Comment by thelounge-zz** [comment]
<?php declare(strict_types=1); is also not loved and ignores @package

**Comment by jaapio** [comment]
From a new test case I added to our test suite it looks like phpDocumentor is not able to process a file containing a shebang at all. Even the file level docblock is not processed. 

Thanks for reporting this. I will try to find why this is happening.

**Comment by thelounge-zz** [comment]
explains why it only got visible due trying to minimize cli params and remove default package name

**Comment by thelounge-zz** [comment]
<?php declare(strict_types=1); as first line before the docblock has the same result - so it looks like everything but "<?php" as first line ends in the same result

"not able to process a file containing a shebang at all" is not entirely correct becuse when the file contains php functions they are part of the generated doc but in the package "Default" - so only the docblock of the file is not processed

**Comment by thelounge-zz** [comment]
<?php declare(strict_types=1); as first line before the docblock has the same result - so it looks like everything but "<?php" as first line ends in the same result

"not able to process a file containing a shebang at all" is not entirely correct becuse when the file contains php functions they are part of the generated doc but in the package "Default" - so only the docblock of the file is not processed

**Comment by thelounge-zz** [comment]
hell what is wrong with github and the "No description provided" nonsense :-(

declare(strict_types=1) as first line before the docblock has the same result (which i would prefer directly after the php-tag in the same line) - it looks like everything but a pure php tag as first line and whatever before the file sdocblock comment ends in the same result

"not able to process a file containing a shebang at all" is not entirely correct becuse when the file contains php functions they are part of the generated doc but in the package "Default" - so only the docblock of the file is not processed

**Comment by jaapio** [comment]
This will require some additional tests. Working on that as well.

**Comment by jaapio** [comment]
I added a fix in phpDocumentor/reflection to solve this. Files starting with a shebang and `declare` node are now processed correctly by that library. It will be added into our master branch here soon.

**Comment by jaapio** [comment]
Fix has been added to the master branch. And will be part of the next release

**Comment by thelounge-zz** [comment]
a phar download would be cool to verify

**Comment by mvriel** [comment]
@thelounge-zz the phar file on [this page](https://github.com/phpDocumentor/phpDocumentor/actions/runs/36264814) contains both this fix and the fix for the iso-8859-1 encoding

**Comment by jaapio** [comment]
You could try to download the nightly build as described in the Readme.
I don't want to create a release right now since we are working on some other fixes.
It should not take an other year :grin: to get a release ready.

Let me know if you need help with the nightly download.

**Comment by thelounge-zz** [comment]
"phpDocumentor 2750564" looks *fucking good* and brings also @todo back to the documentation, this one solves *any* of my issues and since phpDocumentor.phar is part of my meta-project folder if have all i need no matter when you feel it#s time for a realse - THANK YOU!

i moved all strict-types declarations into the first line with the php-tag which makes it so much easier with "kfind" seaching for "<?php" and find missing ones because it shows the first occurrence without open any file

no longer anything falls into "Default" package in the deployed tree, it still is shown but that is https://github.com/phpDocumentor/phpDocumentor/issues/2255#issuecomment-581163953

-------------------------------------

one case in a customer project where the functions are falloing into "Default" package instead "ContentLounge" -> "AFI" which is solved by move the strict_types declaration to the first line

 strange side effect given that before this didn't work at all and there are pretty sure files with that style and so worth to look to not break code of other projects for phpdoc out there

https://pastebin.com/Yf5zvBLX

-------------------------------------

Tag "see" with body "@see setByteOrder, getByteOrder" has error "\setByteOrder," is not a valid Fqsen.

i can live without @see Tags pretty fine, that's an external library and i am pretty sure bind that tag to a valid Fqsen is wrong - for me this would be some completly free description with a link to a website or whatever

but hey, it's part of the documentation now below errors which is pretty fine

-------------------------------------

@example form "phpmailer" should be handeled like @see above and why phpmailer's SMTP class falls into "Default" is unclear for me, but that's 3rd party stuff not that important from my personal point of view at the moment

20:19:11 ALERT     [app]   Unable to parse file "global_class.phpmailer.php", an error was detected: The tag "@example ['List-Unsubscribe', 'List-Help']" does not seem to be wellformed, please check it for errors
20:19:11 ALERT     [app]   Unable to parse file "global_class.phpmailer.php", an error was detected: The tag "@example ['List-Unsubscribe', 'List-Help']" does not seem to be wellformed, please check it for errors
0:01.79

**Comment by thelounge-zz** [comment]
for phpmailer you simply can download the rpm from https://koji.fedoraproject.org/koji/buildinfo?buildID=1421176 and unpack it on a fedora/centos machine or try https://github.com/PHPMailer/PHPMailer directly (the global_class.phpmailer.php is just a file renaming to make my autoloaders and shim-layer happy)

**Comment by jaapio** [comment]
Thanks I glad to hear that phpdocumentor is working well for you!
We are working on the issue of the example tag. Because it is important to support the format you are describing.

Thanks for all your feedback we do really appreciate your input. Please let us know if you have any issues with phpdocumentor. We are looking forward to help you whenever we can.

**Comment by thelounge-zz** [comment]
i say thank you for the shape we have no and sorry for my tourette outburst last december after give it a try again and practically completly non working

i am developer long enough to know that tiny little stuff can have that results and make something look linke completly uneusable while on the other hand i am sure that in the last weeks some real hard work pushed it from a disappointing state to "well, ehere and there some coesmetics but cool stuff" and it's impressing fast compared a few years ago

AFI - Technische Referenz
0:04.34

ContentLounge - Technische Referenz
0:07.72

Globale Includes - Technische Referenz
0:01.88
