### ISSUE TITLE
PhpStan bump

### ISSUE THREAD

**Issue by orklah** [phpDocumentor/phpDocumentor#2266]
I started running Psalm on phpDocumentor and I have some improvement to push, but first I'd like to bump PhpStan at least on 0.12.4 to have access to list<> type and removing every @phpstan- array<int,> that I had to put everywhere before. A new version is out since yesterday so while I'm at it, I could try to push that one.

How shoud I proceed? Should I go to each phpDocumentor and run PhpStan on last version and ensure this won't break builds? Then we'll be able to bump the version on your QA tool?

**Comment by jaapio** [comment]
The first step was to create a separate repo for our code style. Second one on the list is a new phpstan setup. I'm currently working on that. It should not be as hard as the code style. So it will be finished soon. 
If that's done we should be able to bump phpstan per repo :-)

**Comment by orklah** [comment]
Great! I look forward to it!

Keep me updated, I'll try to fix new issues in repos if they appear

**Comment by jaapio** [comment]
Ok, the new phpstan action is available now. Check https://github.com/phpDocumentor/phpstan-ga for all versions. You should now be able to run phpstan 0.12.9 in the pipeline 

You may want to revert this commit: https://github.com/phpDocumentor/phpDocumentor/commit/98489536400acfb81540d3edbe165a2ce78680fb
Let me know if you have any questions or issues
