### ISSUE TITLE
Inform user that a new version is available

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2281]
In order to assist users to determine when it is time to upgrade phpDocumentor, we want to show a message at the start when the installed version is older than the latest tagged release on Github.

This determination should only look within the same major version; and if multiple releases have been done since the installed version show an elevated error instead of merely a warning.

**Comment by mvriel** [comment]
This is being addressed in PR https://github.com/phpDocumentor/phpDocumentor/pull/2283

**Comment by ADmad** [comment]
Isn't subscribing to Github releases a good enough way to be notified about new releases? If one has installed using composer then then can use `composer outdated` to check for new version of packages.

Personally I wouldn't want my docs generation tool to connect to the net to check for new version availability unless I explicitly ask it to.
