### ISSUE TITLE
Please revert the drop of XML template

### ISSUE THREAD

**Issue by redaxmedia** [phpDocumentor/phpDocumentor#2292]
Hello folks,

I'm pretty sure there is a good reason you removed the XML template and XML writer.

Anyway, the documentation of my CMS is based on the structure.xml - I was forced to use `dev-master` for years as 2.x does not support latest PHP versions.

I'm super happy to see that you finally release 3.x but removing the XML support now puts me in the super bad situation that my website no longer has API docs.

So... Please consider to revert that decision.

Thank you

**Comment by mvriel** [comment]
We needed to radically simplify the codebase in order to ensure we can maintain the project with the capacity that we have, and focus on the pivot that we want to do to be able to be a provider of all sorts of documentation.

One of the things I am considering is to reintroduce the generation of the structure.xml not by reintroducing the XML writer; but by adding a twig-based template that renders XML output.

I have proposed this in the team and we are currently taking this course into consideration. I will update this issue as soon as there is a clear decision

**Comment by redaxmedia** [comment]
> We needed to radically simplify the codebase in order to ensure we can maintain the project

I am 100% with you guys

In case you want my support for development. It needs just a scaffolding test with basic setup and I can work against this using the TDD approach.

**Comment by oliverschloebe** [comment]
+1 for bringing back the `structure.xml` file.

**Comment by jaapio** [comment]
If the referenced commit build passes a nightly build should be available in github actions for download. It will contain a new template named xml. which will give you the structure file like you had before. 
Please let me know if this fits your needs.

**Comment by jaapio** [comment]
https://github.com/phpDocumentor/phpDocumentor/suites/504075807/artifacts/2606839 the download can be found here.

**Comment by oliverschloebe** [comment]
@jaapio Thanks so much for bringing the `structure.xml` file/template back!

After a quick run I noticed the line numbers not being correctly filled, e.g. `<docblock line="">` is either empty or `0` when parsing the WordPress trunk which worked before. Same for `<argument line="">` tags.

**Comment by jaapio** [comment]
Thanks for your feedback. I will investigate what is going on.

**Comment by oliverschloebe** [comment]
> Thanks for your feedback. I will investigate what is going on.

Thank you! If you need both the new and older `structure.xml` files (containing data from the same project) for comparison reasons, just let me know.

**Comment by jaapio** [comment]
The old file will help me to see the differences easier.

**Comment by oliverschloebe** [comment]
https://send.firefox.com/download/5467e7c0cfbde622/#XP4JlflFbYCehSzE9FXTtQ :v: 
_(FYI, expires after 5 downloads or 7 days)_

**Comment by oliverschloebe** [comment]
As for the missing line numbers and `<argument>` nodes in the `<function>` nodes this line has an error: https://github.com/phpDocumentor/phpDocumentor/blob/d0535baf35e768c285c4273cb5cc473d16aa9816/data/templates/xml/structure.xml.twig#L21

should be
```twig
{{ include('docblock.xml.twig', {descriptor: function}) }}
```
The `<argument>` nodes are still faulty, even though the `argument.xml.twig` template looks fine to me (from a noob perspective).

**Comment by jaapio** [comment]
I fixed a number of issues in the xml template. The output is not 100% equal to what you got from v2, as said before a lot has been changed.

Please report new issues when you are missing something in the new template. I'm closing this one because everything that has been asked for is now done. We are working towards a v3 final release, and after that more stable releases will follow in a shorter time. Allowing us to add information to the template and fix issues you are reporting. 

Thanks for all the feedback you gave until now, I'm looking forward to seeing new issues coming whenever you have a problem with phpDocumentor.

**Comment by oliverschloebe** [comment]
Thanks @jaapio for your work so far! ❤️ I'll be testing your changes soonish and will open new tickets when necessary (and maybe even provide fixes myself).

Thanks again for bringing `structure.xml` back!

**Comment by redaxmedia** [comment]
@jaapio You took the evidence to care about the community, thank you so much for listening.

I was able to generate the [API documention](https://redaxscript.com/api) for my CMS based on the master branch of phpDocumentator. Looking forward to the next release candidate!

Bug report: Type and Description are missing for the fields / properties of classes.

**Comment by jaapio** [comment]
Without a community we are nowhere. I'm doing this work just for people like you. Not listening is not an option.

Could you please report a new issue for the bug you found? I won't be able to fix it quite soon. And I might forget to do that.

**Comment by janareddymareddy** [comment]
HI,

i also using structure.xml generated by phpDocumentor in custome pages.

we planned to upgtade from old version, just installed V3.0.0 using composer and tried to generate structure.xml by passinf --template=xml.

but i noticed few tags are missing in the xml file. inside <class> tag <properties> and <method> tags are missed.

the command what i am executing is like this 

phpdoc project:run -t C:\Users\jrm\AppData\Local\Temp/phpDocumentor3 -d "E:\webportal_master\webportal\WebPortal\Portal" -c "E:\webportal_master\webportal\WebPortal\Build/phpdoc.distv3.xml" --template=xml'

if i am wromg please let me know.

**Comment by jaapio** [comment]
@janareddymareddy could you please open a new issue for this? This issue has been closed about a year ago.. nobody will ever track this. your command looks good to me. 

At the moment I do not have time to fix this issue.  If you can create a PR that would be awesome. The new xml template can be found here: https://github.com/phpDocumentor/phpDocumentor/tree/master/data/templates/xml

If you copy the contents of this directory and use the path to your local directory you should be able to do local modifications to the template. Most likely you will have to fix something in: https://github.com/phpDocumentor/phpDocumentor/blob/master/data/templates/xml/docblock.xml.twig

Thanks in advance.
