### ISSUE TITLE
Ignored folders are still accessed and it can cause a permission error

### ISSUE THREAD

**Issue by NicolasCARPi** [phpDocumentor/phpDocumentor#2295]
## Expected Behavior
Using the `--ignore/-i` flag should prevent phpDocumentor to go in that directory entirely.

## Actual Behavior
If we have a directory where the user executing the phpDocumentor process doesn't have right to access, an error will be thrown even if this directory should be ignored.

## Steps to Reproduce the Problem

~~~bash
cd /tmp
mkdir bug && cd bug
# now let's create a forbidden folder
mkdir -m 0700 forbidden
sudo chown root:root forbidden
phpDocumentor run -i forbidden
~~~

The error is thrown by Flysystem from [this file](https://github.com/thephpleague/flysystem/blob/1.x/src/Adapter/Local.php#L495):
ERROR: DirectoryIterator::__construct(./forbidden): failed to open dir: Permission denied

I am not familiar with the codebase enough to go further :)

## Your environment

* Version used: 3.0.0-rc
* Install method: phar
* php version: 7.4.3
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Archlinux

**Comment by jaapio** [comment]
Thanks for reporting this. I upgraded a dependency to fix this issue. We added a fix in FlyFinder to address this issue. The fix is now available in the master branch and will be part of the next release

**Comment by NicolasCARPi** [comment]
Thank you @jaapio for fixing this issue!
