### ISSUE TITLE
Searching documentation

### ISSUE THREAD

**Issue by pflammer** [phpDocumentor/phpDocumentor#2302]
# Feature request: Searchability

Perhaps this already exists in some way or other: is there a way to search the documentation (e.g. class/method names)?

This seems to be one of the most important part of a documentation system (trying to find if a method exists to fit some bill). How do phpDocumentor users do this?

**Comment by jaapio** [comment]
Luckily for you we implemented this already in v3. In our brand new default theme is a search tool implemented.
V3 is in release candidate now. And should be stable enough to be used. 

Please let us know what you think of it.
