### ISSUE TITLE
[phpDocumentor 3] Bug : no classes.svg for classes graphs

### ISSUE THREAD

**Issue by Yivan** [phpDocumentor/phpDocumentor#2306]
Hello,

I was trying to see the class diagram generated by GraphViz, and it seems the v3 of phpDocumentor don't create the image `classes.svg` which should be in the `graphs` directory of the report. `graphs/classes.html` call this image.

All reports where generated on Linux.

I tried with the docker image phpdoc/phpdoc:3.0 and with the phar file too (installing `apt install graphviz` before), and same for both no `classes.svg` are created.
Running verbose mode (-vvv) don't bring any clues and it even says the file is written! But the file is not physically in the `graphs` folder:
```
21:45:22 NOTICE    [app]   Writer Graph  on graphs/classes.svg
21:45:22 NOTICE    [app]   Writer Graph  on graphs/classes.svg
```
It is not a linux file permission problem as all others files/folders of the reports are well created.

So it seems there is a bug somewhere preventing this image to be created.

**I got two side questions please:**
- where is the link to this `classes.html` file on the generated reports home page or somewhere else ? I found the `graphs` directory by navigating directly on the result reports folder, but i imagine there is somewhere an html link on the report to this diagram.
- graphviz is only used for this classes.html page ?

Thanks.

**Comment by jaapio** [comment]
Hi,
Thanks for your report, because we got a lot of questions about the missing graphs in the templates we decided to introduce a new setting mechanism that is not properly documented yet.

When you execute phpdoc add the argument `--setting=graphs.enabled=true` this willl enable our graph feature.

I will keep this issue open to ensure we add the missing docs.

**Comment by Yivan** [comment]
Thanks, it works with this parameter! Yes it should be documented for sure.

Just add too in the documentation that some binaries must be installed : `graphviz` and `plantuml`.

By the way on last debian 10 (buster), plantuml is installed in /user/bin (and not /bin) so a symlink needs to be mannualy created after install. It seems PHPDoc calls directly the binary using transversal path... not really clean and robust. I think it should rely on PATH env variable to execute it. I found this because I get an error just after installing plantuml (so without making the manual symlink):

![image](https://user-images.githubusercontent.com/9025839/76687151-82a49700-6621-11ea-9ae5-8cf4ee1c4e2c.png)

For Debian the way to install binary is:
```
apt-get update && apt-get install -y graphviz plantuml
ln -s  /usr/bin/plantuml /bin/plantuml
```
And with this graphs generate nicely : )

**Comment by filips123** [comment]
Can information that you need to install PlantUML and add symlink also be added to README? PlantUML is separate package and you won't get it if you install just Graphviz. Also, can PHPDoc also fix call to PlantUML so it doesn't depend on specific path?

**Comment by withmorten** [comment]
I have another interesting issue, I get the error that it can't exec plantuml at the following path:

`ERROR     [app] Generating the class diagram failed ["error" => "sh: 1: exec: phar:///home/morten/phpDocumentor.phar/bin/plantuml: not found\n"]`

This obviously is wrong. I run it like this: `./phpDocumentor.phar -d /some/dir -t /some/other/dir --setting=graphs.enabled=true`
