### ISSUE TITLE
needs a dark theme. my eyes are bleeding.

### ISSUE THREAD

**Issue by yoosefi** [phpDocumentor/phpDocumentor#2308]
a computer screen is not a piece of paper. it's a light bulb.

this project has badly needed a monospace dark theme for a long long time.

putting light blue on a white background is a sick joke.

**Comment by jaapio** [comment]
Hi @yoosefi 

I think you are pointing me at the docs that are generated by phpDocumentor? I'm currently working on a part to make it easier for you to customize the css used in the template, so you can add this yourself. 
The new `default` template supports css variables to make it even easier to overwrite the used colors. I will update the docs soon to show you how this can be done.

**Comment by jaapio** [comment]
As said, I added a section on our docs to describe how to change the collors of a template.

https://docs.phpdoc.org/3.0/getting-started/changing-the-look-and-feel.html

Closing this because all that needs to be done is now here.

**Comment by yoosefi** [comment]
i went ahead and started my own documenter instead
