### ISSUE TITLE
@see is not recognized as a special tag in template

### ISSUE THREAD

**Issue by henrotaym** [phpDocumentor/phpDocumentor#2311]
I'm using the release candidate 3.0 version and I can't use the tag @see properly.

    /**
     * Setting up OVH client and IsoConverter.
     * @see \App\Voip\CountryToIso
     */
    public function __construct(CountryToIso $isoConverter)
    {
        $this->isoConverter = $isoConverter;
        $this->setClient();
    }

## Expected Behavior
I should have a specific section like 'see also' with a link to the other class(which is documented and included during build).

## Actual Behavior
@see is not recognized and content is added to the tags section without showing anything.
![image](https://user-images.githubusercontent.com/24230736/76645997-6ab61000-655a-11ea-9e2a-c1c935059357.png)

## Steps to Reproduce the Problem

  1. Create a dockblock for any class method
  2. Add @see tag referencing a different class
  3. Generate documentation

## Environment

* Version used: 3.0.0-rc
* Install method: using phar
* Theme: default
* php version: 7.4.3
* Operating system: windows 10

**Comment by jaapio** [comment]
Thanks for reporting this, as the other issues you reported about tag rendering this item is fixed in our master branch. There is a build available to see if we accually covered all your needs. please consult the readme for info how to get this phar build.
