### ISSUE TITLE
@uses tag is not recognized as it should

### ISSUE THREAD

**Issue by henrotaym** [phpDocumentor/phpDocumentor#2312]
I'm using the release candidate 3.0 version and I can't use the tag @uses properly.

    /**
     * Remove professional from number given.
     * @uses \App\Voip\CountryToIso Getting professional iso code from country.
     */
    public function removeProfessionalFromVoip(string $number): array
    {

## Expected Behavior
I should have a specific section like 'using' with a link to the other class(which is documented and included during build). The linked class should have a link to this one.

## Actual Behavior
@uses is not recognized and content is added to the tags section showing only description. The other class don't get any link to this one.

![image](https://user-images.githubusercontent.com/24230736/76648170-74da0d80-655e-11ea-9f7f-bcf87cf165c9.png)

## Steps to Reproduce the Problem

  1. Create a dockblock for any class method
  2. Add @uses tag referencing a different class
  3. Generate documentation

## Environment

* Version used: 3.0.0-rc
* Install method: using phar
* Theme: default
* php version: 7.4.3
* Operating system: windows 10

**Comment by jaapio** [comment]
Thanks for reporting this, as the other issues you reported about tag rendering this item is fixed in our master branch. There is a build available to see if we accually covered all your needs. please consult the readme for info how to get this phar build.

**Comment by henrotaym** [comment]
There's only one missing point. There's no automatic 'used-by' tag in the linked class.
