### ISSUE TITLE
[PropertyInfo] Not compatible with symfony v5 

### ISSUE THREAD

**Issue by JHoelzel** [phpDocumentor/phpDocumentor#2317]
Hey guys,
while updating from 4.3 to current i get a couple of these:
`Error: Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\InvalidTag::getType()

.../vendor/symfony/property-info/Extractor/PhpDocExtractor.php:145`

so basically iam using unexpected tags

## Expected Behavior
my tags should be ignored

## Actual Behavior
the tag is failing and throwing an error

## Steps to Reproduce the Problem

   /**
     * @var []Person
     * @Assert\Count(minMessage="form.trial_create.persons_minimum", min=1)
     */

## Your environment
"Aws\Symfony\AwsBundle"
"Symfony\Bundle\DebugBundle\DebugBundle"
"Doctrine\Bundle\DoctrineBundle\DoctrineBundle"
"Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle"
"Symfony\Bundle\FrameworkBundle\FrameworkBundle"
"Knp\Bundle\GaufretteBundle\KnpGaufretteBundle"
"Symfony\Bundle\MakerBundle\MakerBundle"
"Symfony\Bundle\MonologBundle\MonologBundle"
"Nelmio\ApiDocBundle\NelmioApiDocBundle"
"Symfony\Bundle\SecurityBundle\SecurityBundle"
"Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle"
"Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle"
"Symfony\Bundle\TwigBundle\TwigBundle"
"Symfony\Bundle\WebProfilerBundle\WebProfilerBundle"
"Symfony\Bundle\WebServerBundle\WebServerBundle"

PHP Configuration
7.2.26 -1+ubuntu16.04.1+deb.sury.org+1
PHP version
64 bits
Architecture
n/a
Intl locale
Europe/Berlin
Timezone

its WSL if it matters

## Fix
in .../vendor/symfony/property-info/Extractor/PhpDocExtractor.php:145

replace the line in phpdoc extractor
from
` if ($tag!= null && null !== $tag->getType()) `
 with 
`if ($tag!= null && !is_a($tag, 'phpDocumentor\Reflection\DocBlock\Tags\InvalidTag') &&null !== $tag->getType()) `

## personal flavor:
i added 
`  if(is_a($tag, 'phpDocumentor\Reflection\DocBlock\Tags\InvalidTag')){
                throw new \InvalidArgumentException(sprintf('The Tag: "%s"is not a valid tag.', $tag));
            }`

to identify my tags

**Comment by jaapio** [comment]
As said on the referenced symfony issue, this is a change by purpose. Let's continue the discussion there.

**Comment by JHoelzel** [comment]
OK =) although i think a more explicit error message would be nice but i agree that a "is_a" call ist costly.

**Comment by jaapio** [comment]
The more explicit message is now available, before these tags were just silently ignored. All that needs to be done is extract the message from the invalidtag object. An explicit error would break the parsing of docblocks which you don't want to have in all cases.

**Comment by JHoelzel** [comment]
thank you very much! and Super quick too!
