### ISSUE TITLE
Some options of 'phpdoc.dist.xml' config file are ignored when building docs

### ISSUE THREAD

**Issue by henrotaym** [phpDocumentor/phpDocumentor#2319]
I'm trying to use 'phpdoc.dist.xml' as my config file. But I can't make it work, it seems like it's parsed but ignored for some options.

``` xml <?xml version="1.0" encoding="UTF-8" ?>
<phpdoc>
    <title>Voip documentation</title>
    <parser>
        <target>./phpdoc/cache</target>
        <extensions>
            <extension>php</extension>
        </extensions>
        <visibility>
            <item>public</item>
        </visibility>
    </parser>
    <transformer>
        <target>./public/docs</target>
    </transformer>
    <transformations>
        <template name="clean" />
    </transformations>
    <files>
        <directory>./app</directory>
    </files>
</phpdoc>
```

- Cache is built at the right location (working as expected)
- Documentation is built at right location (working as expected)
- only app folder is parsed (working as expected)

## Expected Behavior
 - I should have the 'clean' template
 - I should have only public elements, not protected ones
 - I may be wrong but I think title in the left upper part of template should be 'Voip documentation' too.

## Actual Behavior
- Template is default
- I have public and protected elements
- Title is default one ('documentation')

## Steps to Reproduce the Problem

  1. Create a 'phpdoc.dist.xml'
  2. run phpdoc command

## Your environment

* Version used: 3.0.0-rc
* Install method: using phar file
* php version: 7.4
* Operating system: windows

**Comment by lcharette** [comment]
I can confirm the title issue. 

- Version used: 3.0.0-rc
- Install method: using phar file
- php version: 7.3
- Operating system: Linux

**Comment by redcuillin** [comment]
FYI, in addition to the bugs outlined in the OP, I have found that <ignore> within <files> section also does not work. Not logging as a separate bug as appears to be covered under the title of this one.

Example: 
```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdoc>
	<title>Project Name</title>
	<parser>
		<target>docs</target>
	</parser>
	<transformations>
		<template name="responsive" />
	</transformations>
	<transformer>
		<target>docs</target>
	</transformer>
	<files>
		<directory>path</directory>
		<directory>path2</directory>
		<ignore>*/ignore_me/*</ignore>
		<ignore>*/ignore_me2/*</ignore>
	</files>
</phpdoc>
```
==Expected behaviour:==
(In addition to the bugs already mentioned in the original bug report): Any directories called 'ignore_me' or 'ignore_me2' should be excluded from documentation and not be processed by the parser.

==Actual behaviour:==
Directories are parsed and output in the documentation. Errors mentioned in the bug report are also seen.

**Comment by oliveratgithub** [comment]
Additionally in v3.0.0-rc it is **no longer supported to specify output pathes and file names for log-files** under `<logging>`.

### Example
```
	<logging>
		<level>warn</level>
		<paths>
			<default>/var/log/phpdoc/{DATE}.log</default>
			<errors>/var/log/phpdoc/{DATE}.errors.log</errors>
		</paths>
	</logging>
```
### Actual behaviour
The settings `<paths>...</paths>` throws an Error while parsing the XML-Config, mentioning that his is not an allowed setting to be used under `<logging>`.

### Environment
* Version used: v3.0.0-rc
* Install method: phpDocumentor.phar
* php version: PHP 7.3.11 (cli) (built: Apr  3 2020 08:00:20) ( NTS )
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS 10.15.5 Beta (19F62f)
* Link to your project: [zorgch/zorg-code/tree/upgrade-php-7.x](https://github.com/zorgch/zorg-code/tree/upgrade-php-7.x)

**Comment by oliveratgithub** [comment]
Also the parameter

```
<phpdoc>
    <title>My Code docu</title>
```

seems not to be applied within a theme. Tested with the "clean" theme.

Output for twig placeholder `{{ project.name }}` is just empty/blank.

**Comment by jaapio** [comment]
The latest build: https://github.com/phpDocumentor/phpDocumentor/suites/653832724/artifacts/5657511 should fix the issue for `title` and `template` 

I need to fix the visibility issue. But that's work in progress.

**Comment by jaapio** [comment]
I think everything in this issue is now covered. 

The only issue left, is the log location. phpDoc v3 will not support log locations. Feel free to open a new issue to discuss that. 

Thanks for reporting all of this, to everyone involved in this issue.
