### ISSUE TITLE
@since & @version

### ISSUE THREAD

**Issue by daruiz31** [phpDocumentor/phpDocumentor#2324]
I'm working with responsive-twig
I am using version 3.0.0

I have a problem with labels @ since and @ version
if I put only the number is not shown

`/**
	 * Función para la creación de pdf voucher/imprimibles. 	 
	 * 
	 * @package		Contingencia 
	 * @subpackage	Controllers	
	 * @category	Function
	 * @access 		public
	 * @version     V 1.0.0	 <<<<<<<<<<<<<<<------------- here
	 * @return 		array $data_pdf :: [ $hc_pdf , $data_voucher, $direccion, $tipo_imp ]
	 */
`

if version or since is @ version something 1.0.0 works
if version or since is @ since 1.0.0 it does not work

[Image](https://ibb.co/b2hwkf5)

**Comment by jaapio** [comment]
Hi,

Thank for your report. I think this is not an issue in phpdocumentor but in the way you are using the version tag. The format of the version tag is `@since [version] [<description>]` 
The version should start with a number.
