### ISSUE TITLE
v3.0.0-rc: "Search result" links are broken on index.html page

### ISSUE THREAD

**Issue by scrawlon** [phpDocumentor/phpDocumentor#2326]
This issue is specifically related to using the Search form on the main index.html page. When searching from the index.html page, the search results links are broken.

However, when using the Search form on any internal page (ex. /reports/errors.html), the search results links are correct.

This appears to be related to the file searchIndex.js . Here's an example from a test project:

```javascript
Search.appendIndex(
    [
        {
            "fqsen": "\\myFunction\u0028\u0029",
            "name": "myFunction",
            "summary": "A\u0020summary\u0020informing\u0020the\u0020user\u0020what\u0020the\u0020associated\u0020element\u0020does.",
            "url": "../namespaces/default.html#function_myFunction"
        },                
        {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "../namespaces/default.html"
        }            
    ]
);
```

It seems the relative URLs don't work when viewing index.html .

## Your environment

I'm using version v3.0.0-rc in OS X 10.13.6 and Windows 10 environments.

Let me know if you need any other info. Thanks.

**Comment by jaapio** [comment]
Related to #2493

**Comment by mvriel** [comment]
I have linked the relevant PR; as soon as that is merged, this issue will be closed
