### ISSUE TITLE
use statement in traits is ignored.

### ISSUE THREAD

**Issue by Dragonrun1** [phpDocumentor/phpDocumentor#2328]
## Expected Behavior
That trait show the other traits they use just like classes do.

## Actual Behavior
No uses for traits that use other traits.

## Steps to Reproduce the Problem

  1. Create docs for my project at https://github.com/Dragonrun1/uuid64type
  2. Compare output from Uuid64Generator to Uuid64NGId

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpful if you link to your project
or add any code that is involved in to the issue.

* Version used:  v3.0.0-rc (phar)
* php version: PHP 7.3.15 (cli) (built: Feb 18 2020 12:44:23) ( NTS MSVC15 (Visual C++ 2017) x64 )
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10 Home
![Uuid64Generator2020-04-07](https://user-images.githubusercontent.com/1431541/78732702-31be5080-78f8-11ea-91d0-b0e0a90ed244.png)
![Uuid64NGId2020-04-07](https://user-images.githubusercontent.com/1431541/78732704-32ef7d80-78f8-11ea-94dc-f5e024330606.png)

**Comment by jaapio** [comment]
This issue is releated to: https://github.com/phpDocumentor/TypeResolver/issues/82

Since this is not a phpDocumentor issue I'm closing this one. Please track the related issue to see if this issue is solved
