### ISSUE TITLE
Remove/fix count() warning on main doc page.

### ISSUE THREAD

**Issue by steven7mwesigwa** [phpDocumentor/phpDocumentor#2333]
Why I'm I receiving this warning on my doc page.

`Warning: count(): Parameter must be an array or an object that implements Countable in phar:///Applications/XAMPP/xamppfiles/htdocs/xxx-xx/phpDocumentor/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1293 Warning: count(): Parameter must be an array or an object that implements Countable in phar:///Applications/XAMPP/xamppfiles/htdocs/xxx-xx/phpDocumentor/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1293`

## Your environment
* Version used: v3.0.0-rc
* Install method : Using the PHAR
* php version : 7.3
* Operating system and version (Windows 10):
![phpdocumenter-warning-count](https://user-images.githubusercontent.com/24929438/79751894-0d14a080-831c-11ea-8842-8a1ed04ff191.png)

**Comment by jaapio** [comment]
I need more information to help you. 

But since the latest release is a bit outdated I think you might want to give the latest build a try:
https://github.com/phpDocumentor/phpDocumentor/suites/653832724/artifacts/5657511

**Comment by steven7mwesigwa** [comment]
@jaapio  I have tried using the latest build you suggested and it appears that the 'warning' in particular has disappeared.

Everything is fine now. Thanks for the link.

I believe the 'issue' can now be closed.
