### ISSUE TITLE
v3.0.0-rc: Template setting from XML-Config is not recognised nor applied

### ISSUE THREAD

**Issue by oliveratgithub** [phpDocumentor/phpDocumentor#2334]
## Expected Behavior
Using

```
<phpdoc>
…
	<transformations>
		<template name="clean" />
	</transformations>
…
```
should parse the phpDocu using the `clean`-template

## Actual Behavior
Specifying a template, e.g. `clean`, within a custom XML-config file, does not apply this template – but falls back to the default template instead.

It works to change the template for the phpDocu output on the command line only, by adding something like: `php ./phpDocumentor.phar … --template="clean"`

## Steps to Reproduce the Problem

  1. Add a custom phpDocu XML-Config File including a `<transformation><template name="template-name"></transformation>` setting
  2. Run the phpDocumentor PHAR using `php ./phpDocumentor.phar -c /path/to-phpdocu/custom_config.xml`
  3. Open the `index.html` within the generated phpDocu directory, the template used is not the `clean`-template.

Also check out the examples - especially "_Apendix B_" on the official phpDocu-website: [docs.phpdoc.org/latest/references/configuration.html](https://docs.phpdoc.org/latest/references/configuration.html)

## Your environment

* Version used: v3.0.0-rc
* Install method: phpDocumentor.phar
* php version: PHP 7.3.11 (cli) (built: Apr  3 2020 08:00:20) ( NTS )
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS 10.15.5 Beta (19F62f)
* Link to your project: [zorgch/zorg-code/tree/upgrade-php-7.x](https://github.com/zorgch/zorg-code/tree/upgrade-php-7.x)

**Comment by NesCafe62** [comment]
Don't know if this can help... I encountered a problem with template config in v3 too. My old was not working:
```
<template>
    <!-- author, description, etc. -->
    <parameters>
        <parameter key="twig-debug">true</parameter>
        <parameter key="twig-extension">TwigExtension\IsTypeExtension</parameter>
  </parameters>
```
So I found somewhere a way:
```
<template>
  <!-- ... -->
  <transformations>
    <transformation writer="twig" source="templates/markdown-pandora/index.md.twig" artifact="README.md">
      <parameter key="twig-debug">true</parameter>
      <parameter key="twig-extension">TwigExtension\IsTypeExtension</parameter>
    </transformation>
  </transformations>
</template>
```

**Comment by oliveratgithub** [comment]
> So I found somewhere a way

Thanks @NesCafe62 I'll look into this. Can you explain where you got all this information?
Is there somewhere an up-to-date list with all available Templates, Templates Extensions, etc.?

**Comment by NesCafe62** [comment]
Don't remember exactly... Most possible I just looked in default responsive-twig template sources https://github.com/phpDocumentor/phpDocumentor/blob/master/data/templates/responsive-twig/template.xml

**Comment by oliveratgithub** [comment]
Related issue #2319

**Comment by jaapio** [comment]
V3 is using a new config format which is documented in our docs, https://docs.phpdoc.org/3.0/references/configuration.html

we tried to make it possible to use your v2 configs. but we have missed some options. `template` was one of those. 

I think this issue has been fixed. Otherwise, we will keep this in track in issue #2319 since both are targetting the same issue.
