### ISSUE TITLE
PHP Notice:  SplFileInfo::getType(): Unknown file type (0) in vendor\league\flysystem\src\Adapter\Local.php on line 508 and UndefinedMethodError 

### ISSUE THREAD

**Issue by hguenot** [phpDocumentor/phpDocumentor#2337]
I want to make PHP doc of 2 libraries yii2-gftp and yii2-gsftp (`gsftp` depend of `gftp`). So my folder structure is : 

- E:\dev\yii2-lib
  - yii2-gftp
    - vendor
    - Class.php
  - yii2-gsftp
    - vendor
    - OtherClass.php

The two libraries use composer as dependency manager so I need to exclude `vendor` folder.
From base folder (`E:\dev\yii2-lib`) I try multiple commands without success.

## Expected Behavior
Generates PHP for both folders in one location excluding the two vendor path

## Actual Behavior
As explain, from base folder (`E:\dev\yii2-lib`) I try multiple commands without success : 

1. `php D:\phpDocumentor\phpDocumentor.phar --directory=yii2-gftp --ignore=vendor --target=doc\gftp --verbose`
   This result in various error.
   The most significant are : 
   - PHP Notice
     ```
     PHP Notice:  SplFileInfo::getType(): Unknown file type (0) in phar://D:/phpDocumentor/phpDocumentor.phar/vendor/league/flysystem/src/Adapter/Local.php on line 508
     ```
   - UndefinedMethodError : 
     ```
     [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]
     Attempted to call an undefined method named "getMethods" of class "phpDocumentor\Reflection\Fqsen".
     ```
   See [command-1.log](https://github.com/phpDocumentor/phpDocumentor/files/4514281/command-1.log) for full log

2. `php D:\phpDocumentor\phpDocumentor.phar --directory=E:\dev\yii2-lib\yii2-gftp --ignore=E:\dev\yii2-lib\yii2-gftp\vendor --target=doc\gftp --verbose`
   This fail also. PHP Notice disappear but the `UndefinedMethodError` error remains.
   See [command-2.log](https://github.com/phpDocumentor/phpDocumentor/files/4514308/command-2.log) for full log

3. `php D:\phpDocumentor\phpDocumentor.phar --directory=E:\dev\yii2-lib\yii2-gftp --ignore=vendor --target=doc\gftp --verbose`
   This works well but I generate documentation for only one library.
   One non intuitive thing : I need to put full path to `--directory` option but relative for `--ignore` option
   See [command-3.log](https://github.com/phpDocumentor/phpDocumentor/files/4514321/command-3.log)

4. `php D:\phpDocumentor\phpDocumentor.phar --directory=E:\dev\yii2-lib\yii2-gftp --directory=E:\dev\yii2-lib\yii2-gsftp --ignore=vendor --target=doc\gftp --verbose`
   This fails :
   - phpDocumentor generate sources from the second `vendor` folder (`E:\dev\yii2-lib\yii2-gftp`) - in fact only the subfolders not in the first `vendor` folder.
   - the PHP notices and the `UndefinedMethodError` error appear again.
   See [command-4.log](https://github.com/phpDocumentor/phpDocumentor/files/4514363/command-4.log)
   remark, if I invert the `--directory` options, the `vendor` folder as correctly ignored (suppose because the "subfolders diff" is empty in that case) 

## Steps to Reproduce the Problem

1. Clone the two libraries in the same folder:
   - [hguenot/yii2-gftp](https://github.com/hguenot/yii2-gftp)
   - [hguenot/yii2-gsftp](https://github.com/hguenot/yii2-gsftp)
2. See sample commands above

## Your environment
* Version used: v3.0.0-rc
* Install method: phar
* php version: 
   ```
   PHP 7.3.5 (cli) (built: May  1 2019 13:17:17) ( ZTS MSVC15 (Visual C++ 2017) x64 )
   Copyright (c) 1997-2018 The PHP Group
   Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
   ```
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Window 10
* Link to your project:
  - [hguenot/yii2-gftp](https://github.com/hguenot/yii2-gftp)
  - [hguenot/yii2-gsftp](https://github.com/hguenot/yii2-gsftp)

**Comment by jaapio** [comment]
phpdocumentor is using a git ignore like notation to ignore directories. When no wildcards (`*`) are defined and no paths are defined we consider that the provided ignore is relative to the current working directory or if provided relative to the config file. 

`php D:\phpDocumentor\phpDocumentor.phar --directory=E:\dev\yii2-lib\yii2-gftp --ignore=E:\dev\yii2-lib\yii2-gftp\vendor --target=doc\gftp --verbose` should work. 

the issue you have with the undefined method should be fixed in this build: https://github.com/phpDocumentor/phpDocumentor/suites/653832724/artifacts/5657511

Please let me know if the issue still persist when you are using that build. 

I could not install your projects due a version issue in the composer.json. 

The current corona situation is slowing down the team. So a new release will have to wait, unfortunately.

**Comment by jaapio** [comment]
Closing because we have everything covered. Feel free to open an issue when the problem persists.
