### ISSUE TITLE
v3.0.0-rc: phpDocumentor.phar with PHP PSR extension is not working

### ISSUE THREAD

**Issue by dmarkic** [phpDocumentor/phpDocumentor#2351]
## Expected Behavior
phpDocumentator.phar should run

It works if I clone the v3.0.0.-rc and run bin/phpdoc -h

## Actual Behavior
PHP Fatal error:  Cannot declare interface Psr\EventDispatcher\EventDispatcherInterface, because the name is already in use in phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/psr/event-dispatcher/src/EventDispatcherInterface.php on line 9
PHP Stack trace:
PHP   1. {main}() /home/dejan/phpdoc3/phpDocumentor.phar:0
PHP   2. require() /home/dejan/phpdoc3/phpDocumentor.phar:14
PHP   3. phpDocumentor\Console\Application->run() phar:///home/dejan/phpdoc3/phpDocumentor.phar/bin/phpdoc:43
PHP   4. phpDocumentor\Console\Application->doRun() phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/symfony/console/Application.php:140
PHP   5. phpDocumentor\Console\Application->registerCommands() phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:75
PHP   6. phpDocumentor\Kernel->boot() phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/symfony/framework-bundle/Console/Application.php:169
PHP   7. phpDocumentor\Kernel->initializeContainer() phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/symfony/http-kernel/Kernel.php:126
PHP   8. ContainerU0GhpWI\phpDocumentor_KernelProdContainer->set() phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/symfony/http-kernel/Kernel.php:439
PHP   9. ContainerU0GhpWI\phpDocumentor_KernelProdContainer->ContainerU0GhpWI\{closure:phar:///home/dejan/phpdoc3/phpDocumentor.phar/var/cache/prod/ContainerU0GhpWI/phpDocumentor_KernelProdContainer.php:68-131}() phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/symfony/dependency-injection/Container.php:150
PHP  10. include_once() phar:///home/dejan/phpdoc3/phpDocumentor.phar/var/cache/prod/ContainerU0GhpWI/phpDocumentor_KernelProdContainer.php:75
root@develop:/home/dejan/phpdoc3# ./phpDocumentor.phar --help
PHP Fatal error:  Cannot declare interface Psr\EventDispatcher\EventDispatcherInterface, because the name is already in use in phar:///home/dejan/phpdoc3/phpDocumentor.phar/vendor/psr/event-dispatcher/src/EventDispatcherInterface.php on line 9

## Steps to Reproduce the Problem

  1. Install psr.so php extension
  2. Run phpDocumentator.phar
  3.

## Your environment

I've tested:
* https://github.com/phpDocumentor/phpDocumentor/releases/tag/v3.0.0-rc
* https://github.com/phpDocumentor/phpDocumentor/actions/runs/64641141

* Version used: 3.0.0-rc
* Install method: Download 3.0.0-rc and latest
* php version: PHP 7.3.14-1~deb10u1
* Operating system and version: Debian 10.3

**Comment by jaapio** [comment]
Thanks for reporting this, I don't have a short term solution for this particular issue. Since the PSR extension is not an official PHP extension we cannot support it. Removing the PSR interfaces from the phar will break it for most other users. 

Since you are running on Debian I can recommend you use the docker image of phpdoc.
`docker run --rm phpdoc/phpdoc:rc` which is running phpdocumentor in isolation. 

Maybe we can scope our phar in the future but that is not possible right now. Since this is a edge case I cannot spend a lot of time to help you out.

**Comment by dmarkic** [comment]
Thanks for the reply. I figured out the problem: I've created by own conf.d directory and I load phar like this with custom conf.d directory (where I've removed psr extension)

```
PHP_INI_SCAN_DIR=~/phpdoc3/ini/conf.d ./phpDocumentor.phar
```
It's an OK solution if some extensions are loaded by default that interfere with what's in phar file.
