### ISSUE TITLE
how can run with phar in windows? 

### ISSUE THREAD

**Issue by Camelia2020** [phpDocumentor/phpDocumentor#2352]
I want run php phpDocumentor.phar in windows for my app folder in laravel. But I get error for syntax. 
php phpDocumentor.phar -t [my code] -d [my result directory] -i [my ignore files] 

Please help me? 
Thank you.

**Comment by jaapio** [comment]
Can you please provide me the syntax error you get and the specs of your system like we are asking when you create a bug report? I don't have enough information right now to help you.

**Comment by Camelia2020** [comment]
Windows 8.1 
Laravel 7.5.2
use php doc in windows with command line

When I run, it gives an error and shows the guide.

**Comment by jaapio** [comment]
I really need more info to help you. Please open a new issue and use the bug issue type and provide as much information as possible. Multiple people used phpdocumentor on windows to I don't think that's the issue. 

I would recommend you to also check our docs https://docs.phpdoc.org/3.0/getting-started/your-first-set-of-documentation.html#running-phpdocumentor
