### ISSUE TITLE
PHPDocumentor Project board word triage/triaged not spelled correctly

### ISSUE THREAD

**Issue by HonkingGoose** [phpDocumentor/phpDocumentor#2356]
## Expected Behavior

Linked project board contains correct spelling for the word triage and triaged.

## Actual Behavior

Linked project board contains misspellings: "traige" or "traiged".

## Steps to Reproduce the Problem

1. Go to https://github.com/orgs/phpDocumentor/projects/
2. The middle card has a project "phpDoc issue traige board", the title and description contain the misspelling.
3. Notice that the word traige is not spelled the way it should be.

## Your environment
Firefox browser

**Comment by jaapio** [comment]
is has been fixed. Thanks
