### ISSUE TITLE
No errors, no Markers

### ISSUE THREAD

**Issue by guenneguezt** [phpDocumentor/phpDocumentor#2392]
I use :
phpDocumentor v3.0.0-beta
PHP 7.2.10
When I run "phpdoc run", there is no errors detected.
There is lot off method that are not documented.
Why they aren't detected on error (like with phpDocumentor v2) ?

Thanks

**Comment by mvriel** [comment]
In V3, we have changed a lot in the architecture. This forced us to redo the validation of docblocks completely, and to focus on delivering V3, we have decided to postpone reintroducing that feature.

As for the absence of markers, at the moment markers can only be detected if you enable source code inclusion. Marker scanning is done during the rendering phase and needs the source code to work. By default, source code inclusion is off.

Does it work if you use the --sourcecode flag?

**Comment by guenneguezt** [comment]
Hi
Thanks for reply.
with --sourcecode flag I have :
> PHP Fatal error:  Namespace declaration statement has to be the very first statement or after any declare call in the script in phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Style/SymfonyStyle.php on line 498
> PHP Stack trace:
> PHP   1. {main}() /usr/local/bin/phpdoc2:0
> PHP   2. require() /usr/local/bin/phpdoc2:14
> PHP   3. phpDocumentor\Console\Application->run() phar:///usr/local/bin/phpdoc2/bin/phpdoc:43
> PHP   4. phpDocumentor\Console\Application->doRun() phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Application.php:141
> PHP   5. phpDocumentor\Console\Application->renderRegistrationErrors() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:78
> PHP   6. spl_autoload_call() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
> PHP   7. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
> PHP   8. Composer\Autoload\includeFile() phar:///usr/local/bin/phpdoc2/.box/vendor/composer/ClassLoader.php:322
> 
> Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Style/SymfonyStyle.php on line 498
> 
> Call Stack:
>     0.0002     386096   1. {main}() /usr/local/bin/phpdoc2:0
>     0.1037    2313768   2. require('phar:///usr/local/bin/phpdoc2/bin/phpdoc') /usr/local/bin/phpdoc2:14
>     0.1189    3947520   3. phpDocumentor\Console\Application->run() phar:///usr/local/bin/phpdoc2/bin/phpdoc:43
>     0.1275    4184048   4. phpDocumentor\Console\Application->doRun() phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Application.php:141
>     0.3542    8586656   5. phpDocumentor\Console\Application->renderRegistrationErrors() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:78
>     0.3543    8586656   6. spl_autoload_call() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
>     0.3543    8586736   7. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
>     0.3543    8586736   8. Composer\Autoload\includeFile() phar:///usr/local/bin/phpdoc2/.box/vendor/composer/ClassLoader.php:322
> 
> PHP Parse error:  syntax error, unexpected end of file, expecting '{' in phar:///usr/local/bin/phpdoc2/vendor/symfony/error-handler/Error/FatalError.php on line 89
> PHP Stack trace:
> PHP   1. {main}() /usr/local/bin/phpdoc2:0
> PHP   2. require() /usr/local/bin/phpdoc2:14
> PHP   3. phpDocumentor\Console\Application->run() phar:///usr/local/bin/phpdoc2/bin/phpdoc:43
> PHP   4. phpDocumentor\Console\Application->doRun() phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Application.php:141
> PHP   5. phpDocumentor\Console\Application->renderRegistrationErrors() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:78
> PHP   6. spl_autoload_call() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
> PHP   7. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
> PHP   8. Composer\Autoload\includeFile() phar:///usr/local/bin/phpdoc2/.box/vendor/composer/ClassLoader.php:322
> 
> Parse error: syntax error, unexpected end of file, expecting '{' in phar:///usr/local/bin/phpdoc2/vendor/symfony/error-handler/Error/FatalError.php on line 89
> 
> Call Stack:
>     0.0002     386096   1. {main}() /usr/local/bin/phpdoc2:0
>     0.1037    2313768   2. require('phar:///usr/local/bin/phpdoc2/bin/phpdoc') /usr/local/bin/phpdoc2:14
>     0.1189    3947520   3. phpDocumentor\Console\Application->run() phar:///usr/local/bin/phpdoc2/bin/phpdoc:43
>     0.1275    4184048   4. phpDocumentor\Console\Application->doRun() phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Application.php:141
>     0.3542    8586656   5. phpDocumentor\Console\Application->renderRegistrationErrors() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:78
>     0.3543    8586656   6. spl_autoload_call() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
>     0.3543    8586736   7. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
>     0.3543    8586736   8. Composer\Autoload\includeFile() phar:///usr/local/bin/phpdoc2/.box/vendor/composer/ClassLoader.php:322
> 
> PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
> PHP Stack trace:
> PHP   1. {main}() /usr/local/bin/phpdoc2:0
> PHP   2. require() /usr/local/bin/phpdoc2:14
> PHP   3. phpDocumentor\Console\Application->run() phar:///usr/local/bin/phpdoc2/bin/phpdoc:43
> PHP   4. phpDocumentor\Console\Application->doRun() phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Application.php:141
> PHP   5. phpDocumentor\Console\Application->renderRegistrationErrors() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:78
> PHP   6. spl_autoload_call() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
> PHP   7. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
> PHP   8. Composer\Autoload\includeFile() phar:///usr/local/bin/phpdoc2/.box/vendor/composer/ClassLoader.php:322
> 
> Fatal error: Exception thrown without a stack frame in Unknown on line 0
> 
> Call Stack:
>     0.0002     386096   1. {main}() /usr/local/bin/phpdoc2:0
>     0.1037    2313768   2. require('phar:///usr/local/bin/phpdoc2/bin/phpdoc') /usr/local/bin/phpdoc2:14
>     0.1189    3947520   3. phpDocumentor\Console\Application->run() phar:///usr/local/bin/phpdoc2/bin/phpdoc:43
>     0.1275    4184048   4. phpDocumentor\Console\Application->doRun() phar:///usr/local/bin/phpdoc2/vendor/symfony/console/Application.php:141
>     0.3542    8586656   5. phpDocumentor\Console\Application->renderRegistrationErrors() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:78
>     0.3543    8586656   6. spl_autoload_call() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
>     0.3543    8586736   7. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpdoc2/vendor/symfony/framework-bundle/Console/Application.php:207
>     0.3543    8586736   8. Composer\Autoload\includeFile() phar:///usr/local/bin/phpdoc2/.box/vendor/composer/ClassLoader.php:322

Thanks
Thomas

**Comment by mvriel** [comment]
That's not supposed to happen :thinking: Unfortunately, due to priorities I cannot check this further at this specific moment (I am focused on the new templates). I have marked the issue as a bug so that it can be picked up by the team, or by a glorious contributor :innocent:

**Comment by jaapio** [comment]
I just did a quick check, The current version in master doesn't have this issue. So I expect this to be fixed. 

@guenneguezt you might want to give the RC release a try. If that doesn't work either, you could give a nightly build a try.

Thanks for reporting this issue. Let us know if you have any questions or issues, by creating a new issue at any moment.

**Comment by guenneguezt** [comment]
It's right with the rc version.
With "@todo", it's detect there is a markers, but there is no type, no line number, no description.
With markers défine like :
    <markers>
      <item>TODO</item>
    </markers>
It work.

Also, is it possible to define --sourcecode in the phpdoc;.xml

Thanks
Thomas
