### ISSUE TITLE
3.0.0: Integer 0 default value of property get misrepresented as empty string

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2419]
**Given the following piece of code in file `src/issue-2419.php`:**
``` php
<?php
class Foo {
    /**
     * Summary.
     *
     * @var int
     */
    protected $itemCount = 0;
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect to see the property recognized as an integer with a default value of integer `0`.

## Actual behavior
The default value is shown as an empty string which is an oxymoron as the type is `int`.

![issue-2419](https://user-images.githubusercontent.com/663378/84604599-6ff76380-ae97-11ea-8f55-673d58a7c430.png)

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php#L86-L93)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/docs/phpdoc/classes/PHPCSUtils-AbstractSniffs-AbstractArrayDeclarationSniff.html#L412-L448)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-AbstractSniffs-AbstractArrayDeclarationSniff.html#property_itemCount)
    _Note: the online docs have not been updated recently, but will be soon._

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by mvriel** [comment]
This issue should be fixed in the commit above

**Comment by jrfnl** [comment]
Tested & fix confirmed. Thanks for the quick turn-around @mvriel ! :heart:
