### ISSUE TITLE
3.0.0: --visibility CLI argument does not respect constant visibility

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2420]
This relates to [class constant visibility](https://www.php.net/manual/en/language.oop5.constants.php#example-194) as [introduced in PHP 7.1](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.class-constant-visibility).

**Given the following piece of code in file `src/issue-2420.php`:**
``` php
<?php
class Issue2420
{
    public const PUBLIC_CONST = 'foo';
    protected const PROTECTED_CONST = 'foo';
    private const PRIVATE_CONST = 'foo';

    public $public_prop = 'foo';
    protected $protected_prop = 'foo';
    private $private_prop = 'foo';
    
    public function public_method() {}
    protected function protected_method() {}
    private function private_method() {}
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

and running with the command: `phpdoc --visibility=public,protected` or `phpdoc --visibility=public`

## Expected behavior
I'd expect only `public` and `protected` constants, properties and methods, or for the second command only `public` constants, properties and methods to be included in the documentation.

## Actual behavior
While the visibility for properties and methods are respected, this is not the case for constants.

Whichever way phpdoc is call, all constants are shown in the documentation. The constant visibility is ignored completely.

### Output with `phpdoc --visibility=public`:
> ![issue-2420-only-public](https://user-images.githubusercontent.com/663378/84605298-94097380-ae9c-11ea-9fbc-78e996bb0a80.png)

### Output with `phpdoc --visibility=public,protected`:
> ![issue-2420-public-protected](https://user-images.githubusercontent.com/663378/84605299-953aa080-ae9c-11ea-87f3-058f94f3a323.png)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc --visibility=public,protected`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by jaapio** [comment]
Constant visibility is now supported.

**Comment by jrfnl** [comment]
@jaapio Hero :superhero: You seem to be on :fire:
