### ISSUE TITLE
3.0.0: slashes in strings display escaped/doubled

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2421]
**Given the following piece of code in file `src/issue-2421.php`:**
``` php
<?php
class Issue2421 {
    /**
     * Regular expression to check if a given identifier name is valid for use in PHP.
     *
     * @var string
     */
    const PHP_LABEL_REGEX = '`^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$`';
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect to see the constant value to be displayed as declared in the code.

## Actual behavior
The slashes in the constant value are displayed as double slashed.

![issue-2421](https://user-images.githubusercontent.com/663378/84605576-cf0ca680-ae9e-11ea-9518-3fbdbdee6f73.png)

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/Utils/NamingConventions.php#L30-L37)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/docs/phpdoc/classes/PHPCSUtils-Utils-NamingConventions.html#L150-L184)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-NamingConventions.html#constant_PHP_LABEL_REGEX)
    _Note: Link will not work yet as the online docs have not been updated recently. Once they are (soon), the link will show the issue_

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by mvriel** [comment]
Investigated the issue and it seems to be related to the passing of this value into the templates and not with the template itself. As discussed with @jaapio, I am skipping any issue not related to the templates at the moment

**Comment by jaapio** [comment]
This issue goes even deeper than phpDocumentor itself. 
We are using the `PrettyPrinter` of `PHP-Parser` to convert values to there respective value. 
This is also the reason why default values of properties are losing there newlines. The values are tokenized and parsed as they are normal statements. This means that we are not reading code but stringified tokens. Which do not have any newlines. 

Fixing this could be tricky... I'm going to remove the slashes manually for now. This issue might return for other values. Which needs to be checked as well.

**Comment by jaapio** [comment]
This issue should be fixed now for:
- property default values
- method argument default values
- constant values

I didn't check if this issue also exists in docblock values since we are not using php-parser to print those.

**Comment by jrfnl** [comment]
@jaapio Thank you so much!

**Comment by jrfnl** [comment]
@jaapio Hmm.. just noticed... when a single backslash is used in a non-text string context, like when using a FQN constant `\T_IF` in a property declaration, that single backslash is now also removed...
