### ISSUE TITLE
3.0.0: inconsistent handling of @see tag linking to class outside of project

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2423]
**Given the following piece of code in file `src/issue-2423.php`:**
``` php
<?php
/**
 * Class summary.
 *
 * A description containing an inline {@see \Vendor\Package\Foo} tag to a class outside of the project.
 *
 * @see \Vendor\Package\Foo
 */
class Issue2423 {}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
As the class referenced in the `@see` tag is outside of the project being documented, I'd expect both the inline `@see` tag as well as the stand-alone `@see` tag to just show the name to the class and not to attempt to create a non-working link.

Additional suggestion: as it is known via the use of `@see` that a code element is being referenced, it would be great if element name code be treated as if it were wrapped in markdown backticks.

## Actual behavior
The inline tag shows the (non-linked) name. The stand-alone tag results in a broken link which results in a 404.

![issue-2423](https://user-images.githubusercontent.com/663378/84607246-7fcd7280-aeac-11ea-923a-49c75954e105.png)

HTML output for the broken stand-alone `@see ...` tag:
```html
<dt class="phpdocumentor-tag-list__entry">
	<span class="phpdocumentor-tag__name">see</span>
</dt>
<dd class="phpdocumentor-tag-list__definition">
	<span class="phpdocumentor-tag-link"><a href="../\Vendor\Package\Foo"><abbr title="\Vendor\Package\Foo">Foo</abbr></a></span>
	<section class="phpdocumentor-description"></section>
</dd>
```

HTML output for the inline `{@see ...}` tag:
```html
<section class="phpdocumentor-description"><p>A description containing an inline \Vendor\Package\Foo tag to a class outside of the project.</p></section>
```

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/Tokens/Collections.php#L15-L25)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/docs/phpdoc/classes/PHPCSUtils-Tokens-Collections.html#L74-L115)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Tokens-Collections.html) (class docblock)
    _Note: the online docs have not been updated recently, but will be soon._

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by mvriel** [comment]
The main issue is resolved through commit 07b1dc7891f34401da5167ea0f81af3092f4abca; the suggestion however, is a little bit more complicated as the Description rendering is not part of the templates.

I will keep this issue open to look into the suggestion, to see if we can make this easier to solve. Since this is a code issue and not a template issue; I will have to park this for the moment

**Comment by jrfnl** [comment]
Thanks for looking into this. The main issue being fixed is already a great step forward :+1:

**Comment by jaapio** [comment]
This has been fixed with the new description handling

**Comment by jrfnl** [comment]
Thanks again @jaapio !
