### ISSUE TITLE
3.0.0: inconsistent display of @see tags linking to class within the project

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2424]
**Given the following piece of code in file `src/issue-2424-a.php`:**
``` php
<?php
namespace Project\Sub\Level;

/**
 * Class summary.
 *
 * A description containing an inline {@see \Project\Other\Level\Issue2424B::bar()} tag
 * to a class inside of the project.
 *
 * @see \Project\Other\Level\Issue2424B::bar()
 */
class Issue2424A {}
```

and this code in file `src/issue-2424-b.php`:
```php
<?php
namespace Project\Other\Level;

class Issue2424B
{
	public function bar() {}
}

```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
For this `@see` tag to an existing class within the same project, I'd expect either both class names to be displayed in long form or both in short form.

Personally, I think short form should be preferred for both (with the mouse-over to long form as is already in place for the current short form in the tags list).

If there would be a difference at all, I'd expect short form to be used for the inline tag for readability and long form to be used for the stand-alone tag.

## Actual behavior
The way Fully Qualified Names are displayed is inconsistent between inline `{@see ...}` tags and stand-alone `@see` tags.

Note: this behaviour is independent of whether an FQN or an unqualified name is used in the docs.

![issue-2424](https://user-images.githubusercontent.com/663378/84608107-23208680-aeb1-11ea-80f2-6235b04b5641.png)

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/Tokens/Collections.php#L335-L354)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/docs/phpdoc/classes/PHPCSUtils-Tokens-Collections.html#L1065-L1118)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Tokens-Collections.html#property_parameterTypeTokens)
    _Note: the online docs have not been updated recently, but will be soon._

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by mvriel** [comment]
Related to the suggestion of issue https://github.com/phpDocumentor/phpDocumentor/issues/2423; a code change is needed to alter the way the description is rendered

**Comment by jaapio** [comment]
This has been fixed with the new description handling.
