### ISSUE TITLE
3.0.0: import use statements are disregarded

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2425]
**Given the following piece of code in file `src/issue-2425-a.php`:**
``` php
<?php
namespace Project\Sub\Level;

use Project\Other\Level\Issue2425B;
use Project\Other\Level\Issue2425C as Aliased;

/**
 * Class summary.
 *
 * A description containing an inline {@see Issue2425B::bar()} tag
 * to a class inside of the project referenced via a use statement.
 *
 * And here is another inline {@see Aliased::bar()} tag to a class
 * aliased via a use statement.
 */
class Issue2425A {}

```

and this code in file `src/issue-2425-b.php`:
```php
<?php
namespace Project\Other\Level;

class Issue2425B
{
	public function bar() {}
}
```

and this code in file `src/issue-2425-c.php`:
```php
<?php
namespace Project\Other\Level;

class Issue2425C
{
	public function bar() {}
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect the unqualified names used in the `@see` tags to be resolved to the fully qualified name using the import `use` statement and to be recognized as classes within the project for which a documentation page exists.

## Actual behavior
The unqualified names do not get resolved using the import `use` statement, but are using the current namespace and therefore cannot be found in the project and don't get linked properly.

> ![issue-2425](https://user-images.githubusercontent.com/663378/84608805-5d3f5780-aeb4-11ea-9283-c6b4ad308cc2.png)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code samples and config.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by mvriel** [comment]
Investigated the issue and it seems to be related to the passing of this value into the templates and not with the template itself. As discussed with @jaapio, I am skipping any issue not related to the templates at the moment

**Comment by jaapio** [comment]
I pushed a first draft of the improved version to handle descriptions in a more flexible way. Now switching to some other work, because the reported issue is deeper. Nobody ever tried using aliases in see tags?

**Comment by jaapio** [comment]
Created a second PR to fix the actual issue: https://github.com/phpDocumentor/ReflectionDocBlock/pull/226

**Comment by jrfnl** [comment]
@jaapio Thank you for all your work on this! I can't say much about the PRs themselves, but I'm exited to see this handled! :heart:

**Comment by jaapio** [comment]
PR is merged, some pending other PR is holding me back from creating a new tag right now. But I expect this other PR to be merged soon. So we can prepare a new phpDocumentor nightly with this fixed.
