### ISSUE TITLE
3.0.0: output directory not cleared between doc generation

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2429]
Generating the docs with a different template and/or different version of phpDocumentor can leave a lot of stray files around which _may_ interfere.

## Expected behavior
That the output directory `.phpdoc/build/` is cleared between runs.

## Actual behavior
It isn't.

This includes leaving `.htaccess` files, source code in `txt` files etc

A demo of this behaviour showing the results in separate commits can be seen in this branch: https://github.com/jrfnl/phpDocumentor-issue-demo/tree/demo/issue-2429

For efficiency, it may be an idea to create a file in the cache directory which keeps track of:
- Used configuration for the run
- CLI arguments used for the run
- PHP version used for the run
- PHP extensions loaded during the run
- phpDocumentor version used for the run
- anything else relevant which I'm forgetting

... using file hashes where necessary.

And then if anything relevant has changed in the next run, to clear the output directory before regenerating the output.

I imagine something like this is already in place for clearing the `cache`. If not, it probably should be.

## Steps to reproduce the problem

* Take any project with a phpDocumentor config.
* Make sure the output directory is not set to be `.gitignore`d.
* Generate docs with the `default` template & commit the output (to a "test" branch or something).
* Regenerate the docs now using the `clean` template. Do NOT commit.
* Regenerate the docs with the `default` template.
* See that there are a lot of uncommitted files which were generated by the `clean` template and should no longer be there.

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by mvriel** [comment]
There is a system in place that detects changes in the config (both from file and CLI), and will 'force' clearing of the cache.

I am on the fence whether we should be responsible for clearing that folder; automatically clearing the folder may have other unintended effects and is destructive / non-recoverable. I would like a second opinion by @jaapio, but I feel that destroying a folder is more hazardous than lingering artefacts.

It _may) also be detrimental to performance when working with remote filesystems; as most remote filesystems only allow file-by-file deletions

**Comment by jaapio** [comment]
Clearing the target directory does have a lot of downsides. We are never clearing any folders because users might want to move around with files. The only thing we could do is detect that the folder is not empty and show a warning about that, IMO.

I had enough tools that would clear a directory but I needed to put an extra .htaccess in there to protect it for example. Or when you are misspelling some directory and your /usr/bin folder on linux was cleared.... so this is a no go for me. 
It's the users responsibility to clean up the target directory.

**Comment by jrfnl** [comment]
I understand your point of view.

In that case, I'd like to suggest to re-open this issue as a documentation issue. I do believe users should be made aware of the fact that they are responsible for clearing the output folder between runs.

Note: this also affects documentation for, for instance, removed classes, as the files for those remain, even though they are not linked anymore from the phpDoc generated documentation.

Those files _may_ still get indexed by search engines or have been bookmarked by end-users, so making it clear that the folder needs to be (manually) emptied before doc regeneration does sound like something which should be prominently mentioned.

**Comment by mvriel** [comment]
Ticket reopened and tagged with the documentation label :)

**Comment by jaapio** [comment]
Added a note about target directory clearing in the `Running phpDocumentor` page.

```
.. note::

    The target directory is not cleared before generating documentation. This allows you to add additional files to the
    target directory that are not part of your project and have them included in the documentation.
    If you rerun phpDocumentor you will have to manually remove the old documentation files.
```
