### ISSUE TITLE
3.0.0: "true"/"false" types not respected/lost specificity by showing "bool"

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2432]
**Given the following piece of code in file `src/issue-2432.php`:**
``` php
<?php
abstract class Issue2432 {
    /**
     * Process the array opener and closer.
     *
     * @return true|void Returning `true` will short-circuit the sniff and stop processing.
     */
    abstract public function processOpenClose();

    /**
     * Do something
     *
     * @param int|false $param Integer or false to skip this check.
     *
     * @return int|false Integer or false when the logic ran into a problem.
     */
    public function processSomething($param) {}
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect the "Type" of the parameter/return to respect the `true`/`false` keywords.

## Actual behavior
`true`/`false` looses specificity by being changed into `bool`.

While technically correct, this looses information which may be essential/relevant.

Asides from that, both [PSR 5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types), as well as the phpDocumentor own documentation on Types (both in [guides](https://docs.phpdoc.org/3.0/guides/types.html) as well as [reference](https://docs.phpdoc.org/3.0/references/phpdoc/types.html)), state that the `true`/`false` keywords should be supported as they are.

I could understand the change if the Type was given as `true|false`. Changing that to `bool` is correct.
But if the Type specifies just one boolean possibility, that should not be changed.

> ![issue-2432](https://user-images.githubusercontent.com/663378/84705901-65eb6880-af5c-11ea-9f8b-544f61c710c4.png)

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php#L283-L303)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/docs/phpdoc/classes/PHPCSUtils-AbstractSniffs-AbstractArrayDeclarationSniff.html#L766-L770)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-AbstractSniffs-AbstractArrayDeclarationSniff.html#method_processOpenClose)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by mvriel** [comment]
Ah, crap. I remember this issue. The TypeResolver component is responsible for converting this to a proper type; though it is a bit too thorough and converts the true|false pseudotype to a regular bool. @jaapio and I have been discussing this one, and a change is needed in the TypeResolver to support Pseudotypes, and that those PseudoTypes extend/implement a regular type so that you can both know it is a True/False pseudotype, and a Boolean 'real' type.

I am not sure how far work on this is, but it is kinda hard to quickly fix this.

**Comment by jrfnl** [comment]
Thanks for looking into this and confirming it as a bug. I understand this will take some time. Either way, I look forward to a fix in the foreseeable future.

**Comment by jaapio** [comment]
Fixed, this was easier than expected :-D

**Comment by jrfnl** [comment]
Uh oh... this commit broke display of the return type... see #2463

**Comment by jrfnl** [comment]
Actually, looking at the demo code, it also broke select parameter types.
