### ISSUE TITLE
3.0.0: CLI argument --ignore-tags is not working

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2433]
**Given the following piece of code in file `src/issue-2433.php`:**
``` php
<?php
class Issue2433 {

    /**
     * Summary.
     *
     * @codeCoverageIgnore
     */
    function foo()
}

```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

The output looks like this:

> ![issue-2433](https://user-images.githubusercontent.com/663378/84707807-a8627480-af5f-11ea-8e77-b5bb58c7f702.png)

Based on the documentation I should be able to get rid of the `codeCoverageIgnore` tag showing by using the `--ignore-tags` option.

> Contrary to phpDocumentor 1, version 2 will now display all tags by default; if you want to omit specific tags from the documentation you can do that using the --ignore-tags option. By providing a comma-separated list of tag names (case-sensitive) phpDocumentor can be instructed to omit those tags, and their contents, from the documentation.

Source: https://docs.phpdoc.org/3.0/guides/running-phpdocumentor.html#determining-content

The `-h` option also shows that CLI argument:
```
      --ignore-tags[=IGNORE-TAGS]                Tag that will be ignored, defaults to none. package, subpackage and ignore may not be ignored. Add multiple options of this type to ignore multiple tags. (multiple values allowed)
```

## Expected behavior
That if I use `--ignore-tags=codeCoverageIgnore` the `codeCoverageIgnore` tag would no longer show.

## Actual behavior
It still shows.

Looks like the whole `--ignore-tags` CLI option has not been implemented yet in phpDocumentor 3 (or possibly renamed ?).

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php#L283-L303)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/docs/phpdoc/classes/PHPCSUtils-AbstractSniffs-AbstractArrayDeclarationSniff.html#L758-L763)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-AbstractSniffs-AbstractArrayDeclarationSniff.html#method_processOpenClose)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc --ignore-tags=codeCoverageIgnore`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by jaapio** [comment]
The new build will fix the intended behavior of the commandline argument and the ignore-tags configuration option. You can have a look at our own configuration which does ignore a number of tags now.

**Comment by jrfnl** [comment]
Awesome!
