### ISSUE TITLE
3.0.0: XSD unnecessarily restrictive and non-compliant with documentation

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2436]
## Setting the scene

According to the documentation only those things which you want to change need to be/should be set in the configuration file.

> phpDocumentor follows the **_convention over configuration_** style and as such it is only necessary to specify the options which you want to change with regard to the defaults.

Source: https://docs.phpdoc.org/3.0/references/configuration.html#basic-configuration

## Issue 1

Now, given a minimal configuration like this:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
</phpdocumentor>
```

### Expected behavior
I'd expect no XML errors when linting the config file.

### Actual behavior
Linting the XML against the XSD will fail with the following error complaining about a missing `<paths>` element:
```bash
# xmllint --noout --schema /path/to/phpDocumentor/data/xsd/phpdoc.xsd ./phpdoc.dist.xml
./phpdoc.dist.xml:11: element version: Schemas validity error : Element '{https://www.phpdoc.org}version': This element is not expected. Expected is ( {https://www.phpdoc.org}paths ).
./phpdoc.dist.xml fails to validate
```

This defies the principle of _convention over configuration_, as this means that the `<paths>` element is required, even when you just want to use the default `/.phpdoc/build/` and `/.phpdoc/cache/` directories for the output.

Also note that the `phpdoc` command will run fine without the `<paths>` element.

## Issue 2

The use of `<xs:sequence>` means that the elements *have* to be in a specific order, which makes the config file quite fiddly.

Is there a reason for that ? Is it really necessary ?

Given the following configuration - note the addition of the `<title>` element at the bottom:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <paths>
        <output>.phpdoc/build/</output>
        <cache>.phpdoc/cache/</cache>
    </paths>

    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>

    <title>Demo</title>

</phpdocumentor>
```

### Expected behavior
I'd expect no XML errors when linting the config file.

### Actual behavior
Linting the XML against the XSD will fail with the following error:
```bash
# xmllint --noout --schema /path/to/phpDocumentor/data/xsd/phpdoc.xsd ./phpdoc.dist.xml
./phpdoc.dist.xml:21: element title: Schemas validity error : Element '{https://www.phpdoc.org}title': This element is not expected. Expected is one of ( {https://www.phpdoc.org}version, {https://www.phpdoc.org}setting, {https://www.phpdoc.org}template ).
./phpdoc.dist.xml fails to validate
```

The XSD basically wants the `<title>` tag as the first element, though the error message isn't very readable and gives the impression that `title` isn't even allowed.

Again note that the `phpdoc` command will run fine when the elements are not in the "correct" order.

## Suggested solution

The above are just two examples. I'd like to suggest to do a very critical review of the XSD file and make it less restrictive whenever possible.

## Steps to reproduce the problem

1. Issue can be reproduced with the above sample config files on any random PHP project.
2. Make sure [xmllint](http://xmlsoft.org/xmllint.html) is installed and run:
    ```bash
    xmllint --noout --schema /path/to/phpDocumentor/data/xsd/phpdoc.xsd ./phpdoc.dist.xml
    ```
    (adjust the paths to match your own system setup) and observe the XMl validation errors.
3. Run `php -f /path/to/phpDocumentor/bin/phpdoc` and observe that the run doesn't throw any errors.

.. or have a look at the issue demo branch here: https://github.com/jrfnl/phpDocumentor-issue-demo/tree/demo/issue-2436

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by jaapio** [comment]
I had a look at the issues you are reporting. Some of the forced orders can be removed others are not. This is a limitation by XSD 1.0 which is most common. 

I removed the strict order when possible but we will have to live with some limitations. Your first issue has been solved. It should not have been manditory anymore.

**Comment by jrfnl** [comment]
Thank you!
