### ISSUE TITLE
3.0.0: @method tag showing in class Tags list and other nit-picks

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2438]
**Given the following piece of code in file `src/issue-2438.php`:**
``` php
<?php
/**
 * Class summary.
 *
 * @method static int[]    foo()            Description of foo.
 * @method static string[] bar(string $arg) Description of bar.
 *                                          More details about bar.
 */
class Issue2438
{
    /**
     * Method summary.
     *
     * @param string $name Method name.
     * @param array  $args Unused.
     *
     * @return array|false
     */
    public static function __callStatic($name, $args)
    {
        switch ($name) {
            case 'foo':
                return [1, 2, 3];
            case 'bar':
                return ['a', 'b', 'c'];
        }

        return false;
    }
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect:

TOC:
1. The methods to show in the class TOC. :heavy_check_mark:
2. The methods added via the `@method` tag are listed below "normal" methods.  :x:
3. The `method` tags not to show in the class Tags list. :x:
4. The description to show as the method summary if one sentence (up to the first period). If more than one sentence: the first sentence to show as the method summary. :x:

Method list:
1. The methods to show in the Method list :heavy_check_mark:
2. The methods to be listed in the Method list below "normal" methods.  :x:
3. The first sentence of the description (up to the first period) to show as the method summary. :x:
4. The rest of the description to show as the long description. :x:

## Actual behavior
See the :heavy_check_mark: and :x:'s above.

The more serious issue is the `method` tag showing in the class Tags list (TOC:3).

I'm not sure if this is a templating issue or an issue with the way the data is saved in the AST cache, but the way it is now, is confusing and more noise than having the tag is worth.

The list order is second on my priority list.

The summary being shown as description is something I can live with if needs be.

### TOC
> ![issue-2438-class-overview](https://user-images.githubusercontent.com/663378/84734441-1ed39680-afa1-11ea-81e7-cc3b4443e2d8.png)

### Method list
> ![issue-2438-method-overview](https://user-images.githubusercontent.com/663378/84734443-1f6c2d00-afa1-11ea-8e7a-5f08aaf865ee.png)

## As found in project

* [Direct link to the source code where the issue was found](https://github.com/PHPCSStandards/PHPCSUtils/blob/7a54196a2c079dae38d2bd5b5eb605f514d9c3e6/PHPCSUtils/BackCompat/BCTokens.php#L44-L58)
* [Direct link to the HTML source of the generated docs](https://github.com/PHPCSStandards/PHPCSUtils/blob/develop/docs/phpdoc/classes/PHPCSUtils-BackCompat-BCTokens.html)
* [Output as seen online](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-BackCompat-BCTokens.html)
    _Note: the online docs have not been updated recently, but will be soon._

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config or via the linked project.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils/
* Link to output as committed: https://github.com/PHPCSStandards/PHPCSUtils/tree/develop/docs/phpdoc
* Link to output online: https://phpcsutils.com/phpdoc/

**Comment by mvriel** [comment]
Resolved by https://github.com/phpDocumentor/phpDocumentor/commit/28d82cdf2c6892126159b8b932db23a84a97bfe9

The only thing that is not addressed is to show the first sentence of the description as summary change as this is an interesting bit and I will create a separate improvement for it

**Comment by jrfnl** [comment]
@mvriel I can see that the issue is addressed, however, this commit broke other things... see #2462
