### ISSUE TITLE
3.0.0: multiple @var tags for compound constant/property declarations not handled correctly

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2441]
## Setting the scene

From the documentation of the `@var` tag:

> The @var tag MUST contain the name of the element it documents. An exception to this is when property declarations only refer to a single property. In this case the name of the property MAY be omitted.
>
> This is used when compound statements are used to define a series of properties. Such a compound statement can only have one DocBlock while several items are represented.

&lt;snip&gt;

> Even compound statements may be documented:
> ```php
> class Foo
> {
>   /**
>    * @var string $name        Should contain a description
>    * @var string $description Should contain a description
>    */
>   protected $name, $description;
> }
> ```

Source: https://docs.phpdoc.org/3.0/references/phpdoc/tags/var.html

## Issue Description

_Previously #885, #1439_

The `@var` tag is nowadays used for both (class) constants as well as properties and other variables.

**Given the following piece of code in file `src/issue-2441.php`:**
``` php
<?php
class Issue2441
{
    /**
     * This is foo.
     *
     * @var string COMPOUND_A_WITH_NAME
     * @var int    COMPOUND_B_WITH_NAME
     */
    const COMPOUND_A_WITH_NAME = 'foo',
        COMPOUND_B_WITH_NAME = 1; // <= BUG.

    /**
     * This is foo.
     *
     * @var string $compound_a_with_name
     * @var int    $compound_b_with_name
     */
    protected $compound_a_with_name = 'foo',
        $compound_b_with_name = 1; // <= BUG.
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect the `COMPOUND_A_WITH_NAME` constant and the `$compound_a_with_name` property to get the type `string` and the `COMPOUND_B_WITH_NAME` constant and the `$compound_b_with_name` property to have the type `int`.

## Actual behavior
The "element name" in the `@var` tag is disregarded and only the first `@var` tag is taken into account, resulting in both the `COMPOUND_B_WITH_NAME` constant and the `$compound_b_with_name` property having the incorrect type `string`.

### Constants
> ![issue-2441-constants](https://user-images.githubusercontent.com/663378/84754459-b2688f80-afc0-11ea-9bf0-00f544524db7.png)

### Properties
> ![issue-2441-properties](https://user-images.githubusercontent.com/663378/84754462-b3012600-afc0-11ea-8643-aaeb5884ee56.png)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by gaxweb** [comment]
Wow, three years and still broken?

**Comment by MLIMG** [comment]
> Wow, three years and still broken?

you know how many ppl work on this project?

**Comment by jrfnl** [comment]
@gaxweb Your remark is not constructive and adds no value to this issue. Have you tried contributing instead of complaining ?

**Comment by gaxweb** [comment]
Yeah, that might have been an uncalled for, snarky remark. Sorry, I guess. But if none of the 154 contributors can fix it within 3 years, maybe the code is over engineered to the point that nobody wants to work on this?

And now you want me, an outsider, to fix it? I did have a look before I posted that comment actually, but apparently I'm too stupid to even figure out where _the magic_ happens. I can't see the forest for all the trees. There's so much scaffolding, I can't find the business logic. So I'm afraid I can't help you even though I'd have, if you can believe it.

I was simply surprised that the documentation describes this as a feature when it doesn't actually work - 3 years later. I know I could comment each property individually, but I don't like bloating my code with extra comment noise just because auxiliary middleware has a bug.

**Comment by jrfnl** [comment]
@gaxweb Well, in reality there are not 154 active contributors, but mostly 2 and they do this in their spare time, so please respect that.

If you have questions about contributing, the [contributors guide](https://github.com/phpDocumentor/phpDocumentor/blob/master/CONTRIBUTING.md) may help and I presume asking specific questions on how to get started with something may help. Complaining will not.

(and just to clarify, I'm not asking _you_ to fix _this_ issue. Contributing can take many forms and if done strategically, can help free up some of the limited maintainer time for issues like this. I'm not sure what is currently the best way to help in _this_ project, but I find that asking maintainers what would help them most is a good place to start.)
