### ISSUE TITLE
3.0.0: property type missing in TOC when not explicitly declared

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2442]
**Given the following piece of code in file `src/issue-2442.php`:**
``` php
<?php
class Issue2442
{
    public $nodocblock = 'foo';

    /**
     * Summary.
     */
    public $docblock_novar = 'foo';

    public string $nodocblock_typed = 'foo';

    /**
     * Summary.
     *
     * @var string
     */
    public $docblock_var = 'foo';

    /**
     * Summary.
     */
    public function foo() {}
}
```

<details>
  <summary><b>with the following config:</b></summary>

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Demo</title>
    <version number="latest">
        <api format="php">
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <template name="default"/>
</phpdocumentor>
```
</details>

## Expected behavior
I'd expect the TOC to show type `mixed` for properties which don't have a `@var` type, nor a type declaration, just like is done for methods without a return type declaration nor a `@return` tag.

## Actual behavior
The type is not shown in the TOC and there is a "stray" colon at the end of the line.

![issue-2442](https://user-images.githubusercontent.com/663378/84759484-13936180-afc7-11ea-96c6-b01e8684ff9e.png)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config.
2. Run `php -f /path/to/phpDocumentor/bin/phpdoc`

## Your environment

* Version used: phpDocumentor v3.0.x-dev@d15f2d6
* Install method: git clone
* PHP version: 7.4.6
* Operating system and version: Windows 7

**Comment by mvriel** [comment]
Fixed on master! Thanks for reporting and the awesome report

**Comment by jrfnl** [comment]
Tested & fix confirmed. Thanks for the quick turn-around @mvriel !
