### ISSUE TITLE
FR: add support for dot prefixed config file names

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2452]
# Feature request

Related to / follow-up to #1997 and #2451 

I was wondering if you'd be open to adding support for additional config file names, to be precise, the existing config files, but with a dot-prefix, like `.phpdoc.xml.dist`, `.phpdoc.dist.xml`, `.phpdoc.xml`.
A lot of CI/QA related tooling support dot prefixed config files, though definitely not all, most notably PHPUnit does not support it.

The advantages would be that:
* The config file(s) will be hidden in UNIX-based systems
* The config file(s) will be naturally grouped with other config files whose name starts with a dot.
    ... And makes it clear these files are not part of the project itself, but describe how the project behaves for the purpose of certain tools.

Precedence-wise, I'd suggest the `.` prefixed files to have higher precedence than their non-dot prefixed counter-parts, but other than that the same order, so the precedence order would then become something along the lines of (also see open question about this in #2451):

* `.phpdoc.xml`
* `phpdoc.xml`
* `.phpdoc.dist.xml`
* `phpdoc.dist.xml`
* `.phpdoc.xml.dist`
* `phpdoc.xml.dist`

Though it could be argued that the dist dot files should both have a higher precedence than the non-dot versions, i.e.:

* `.phpdoc.xml`
* `phpdoc.xml`
* `.phpdoc.dist.xml`
* `.phpdoc.xml.dist`
* `phpdoc.dist.xml`
* `phpdoc.xml.dist`

Related:
* https://github.com/squizlabs/PHP_CodeSniffer/issues/1566 (Supported since 2017 / PHPCS 3.1.0)
* https://github.com/sebastianbergmann/phpunit/issues/3030 (Closed)

**Comment by mvriel** [comment]
AFAIC, since we already have a list of config files it shouldn't be much of an issue. The only things would like to double-check is whether this is a merging behaviour or an overriding behaviour. I kind of forgot whether the config files merge together or one physical file overrides the rest

**Comment by jrfnl** [comment]
IIRC the current behaviour is to override.

This is the same as PHPUnit and PHP_CodeSniffer. Both override as well, though PHP_CodeSniffer allows for including another config, which I find an awesome feature, like so:
```xml
<?xml version="1.0"?>
<ruleset name="My CS">

    <rule ref="./phpcs.xml.dist"/>

     ... overrule anything you want changed from the imported file ...
</ruleset>
```

(typical example of a local `phpcs.xml` file, including the `phpcs.xml.dist` file)

**Comment by jrfnl** [comment]
:+1: :+1:
