### ISSUE TITLE
Template suggestion: add "back to top"

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2453]
# Template issue/request

I believe it would be useful to have a "back to top" option at the bottom of each documented element linking to the TOC on the page, especially for large classes.

![image](https://user-images.githubusercontent.com/663378/84886465-c1b90d00-b094-11ea-8f2d-8da686e4149b.png)

This could also be a "floating" _back to top_ element which appears as soon as you scroll below the fold, like in the php manual:

![image](https://user-images.githubusercontent.com/663378/84886076-3770a900-b094-11ea-8605-5359755931a3.png)

I'm pretty sure there will be standard JS implementations around for things like this, though I haven't looked into this for a while, so can't suggest one.

**Comment by mvriel** [comment]
Can be solved without JS luckily by adding an anchor at the top of the page and using a styles link to go to that anchor :)

**Comment by mvriel** [comment]
Thank you for reporting this issue; I have resolved it in a very similar way to the PHP documentation (not on purpose :) )

**Comment by jrfnl** [comment]
Tested & confirmed fixed. Looks good. The only nit-pick I see is that the "back to top' always shows, not just once you've scrolled below the fold, that's nothing to worry about.
