### ISSUE TITLE
Template suggestion: make linking to sections easy

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2454]
# Template issue/request

It would be useful to easily be able to copy a link to a particular section in the docs, for instance to paste in a reply to an open issue (friendly RTFM reply).

This is a feature which both the PHP manual as well as GitHub support, which makes it something which I missed straight away.

Based on the above, I expect there will be simple JS scripts available which can add this feature without much coding involved. After all, the sections all already have IDs. There may even be a CSS only solution for this.

### Example from the PHP manual:
Normal view:
> ![phpdoc-easy-link-to-headers-phpmanual-example-1](https://user-images.githubusercontent.com/663378/84887306-d5b13e80-b095-11ea-8c3f-9e2c66a3b22c.png)

On mouse-over of the title:
> ![phpdoc-easy-link-to-headers-phpmanual-example-2](https://user-images.githubusercontent.com/663378/84887308-d5b13e80-b095-11ea-92a6-ecba1c59b8d9.png)

### Example from a GH readme:
Normal view:
> ![phpdoc-easy-link-to-headers-github-example-1](https://user-images.githubusercontent.com/663378/84887303-d518a800-b095-11ea-9f49-84ee9d4d9487.png)

On mouse-over of the title:
> ![phpdoc-easy-link-to-headers-github-example-2](https://user-images.githubusercontent.com/663378/84887305-d518a800-b095-11ea-8405-00004771bae6.png)

**Comment by mvriel** [comment]
I thought I already added this :thinking: I will check that. No JS is necessary, long life CSS :)

**Comment by mvriel** [comment]
Thanks for reporting this; I have fixed this in 2c41a6b789138c7894ecc771c4112f13e6495e53.
I have not added deep links to all headings as I believe that some do not need them. Though the important ones have them :)

**Comment by jrfnl** [comment]
Again: awesome! Tested & confirmed fixed. Thanks for the quick turn-around :heart:
