### ISSUE TITLE
Template suggestion: don't show "Global" in menu when everything is namespaced

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2457]
# Template issue/request

For a project which only contains namespaced code, the "Global" menu item doesn't add any value.

I'd like to suggest removing it from/not adding it to the menu if there is nothing but named namespaces in the global namespace.

![image](https://user-images.githubusercontent.com/663378/84919556-5dad3d80-b0c2-11ea-85d1-ac5fd5822f01.png)

**Comment by mvriel** [comment]
https://media.giphy.com/media/26u4eMNSMWydF0v8A/giphy.gif

**Comment by mvriel** [comment]
![image](https://user-images.githubusercontent.com/193704/85149232-55373d00-b251-11ea-966b-b34b22619ef0.png)

**Comment by mvriel** [comment]
Done and did it!

**Comment by jrfnl** [comment]
Awesome! Thank you so much @mvriel !
