### ISSUE TITLE
Source view is not working with template "clean" on phpDocumentor 3.0.0 rc (phar file)

### ISSUE THREAD

**Issue by WebDevLan4You** [phpDocumentor/phpDocumentor#2471]
#1695  Expected behavior
Source Code view

## Actual behavior
![error-source-code-clean template](https://user-images.githubusercontent.com/22098517/87030875-88cb0e80-c1e2-11ea-94a0-5d8518379e38.png)

![error-source-code-clean template-1](https://user-images.githubusercontent.com/22098517/87031958-2410b380-c1e4-11ea-94b0-546d326519bf.png)

## Steps to reproduce the problem

sudo php phpDocumentor.phar run --config phpdoc.dist.xml --force --template="clean" --sourcecode

## Your environment
* Version used: 3.0.0-rc phpDocumentor.phar
* phar File
* PHP version 7.4.2
* Ubuntu 20.04

added phpdoc.dist.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<phpdocumentor>
    <title><![CDATA[API DOC ]]></title>
    <parser>
        <encoding>utf-8</encoding>
        <default-package-name>Some Package</default-package-name> 
        <target>/management/docs/</target>
        <markers>
        <item>TODO</item>
        <item>FIXME</item>
      </markers>
    </parser>
    <transformer>
        <target>/management/docs/</target>
    </transformer>
    <files>
        <directory>Module</directory>
     
      
    </files>
     
   
</phpdocumentor>
```

**Comment by WebDevLan4You** [comment]
Demo on phpDoc no source code view: https://demo.phpdoc.org/3.0/clean/classes/phpDocumentor-Kernel.html#source-view

**Comment by jaapio** [comment]
Our latest nightly build is able to render the sources with the `--sourcecode` flag enabled. 

Please let us know when you have any problems running this version.
