### ISSUE TITLE
Error when building the documentation

### ISSUE THREAD

**Issue by tbela99** [phpDocumentor/phpDocumentor#2475]
PHP 7.4
command line
```sh
./phpDocumentor.phar -d src/ -t docs/api
```
## Expected behavior

No errors

## Actual behavior

```txt
Parsing files
  9/82 [===>------------------------]  10%21:48:49 ALERT     [app]   Unable to parse file "src/TBela/CSS/Property/Property.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
21:48:49 ALERT     [app]   Unable to parse file "src/TBela/CSS/Property/Property.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 33/82 [===========>----------------]  40%21:48:49 ALERT     [app]   Unable to parse file "src/TBela/CSS/RuleList.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
21:48:49 ALERT     [app]   Unable to parse file "src/TBela/CSS/RuleList.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 74/82 [=========================>--]  90%21:48:50 ALERT     [app]   Unable to parse file "src/TBela/CSS/Value/Set.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
21:48:50 ALERT     [app]   Unable to parse file "src/TBela/CSS/Value/Set.php", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given
 82/82 [============================] 100%21:48:50 ERROR     [console] Error thrown while running command "-d 'src/' -t 'docs/api'". Message: "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()" ["exception" => Error { …},"command" => "-d 'src/' -t 'docs/api'","message" => "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()"]
21:48:50 ERROR     [console] Error thrown while running command "-d 'src/' -t 'docs/api'". Message: "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()" ["exception" => Error { …},"command" => "-d 'src/' -t 'docs/api'","message" => "Call to undefined method phpDocumentor\Reflection\Fqsen::getMethods()"]
```
## Steps to reproduce the problem

1. run the phar using './phpDocumentor.phar -d src/ -t docs/api'
2.
3.

## Your environment
PHP 7.4.7

* Version used: 3.0.0-rc
* Install method Phar
* PHP version 7.4.7
* Operating system and version (e.g. Ubuntu 20.04, Windows 10):
* Link to your project: https://github.com/tbela99/css
* Attach code that is involved './phpDocumentor.phar -d src/ -t docs/api'

**Comment by WebDevLan4You** [comment]
hi,
possible solution, you have to check your comments above your function in your files.
if the syntax wrong an error occurs like above in your comment.

correct
```
@param string $myvariable some comment
```
wrong
```
@param $myvariable string some comment
```
or
```
@param &string $myvariable some comment
```

and so on!

**Comment by tbela99** [comment]
this is not the case. 

- The rc version crashes with fatal error. 
- The latest stable produce the documentation but many classes are missing (see #2476).
- The phar referenced on the phpdoc.org produces everything but produces a lot of notice. there is already an issue covering this

**Comment by WebDevLan4You** [comment]
if some error happens the whole file won't get parsed, so the class would be missing!

**Comment by tbela99** [comment]
did you read my answer? I said "The phar referenced on the phpdoc.org website produces everything but generates a lot of notice"
I use PHP 7.4

this binary produces documentation for all the files https://phpdoc.org/phpDocumentor.phar
the current stable as well as the rc are not generating documentation for all the files as stated in #2476

**Comment by jaapio** [comment]
I just confirmed that this isn't an issue anymore. Please let us know when you still experience issues with the latest nightly build.
