### ISSUE TITLE
Classes in the namespace are missing

### ISSUE THREAD

**Issue by tbela99** [phpDocumentor/phpDocumentor#2476]
classes in the namespace \TBela\Css are missing. There are many classes that are missing from the generated documentation
- \TBela\CSS\Color
- \TBela\CSS\Parser
- ...
## Expected behavior

Document all classes in the namespace \TBela\CSS

## Actual behavior

Does not document all classes in the namespace \TBela\CSS

## Steps to reproduce the problem

1. run './phpDocumentor.phar -d src/ -t docs/api'
2. check the generated output
3. classes are missing

## Your environment

PHP 7.4
Centos 7

* Version used: 2.9.1
* Install method Phar
* PHP version 7.4.7
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Centos 7
* Link to your project: https://github.com/tbela99/css
* Attach code that is involved: './phpDocumentor.phar -d src/ -t docs/api'

**Comment by juliushaertl** [comment]
I'm also seeing this issue with our repo with the rc:

```
git clone https://github.com/nextcloud/server.git
phpDocumentor.phar -d lib/public -t "./api"
```

I remember this was fixed in some beta already as I reported something similar earlier in https://github.com/phpDocumentor/phpDocumentor/issues/2294 but with the rc this showed up again.

Let me know if you need anything further.

**Comment by juliushaertl** [comment]
As mentioned in https://github.com/phpDocumentor/phpDocumentor/issues/2294 the current build from master that can be downloaded from https://github.com/phpDocumentor/phpDocumentor/actions/runs/218122449 don't have this issue for me anymore.

**Comment by jaapio** [comment]
I just confirmed that this isn't an issue anymore. Please let us know when you still expirence issues with the latest nightly build.
