### ISSUE TITLE
ALERT     [app]   Unable to parse file "<filename>", an error was detected: array_walk_recursive() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by Stefanius67** [phpDocumentor/phpDocumentor#2484]
## Expected behavior
generate entry in the documentation error list with linenumber and continue parsing the file

## Actual behavior
cancels parsing of the affected file and content is not included in the documentation

## Steps to reproduce the problem
So far found following triggers for this error:
_**@see classname->method()**_ instead of _**@see classname::method()**_

_**@param int/string**_ instead of _**@param int|string**_ or _**@param mixed**_

## Your environment
* Version used: 3.0.0-rc
* Install method: PHAR
* PHP version: 7.4.3
* Operating system and version:  Ubuntu 20.04

**Comment by jaapio** [comment]
I think this is fixed in the nightly build. You may want to give that a try.

**Comment by Stefanius67** [comment]
fixed in Version/Build 2e1ed05
