### ISSUE TITLE
Newline <br> ignored in long description.

### ISSUE THREAD

**Issue by Stefanius67** [phpDocumentor/phpDocumentor#2486]
&lt;br&gt; (&lt;br/&gt;) as a line break is ignored (more specifically, the HTML tag is masked as normal text).

The only way to force a line break in the long description is to insert further empty lines or use sorted/unsorted lists. 
In many cases, however, this does not make sense or uses a lot of space in the docBlock.

## Expected behavior
process the &lt;br&gt; Tag

## Actual behavior
 &lt;br&gt; Tag is ignored

## Steps to reproduce the problem
Insert  &lt;br&gt; Tag in any long description.

## Your environment
* Version used: 2e1ed05
* PHAR from github
* PHP version: 7.4
* Operating system and version: Ubuntu 20.04

**Comment by jaapio** [comment]
Fixed in https://github.com/phpDocumentor/phpDocumentor/commit/558410
