### ISSUE TITLE
Clean Template: Entry: 'No protected xxxx found' even if --visibility hides protected level

### ISSUE THREAD

**Issue by Stefanius67** [phpDocumentor/phpDocumentor#2489]
# Template issue/request

Clean Template
Entry: 'No protected xxxx found' even if --visibility hides protected level.
If protected/private level is excluded with --visibility parameter, there should no entry 'No protected xxxx found' be generated.

(I personally find this entry superfluous anyway, regardless of whether entries are not available or whether they have been hidden by the visibility param)

![phpDoc-Issue1](https://user-images.githubusercontent.com/28049647/88538357-86a0e680-d00f-11ea-9b7a-2a53cd68ea8c.png)

**Comment by WebDevLan4You** [comment]
hi @Stefanius67 so i know there is no longer support for the "Clean" Template for version 3 & newer.
Read this: https://github.com/phpDocumentor/phpDocumentor/issues/2485#issuecomment-662587713

**Comment by Stefanius67** [comment]
Thanks for that info - i havent read the #2485 issue so far.

The 'clean' template is still included in the project ([https://github.com/phpDocumentor/phpDocumentor/tree/master/data/templates/clean](url)) and calling phpDoc with the `--template=clean` parameter also does not generate any warnings or errors. So I've used this template also in Version 3 because for me it's more clearly structured than the default template (the design is only secondary for me...).

I will now use the default template, close this issue and wait for the announced community corner.

(Unfortunately, I can no longer use phpDoc version 2.9 for my 'live' documentation, since PHP 7.4 code, which contains, for example, 'Nullable type hints', no longer achieves a reasonable result.)
