### ISSUE TITLE
Trait namespace empty

### ISSUE THREAD

**Issue by BasvanH** [phpDocumentor/phpDocumentor#2501]
When generating the PHPDoc webcontent, my traits folder/namepsace stays empty. In my classes who use the traits, I do however see the imported methods.

## Expected behavior
I would expect the Trait namespace to be filled with my traits.

## Actual behavior
No traits in the webcontent.

## Example of a trait file
```
<?php

namespace App\Traits;

/**
 * TestTrait
 * 
 * This is a test trait
 *
 * @author john@do.com
 */
trait Test
{
    /**
     * Generates a password.
     *
     * @return string Returns a password.
     */
    public function generate_password()
    {
      return 'sdfsfds';
    }
}
```

Executon of phpdoc: 
`php phpDocumentor3.phar  -d ./app -t public/docs/api`

## Your environment
* Version used: 3.0.0-rc
* phpDocumentor3.phar
* PHP version 7.4.7 on IIS
* Operating system and version Windows 2016

**Comment by jaapio** [comment]
Thanks for reporting. I couldn't reproduce this issue with the latest version on master. There were quite a lot of changes since RC. So I expect this to be fixed. 
If you want to give if a try yourself please download the latest version https://github.com/phpDocumentor/phpDocumentor#nightly-builds

**Comment by BasvanH** [comment]
Just run the latest version from https://github.com/phpDocumentor/phpDocumentor/suites/1286527562/artifacts/20002772 but my traits are not generated.

They are in `/App/Traits`, when browsing to `namespaces/app-traits.html` the page has no content.

**Comment by jaapio** [comment]
Thanks for your feedback, we are going to investigate this.

**Comment by jaapio** [comment]
I just pushed a commit which fixes this issue: https://github.com/phpDocumentor/phpDocumentor/commit/8b6fc2079926cc117936bd9caa6d72511cb6f9f2

The cause was an invalid fix in the template. 

Please find a new build at: https://github.com/phpDocumentor/phpDocumentor/runs/1216830162 
let me know when you experience any problems.

**Comment by BasvanH** [comment]
I can confirm it works, thanks!
