### ISSUE TITLE
[v3.0.0-rc] End of line not parsed properly when looking at @packages directives

### ISSUE THREAD

**Issue by yourpropertyexpert** [phpDocumentor/phpDocumentor#2512]
In 3.0.0-rc, something odd is happening when parsing a file that has a @package directive in the file summary block.

The impact is that the transformation stage is throwing up an error message about a file name being too long.

## Expected behavior

It shouldn't give error message along the lines of the following

## Actual behavior

When processing a directory that contains a file that starts with something like:

`<?php
/**
 * Part of the WerAreWe APIs
 * @package addcustomerlogo
 *
 * This is an API call. It should NOT use the standard page display functions
 * Add a new site image[.....]`

... I end up with a runtime warning along the lines of

`
Applying transformations (can take a while)
--
27 | 147/147 [============================] 100%
28 | 1/16 [=>--------------------------]   6%
29 | 4/16 [=======>--------------------]  25%11:42:18 WARNING   [php] Warning: file_put_contents(/tmp/api/packages/addcustomerlogoPartoftheWerAreWeAPIsThisisanAPIcall-ItshouldNOTusethestandardpagedisplayfunctionsYouneedtosupplytheseparamatersorganisationsetbyThejsonoutputmaycontainthefollowingelementssuccesserrorIfsuccessisfalsethenerrorwillcontainanerrormessageIfsuccessistruethenitwassuccessfulandreturnwillcontaintheimagecopyrightWerAreWeLtd2020.html): failed to open stream: File name too long ["exception" => ErrorException { …}]
`

So, it's basically trying to name the package file after the @package line and the following lines in the DocBlock.

## Steps to reproduce the problem

1. Trying to run v3.0.0-rc with the sample above

## Your environment

* Version used: 3.0.0-rc
* Install method: curl the phar file
* PHP version:  PHP 7.3.12
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Linux 2a7b1e264a75 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux

* Link to your project: [Not available]

**Comment by jaapio** [comment]
The problem you are facing is related to the order of your docblock. The structure must be as described in our documentation:
https://docs.phpdoc.org/latest/guides/docblocks.html

It is not possible to have tags inside your description. Because phpDocumentor will think that your description belongs to the latest tag. In your case, a `@package` doesn't have a description but only the package name, so everything after the `@package` is part of the package name.
