### ISSUE TITLE
Exception to run phpdoc  Argument 1 passed to phpDocumentor\Descriptor\PropertyDescriptor::setType() 

### ISSUE THREAD

**Issue by FuriosoJack** [phpDocumentor/phpDocumentor#2513]
When the command is executed from the console, without using phpdoc.xml it generates the exception

## Expected behavior
It is expected that instead of throwing the exception it should show the file it is processing in order to correct it and run the command again.

## Actual behavior
It is expected that instead of throwing the exception it should show the file it is processing in order to correct it and run the command again.

  7/17 [===========>----------------]  41%11:07:56 ERROR     [console] Error thrown while running command "-d app -t docs --log 'file.log' --template=clean". Message: "Argument 1 passed to phpDocumentor\Descriptor\PropertyDescriptor::setType() must implement interface phpDocumentor\Reflection\Type, null given, called in /home/juan/Documentos/Trabajo/crm-laravel7/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Descriptor/ClassDescriptor.php on line 265" ["exception" => TypeError { …},"command" => "-d app -t docs --log 'file.log' --template=clean","message" => "Argument 1 passed to phpDocumentor\Descriptor\PropertyDescriptor::setType() must implement interface phpDocumentor\Reflection\Type, null given, called in /home/juan/Documentos/Trabajo/crm-laravel7/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Descriptor/ClassDescriptor.php on line 265"]
11:07:56 ERROR     [console] Error thrown while running command "-d app -t docs --log 'file.log' --template=clean". Message: "Argument 1 passed to phpDocumentor\Descriptor\PropertyDescriptor::setType() must implement interface phpDocumentor\Reflection\Type, null given, called in /home/juan/Documentos/Trabajo/crm-laravel7/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Descriptor/ClassDescriptor.php on line 265" ["exception" => TypeError { …},"command" => "-d app -t docs --log 'file.log' --template=clean","message" => "Argument 1 passed to phpDocumentor\Descriptor\PropertyDescriptor::setType() must implement interface phpDocumentor\Reflection\Type, null given, called in /home/juan/Documentos/Trabajo/crm-laravel7/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Descriptor/ClassDescriptor.php on line 265"]

In PropertyDescriptor.php line 82:
                                                                               
  Argument 1 passed to phpDocumentor\Descriptor\PropertyDescriptor::setType()  
   must implement interface phpDocumentor\Reflection\Type, null given, called  
   in /home/juan/Documentos/Trabajo/crm-laravel7/vendor/phpdocumentor/phpdocu  
  mentor/src/phpDocumentor/Descriptor/ClassDescriptor.php on line 265    

## Steps to reproduce the problem

1. vendor/bin/phpdoc -d app -t docs --log file.log --template=clean

* Version used: 3.0.0-alpha1
* Install method: composer
* PHP version 7.3
* Operating system and version Ubuntu 20

* Attach code that is involved: Isprivate project laravel
* ...

**Comment by jaapio** [comment]
Hi @FuriosoJack 

You are using an alpha version of phpDocumentor 3. I to highly recommend to update phpDocumentor to RC1 release or even the nightly build which you can find here: https://github.com/phpDocumentor/phpDocumentor/suites/1190410849/artifacts/17509880 

Or consult the readme of this repo how to get a more recent nightly build when you are trying this later. The alpha version contained a number of bugs that were already fixed in the later releases.
