### ISSUE TITLE
"public function" keywords without anything else

### ISSUE THREAD

**Issue by simivar** [phpDocumentor/phpDocumentor#2585]
in `tests/functional/phpDocumentor/tags/InlineExampleTagTest.php` on line 11, there are `public function` keywords without anything else following. From what I see it was introduced in 76784d4b0c3a22acc5933643ac1d9aa81499f1f9.

https://github.com/phpDocumentor/phpDocumentor/blob/master/tests/functional/phpDocumentor/tags/InlineExampleTagTest.php#L11

## Expected behavior

A proper test case in class.

## Actual behavior

PHP Parse error:  syntax error, unexpected '}' in /mnt/c/[...]/phpDocumentor/tests/functional/phpDocumentor/
tags/InlineExampleTagTest.php on line 12

## Steps to reproduce the problem

1. Checkout `master` branch
2. Run PHPUnit tests.

**Comment by jaapio** [comment]
Thanks for reporting this!.
