### ISSUE TITLE
Undefined $dsn variable in DsnTest

### ISSUE THREAD

**Issue by simivar** [phpDocumentor/phpDocumentor#2586]
From what I see in the #2584 test for Dsn was introduced. Unfortunately on line 68 undefined variable is used, look [here](https://github.com/phpDocumentor/phpDocumentor/pull/2584/files#diff-0fdb98e3cf0bf50eedc283de84e7c950R68).

## Expected behavior

Passing tests

## Actual behavior

There was 1 error:

1) phpDocumentor\DsnTest::testPathNotStartingWithSlash
Undefined variable: dsn

## Steps to reproduce the problem

1. Checkout master branch
2. Run PHPUnit tests

**Comment by jaapio** [comment]
Thanks for this one.
