### ISSUE TITLE
Generics are not displayed correctly

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2645]
When showing documentation for a class containing Generics; the escaping does weird things. It looks like the brackets for the generics are not escaped and as such are interpreted as an HTML tag.

I believe that this is because that specific location uses a twig raw filter to escape encoding because we wanted to use a bit of HTML there. It should be investigated and made so that the encoding is done correctly / no raw filter is needed there.

Example:

![image](https://user-images.githubusercontent.com/193704/96630084-c75d8280-1314-11eb-866c-632a5aa58360.png)

While the webinspector says:

![image](https://user-images.githubusercontent.com/193704/96630118-d6dccb80-1314-11eb-9687-166feccca20d.png)

**Comment by jaapio** [comment]
problem is in the rendering of:
`array<string, string>` but we need to make sure that `string[]` is also working as expected. 

we need to copy the behavior of the types but in a more advanced way, since we want to have links to type we know
