### ISSUE TITLE
Summary adds unwanted line break for ".." and "..."

### ISSUE THREAD

**Issue by WoodrowShigeru** [phpDocumentor/phpDocumentor#2649]
It seems the parser can't handle successive periods (or dot-dots, or ellipsis) in the summary line. It adds an unwanted newline (or line break) after the first period. Attempts to escape with backslash or wrap in backticks didn't work for me.

(At the least, let users have a way to escape it in some way. Currently, the line break is unavoidable)

## Expected behavior

```
Lorem ipsum ".." dolor sit amet.
```

## Actual behavior

```
Lorem ipsum ".

." dolor sit amet.
```

## Steps to reproduce the problem

```
/**
 * Lorem ipsum ".." dolor sit amet.
 *
 * Descriptions ".." are fine.
 *
 * @return void
 */
public function irrelephant() {}
```

## Your environment

* Ubuntu 18.04.5
* LAMP, Server version: Apache/2.4.29 (Ubuntu), Server built: 2020-08-12T21:33:25
* PHP 7.2.24
* phpDocumentor 2.9.0, installed manually by downloading the tar-ball from the releases tab of this github.

**Comment by mvriel** [comment]
I just checked this in phpDocumentor 3.0 and the issue seems to be resolved there. I did spot a possible issue with functions in the global namespace but when I try your example as a class method I get proper output

**Comment by mvriel** [comment]
(just rechecked the other issue I mentioned above; the example that was included in this issue is a class method and is invalid PHP outside of a class. I had missed that :) So: no problem)
