### ISSUE TITLE
Admonition rendering does not work

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#2672]
When rendering RestructuredText components and using an admonition (such as "note", "important", etc); these are not rendered at all and styling is missing.

After this issue, admonitions should 

1. render
2. be styled
3. Contain an icon showing the type of admonition

**Comment by jaapio** [comment]
This issue has been fixed by the new integration. If you pick the master branch or our v3 docker tag this is solved.

Any new release will contain this, fix.
