### ISSUE TITLE
Font Awesome is loaded twice in the HTML template, with conflicting technologies

### ISSUE THREAD

**Issue by mlwilkerson** [phpDocumentor/phpDocumentor#2686]
## Expected behavior
Font Awesome should be loaded at most one time, and it should be either Webfont technology or SVG technology, not both.

Ironically, I was publishing the latest version the Font Awesome WordPress plugin when I noticed this problem in its own generated API docs 😄.

## Actual behavior
Both are being loaded.

See [here in layout.html.twig](https://github.com/phpDocumentor/phpDocumentor/blob/8332a760a3e8c280aa1996194eadb9c5c4d840d2/data/templates/default/layout.html.twig#L14) and [here](https://github.com/phpDocumentor/phpDocumentor/blob/8332a760a3e8c280aa1996194eadb9c5c4d840d2/data/templates/default/layout.html.twig#L19).

## Steps to reproduce the problem

It's self-evident from reading the code.

## Your environment

N/A

* Version used: the problem is currently on the master branch

---
I'd gladly put up a PR to fix this, but I'm not sure which to remove since I don't know what is the desired behavior here. The choice of Font Awesome technology depends upon the use cases. But it's never correct to load it twice. Probably the simplest approach, unless you know that you require SVG/JS-only features, like [Power Transforms](https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms), is to drop the `all.min.js` and just keep the Webfont/CSS technology via `all.min.css`.

**Comment by jaapio** [comment]
To be honest I don't know either which one is needed. I think we can go with `all.min.css`. 

A pr would be more than welcome :+1:
