### ISSUE TITLE
phpDocumentor.phar (3.0.0) does not work at all on openSUSE 15.2

### ISSUE THREAD

**Issue by restena-sw** [phpDocumentor/phpDocumentor#2729]
I just downloaded the final version 3.0.0 phar (congrats for this big milestone!) and wanted to run it on an openSUSE 15.2 (PHP 7.4 installed). After clearing some needed php modules (fileinfo) the final error I get is:

```
> phpDocumentor.phar
 [WARNING] Some commands could not be registered:                                                                       

In ArrayNode.php line 320:
                                                                                                                                                                        
Unrecognized option "plugins" under "phpdocumentor". Available options are "configVersion", "files", "logging", "parser", "title", "transformations", "transformer".  

There are no commands defined in the "project" namespace.  
```

This happens regardless if I call the phar without any arguments, with a "-h" or with the real arguments in my Makefile (which worked in the alphaX times of v3).

## Expected behavior
phpDocumentor.phar should execute.

## Actual behavior
Regardless which cmdline switches are given, the same error occurs (see above).

## Steps to reproduce the problem

1. install openSUSE 15.2, php7 with php7-fileinfo
2. run "phpDocumentor.phar"

## Your environment

* Version used: 3.0.0
* Install method: phar
* PHP version PHP 7.4.6
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): openSUSE 15.2
* Link to your project: I don't get that far - error occurs without any code being processed
* Attach code that is involved: I don't get that far - error occurs without any code being processed

**Comment by jaapio** [comment]
Hi @restena-sw 

I think you have an issue with your config file. Please try to run with `--config=none` which will ignore your configuration. 

If it does run with that, please share your configuration.

**Comment by restena-sw** [comment]
The tool was never before installed on my new work-from-home machine, so that would surprise me. And indeed:

```
> phpDocumentor.phar -h --config=none

 [WARNING] Some commands could not be registered:

In ArrayNode.php line 320:

Unrecognized option "plugins" under "phpdocumentor". Available options are "configVersion", "files", "logging", "parser", "title", "transformations", "transformer".

There are no commands defined in the "project" namespace.
```

**Comment by restena-sw** [comment]
Coming back to this... you were right. There was a phpdoc.xml configuration file in the root of my project and it did contain a "plugins" entry. I deleted that and now things work fine.

The only thing unclear at this point is why --config=none did not actually ignore the config file.

Anyway, closing this issue as the material part of it is solved.

Thanks!

**Comment by jaapio** [comment]
Thanks for your response.
