### ISSUE TITLE
Remove dev dependencies and release 3.0.1

### ISSUE THREAD

**Issue by redaxmedia** [phpDocumentor/phpDocumentor#2731]
Hey folks,

1. I had to enable flag `"minimum-stability": "dev"``in order to install phpdocumentor in version 3.0.0
1.1 The reason for this are dev dependencies in a stable release
2. This causes to load phpdocumentor/reflection (4.x-dev 6272b5e) that is not compatible

See related issue with links to build jobs: https://github.com/phpDocumentor/Reflection/issues/191

* Version: 3.0.0
* PHP version: 7.4
* OS: Ubuntu

**That being said... please don't use dev dependencies in stable releases and consider to publish phpdocumentor 3.0.1 with graphviz 2.0.0-alpha1 as soon as possible.**

**Comment by jaapio** [comment]
refs #2806

**Comment by redaxmedia** [comment]
@jaapio Thanks a lot for your work
