### ISSUE TITLE
Latest phar fails on MacOS High Sierra PHP 8

### ISSUE THREAD

**Issue by topdown** [phpDocumentor/phpDocumentor#2750]
Trying to generate PHP documentation for a custom PHP project on:
MacOS High Sierra 10.13.6 
PHP Version
```
PHP 8.0.0 (cli) (built: Dec  7 2020 10:02:01) ( NTS )                                     
Copyright (c) The PHP Group                                                               
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies                                   
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans                        
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies 
```
Install
```
wget https://phpdoc.org/phpDocumentor.phar
chmod +x phpDocumentor.phar
```
I tried running against my code with the same failure as below. So I tried the example in the docs.
```
cd src
phpDocumentor -d . -t docs --config=none
```

## Actual behavior
```
[WARNING] Some commands could not be registered:                               
In Filter_6ae6af3.php line 5:                                                                 
  Call to undefined function ContainerLx0j6hQ\include_once\dirname()  
                                         
  There are no commands defined in the "project" namespace.  
```
I also tried with a configuration file.

I get the same response always.                                                           

## Expected behavior
Documentation to be generated 

* Version used: Latest phar
* Install wget phar
* PHP version 8
* MacOS High Sierra 10.13.6 
* Any code, the simple example here https://docs.phpdoc.org/3.0/guide/getting-started/your-first-set-of-documentation.html fails

**Comment by jaapio** [comment]
hi,

unfortunately phpdocumentor doesn't run yet on php8. besides that we do not support any php8 features yet. Please run phpDocumentor on php 7.4. It will be able to process your php8 code. But it won't understand all constructions.
