### ISSUE TITLE
Specific function(s) not getting indexed/documented from WordPress source

### ISSUE THREAD

**Issue by oliverschloebe** [phpDocumentor/phpDocumentor#2751]
Hi, after parsing the WordPress core files into a `structure.xml` file I noticed that 1 function (or maybe more; havn't tested yet) from the file `/wp-includes/taxonomy.php` isn't present in the generated `structure.xml` file and I can't figure out why.

## Expected behavior
The function `get_germs()` from the WordPress source file [`/wp-includes/taxonomy.php`](https://wpseek.com/source/wp/latest/nav.html?wp-includes/taxonomy.php.html) should be present in the generated [`structure.xml`](https://wpseek.com/source/wp/docblox/structure.xml) coming from phpDocumentor.

## Actual behavior
The function `get_germs()` from the WordPress source file [`/wp-includes/taxonomy.php`](https://wpseek.com/source/wp/latest/nav.html?wp-includes/taxonomy.php.html) **is not** present in the generated [`structure.xml`](https://wpseek.com/source/wp/docblox/structure.xml) coming from phpDocumentor even though other functions from that file were properly documented and are present in the `structure.xml` file.
The command from step 2 (see below) does not print any parse errors or warnings related to `/wp-includes/taxonomy.php`.

## Steps to reproduce the problem

1. Checkout the current WordPress core from https://github.com/WordPress/WordPress
2. Run in CLI: `php phpdoc parse --force -d ./wp/source -t ./wp/target --cache-folder ./wp/cache -c ./phpdoc.xml --template=xml --title=WordPress`
3. Verify that the function `get_germs()` from the WordPress source file `/wp-includes/taxonomy.php` **is not** present in the generated `structure.xml` file.

## Your environment

* Version used: [3.0.0](https://github.com/phpDocumentor/phpDocumentor/releases/tag/v3.0.0)
* Install method: Phive
* PHP version: 7.4.13
* Operating system and version: Ubuntu 18.04.5 LTS
* Link to your project: https://wpseek.com/file/wp-includes/taxonomy.php/ (this is generated from the `structure.xml` file)

`phpdoc.xml` used:
```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="data/xsd/phpdoc.xsd">
    <paths>
        <output>wp/target</output>
    </paths>
    <version number="3.0.0">
        <folder>wp/target</folder>
        <api>
            <source dsn=".">
                <path>wp/source</path>
            </source>
            <output>api</output>
            <ignore hidden="true" symlinks="true">
                <path>vendor/**/*</path>
                <path>wp-includes/js/**/*</path>
                <path>wp-includes/sodium_compat/**/*</path>
                <path>wp-includes/ID3/*</path>
                <path>wp-content/**/*</path>
                <path>wp-admin/load-scripts.php</path>
                <path>wp-admin/load-styles.php</path>
                <path>wp-admin/includes/noop.php</path>
                <path>wp-includes/class-*.php</path>
            </ignore>
            <extensions>
                <extension>php</extension>
            </extensions>
            <default-package-name>WordPress</default-package-name>
        </api>
    </version>
    <template name="xml"/>
</phpdocumentor>
```

**Comment by jaapio** [comment]
Hi @oliverschloebe 

Those functions are hidden because they contain the `@internal` tag. If you want to include everything set the visibility to `internal` 

`<visibility>internal</visibility>`
