### ISSUE TITLE
XML Configuration Failure for Setting Tag (phpDoc 3)

### ISSUE THREAD

**Issue by blackdrago** [phpDocumentor/phpDocumentor#2776]
I'm trying to add the --setting=graphs.enabled=true parameter to my phpdoc.dist.xml file. From the example on this page, Appendix B: https://docs.phpdoc.org/3.0/guide/references/configuration.html - the expected XML for any setting is like so:

```
<setting name="string" value="string"/>
```

So I add this tag (modified for the graphs enabled tag) to my (previously working) phpdoc.dist.xml file. I've included the entire XML below:

```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.phpdoc.org" configVersion="3" xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd">
  <title><![CDATA[Utility Package]]></title>
  <paths>
    <output>src/resources/devdocs/php</output>
    <cache>src/resources/devdocs/php/cache</cache>
  </paths>
  <setting name="graphs.enabled" value="true"/>
  <version number="3.0.0">
    <api>
      <source dsn=".">
        <path>src/</path>
      </source>
      <ignore>
        <path>src/resources/devdocs/</path>
        <path>tests/</path>
      </ignore>
      <markers>
        <marker>ORACLESPEC</marker>
        <marker>TODO</marker>
        <marker>FIXME</marker>
      </markers>
    </api>
  </version>
  <template name="clean"/>
</phpdocumentor>
```

## Expected behavior
Now phpdoc -c should do the same thing that phpdoc -c --setting=graphs.enabled=true used to do.

## Actual behavior
A warning, then an error is reported:
```
 [WARNING] Some commands could not be registered:                                              

In ArrayNode.php line 326:
Unrecognized option "0" under "phpdocumentor.settings". Available options are "name", "value".                                                                                        

There are no commands defined in the "project" namespace. 
```

If I remove the setting tag from the XML, documentation is generated as expected.

## Your environment
* Version used: 3.0.0-alpha1
* Install method: Homebrew + composer
* PHP version: 7.2.34
* Operating system and version: MacOS Mojave (10.14)
* Link to your project:

How do you add the --setting=graphs.enabled=true parameter to your configuration file?

**Comment by jaapio** [comment]
Thanks for reporting this. I just pushed a fix for this issue. It will be part of our nightly builds
