### ISSUE TITLE
Interface extension styles do not match that of classes

### ISSUE THREAD

**Issue by rowansays** [phpDocumentor/phpDocumentor#2778]
# Template issue/request

I noticed that interface titles display a bit differently than class titles. In my opinion, the class titles are styled much better. Please see screenshots below.

I addressed this issue in a custom template by changing the class name in the [interface title template](https://github.com/phpDocumentor/phpDocumentor/blob/master/data/templates/default/components/interface-title.html.twig#L4)

```
-        <span class="phpdocumentor-interface__extends">
+        <span class="phpdocumentor-element__extends">
```

Example 1: Class that extends a class.

![Screen Shot 2021-01-28 at 01 30 18](https://user-images.githubusercontent.com/74547960/106118081-91484f80-6108-11eb-8564-4b683642f45d.png)

Example 2: Interface that extends an interface.

![Screen Shot 2021-01-28 at 01 32 08](https://user-images.githubusercontent.com/74547960/106118219-b6d55900-6108-11eb-9826-01fefac964a7.png)

**Comment by jaapio** [comment]
Thanks for reporting :+1:

**Comment by rowansays** [comment]
You’re welcome. Thanks for the quick fix :)
