### ISSUE TITLE
Default template: Anchor tag left open in search.js

### ISSUE THREAD

**Issue by rowansays** [phpDocumentor/phpDocumentor#2783]
Hello,
I noticed that there is an anchor tag that is never closed in the javascript template for the search script. [Here's a link](https://github.com/phpDocumentor/phpDocumentor/blob/0b13b5f08d2dba6b051bc56554eb976abb9bc612/data/templates/default/search.js.twig#L114).

**Comment by jaapio** [comment]
Thanks for reporting this issue. :1st_place_medal:

**Comment by rowansays** [comment]
You’re welcome. Thanks for the quick fix :)
