### ISSUE TITLE
Returns section not appearing for normal functions

### ISSUE THREAD

**Issue by MKen212** [phpDocumentor/phpDocumentor#2807]
The returns section from an ```@return``` tag is not appearing for a normal function, although it is appearing when the function is included as a method in a class.

## Expected behavior
As per the documentation _"Structural Elements of type method or function, that are tagged with the ```@return``` tag, will have an additional section Returns in their content description that shows the return Type and description."_ 

Example test file for a method within a class:
```
<?php
class Test
{
  /**
   * Test Method
   *
   * @param string $myArgument Argument Description.
   *
   * @return bool  Return Description
   */
  public function myFunction($myArgument)
  {
    return true;
  }
}
```
This produces the following output, which includes the "Return values" as expected:
![image](https://user-images.githubusercontent.com/46496040/107042151-b2243b00-67c1-11eb-8e15-cd3719afbbbf.png)

## Actual behavior
If you create THE SAME function but not inside a class, e.g.
```
<?php
/**
 * Test function
 *
 * @param string $myArgument Argument Description.
 *
 * @return bool  Return Description
 */
function myFunction($myArgument)
{
  return true;
}
```
Then you do not get the "Return values" section:
![image](https://user-images.githubusercontent.com/46496040/107042480-1ba44980-67c2-11eb-99cc-d5955af52f48.png)

## Your environment
* Version used: 3.0.0
* Install method: ```wget https://phpdoc.org/phpDocumentor.phar```
* PHP version: 7.3.19-1
* Operating system and version: Debian GNU/Linux 10.6

**Comment by jaspervann** [comment]
Same issue here, using the latest docker image

**Comment by mvriel** [comment]
This is fixed on master and will be included in the next release; in the meantime you could use one of the PHARs that is built in our pipeline. On every commit we build a test version of the PHAR and the latest one should include this fix: https://github.com/phpDocumentor/phpDocumentor/suites/2463444487/artifacts/52931706

Please note that this is a build from master and includes other features and bugfixes, but is not thoroughly tested by a human
