### ISSUE TITLE
The `folder` and `output` elements are not working as I expected

### ISSUE THREAD

**Issue by ngmy** [phpDocumentor/phpDocumentor#2819]
I tried to create the `phpdoc.dist.xml` file by reading this [document](https://docs.phpdoc.org/3.0/guide/references/configuration.html).
But the `folder` and `output` elements are not working as I expected.
Is there something wrong with my `phpdoc.dist.xml` file?

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <paths>
        <output>docs</output>
    </paths>
    <version number="3.0.0">
        <folder>latest</folder>
        <api>
            <source dsn=".">
                <path>src</path>
            </source>
            <output>api</output>
        </api>
    </version>
</phpdocumentor>
```

## Expected behavior

The documentation is generated under the `docs/latest/api` directory.

## Actual behavior

The documentation is generated under the `docs` directory.

## Steps to reproduce the problem

1. Run `php tools/phpDocumentor --force`

## Your environment

* Version used: 3.0.0
* Install method: Phar
* PHP version: 7.4.11
* Operating system and version (e.g. Ubuntu 20.04, Windows 10):  Ubuntu 18.04.5 LTS (Laradock's workspace container)

**Comment by izamoramx** [comment]
I have this same issue. I tried using the example config file provided in the documentation (with some minor corrections to make it run) and both 'folder' and 'api/output' tags are ignored no matter what. I tried different variations of the configuration and the only output ever used is the one from 'paths'

**Comment by jaapio** [comment]
This is a known issue. There are some situations not covered correctly. 
I will close this issue because we are planning to improve this behavior in #2231.
I would like to have your input on that issue. 

Thanks in advance :-)

**Comment by izamoramx** [comment]
@jaapio do you have an ETA on that change?
