### ISSUE TITLE
@var ignores the description section

### ISSUE THREAD

**Issue by izamoramx** [phpDocumentor/phpDocumentor#2820]
When using the @var tag and providing a description for the tag, the generator ignores the description entirely

## Expected behavior
/** @var string|null Short docblock, should contain a description. */
    protected $description = null;

Should produce something like this:
$description : string|null Short docblock, should contain a description.

## Actual behavior
The document only shows:
$description : string|null

## Steps to reproduce the problem

1. As the documentation example tag a constant or property of a class with the '@var' tag
   /** @var string|null Short docblock, should contain a description. */
    protected $description = null;
2. Generate the documentation
3. Confirm result in documentation page

## Your environment

* Version used: 3.0.0-alpha1
* Install method: PHAR file
* PHP version: 7.4.15
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Windows 10
* Link to your project:
* Attach code that is involved
* ...

**Comment by brbrowning21** [comment]
It seems like it only processes `@var` descriptions when they are put in the DocBlock summary instead.
```php
/**
 * This will actually show up.
 * 
 * @var string|null This won't show up.
 */
$description = null;
```

This seems go go against the most common way of using `@var` tags, described in
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#517-var

**Comment by jaapio** [comment]
I added the `@var` description in the property section of the template. It is not possible to make it part of the TOC, since a description of a tag can be multi-line which would not fit into the TOC.
