### ISSUE TITLE
[Default template] Privacy issues by loading external scripts

### ISSUE THREAD

**Issue by Bill-ColeUS** [phpDocumentor/phpDocumentor#2825]
# Template request

I would like to request better privacy. Many of us in our workplace, are not allowed to load external scripts when browsing local content (like the documentation of a private project).

The default template loads google fonts (a serious privacy issue, since google monitors all requests, IP addresses, browser data, all sorts of things) among other links like javascript libraries.

This can be easily avoided, by using google fonts stored locally, the following project gives you a nice GUI for downloading the CSS+font files:
https://google-webfonts-helper.herokuapp.com/fonts

Eventually, I had to clone the default template, modify the `layout.html.twig` file to point to local files for all scripts/fonts/css.

I understand that this has various implications, like maintaining local versions of foreign projects, but these things can be solved with a little work.

Thank you.

**Comment by mvriel** [comment]
Hello Bill,

One of the things we would like, is to use webpack to bundle various assets for a template to remove the need for CDN stored assets. This dependency would not be part of generating documentation using phpDocumentor; but rather during development of phpDocumentor to pre-build Javascript libraries and fonts.

I cannot give a timeline when this may be done; at the moment our focus lies on adding support for multiple versions of a codebase in one documentation site, and the new Guides feature that will allow you to render hand-written documentation from RestructuredText files.
