### ISSUE TITLE
Page of templates is down

### ISSUE THREAD

**Issue by Kwadz** [phpDocumentor/phpDocumentor#2826]
URL: https://phpdoc.org/templates
Link location: https://docs.phpdoc.org/3.0/guide/getting-started/your-first-set-of-documentation.html#read-more

![image](https://user-images.githubusercontent.com/1472599/108066774-1c5d9b00-7060-11eb-8d51-bcdb65107023.png)

**Comment by bu4ak** [comment]
\+

**Comment by jaapio** [comment]
Please check demo.phpdoc.org

**Comment by mvriel** [comment]
Thank for reporting this; the offending page has been removed as part of an ongoing effort to (re)write more documentation for phpDocumentor
