### ISSUE TITLE
plantuml not found

### ISSUE THREAD

**Issue by FrankMarkwort** [phpDocumentor/phpDocumentor#2832]
This only works if it is called from a certain directory depth.

https://github.com/phpDocumentor/phpDocumentor/blob/6088101c18b35e129bc224c6ac56b99be9e5f226/src/phpDocumentor/Transformer/Writer/Graph/PlantumlClassDiagram.php#L61

**Comment by mvriel** [comment]
Thanks for reporting this; a more appropriate solution would be to use Symfony's project_dir path determination in the dependency injection setup. I have issues PR https://github.com/phpDocumentor/phpDocumentor/pull/2841 to address this
