### ISSUE TITLE
Markdown tables are not handled

### ISSUE THREAD

**Issue by shavounet** [phpDocumentor/phpDocumentor#2834]
I use GFM tables in the "description" section for my class but it's not rendered

## Expected behavior

With the following PHPDoc
```php
/**
 * Some summary
 *
 * Some description
 *
 * ##### Options
 *
 * | Code | Type | Required | Default | Description |
 * | ---- | ---- | :------: | ------- | ----------- |
 * | `property` | `string` | **X** | | Property path to read from input |
 *
 */
```

The table should be rendered like this

| Code | Type | Required | Default | Description |
| ---- | ---- | :------: | ------- | ----------- |
| `property` | `string` | **X** | | Property path to read from input |

I tried with multiple examples (and very simple ones), none works.

## Actual behavior

The table is not transformed.

![image](https://user-images.githubusercontent.com/2323369/109319717-770ca900-784f-11eb-9283-97e1b77bb654.png)

## Steps to reproduce the problem

See above, there is no additional configuration.

## Your environment

* Version used: 3.0.0
* Install method : phar archive from github releases
* PHP version : 7.2
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Debian 10 (in a Docker image)

**Comment by Matslom** [comment]
Looks like the markdown converter is not configured to use tables. `League\CommonMark\MarkdownConverter` by default doeesn't support tables.
https://github.com/phpDocumentor/phpDocumentor/blob/c8fded0479e31d5133ca26b3fc64e05b7cd2eae7/config/services.yaml#L246-L253
