### ISSUE TITLE
Valid PHP8 attribute syntax causes syntax errors

### ISSUE THREAD

**Issue by meenzen** [phpDocumentor/phpDocumentor#2844]
## Expected behavior

PhpDocumentor ignores the attributes and parses the files normally.

## Actual behavior

When attributes are on the same line as the function definition or span multiple lines, it causes problems.

```php
// working as it should
#[Pure]
private function test(): string
{
    return "This is a test"; 
}
```

```php
// this causes a syntax error
#[Pure] private function test(): string
{
    return "This is a test"; 
}
```

```php
// this also causes a syntax error
#[Route('/very/cool/route/{foo}/{bar}', name: 'very_cool_route',
    defaults: ['foo' => 'foo', 'bar' => 'bar'])]
private function test(): string
{
    return "This is a test"; 
}
```

## Steps to reproduce the problem

1. Run phpDocumentor on these files: [Example.zip](https://github.com/phpDocumentor/phpDocumentor/files/6089247/Example.zip)

## Your environment

* Version used: 3.0.0
* Install method: manual download of the phpDocumentor.phar
* PHP 8.0.2
* Windows 10 1909

**Comment by jaapio** [comment]
Thanks for reporting this. however, phpDocumentor doesn't support the new attributes in some way I just created a pr to upgrade our internal parser which should be a fix for this issue. The new parser supports most of the new php8 syntax which is applicable for phpDocumentor. Attributes need to be added. Which is already on our list. But we didn't give it a high priority. 

I consider this issue fixed when #2848 is merged to master.
