### ISSUE TITLE
The documentation does not contain all the classes

### ISSUE THREAD

**Issue by tbela99** [phpDocumentor/phpDocumentor#2882]
I tried the latest version with https://github.com/tbela99/css
still a lot of classes are missing and a lot are reported in the wrong namespace. 
here are the issues I have noticed
## Expected behavior

see the error description below

## Actual behavior

- missing classes
- missing namespaces
- classes in the incorrect namepace

## Steps to reproduce the problem

1. clone https://github.com/tbela99/css
2. download phpdocumentor phar archive
3. from the top level directory generate the documentation using php 7.4 'php ./phpDocumentor.phar -d ./src/TBela/CSS/ -t ./docs/api'

## Your environment

* Version used: 3.0.0-alpha1
* Install method : wget "https://phpdoc.org/phpDocumentor.phar" && chmod +x phpDocumentor.phar
* PHP version : 7.4
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu 20.04
* Link to your project: https://github.com/tbela99/css
* Attach code that is involved
* ...

**Comment by lkppo** [comment]
Hi,

3.0.0-alpha1 is not compliant with PHP 7.4, and is NOT the last version released. 

For PHP 7.4 compliance use [3.0.0 release](https://github.com/phpDocumentor/phpDocumentor/releases/tag/v3.0.0).

Regards,

**Comment by jaapio** [comment]
I assume that the v3 and v3.1 release are fixing this issue. If not, please open a new issue with some pointers what is actually missing. Please include some screenshots or pointers to what you are missing. Because I cannot clone every project to see what might be wrong.
