### ISSUE TITLE
The given template responsive could not be found or is not readable  

### ISSUE THREAD

**Issue by rino1** [phpDocumentor/phpDocumentor#2883]
`
$ phpdoc -d src/ -t docs/ --template responsive
phpDocumentor v3.0.0

Parsing files
 1/1 [============================] 100%09:22:24 ERROR     [console] Error thrown while running command "-d 'src/' -t 'docs/' --template responsive". Message: "The given template responsive could not be found or is not readable" ["exception" => phpDocumentor\Transformer\Template\TemplateNotFound^ { …},"command" => "-d 'src/' -t 'docs/' --template responsive","message" => "The given template responsive could not be found or is not readable"]

In Factory.php line 173:
                                                                       
  The given template responsive could not be found or is not readable  
 `

Why?

**Comment by pifou25** [comment]
Hi,
not sure if it is related, but I also have a template error:
```
[console] An error occurred while using the console. Message: "Template "tags.html.twig" is not defined." ["exception" => Twig\Error\LoaderError { …},"message" => "Template "tags.html.twig" is not defined."]

In function.html.twig line 59:
                                             
  Template "tags.html.twig" is not defined.  
```
I don't know from where comes this 'tags.html.twig' cause I've no @tags in my docblocks. It may be usefull if the error mention the class and line into my own source code, in addition of the file / line where the error occurs :) 

thanks

**Comment by jaapio** [comment]
We have removed the responsive template from phpdoc v3.
It took too much maintenance to keep both twig and xml templates. Since nobody could really write their own xml templates due the level of complexity, we had to make a choice. 

PhpDocumentor is maintained by just a few people, in our spare time, so we have to kill our darlings sometimes. Sorry for the inconvenience.
