### ISSUE TITLE
Hide inhereit definitions

### ISSUE THREAD

**Issue by gizmore** [phpDocumentor/phpDocumentor#2889]
# Feature request

In my project i have at least two "god" classes; [GDO](https://github.com/gizmore/gdo6/blob/master/GDO/Core/GDO.php) and [GDT](https://github.com/gizmore/gdo6/blob/master/GDO/Core/GDT.php).

These have so much (trivial) methods, that you don't want to get those listed for each child class.

A new option is required for me: "hide_inherited_definitions". Maybe default to no.

XML Proposal:

    <inheritance hide-inherited="0"></inheritance>

An example of my current result is [gdo6/GDO/Docs/DOCS](https://gdo6.gizmore.org/GDO/Docs/DOCS/)

gizmore

**Comment by jaapio** [comment]
The most straightforward way to implement this is to overwrite the `methods` template. You can do this by creating a directory 
`.phpdoc/template/components` in your project root. 

I didn't test this example template but I think the following should work

```
{% set methods = node.methods|sortByVisibility %}
{% if methods is not empty %}
    <section class="phpdocumentor-methods">
        <h3 class="phpdocumentor-elements__header" id="methods">
            Methods
            <a href="{{ link(node) }}#methods" class="headerlink"><i class="fas fa-link"></i></a>
        </h3>
        {% for method in methods %}
            {% include 'components/method.html.twig' %}
        {% endfor %}
    </section>
{% endif %}
```

This will exclude the inherited methods. 

I don't see the use-case to add build in support for this in phpDocumentor itself. This request is to specific for your own project. And won't work for all users like expected.
