### ISSUE TITLE
Unable to Install phpDocumentor 

### ISSUE THREAD

**Issue by Vic4959** [phpDocumentor/phpDocumentor#2895]
I have been trying to install PhpDocumentor using pear, phive, and phar but it all seems not to work. Please can anyone help.

**Comment by lkppo** [comment]
Hi,

You provide too few info. I have a Phar phpdoc running well on Windows. Just download [3.0.0 Phar](https://github.com/phpDocumentor/phpDocumentor/releases/tag/v3.0.0) and its ASC file. Use PHP 7.3. Try to boostrap with the config.xml file from the doc with a single PHP file in a directory, not actually your real code. Play with this test bed. Build on this experience and you will get it working step by step.

Regards,

**Comment by jaapio** [comment]
Needs more info. Please follow the template to create an issue to provide the information we need.

**Comment by lkppo** [comment]
Hello Osita,

Like say jaapio, just feed the default issue template. It's easy and provides insightful info for a good answer.

Regards,
