### ISSUE TITLE
@deprecated tag does not get interpreted

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#2897]
Given the below code sample:
```php
class Collections {
    /**
     * DEPRECATED: old property description
     *
     * @since 1.0.0-alpha3
     *
     * @deprecated 1.0.0-alpha4 Use the {@see \PHPCSUtils\Tokens\Collections::namespacedNameTokens()}
     *                          method instead.
     *
     * @var array <int|string> => <int|string>
     */
    public static $OONameTokens = [
        \T_NS_SEPARATOR => \T_NS_SEPARATOR,
        \T_STRING       => \T_STRING,
        \T_NAMESPACE    => \T_NAMESPACE,
    ];
}
```

## Expected behavior
I'd expect the `{@see ... }` tags in the deprecation description to be interpreted and converted to a link to the mentioned alternative.

## Actual behavior
Instead the tags are shown without the information contained within:
![image](https://user-images.githubusercontent.com/663378/118391690-f2534f00-b635-11eb-9d8b-ff3f2abf644b.png)

## Steps to reproduce the problem

1. Issue can be reproduced with the above code sample and config.
2. Run `php -f phpDocumentor3.phar`

## Your environment

* Version used: 3.0.0
* Install method: Phar
* PHP version: 7.4.16
* Operating system and version: Windows 10
* Link to your project: https://github.com/PHPCSStandards/PHPCSUtils

**Comment by jaapio** [comment]
Thanks for reporting this :+1:

**Comment by jrfnl** [comment]
Thanks for fixing this @jaapio ❤️
