### ISSUE TITLE
Abstract classes render

### ISSUE THREAD

**Issue by jlainezs** [phpDocumentor/phpDocumentor#2898]
# Template issue/request

Given a class list on a package abstract classes are rendered with the same aspect than instantiable classes. Also, the class detail doesn't mention we are looking to an abstract class.

I'm using the phar release version 3.0.0

**Comment by jaapio** [comment]
![image](https://github.com/phpDocumentor/phpDocumentor/assets/1060433/125439e8-56a0-400c-801a-ea8ea3f59567)

Fixed in v3.4.0
