### ISSUE TITLE
Provide a Composer shim

### ISSUE THREAD

**Issue by TravisCarden** [phpDocumentor/phpDocumentor#2930]
# Feature request

This package clearly states that installation via Composer is not recommended--and I can understand why! But Composer is the de facto standard for managing (dev) dependencies in PHP. Have you considered providing a shim like https://packagist.org/packages/phpstan/phpstan that installs a PHAR file instead of requiring all the Composer dependencies?

**Comment by jaapio** [comment]
We are investigating this. I cannot tell you when there will be a way to install phpDocumentor via composer like this but there are potential solutions that allow us to do this. 

I created a project to keep track of the things we need to do. If somebody can assist us. Please share your input.

**Comment by jaapio** [comment]
Here you go: https://packagist.org/packages/phpdocumentor/shim

**Comment by TravisCarden** [comment]
_Nice._ It works great! Thanks!

@jaapio++ 🙂
