### ISSUE TITLE
Documentation XSD file returning 404 not found error

### ISSUE THREAD

**Issue by Dreytac** [phpDocumentor/phpDocumentor#2931]
The XSD file referenced in the documentation at [https://docs.phpdoc.org/latest/phpdoc.xsd](https://docs.phpdoc.org/latest/phpdoc.xsd) is returning a 404 not found error when trying to access it.

## Expected behavior
To have my editor download the XSD file and provide editor hints.

## Actual behavior
Editor does not provide hints. Visiting the url in the browser redirects back to the main documentation page for phpDocumentor.

## Steps to reproduce the problem

1. Create XML as defined in [Appendix A](https://docs.phpdoc.org/3.0/guide/references/configuration.html).
2. Use an editor that provides editor hints.
3. Notice hints don't work.
4. Visit [https://docs.phpdoc.org/latest/phpdoc.xsd](https://docs.phpdoc.org/latest/phpdoc.xsd) in browser.
5. Notice redirect to documentation and a 404 error before the redirect in browser development tools.

## Your environment

* Apache NetBeans v12.4
* Chrome v91.0.4472.106
* Operating system and version: Windows 10

**Comment by jaapio** [comment]
Thanks for reporting this. The file has been added and will be republished on each update.
