### ISSUE TITLE
Encoding error in reStructuredText multiline table cells

### ISSUE THREAD

**Issue by daiwai** [phpDocumentor/phpDocumentor#2937]
If you create a table cell with reStructuredText in the guide that goes over more than one line and in the second or one of the following lines a non-ASCII Unicode character is used, such as the German umlaut "ö". This character will be encoded incorrectly during rendering.

## Expected behavior

non-ASCII UTF-8 encoded characters should be rendered correctly in reST tables

## Actual behavior

non-ASCII UTF-8 encoed characters, that appear in the second or any subsequent line of a multi line table cell are not encoded correctly during rendering.

## Steps to reproduce the problem

Here is a fairly minimal example of the reST markup that triggers the problem

    +---+---+
    | A | B |
    |   | ö |
    +---+---+
This is rendered as

<table>
    <tbody>
        <tr>
            <td>A</td>
            <td>B Ã¶</td>
        </tr>
    </tbody>
</table>

    <table>
        <tbody>
            <tr>
                <td>A</td>
                <td>B Ã¶</td>
            </tr>
        </tbody>
    </table>

instead of

<table>
    <tbody>
        <tr>
            <td>A</td>
            <td>B ö</td>
        </tr>
    </tbody>
</table>

The following examples, on the other hand, _do not_ have that problem and are both rendered correctly:

    +---+---+
    | A | ö |
    +---+---+

    +---+---+
    | A |   |
    |   | ö |
    +---+---+

## Your environment

* Version used: a570609
* Install method: phar
* PHP version: 8.0.7
* Operating system and version: Ubuntu 20.04.2 LTS

**Comment by daiwai** [comment]
This problem is caused by the fact that the `phpDocumentor\Guides\Nodes\Table\TableColumn::addContent` method encodes the passed string with `utf8_encode`.

Since the content of `TableColumn` is already encoded when it is instantiated and all calls to TableColumn::addContent pass the return value of TableColumn::getContent, the content is encoded twice.

So the quickest fix would be to simply remove the call to utf8_encode in `TableColumn::addContent`.

However, the question is why the rows in `TableNode` are `utf8_decode`d at all. I guess this was to simplify the handling of the strings? However, according to composer.json, there is a dependency on the mbstring extension anyway. So from my point of view it would be preferable to use the corresponding mb_* functions for all string operations in `TableNode`. This would presumably make the conversion between UTF-8 and ISO-8859-1 unnecessary while at the same time fix any problems with characters that are not losslessly convertible between UTF-8 and ISO-8859-1.

**Comment by jaapio** [comment]
Fixed by #2938

We adopted the guides parser, there is much to be removed and refactored because phpDocumentor does things differently than the original code. Since this feature is still under heavy development, I think it is ok to just remove this for now. If we want to reintroduce it at some point, it might be at a different location. 

Thanks for your effort to report this bug, and providing a fix.
