### ISSUE TITLE
php Documentor generate class hierarchy diagramm

### ISSUE THREAD

**Issue by camilledrone** [phpDocumentor/phpDocumentor#2942]
Hello, 
I am actually discovering phpDocumentor to generate a documention from my php code. On the result as a hmtl page, I found a tab "class hierarchy diagram" but there is nothing in it (my api documentation is working well). Do you how to generate thsi diagram?
Thank you

**Comment by jaapio** [comment]
Please check the readme: https://github.com/phpDocumentor/phpDocumentor#installation

`--setting=graphs.enabled=true.`
