### ISSUE TITLE
PHP8 Attributes - Unable to parse file

### ISSUE THREAD

**Issue by natanfelles** [phpDocumentor/phpDocumentor#2948]
Issue #2844 should not be closed, or a new bug has appeared. 

phpDocumentor v3.1.0 show ALERTs when unable to parse files with PHP 8 Attributes

## Expected behavior

Expected that the files are successfully parsed.

## Steps to reproduce the problem

1. Download and unzip the [Examples](https://github.com/phpDocumentor/phpDocumentor/files/6089247/Example.zip)
2. Run phpDocumentor

Currently, this output is shown:

```
phpDocumentor v3.1.0

Parsing files
 1/2 [==============>-------------]  50%17:21:49 ALERT     [app]   Unable to parse file "Example.php", an error was detected: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned
 2/2 [============================] 100%17:21:49 ALERT     [app]   Unable to parse file "Example2.php", an error was detected: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned

Applying transformations (can take a while)
 20/20 [============================] 100%
All done in 1 seconds!
```

## Your environment

* Version used: v3.1.0
* Install method: phar
* PHP version: 8.0.8
* Operating system and version: Ubuntu 20.04

Thank you for your awesome work!

**Comment by jaapio** [comment]
hm, it looks like a php-parser update slipped though. 

I will investigate this. Thanks for reporting this!

**Comment by jaapio** [comment]
Could you give the nightly build a try, please? I think this will fix your issue.

https://github.com/phpDocumentor/phpDocumentor/suites/3196507368/artifacts/73838128

**Comment by natanfelles** [comment]
Yes! Fixed. Thank you!

**Comment by jaapio** [comment]
thanks for reporting this back. I will close this issue. We will include it in a next release.
