### ISSUE TITLE
phpDocumentor is throwing errors loading phpdocumentor/Reflection/Php

### ISSUE THREAD

**Issue by Danny-Guzman** [phpDocumentor/phpDocumentor#2949]
I know that composer install isn't recommended but this was working with phpDocumentor v3.0.0 and now it's throwing errors loading phpdocumentor/Reflection/Php not sure what's changed.

## Expected behavior

![image](https://user-images.githubusercontent.com/24319945/124838769-60343c80-df3c-11eb-8afb-95ea8a383222.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/24319945/124838731-4d216c80-df3c-11eb-8494-4cd55d660c2e.png)

## Steps to reproduce the problem

1. composer require phpdocumentor/phpdocumentor:3.1.0
2. ./vendor/bin/phpdoc .

## Your environment

* Version used: 3.1.0
* Install method: composer
* PHP version: 7.4.9
* Operating system and version: Windows 10

**Comment by jaapio** [comment]
It looks like we changed something in the services configuration in our project which is working with a relative path... This relative path will not work when doing a composer install. 

I'm not sure how to fix this yet. But I assume that it might cause issues in other situations. So I'm leaving this issue open for now. So we do not forget about it. 

Thanks for your contribution to make phpDocumentor better!

**Comment by jaapio** [comment]
https://twitter.com/phpDocumentor/status/1426165879205679104 

Please try the new package, I hope this will work for you :-)

**Comment by Danny-Guzman** [comment]
Yep that did it thank you
