### ISSUE TITLE
Guide is not generated

### ISSUE THREAD

**Issue by natanfelles** [phpDocumentor/phpDocumentor#2950]
Configured `guide` is not generated.

## Expected behavior

Expected the guide pages to be generated.

## Actual behavior

`api` sources are generated but `guide` not.

## Steps to reproduce the problem

1. Create a folder with an index.rst file
2. Config it as a `guide` source
3. Run phpdoc

## Your environment

* Version used: a4076d9
* Install method: phar
* PHP version: 8.0.8
* Operating system and version: Ubuntu 20.04

phpdoc.dist.xml file

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    <title>Framework Docs</title>
    <paths>
        <output>build/docs</output>
        <cache>build/docs-cache</cache>
    </paths>
    <version number="latest">
        <folder>latest</folder>
        <api>
            <source dsn=".">
                <path>vendor/natanfelles/**/src</path>
            </source>
        </api>
        <guide>
            <source dsn=".">
                <path>guide</path>
            </source>
            <output>guide</output>
        </guide>
    </version>
</phpdocumentor>
```

guide/index.rst file

```rst
.. meta::
	:layout: landingpage
	:tada: true

Documentation
=============

```

Thank you! :smiley:

**Comment by jaapio** [comment]
Guides are still in an alpha phase, so they are feature flagged. You can enable them with the setting guides.enabled=true.

You can pass this to phpdocumentor with the - - settings option or set the setting in your config file. Please check our makefile for more details about the command

**Comment by natanfelles** [comment]
Ok! Thanks again @jaapio ! :smiley:
