### ISSUE TITLE
Multiple ignore directory bug

### ISSUE THREAD

**Issue by PolDeveloper** [phpDocumentor/phpDocumentor#2954]
Hi,
when I try to exclude more than 1 directory it fails. It works only for one though.

## Expected behavior
It should exclude multiple directories.

## Actual behavior
If there are multiple directories in the ignore command it excludes nothing.

## Steps to reproduce the problem

1. php phpDocumentor.phar -d /Projects/ProjectA/ -t /Projects/ProjectA/phpDoc/ -i "vendor,tests"

## Your environment

* Version used: v3.1.0
* Install method: php phpDocumentor.phar
* PHP version: PHP 8.0.8 (cli) (built: Jul  1 2021 15:26:28) ( NTS )
* Operating system and version: Ubuntu 18.04.5 LTS

Thanks in advance

**Comment by PolDeveloper** [comment]
It looks like this syntax works well:

```bash
php phpDocumentor.phar -d /Projects/ProjectA/ -t /Projects/ProjectA/phpDoc/ -i vendor -i tests
```

**Comment by jaapio** [comment]
This is like expected. Did you find some outdated documentation about this?

**Comment by danieldjewell** [comment]
I can confirm this issue as well: I have a source tree with several "vendor" directories spread out all over the place (in multiple subdirs... I didn't design the layout 😁 ) ... Following the instructions (here: https://docs.phpdoc.org/3.0/guide/guides/running-phpdocumentor.html) for using --ignore, I cannot seem to get the phpDocumentor to exclude these files.

I have also tried using an xml configuration with exclude paths listed there. I have tried multiple syntaxes, too: 

```xml
<ignore hidden="true" symlinks="true">
                <path>vendor/**/*</path>
                <path>wwwsrc/**/*vendor*</path>
                <path>*vendor*</path>
                <path>wwwsrc/**/vendor/*</path>
                <path>*/vendor/*</path>
            </ignore>
``` 

Version used: (v3.1.0 phar // from github releases) 
PHP version: 
```
PHP 8.0.8 (cli) (built: Jul  1 2021 15:25:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies
```

**Comment by PolDeveloper** [comment]
@jaapio 

> This is like expected. Did you find some outdated documentation about this?

I followed this doc - https://docs.phpdoc.org/guide/guides/running-phpdocumentor.html

> A basic example of the --ignore option is excluding one or more directories from your project. If you have a 'vendor' directory that is not relevant to your project documentation, you can exclude it by specifying --ignore "vendor/". To exclude the 'vendor' and 'tests' directories at the project root, separate each directory with a comma: --ignore "vendor/,tests/".

**Comment by jaapio** [comment]
Thanks, I will update the docs. This seems to be outdated. our ignore syntax is more complex now because it supports glob patterns. So the `,` notation will not work anymore. Sorry that we forgot to update the docs.

**Comment by PolDeveloper** [comment]
@jaapio No problem, thanks

**Comment by jaapio** [comment]
@danieldjewell could you please share your configuration so I can help you configure phpdocumentor correctly? I think there is some mismatch between your directories and the ignore paths. Although I cannot be sure that there is a bug somewhere :-)

**Comment by jaapio** [comment]
I updated the documentation
