### ISSUE TITLE
Plantuml Detection Failed - phar - ref #2832 #2841 

### ISSUE THREAD

**Issue by danieldjewell** [phpDocumentor/phpDocumentor#2955]
Plantuml is installed and is available at ```/usr/bin/plantuml``` 

Running phpDocumentor from the PHAR archive, the program tries looking *inside* the phar file for plantuml and does not attempt to look in the system $PATH variable. see issues/PR #2832 and #2841 

Error message: 
```
19:18:38 ERROR     [app] Generating the class diagram failed ["error" => "sh: 1: exec: phar:///<pathremoved>/phpDocumentor.phar/bin/plantuml: not found\n"]
```

## Your environment

```sh
which plantuml
>/usr/bin/plantuml
``` 

* Version used: 3.1.0 
* Install method - PHAR form Github Releases
* PHP version: 8.0.8 
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu 20.04

**Comment by danieldjewell** [comment]
Additionally: 

Installing the PHAR to /usr/local/bin/ results in the same error:

```
19:27:03 ERROR     [app] Generating the class diagram failed ["error" => "sh: 1: exec: phar:///usr/local/bin/phpDocumentor/bin/plantuml: not found\n"]
```

**Comment by jaapio** [comment]
Hm shell is not aware of `phar://`, which is a php thing. I think the way we are trying to distribute this will not work :-( 

Thanks for reporting this.

**Comment by jaapio** [comment]
To fix this issue I added a condition, which requires you to install plantuml on your computer. When phpdocumentor is running as a phar it will handover the command to your shell. Location of installation doesn't matter as long it is in your path. So the shell can find it. 

I'm afraid this is the best we can get right now, unless we allow phpDocumentor to install plantuml.

**Comment by danieldjewell** [comment]
@jaapio You're welcome :grin: -- I think that as long as the phpDocumentor > shell handover causes it to look in $PATH for the executable... That works. (At a minimum, on Linux/Unix systems, look in /usr/bin and /usr/local/bin)

Alternatively, perhaps https://symfony.com/doc/current/components/process.html#finding-an-executable ... or a runtime configuration option to explicitly set the absolute plantuml path?
