### ISSUE TITLE
The rST rendering does not probably handle links

### ISSUE THREAD

**Issue by stof** [phpDocumentor/phpDocumentor#2956]
## Expected behavior
rST links are rendered properly. FYI, the markup is rendered properly by Github: 
![image](https://user-images.githubusercontent.com/439401/126478234-92a67ca3-2b9c-4374-846f-fbd26ab9d80b.png)

## Actual behavior
the rST link markup is rendered in the output (with the URL becoming a link on its own)

## Steps to reproduce the problem

1. Go to https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/method.html#method
2. Look at the links 
![image](https://user-images.githubusercontent.com/439401/126478137-ae583f53-a7dc-456f-9a1e-c5cdbdcea870.png)

## Your environment

the one used to render the docs.phpdoc.org website (no idea about its config, but maintainers will know about it hopefully)

**Comment by jaapio** [comment]
I investigated this... if it only was the rendering... there seems to be an issue with the [SpanProcessor](https://github.com/phpDocumentor/phpDocumentor/blob/master/src/Guides/RestructuredText/Span/SpanProcessor.php#L19) this part is quite new... but not written by us. 

I have to take a deep dive to figure out what is actually happening here.

**Comment by jaapio** [comment]
Will be fixed with #2959
