### ISSUE TITLE
XML output missing method tags

### ISSUE THREAD

**Issue by janareddymareddy** [phpDocumentor/phpDocumentor#2965]
HI,

i also using structure.xml generated by phpDocumentor in custome pages.

we planned to upgtade from old version, just installed V3.0.0 using composer and tried to generate structure.xml by passinf --template=xml.

but i noticed few tags are missing in the xml file. inside "<class>" tag "<properties>" and "<method>" tags are missed.

the command what i am executing is like this

phpdoc project:run -t C:\Users\jrm\AppData\Local\Temp/phpDocumentor3 -d "E:\webportal_master\webportal\WebPortal\Portal" -c "E:\webportal_master\webportal\WebPortal\Build/phpdoc.distv3.xml" --template=xml'

if i am wromg please let me know.

i am using phpdoc 3.0.0, Windows - 10 and ZendServer 2 PHP 7.3

**Comment by jaapio** [comment]
Hi,

Could you please add an example of what you are missing in the output? I do not understand your issue.

**Comment by janareddymareddy** [comment]
Hi Jaapio.

i am attaching 3 XML files generated by 3 different versions of phpDocumenter.

we are generating XML and preparing documentation by transforming the XML with custom template.

for same code base if we generate XML in V3.0 we see many methods and properties are not exists in XML

please go through the XML's, you can get an idea on this issue.

commands we are using is   phpdoc project:run -t C:\Users\jrm\AppData\Local\Temp/phpDocumentor2.9 -c "E:\webportal_master\webportal\WebPortal\Build/phpdoc.distv2.9.xml" --template=xml

phpdoc project:run -t E:\webportal_master\webportal\WebPortal\Build\documentation3 -d E:\webportal_master\webportal\WebPortal\Portal -c "E:\webportal_master\webportal\WebPortal\Build/phpdoc.distv3.xml" --template=xml

[structure.zip](https://github.com/phpDocumentor/phpDocumentor/files/6952145/structure.zip)

**Comment by jaapio** [comment]
Hi,

Thanks for your help, I found a typo in the xml, which caused the parent-properties to be missing in the output. It would be helpfull if you could give the attached phar a try, and return me the results :-) 

Thanks in advance. 
[phpDocumentor.zip](https://github.com/phpDocumentor/phpDocumentor/files/6952513/phpDocumentor.zip)

**Comment by janareddymareddy** [comment]
Hi jaapio,

with new phar its working fine. is there any option to install same version(above given phar version) using composer. i would like to execute with phpdoc command.

**Comment by jaapio** [comment]
I will try to create a release soon. 

https://github.com/phpDocumentor/shim will get a new tag (3.1.1) which will contain this fix.

**Comment by jaapio** [comment]
A new release is available now
