### ISSUE TITLE
Docblocks in the Class is not parsed by phpdoc 

### ISSUE THREAD

**Issue by janareddymareddy** [phpDocumentor/phpDocumentor#2966]
**<?php

namespace MCS\ConnectApi;

use JRM\Calls\Call;

include_once(\JRM::GetPortalPath() . "modules/helpdesk/lib.calls.php");
require_once(\JRM::GetLibraryPath() . "fmgeneral/helpdesk/lib.dto.calls.php");
require_once(\JRM::GetPortalPath() . "modules/helpdesk/hdutilities.php");

/**
 * Calls webservices
 * @package myJRM_WebServices_Connect_CallsAPI
 * @ConnectAPI(Facility Management)
 */
class calls
{
    **/**
     * Returns a set of Calls as Search Result on the basis of the specified options.
     *
     * @param \DTO_FindOptions $options
     * @return \MCS\Calls\Dto\SearchResult
     * @throws \MCS\Common\Exceptions\AuthorizationException
     * @ConnectAPIMethod
     */**

    public function searchCalls(\DTO_FindOptions $options = null)
    {
        \MCSRights::requireAll('useWebHelpBackOffice');
        $calls = new \MCS\MetaObject\Type\Calls(
            API::getOverview(
                'Calls',
                'allcalls'
            )
        );
}

the searchCalls DocBlock is not parsed.

this is an example i have given this calls class have 15 functions all 15 functions are not parsed**

my command is:  phpdoc project:run -t C:\Users\jrm\AppData\Local\Temp/phpDocumentor3 -f E:\webportal_master\webportal\WebPortal\Tests\connect\calls\Calls.php --force
 
* Version used: 3.0.0-alpha1
* Install method: Composer
* PHP version 7.3
* Operating system and version (e.g. Ubuntu 20.04, Windows 10):Windows 10
* Link to your project:
* Attach code that is involved
* ...

**Comment by jaapio** [comment]
Please upgrade to 3.1.0 stable. I remember that we had some issues regarding require tags at the start of files. 

If the issues persists let me know. 
Thanks!
