### ISSUE TITLE
Files with forced global namespace fail with "" is not a valid Fqsen.

### ISSUE THREAD

**Issue by cherrador** [phpDocumentor/phpDocumentor#2967]
I am not an expert on phpDocumentor but I have searched for 5 days how to solve this problem. I tried to run this on Windows 10 and Ubuntu, the same problem. Maybe someone has a valid workaround to avoid this error.

I have a setup file that when it is loaded, it needs to be forced to global namespace. However, the phpDocumentor fails with the error 
```
Unable to parse file "setup.php", an error was detected: "" is not a valid Fqsen.
```
I tried to simplify a case with the minimum of one file where I can reproduce the error and how to find a workaround. I was able to find how to bypass the error, but is not a useful workaround as now, the code does not work as original intended.

Here the minimum PHP file to test the case. Notice the `namespace {` do not have a namespace, this is how to force the code to run on the global namespace.

```php
<?php
/**
* setup.php - Document the file.
*
* File long description goes here.
*
* @author Test Sample
*/

namespace {
  /**
  * autoloader function.
  *
  * Function long description goes here.
  *
  * @param string $class Namespaced class name
  * @return void
  */
  function libAutoload($class){
    echo 'Do something';
  }
  spl_autoload_register('libAutoload');
}
?>
```

This is a valid case of writing a empty namespace to indicate *global* namespace. It is documented on PHP manual (example 3):
[Defining multiple namespaces in the same file](https://www.php.net/manual/en/language.namespaces.definitionmultiple.php).

Of course I am no trying to have multiple namespaces on the same file, only one global. However, if I try a file with 2 namespaces like the one on the example 3 file, it gives the same error.

Tried to look and traceback the project source code and it looks like it is not taking on consideration the possibility of a empty namespace that it finally fail on the `reflexion-common/src/Fqsen.php`  on line 49 when an empty string namespace was passed as parameter to build the class.

## Expected behavior
To *bypass* the error I put any namespace on the command like something like `namespace Test {` and the phpDocumentor process the file without problem and generate the help file that looks like this:
![image](https://user-images.githubusercontent.com/12229855/128081650-211a67b9-9104-44e8-a7d3-a3ac3f9c1018.png)

However now the code is on the wrong namespace.

## Actual behavior
When it's run without a specific namespace name (global). The code runs properly as intended. But now phpDocumentor gets this error.
```
16:06:58 NOTICE    [app] Parsing files
16:06:58 NOTICE    [app] Parsing setup.php
16:06:58 ALERT     [app]   Unable to parse file "setup.php", an error was detected: "" is not a valid Fqsen.
16:06:58 NOTICE    [app]   -- Found in phar://D:/4safecom/PHPDoc/phpDocumentor.phar/vendor/phpdocumentor/reflection-common/src/Fqsen.php at line 57
16:06:58 NOTICE    [app] Storing cache ..
```
And no documentation for the file is generated.
![image](https://user-images.githubusercontent.com/12229855/128082617-30f23d43-9be4-4731-be6f-8e95582cf1f8.png)

Even removing all the DocBlocks does not help avoiding the error.

## Steps to reproduce the problem

1. Create the php file as described before, name it setup.php
2. Open the CLI an navigate to the folder containing the file.
3. Run the command `php.exe phpDocumentor.phar -f setup.php -t doc --force -v`
4. This will generate the error. Change the debug level parameter to traceback more details `-vvv`.
5. Change the namespace to `namespace Test {`
6. Run again the same command. Now, no errors and it generates the documentation, but not useful code.

## Your environment

* Version used: 3.1.0
* Install method: PHAR 
* PHP version: 7.4
* Operating system: Windows 10, Ubuntu  20.04

**Comment by jaapio** [comment]
This has been fixed in the current version on master. And will be part of the next release
