### ISSUE TITLE
phpdoc project:transform -s command not taking structure.xml path

### ISSUE THREAD

**Issue by janareddymareddy** [phpDocumentor/phpDocumentor#2973]
If i run phpdoc project:transform -s (path to structure.xml), i am getting exception 

[Exception]
  Invalid source location provided, a path to an existing folder was expected

if i remove xml and give folder path just printing "Load cache" and stop execution.

version is : 2.9.1

OS :windows 10, zend server.

we are using old version now 2.0.0 and we are trying to upgrade to 2.9.1

its a bit big code base, we are generating a structure.xml using project:parse and doing some custom changes and using project:transform -s (path to structure.xml) and we are using a custom template. all this process working fine in old version.

when we upgrade to new version facing few issues.

1) project:parse is not generating XML file and not have option to pass --template=xml in project:parse command. using project:run with --template=xml to generate XML file.

2) project:transform -s (path to structure.xml) is not taking the xml path. if i give folder path nothing progressing.

my command is : phpdoc project:transform -s C:\Users\jrm\AppData\Local\Temp\phpDocumentor2.9\structute.xml -t C:\Users\jrm\AppData\Local\Temp/phpDocumentor2.9 -c "E:\webportal_master\webportal\WebPortal\Build/phpdoc.distv2.9.xml"

**Comment by jaapio** [comment]
I'm sorry but we cannot provide any support regarding phpdocumentor v2. 

I'm happy to help you migrate to v3.1.0 of phpDocumentor and provide you with some advice when you are facing issues. but I cannot provide any support on versions that are over 7 years old. And I would be happy to provide fixes for you so you can upgrade to the latest version of phpDocumentor.

**Comment by mvriel** [comment]
Closing because there has been no response in one and a half months and we cannot do anything more to assist
