### ISSUE TITLE
Class's traits not showing up in docs

### ISSUE THREAD

**Issue by Darep** [phpDocumentor/phpDocumentor#2984]
A PHP class with a [trait](https://www.php.net/manual/en/language.oop5.traits.php) doesn't seem to be showing the trait nor the methods inherited from the trait.

## Expected behavior

1. Write a trait
2. Use that trait in a PHP class
3. Generate documentation
4. See the trait & the inherited methods on the class's documentation

## Actual behavior

There is no mention of the traits associated with a class, nor the methods inherited from the trait.

## Steps to reproduce the problem

I have a created a quick small repo to demonstrate this issue: https://github.com/Darep/phpdoc-trait-bug

1. `git clone https://github.com/Darep/phpdoc-trait-bug.git`
2. `cd phpdoc-trait-bug`
3. `docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 run` (or any other method to generate the docs)
4. `open .phpdoc/build/index.html`
5. `php src/Test.php`

## Your environment

* Version used: 3.2
* Install method: tested both Docker and downloading the latest phar
* PHP version: the one bundled into the Docker image, and 7.3.x
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): macOS 11.4
* Link to your project: https://github.com/Darep/phpdoc-trait-bug

**Comment by jaapio** [comment]
Hi,

Thanks for reporting this, it seems that our docker images are not updated since 20 days ago. I fixed this issue recently. 

Somehow the integration with docker hub fails. I will try to fix this asp. Docker changed it's plans for free teams, so we have to apply for the open-source program.

**Comment by Darep** [comment]
Thanks for the quick reply, @jaapio! I will give it a test using the latest code 👍

**Comment by jaapio** [comment]
Docker images are building again, please let me know if you still have this issue :-)

**Comment by jaapio** [comment]
Thanks!
