### ISSUE TITLE
XML template invalid XML due to missing marker.type

### ISSUE THREAD

**Issue by tbpg** [phpDocumentor/phpDocumentor#2986]
# Template issue/request

This part of the `xml` template:
https://github.com/phpDocumentor/phpDocumentor/blob/f34398f15400b77f68d0963bd011b072f0cc0b8a/data/templates/xml/structure.xml.twig#L106-L108

Led to:
```xml
                            < line="9">www.apache.org/licenses/LICENSE-2.0</>
```

You can reproduce by running `phpdoc` in https://github.com/googleapis/google-cloud-php/tree/master/Vision.

**Comment by jaapio** [comment]
Thanks for reporting this. 

It seems to be a bug in phpDocumentor. A fix is on its way.
