### ISSUE TITLE
Composer shim unable to verify phpdoc with phpdoc.asc

### ISSUE THREAD

**Issue by Danny-Guzman** [phpDocumentor/phpDocumentor#2988]
This was working with 3.1.0
## Expected behavior

Install of phpdoc to vendor/bin/ directory

## Actual behavior

Nothing is installed

![image](https://user-images.githubusercontent.com/24319945/130356771-a7ea0136-9e38-4232-a818-6dedff0f4a0a.png)

## Steps to reproduce the problem

1. composer install phpdocumentor/shim

## Your environment

* Version used: 3.1.1
* Install method: composer
* PHP version: 8
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): windows

**Comment by jakzal** [comment]
Not sure if this is related, but phive is not able to verify the key either:

```
./phive.phar --no-progress --home /usr/local/bin/.phive install phpDocumentor -t /usr/local/bin/.phive/tmp/f474e60df5620536af2224cbc21a1668
```

```
Phive 0.14.5 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpdocumentor/phpdocumentor2/releases
Downloading https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.1.1/phpDocumentor.phar
Downloading https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.1.1/phpDocumentor.phar.asc
Downloading key 67F861C3D889C656
Trying to connect to keys.openpgp.org (37.218.245.50)
Trying to connect to keys.openpgp.org (2a00:c6c0::154:1:0:0:1)
[ERROR]    Request failed:  (while requesting https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x67F861C3D889C656)
[WARNING]  Failed with error code 404: Key not found on keyserver
Trying to connect to keyserver.ubuntu.com (162.213.33.9)
Trying to connect to keyserver.ubuntu.com (162.213.33.8)
[WARNING]  Failed with error code 404: Key not found on keyserver
[WARNING]  Failed with error code 6: DNS Problem: Did not find any IP for hostname "hkps.pool.sks-keyservers.net"
[ERROR]    PublicKey 67F861C3D889C656 not found on key servers
```

**Comment by jaapio** [comment]
I'm a fool :-D and repeating tasks are hard. So I automated the release to fix this issue a bit more. 

A new shim tag has been released 3.1.2 which should install with phive and composer.

**Comment by Danny-Guzman** [comment]
This installs without failing but the phpdoc is not installing in the vendor/bin directory so not sure how this can be used? In 3.1.0 all I had to do was run `./vendor/bin/phpdoc . ` and that's it, would be nice to get that behavior back.

**Comment by jaapio** [comment]
Hi @Danny-Guzman 

I just installed phpDocumentor using 

`composer require phpdocumentor/shim` which creates a file `./vendor/bin/phpdoc` in my clean docker environment. 

Can you provide me some more information about what is going on at you system?

**Comment by Danny-Guzman** [comment]
@jaapio Not sure why but it appears now that I've completely deleted the vendor directory. Not sure what happened but glad that its working again, thank you.
