### ISSUE TITLE
Environment variables are empty at "renderVariables".

### ISSUE THREAD

**Issue by wandura** [phpDocumentor/phpDocumentor#3006]
https://github.com/phpDocumentor/phpDocumentor/blob/aae2e648cc1c9dad55b8ec7cd8488ec34dbdd05a/src/Guides/NodeRenderers/SpanNodeRenderer.php#L117

My replace directives for ResturcturedText files are working with v3.1.0 of phpDocumentor but doesn't work anymore if I update to v3.1.2

I have debugged and the replace directive is processing for all replace directives but at the call of `$spanNodeRenderer->renderVariables(...)` the `$environment->variables` is an empty array.

test.rst
```
.. |test_var| replace:: my test var

Title
=====

Test the var: |test_var|
```

Output:
> Title
>
> Test the var:

**Comment by mvriel** [comment]
Thank you for your report; I seldomly use the replacement directive so it is awesome that you report this. I will take a look at it as soon as I can.

Out of curiosity, is this from a public repository on which we can run phpDocumentor's Guides system? The feature is still in Alpha and I am trying to gather as many example sources as I can

**Comment by wandura** [comment]
No, this is not from a public repository.

I have cloned the phpDocumentor repository:
```
git clone --branch v3.1.2 https://github.com/phpDocumentor/phpDocumentor.git
cd ./phpDocumentor
composer install
make install-phive
```

And execute it via:
```
php ./tools/phpDocumentor/bin/phpdoc -c ./phpdoc.dist.xml --log=phpdoc.log -vvv
```

I use the source code instead of the phar file because otherwise I get an error message about not finding plantuml.

My config looks like this:
```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="data/xsd/phpdoc.xsd"
>
    <title>Project name</title>
    <paths>
        <output>build/public</output>
        <cache>build/cache</cache>
    </paths>
    <version number="2.0.0">
        <folder>latest</folder>
        <api format="php">
            <source dsn="../html/">
                <path>app</path>
            </source>
            <output>api</output>
            <extensions>
                <extension>php</extension>
            </extensions>
            <markers>
                <marker>TODO</marker>
                <marker>FIXME</marker>
            </markers>
            <include-source>true</include-source>
        </api>
        <guide format="rst">
            <source dsn=".">
                <path>rst</path>
            </source>
            <output>guide</output>
        </guide>
    </version>
    <setting name="guides.enabled" value="true"/>
    <setting name="graphs.enabled" value="false"/>
    <template name="default"/>
</phpdocumentor>
```

I also noticed in phpDocumentor v3.1.2 that the guide output folder of the config no longer works properly and I had to change it from "guides" to "guide". But because of the other issues with this version, I hadn't looked at it any further.

**Comment by mvriel** [comment]
A fix has been made in Pr https://github.com/phpDocumentor/phpDocumentor/pull/3011; what happened was that we are introducing caching for the parsed contents. But the package on which we based the Guides rendering used shared state between parsing and rendering; and the parsed state was not copied onto the rendering process.

To fix this, we now cache the replaced variables, and use them during rendering
