### ISSUE TITLE
Conflict with XDebug

### ISSUE THREAD

**Issue by pbrilius** [phpDocumentor/phpDocumentor#3025]
## Expected behavior
`phpdox --help` _should_ return the displayed values of **statements**. Instead, it crashes.

## Actual behavior
```shell
phpDox 0.12.0 - Copyright (C) 2010 - 2021 by Arne Blankerts and Contributors



Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.4.16 (Linux)
PHPDox Version: 0.12.0
Exception: Error (Code: 0)
Location: phar:///home/povilasbrilius/.phive/phars/phpdox-0.12.0.phar/phpdox/shared/Environment.php (Line 46)

Call to undefined function TheSeer\phpDox\xdebug_disable()

#0 phar:///home/povilasbrilius/.phive/phars/phpdox-0.12.0.phar/phpdox/CLI.php(50): TheSeer\phpDox\Environment->ensureFitness()
#1 /home/povilasbrilius/.phive/phars/phpdox-0.12.0.phar(485): TheSeer\phpDox\CLI->run()
```

## Steps to reproduce the problem

1. `php -v`
2. 'phpdox --help`

## Your environment

* Version used: 3.0.0-alpha1
* Install method: `phive install phpdox`
* PHP version `7.4.16`
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): `Pop!_OS 21.04`
* Link to your project: none
* Attach code that is involved: none
* ...

**Comment by ashnazg** [comment]
Wrong project... phpdox is not phpdocumentor...

https://github.com/theseer/phpdox

**Comment by pbrilius** [comment]
So **close** this _issue_ then.
