### ISSUE TITLE
Guides: Underscores in titles are gone

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#3033]
When you define a title with an underscore in it, you do not see it in the rendered output and it is not used in the anchor; thus linking to it won't work either.

Repro:

```
My_Title
=======

`My_Title`_ does not work
```

In the repro above it will render as `MyTitle` and the internal target doesn't resolve

**Comment by FeIix** [comment]
Similar problem, but not with a title :
I have some variables names containing underscores.

So if I need to give information about the variable "my_option_name", the generated guide displays it as "myoptionname",
which means my doc is unusable.

I will try markdown to see if i'm more lucky with it.
But at this point I hate rst and feel like we should just be able to drop some HTML pages as guides. (or maybe it's already possible and I missed it ?)

**Comment by jaapio** [comment]
This issue has been fixed by the new integration. If you pick the master branch or our v3 docker tag this is solved.

Any new release will contain this, fix.
