### ISSUE TITLE
No line number for errors

### ISSUE THREAD

**Issue by dregad** [phpDocumentor/phpDocumentor#3057]
## Expected behavior
Errors are shown with the line number where the problem was found in the report

## Actual behavior
Line number is always 0.
e.g. https://docs.phpdoc.org/3.0/reports/errors.html
![image](https://user-images.githubusercontent.com/449891/138725957-aaf871af-83c8-43db-b928-76f05e7290a0.png)

## Steps to reproduce the problem
Run PHPDoc on any source code that contains errors

## Your environment

* Version used: 3.1.2
* Install method PHAR
* PHP version 8.0.11
* Operating system and version Ubuntu 20.04.3 LTS
* Link to your project: problem exists with your own documentation https://docs.phpdoc.org/3.0/reports/errors.html

**Comment by mvriel** [comment]
Thanks for reporting this issue. I can confirm that this issue still exists. A quick glance in the codebase reveals that the location where these errors are generated is unaware of the location of the issue. An InvalidTag object is created by the ReflectionDocBlock library but it does not contain any context to its whereabouts.

I did manage to create an improvement that will attach the line number of the associated element with the error. It may not be the exact line number but it is a lot better than 0 :)

See https://github.com/phpDocumentor/phpDocumentor/pull/3294 for the submitted PR.

**Comment by dregad** [comment]
Thank you guys !
