### ISSUE TITLE
Empty objects / curly braces in php doc blocks

### ISSUE THREAD

**Issue by macwinnie** [phpDocumentor/phpDocumentor#3061]
When documenting with some codeblock e.g. for describing JSON structures in the doc blocks, I want empty objects / dictionaries to be propperly rendered – e.g. this example:

```php
/**
 * ```js
 * {
 *     "lorem": {},
 *     "ipsum": {},
 *     "dolor": []
 * }
 * ```
 */
```

## Expected behavior

The result should show the correct opening and closing curly braces in the documentation

```js
{
    "lorem": {},
    "ipsum": {},
    "dolor": []
}
```

## Actual behavior
 The actual result after running phpDocumentor is:

```js
{
    "lorem": },
    "ipsum": },
    "dolor": []
}
```

## Workaround

My current workaround is to provide a space between the opening and closing curly braces like `{ }` – that fixes the current problem.

## Your environment

* Version used:  `vdev-master@fc06262` (currently published in Docker-Image `phpdoc/phpdoc:3` on 30th of October, 09:23 UTC)
* Install method: Docker
* PHP version: given by your docker image `phpdoc/phpdoc:3`
* Operating system and version (e.g. Docker on MacOS 11.6):
* Attach code that is involved: see minimal examples above

**Comment by jaapio** [comment]
`{` requires an escape sequence which is `{}` so the correct notation in your docblock is `{}}` 

See: https://github.com/phpDocumentor/ReflectionDocBlock/issues/276

Let me know when this doesn't solve your issue.

**Comment by macwinnie** [comment]
Just if someone finds this issue in search results ... the correct notation seems to be `{{}` =)
Thanks for your help, @jaapio !
