### ISSUE TITLE
/configuration page is almost useless

### ISSUE THREAD

**Issue by dktapps** [phpDocumentor/phpDocumentor#3066]
https://docs.phpdoc.org/3.0/guide/getting-started/configuration.html

This page gives almost no meaningful information whatsoever, and tells me to look at the xsd (which isn't the most user-friendly way of displaying config information). I spent 10 minutes thinking "surely they can't possibly expect new users to use THIS as a config reference??"

Much to my surprise, I later discovered that there's a _second_ Configuration page further down the sidebar, which is far more useful: https://docs.phpdoc.org/3.0/guide/references/configuration.html

Please do something about this. It's confusing and sure to be a hair-puller.

**Comment by dktapps** [comment]
The xsd in the repo also doesn't seem to be up to date, so I have PhpStorm screaming at me when I try to add source paths.

Also, https://docs.phpdoc.org/latest/phpdoc.xsd gives a nice 404.

**Comment by thomascorthals** [comment]
I went through the same stages you did.

> Also, https://docs.phpdoc.org/latest/phpdoc.xsd gives a nice 404.

At least it now points to https://github.com/phpDocumentor/phpDocumentor/blob/master/data/xsd/phpdoc.xsd.

**Comment by dktapps** [comment]
> At least it now points to https://github.com/phpDocumentor/phpDocumentor/blob/master/data/xsd/phpdoc.xsd.

I still get a 404.

**Comment by thomascorthals** [comment]
> I still get a 404.

I meant to say that https://docs.phpdoc.org/3.0/guide/getting-started/configuration.html now links to https://github.com/phpDocumentor/phpDocumentor/blob/master/data/xsd/phpdoc.xsd and that link should work.

**Comment by caendesilva** [comment]
Still an issue, both with the quality of the the first configuration page, and the 404.

See https://github.com/phpDocumentor/phpDocumentor/issues/3221

**Comment by mvriel** [comment]
I am working on a major update of the documentation but progress is slow on such things.

**Comment by mvriel** [comment]
XSD links is fixed and since the effort to update the documentation is on-going, I am going to close this issue. Thank you for your feedback!
