### ISSUE TITLE
Error when loading configuration on phpDocumentor run

### ISSUE THREAD

**Issue by LucasWerner437** [phpDocumentor/phpDocumentor#3073]
I've been trying to make phpDocumentor work for my current project. I set up a phpdoc.xml to test it and make a config I can use for the whole team. But there's an error whenever I try to run it.

## Expected behavior

phpDoc should run fine, as expected when reading the docs.

## Actual behavior

An error occurs right at the start :

> Argument 1 passed to phpDocumentor\Configuration\VersionSpecification::__construct() must be of the type string, int given, called in phar://C:/Serveur/php7/phpDoc/phpDocumentor.phar/src/phpDocumentor/Configuration/Configuratio  
  nFactory.php on line 149  

I've tried replacing it with 3.0.0 or v3.0/v3, nothing works. configVersion expects 3 or 2, but constructor expects a string.

## Steps to reproduce the problem

1. Install phpDocumentor globally
2. Create the complete config file from the doc
3. Run phpDoc

## My own config file

````
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd">
    <paths>
        <output>docs</output>
    </paths>
    <!--Zero or more repetitions:-->
    <version number="0.1">
        <!--Optional:-->
        <folder>latest</folder>
        <!--Zero or more repetitions:-->
        <api format="php">
            <source dsn=".">
                <!--1 or more repetitions:-->
                <path>src</path>
            </source>
            <!--Optional:-->
            <output>api</output>
            <!--Optional:-->
            <ignore hidden="true" symlinks="true">
                <!--1 or more repetitions:-->
                <path>path/to/folder</path>
            </ignore>
        </api>
    </version>
</phpdocumentor>
````

## Your environment

* Version used : 3.1.2
* Install : Manually added to windows PATH
* PHP version : 7.4.25
* OS : Windows 10
* Symfony 5 based project (phpDoc installed globally with .phar, no conflicts, at least I think)

**Comment by LucasWerner437** [comment]
So I get no answer and the ticket is closed ? I don't get it.

**Comment by jaapio** [comment]
Your issue has been resolved. But I forgot to answer this issue.

Thanks for reporting
