### ISSUE TITLE
Missing enum support for PHP 8.1

### ISSUE THREAD

**Issue by djairhogeuens** [phpDocumentor/phpDocumentor#3081]
## Expected behavior
Using the new enum type available as from PHP 8.1 (https://wiki.php.net/rfc/enumerations) should be supported by phpDocumentor.

## Actual behavior
The enums are being ignored without a warning and their references are not recognized.

## Steps to reproduce the problem
Define an enum
```php
enum Suit {
  case Hearts;
  case Diamonds;
  case Clubs;
  case Spades;
}
```

Define a class
```php
class C {

  /**
   * @param Suit $suit The suit.
   **/
  public static function someMethod(Suit $suit): void {
    
  }

}
```

Run phpDocumentor. The class `C` will be available but the enum won't be. The method `someMethod` will have an undocumented type for the method argument `$suit`.

## Your environment

* Version used: 3.2.0
* Install method: Docker
* PHP version: Embedded in Docker image
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Embedded in Docker image

**Comment by jaapio** [comment]
Hi,

Thanks for reporting this. the master branch of this project currently supports enums. A release was planned for this month. But due shifting priorities I wasn't able to create a release yet. 

Unfortunately I cannot give any estimate when a new release will happen. I have to much other things to do right now that are more important. You can use the latest tag of our docker image to get enum support.

**Comment by djairhogeuens** [comment]
Thanks @jaapio!
