### ISSUE TITLE
Issue with php7.4 

### ISSUE THREAD

**Issue by ideiasfrescas** [phpDocumentor/phpDocumentor#3084]
phpDocumentor.phar does not run.

## Expected behavior

I am expecting to run phpDocumentor.

## Actual behavior

phpDocumentor is complaining about "simplexml" and "xml" not present. Full message below:

```text
 * The application requires the extension "simplexml". Enable it or install a
   polyfill.
 * The application requires the extension "xml". Enable it or install a
   polyfill.
 * The package "symfony/framework-bundle" requires the extension "xml". Enable
   it or install a polyfill.
```

## Steps to reproduce the problem

1. Just run with a basic configuration file.

## Your environment
Ubuntu 16.04
PHP 7.4
Modules enabled:
```text
calendar
Core
ctype
curl
date
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib
```

PHP 7.4 in my system has libxml installed and I see that in the manual both "simplexml" and "xml" ( i'll assume xmlreader ) both depend on libxml to be present as per pages in the manual [Xmlreader](https://www.php.net/manual/en/xmlreader.requirements.php) and [SimpleXml](https://www.php.net/manual/en/simplexml.requirements.php)

I'm sure this is not an issue with Documentor itself but rather the symphony framework, but I would like your input on this and also on the shim composer complains about.

I will now start working on tracking this issue on Symphony as well.

* Version used: latest phar
* Install method: download and upload to the server
* PHP version: 7.4
* Operating system and version: Ubuntu 16.04
* Link to your project: [local - unable to provide ]
* Attach code that is involved - None at this time.
* ...

Thank you

**Comment by jaapio** [comment]
Hi, 

You need to install `xml` and `simplexml` php extensions. 

I think:

```
sudo apt-get install php-xml php-simplexml` 
```

**Comment by ideiasfrescas** [comment]
That's just it. Even with the ppa correctly added to my machine, it issues:

"E: Couldn't find any package by glob 'php7.4-xml'
E: Couldn't find any package by glob 'php7.4-simplexml'"

When I try to install with your command line ( below is translated from portuguese ):

"php-simplexml is a virtual package made available by:
  php7.0-xml 7.0.33-32+ubuntu16.04.1+deb.sury.org+1
  php7.2-xml 7.2.34-2+ubuntu16.04.1+deb.sury.org+1
You must explicity select one to install."
