### ISSUE TITLE
:art: Default template search is broken

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#3092]
The default template includes a full text search option. However when the search dialog is opened, the content of the main page is pushed to the left of the viewport. And the search dialog is opened as expected. 

The issue is that we had a cypress test which fails, because cypress is not able to clear the search field. 

Apart from the failing test I think we should have the search field in the search results dialog, as it is unexpected for the user to be able to type in a hidden field.

![image](https://user-images.githubusercontent.com/1060433/145671558-8446f922-1275-4745-9bea-b01f9dacdf39.png)

**Comment by marcimat** [comment]
Oh I think I’ve correct the pushed behaviour, on my custom.css simply with
```css
body {
    width: 100%;
}
```

**Comment by mvriel** [comment]
This issue is resolved; closing it
