### ISSUE TITLE
Defining constant in class method leads to parse error

### ISSUE THREAD

**Issue by m0003r** [phpDocumentor/phpDocumentor#3107]
## Expected behavior

Constants defined in methods considered as global constants.

## Actual behavior

Parse error occurs:
`ALERT     [app]   Unable to parse file "test.php", an error was detected: Call to undefined method phpDocumentor\Reflection\Php\Method::addConstant()`

## Steps to reproduce the problem

1. Create file test.php:
```php
<?php

class A {
   public function test() {
       define('CONSTANT', 1);
   }
}
```

2. Run `./phpdoc --validate -f test.php` leads to alert:

## Your environment

* phpDocumentor v3.3.0 (phar file)
* PHP 8.0.12
* CentOS 7

**Comment by jaapio** [comment]
I pushed a fix for this a new release will include this. We are preparing a new release soonish.

**Comment by jaapio** [comment]
I just tagged 3.3.1-rc, I hope this will help you

**Comment by jrfnl** [comment]
@jaapio Appreciated. Thanks!
