### ISSUE TITLE
xsl base path problems

### ISSUE THREAD

**Issue by cebe** [phpDocumentor/phpDocumentor#312]
I tried to create a new theme by copying the old_ocean theme and started modifying the files. I created the theme under a sub directory in my php project, not under docblox-base-dir/data/themes.
Problem is now that I can use my template by running docblox with
`docblox --template build/my-docblox-template`
but the template.xml in build/my-docblox-template does not know that it is located there and not under docblox-base-dir/data/themes.

references to `index.xsl` are resolved to `docblox-base-dir/data/index.xsl`instead of `build/my-docblox-template/index.xsl`

do I have to specify a basePath somewhere and if so, how?

**Comment by jaapio** [comment]
We dropped xml support, so this issue can be closed. Not relevant anymore for v3.
