### ISSUE TITLE
phpdoc/phpdoc 3.3 fails with "Constant::isFinal(): Return value must be of type bool, null returned"

### ISSUE THREAD

**Issue by caugner** [phpDocumentor/phpDocumentor#3147]
## Expected behavior

The `phpdoc/phpdoc:3.3` image should run successfully.

## Actual behavior

```
Using docker image sha256:3caa4af29d3d561cea4d315b31d02cf4bcd5d21e971772df15ecbb877253a5c2 for gitlab.***.***:443/***/dependency_proxy/containers/phpdoc/phpdoc:3.3 with digest gitlab.***.***:443/***/dependency_proxy/containers/phpdoc/phpdoc@sha256:19a88bc569afcd8f4920015b24f6566cc45eab71b2ddb76ca811d448a6bf15ef ...
$ php -v
PHP 8.0.15 (cli) (built: Jan 20 2022 20:08:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
$ phpdoc run -d src -t docs
phpDocumentor vdev-master@4c31809
Parsing files
    1/1127 [>---------------------------]   0%
  113/1127 [==>-------------------------]  10%
  339/1127 [========>-------------------]  30%
  451/1127 [===========>----------------]  40%
  564/1127 [==============>-------------]  50%
  677/1127 [================>-----------]  60%
  902/1127 [======================>-----]  80%
 1015/1127 [=========================>--]  90%
 1127/1127 [============================] 100%12:03:58 CRITICAL  [console] Error thrown while running command "run -d src -t docs". Message: "phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of type bool, null returned" ["exception" => TypeError { …},"command" => "run -d src -t docs","message" => "phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of type bool, null returned"]
In Constant.php line 120:
                                                                               
  phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of t  
  ype bool, null returned                                                      
                                                                               
project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [--examples-dir [EXAMPLES-DIR]] [-s|--setting [SETTING]] [--list-settings] [--parseprivate]
```

## Steps to reproduce the problem

Run the `phpdoc/phpdoc:3.3` Docker image on a project.

## Your environment

* Version used: `3.3` aka `vdev-master@4c31809`
* Install method: Docker
* PHP version: 8.0.15
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu
* Link to your project: (private)
* Attach code that is involved: (private)

**Comment by mxdpeep** [comment]
same issue here, I've rolled back to 3.0

**Comment by redcuillin** [comment]
I presume a related bug, so not logging it in a separate thread:

`CRITICAL  [console] Error thrown while running command "run". Message: "Return v
alue of phpDocumentor\Reflection\Php\Property::isReadOnly() must be of the type bool, null returned" ["exception" => TypeError { …},"
command" => "run","message" => "Return value of phpDocumentor\Reflection\Php\Property::isReadOnly() must be of the type bool, null re
turned"]`

Looks like methods that would have previously accepted null as a loosely typed boolean value are now treating boolean results with strict comparisons.

**Comment by emilas44** [comment]
I got same error :disappointed:

**Comment by jaapio** [comment]
Hi, 

Thanks for reporting this, I'm curious what is going on, as our demo project used in the ci-pipelines do have a readonly property. So it must be something else which isn't covered by  our testcases. Could you please try to run phpdocumentor 3.3.1-rc? To see if this solves your issue? https://github.com/phpDocumentor/phpDocumentor/releases/tag/v3.3.1-rc

If it doesn't it would be helpfull to get the verbose output using: `phpdocumentor --vvvv`

**Comment by mxdpeep** [comment]
CRITICAL  [console] Error thrown while running command "run -d '.' -t
'./doc' --ignore 'vendor/'". Message:
"phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of
type bool, null returned" ["exception" => TypeError { …},"command" => "run
-d '.' -t './doc' --ignore 'vendor/'","message" =>
"phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of
type bool, null returned"]

In Constant.php line 120:


  phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of
type bool, null returned




project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]]
[-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding
[ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]]
[--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers
[MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility
[VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode]
[--template [TEMPLATE]] [--examples-dir [EXAMPLES-DIR]] [-s|--setting
[SETTING]] [--list-settings] [--parseprivate]

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by mxdpeep** [comment]
DEBUG     [console] Command "run -d '.' -t './doc' --ignore 'vendor/' -vvv"
exited with code "1"
[
  "command" => "run -d '.' -t './doc' --ignore 'vendor/' -vvv",
  "code" => 1
]

In Constant.php line 120:


  [TypeError]

  phpDocumentor\Reflection\Php\Constant::isFinal(): Return value must be of
type bool, null returned




Exception trace:
  at
/opt/phpdoc/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/Constant.php:120
 phpDocumentor\Reflection\Php\Constant->isFinal() at
/opt/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/ConstantAssembler.php:42
 phpDocumentor\Descriptor\Builder\Reflector\ConstantAssembler->create() at
/opt/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:103
 phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() at
/opt/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/ClassAssembler.php:83
 phpDocumentor\Descriptor\Builder\Reflector\ClassAssembler->addConstants()
at
/opt/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/ClassAssembler.php:67
 phpDocumentor\Descriptor\Builder\Reflector\ClassAssembler->create() at
/opt/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:103
 phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() at
/opt/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php:137
 phpDocumentor\Descriptor\Builder\Reflector\FileAssembler->addClasses() at
/opt/phpdoc/src/phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php:69
 phpDocumentor\Descriptor\Builder\Reflector\FileAssembler->create() at
/opt/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:103
 phpDocumentor\Descriptor\ProjectDescriptorBuilder->buildDescriptor() at
/opt/phpdoc/src/phpDocumentor/Descriptor/ProjectDescriptorBuilder.php:176
 phpDocumentor\Descriptor\ProjectDescriptorBuilder->createApiDocumentationSet()
at /opt/phpdoc/src/phpDocumentor/Pipeline/Stage/Parser/ParseFiles.php:63
 phpDocumentor\Pipeline\Stage\Parser\ParseFiles->__invoke() at
/opt/phpdoc/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
 League\Pipeline\FingersCrossedProcessor->process() at
/opt/phpdoc/vendor/league/pipeline/src/Pipeline.php:34
 League\Pipeline\Pipeline->process() at
/opt/phpdoc/vendor/league/pipeline/src/Pipeline.php:39
 League\Pipeline\Pipeline->__invoke() at
/opt/phpdoc/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
 League\Pipeline\FingersCrossedProcessor->process() at
/opt/phpdoc/vendor/league/pipeline/src/Pipeline.php:34
 League\Pipeline\Pipeline->process() at
/opt/phpdoc/vendor/league/pipeline/src/Pipeline.php:39
 League\Pipeline\Pipeline->__invoke() at
/opt/phpdoc/src/phpDocumentor/Console/Command/Project/RunCommand.php:290
 phpDocumentor\Console\Command\Project\RunCommand->execute() at
/opt/phpdoc/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at
/opt/phpdoc/vendor/symfony/console/Application.php:1023
 Symfony\Component\Console\Application->doRunCommand() at
/opt/phpdoc/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at
/opt/phpdoc/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at
/opt/phpdoc/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at
/opt/phpdoc/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /opt/phpdoc/bin/phpdoc:44

project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]]
[-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding
[ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]]
[--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers
[MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility
[VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode]
[--template [TEMPLATE]] [--examples-dir [EXAMPLES-DIR]] [-s|--setting
[SETTING]] [--list-settings] [--parseprivate]

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by mxdpeep** [comment]
I have tested all the versions: 3.0.0 and 3.1.0 are working, 3.2.0+ fails

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by mvriel** [comment]
This looks very similar to an issue I just closed where the issue was with the cache: https://github.com/phpDocumentor/phpDocumentor/issues/3202

When new properties are introduced, such as final with constants, in objects that we cache; then upon deserialization the default value is used. This default value is null in many instances are properties are not all typed yet; and since our methods are becoming typed this seems to throw errors like these.

If you are still able to test it, can you throw away your cache before running the newer version?

**Comment by mvriel** [comment]
Upon further research; it would seem the cache is not cleared when a newer version of phpDocumentor is used. I have created the PR above to fix that. This should also solve issues such as the one reported here

**Comment by mxdpeep** [comment]
super 👌

Filip Oščádal 🍀📱
