### ISSUE TITLE
Typed array property not showing type from @var

### ISSUE THREAD

**Issue by rwebster85** [phpDocumentor/phpDocumentor#3155]
When declaring a class property as an array, the type structure entered with the @var tag no longer shows in the generated docs.

## Expected behaviour
I would expect the generated documentation to show the array type like so:

![image](https://user-images.githubusercontent.com/16655270/154490101-0baea16e-77b6-4086-a0f9-4a97666a21d7.png)

## Actual behaviour
The array defaults to mixed.

![image](https://user-images.githubusercontent.com/16655270/154489580-0ba41dc0-ecb5-4f43-9179-79459528290c.png)

## Steps to reproduce the problem

1. Declare a property and include the array type with the @var tag. Like this, for example
![image](https://user-images.githubusercontent.com/16655270/154490190-b99affae-2fe1-4dde-8206-721f47ebc538.png)

2. Give the property the array type.
![image](https://user-images.githubusercontent.com/16655270/154490275-c40a9f6b-ed56-48e1-aaa3-58f3f074fa74.png)

## Your environment

* Version used: 3.3.0
* Install method - Downloaded phar file, manually invoking from CLI.
* PHP version - 8.0
* Operating system and version: Windows 10
* Attach code that is involved
```php
/**
 * @var string[]
 */
private array $files = [];
```

**Comment by mvriel** [comment]
I have been able to reproduce the issue and create a PR to fix it: https://github.com/phpDocumentor/phpDocumentor/pull/3293
