### ISSUE TITLE
`--cache-folder` paths are considered relative to `--config`

### ISSUE THREAD

**Issue by PhrozenByte** [phpDocumentor/phpDocumentor#3158]
The CLI option `--cache-folder` is interpreted relative to a given `--config` file, and not relative to the current working dir. This is (1) unexpected and (2) different from `--target`.

## Steps to reproduce the problem

```shell
cd "$(mktemp -d)"
mkdir src
echo '<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor configVersion="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.phpdoc.org" xsi:noNamespaceSchemaLocation="data/xsd/phpdoc.xsd"></phpdocumentor>' > src/phpdoc.xml
phpdoc run --config src/phpdoc.xml --target phpdoc/phpdoc --cache-folder phpdoc/phpdoc.cache
```

## Expected behavior

phpDocumentor should create `./phpdoc/phpdoc` and `./phpdoc/phpdoc.cache`

## Actual behavior

phpDocumentor actually creates `./phpdoc/phpdoc` and `./src/phpdoc/phpdoc.cache`

Note that `--target` is considered relative to the current working dir, whereas `--cache-folder` is treated relative to `--config` (`src/phpdoc.xml`). `--cache-folder` should be treated relative to the current working dir.

## Your environment

* Version used: 3.3.0
* Install method: PHAR
* PHP version: 7.4.16

**Comment by mvriel** [comment]
Thanks for reporting this! I found this issue while I was fixing another issue in the caching method and I have included the fix in PR https://github.com/phpDocumentor/phpDocumentor/pull/3289
