### ISSUE TITLE
A function argument default value of 0 (zero) not handled

### ISSUE THREAD

**Issue by neil-pearce** [phpDocumentor/phpDocumentor#3193]
## Expected behavior
A default value of zero for a function argument should be handled

## Actual behavior
The default value is not being generated in the Files output:  

test(int $param) : void
Parameters
$param : int
Return values
void —

## Steps to reproduce the problem

```  
<?php
function test(int $param = 0): void
{
}
```

## Your environment

- Version used: phpdocumentor-3.3.1
- Install method: PHIVE
- PHP version: PHP 8.1.4 (cli) (built: Mar 16 2022 09:33:31) (ZTS Visual C++ 2019 x64)
- Operating system and version: Windows 10

**Comment by jaapio** [comment]
Thanks for reporting this, I added a fix to solve this issue.
