### ISSUE TITLE
Enums not assigned the default package name

### ISSUE THREAD

**Issue by neil-pearce** [phpDocumentor/phpDocumentor#3194]
## Expected behavior
Enums should be assigned the default-package-name like any other PHP primitive or pseudo type

## Actual behavior
Enums are not treated as part of the default package

## Steps to reproduce the problem

1. Create an enum without a package tag
2. Set the default package name
3. Run phpdoc

## Your environment

- Version used: phpdocumentor-3.3.1
- Install method: PHIVE
- PHP version: PHP 8.1.4 (cli) (built: Mar 16 2022 09:33:31) (ZTS Visual C++ 2019 x64)
- Operating system and version: Windows 10

**Comment by jaapio** [comment]
Thanks for reporting this, I added a fix to solve this issue.
