### ISSUE TITLE
Enum cases

### ISSUE THREAD

**Issue by neil-pearce** [phpDocumentor/phpDocumentor#3199]
## Expected behavior
A simple enum (ie one that does not includes a method) should include the cases in the Table of Contents for the enum.

## Actual behavior
A simple enum does not generate a TOC but if a method is added to the enum then the TOC includes a list of the enum cases as well as the method(s). However, selecting a case from the TOC results in a file listing of the output directory.

## Steps to reproduce the problem

```
<?php
declare(strict_types=1);

enum Suit
{
    case Hearts;
    case Diamonds;
    case Clubs;
    case Spades;

    public function colour(): string
    {
        return match ($this) {
            self::Hearts => 'red',
            self::Diamonds => 'red',
            self::Clubs => 'black',
            self::Spades => 'black',
        };
    }
}  
```

## Your environment

- Version used: phpdocumentor-3.3.1
- Install method: PHIVE
- PHP version: PHP 8.1.4 (cli) (built: Mar 16 2022 09:33:31) (ZTS Visual C++ 2019 x64)
- Operating system and version: Windows 10

**Comment by mvriel** [comment]
Thank you for reporting this, it seems the router had not been made aware how to render (deep)links to enum cases. PR https://github.com/phpDocumentor/phpDocumentor/pull/3288 should fix that. As soon as it is merged this change will be included in the next release
