### ISSUE TITLE
Documentation XSD file returning 404 not found error 

### ISSUE THREAD

**Issue by caendesilva** [phpDocumentor/phpDocumentor#3221]
This is the exact same issue as #2931, so the following text is copied from that.

The XSD file referenced in the documentation at https://docs.phpdoc.org/latest/phpdoc.xsd is returning a 404 not found error when trying to access it.

## Expected behavior
To have my editor download the XSD file and provide editor hints.

## Actual behavior
Editor does not provide hints. Visiting the url in the browser redirects back to the main documentation page for phpDocumentor.

## Steps to reproduce the problem

1. Create XML as defined in [Appendix A](https://docs.phpdoc.org/3.0/guide/references/configuration.html).
2. Use an editor that provides editor hints.
3. Notice hints don't work.
4. Visit https://docs.phpdoc.org/latest/phpdoc.xsd in browser.
5. Notice redirect to documentation and a 404 error before the redirect in browser development tools.

## Possible workaround
For now, I guess it should be possible to reference the source directly: https://github.com/phpDocumentor/phpDocumentor/blob/master/data/xsd/phpdoc.xsd

Can confirm that the following works in PHPStorm:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/phpDocumentor/phpDocumentor/master/data/xsd/phpdoc.xsd"
>
    <paths>
        <output>build/api</output>
        <cache>build/cache</cache>
    </paths>
    <version number="3.0.0">
        <api>
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
</phpdocumentor>
```

**Comment by mvriel** [comment]
Ah, that is unfortunate indeed! I have corrected the docs, and they now match your workaround / suggestion. This may not be an ideal situation since the XSD is not version bound (master changes frequently) but at least it will provide a working solution. I have made a note to improve this situation in the future, it will require a bit of planning because the XSD may vary between versions of phpDocumentor
