### ISSUE TITLE
Representing a POST var in method

### ISSUE THREAD

**Issue by neoacevedo** [phpDocumentor/phpDocumentor#3223]
# Feature request

Started at https://github.com/phpDocumentor/phpDocumentor/issues/1840.
As `@global` tag is discouraged, I think a new tag, named `@post` or `@param-post` maybe used to describe the parameters sent via post to the method.

**Comment by jaapio** [comment]
It's not that we discourage `@global` just the usage of global variables is discouraged. You can still use the tag.
