### ISSUE TITLE
natashawylie/iviewer is outdated

### ISSUE THREAD

**Issue by Hackwar** [phpDocumentor/phpDocumentor#3226]
Simply said, the iviewer version from https://github.com/natashawylie/iviewer which you are using in phpdocumentor is outdated. The current version in phpdocumentor is 0.7.7, the latest release is 0.7.11. Generally I would question if a library which hasn't been touched for 8 years is the right thing to use here.

**Comment by mvriel** [comment]
So far, the library seems to do its work. I know it was hard to find a good lightweight viewer at the time.

Given that the library currently does not pose issues (not that I know of at least) I am going to close this issue. A more modern solution is always nice; but it works and I need to categorize it as a 'someday' :)

Thank you for reporting this

**Comment by Hackwar** [comment]
Regardless of a more modern solution or not, I would expect that the author had a reason to release 4 new versions after the one you are shipping with your package and would update to that version...
