### ISSUE TITLE
php-mbstring required to resolve TextNormalizer undefined constant MB_CASE_FOLD

### ISSUE THREAD

**Issue by carywreams** [phpDocumentor/phpDocumentor#3230]
## Expected behavior
Installation instructions to include installation of  php-mbstring php extension if the MB_CASE_* constants report as undefined. 

## Actual behavior
phpDocumentor.phar (3.3.1) running with php8.1 errors out with 

```
In TextNormalizer.php line 37: Undefined constant "MB_CASE_FOLD"
```

## Steps to reproduce the problem

ran phpDocumentor.phar on my code base immediately after installation

## Your environment

* Version used: 3.3.1
* Install method: wget
* PHP version: 8.1
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): pop!_os:22.04
* Link to your project:
* Attach code that is involved: not sure, didn't isolate it. If you really need this, let me know in the comments and I'll hunt it down.
* ...

Thanks,
Cary

**Comment by mvriel** [comment]
Thank you for reporting this; I have added the mbstring requirement to the documentation in the installation docs
