### ISSUE TITLE
Raw directive stopped working

### ISSUE THREAD

**Issue by daiwai** [phpDocumentor/phpDocumentor#3240]
The `raw` directive stopped working starting with v3.2.0 and the contents of the raw code block is output as a regular escaped `code` block.

**Comment by mvriel** [comment]
@jaapio could this be related to the same issue that we have with admonitions?

**Comment by jaapio** [comment]
This issue has been fixed by the new integration. If you pick the master branch or our v3 docker tag this is solved.

Any new release will contain this, fix.
