### ISSUE TITLE
Displaying Source Files Still Not Working

### ISSUE THREAD

**Issue by n0nag0n** [phpDocumentor/phpDocumentor#3248]
There's not a ton of documentation about this, but in case I'm missing something, I just can't seem to get source code to show correctly. I know that #2919 is heavily referenced around this repo as this being fixed, but I am not having that great of luck with it (or I lack the understanding on how to get it working).

## Expected behavior
If I run the below command, I would expect that when I click on the source code icon that the source code would display.
```
phpdoc --sourcecode
```
I've also tried `<include-source>true</include-source>` in the config file. I've also tried this with the `--template="clean"` with the same results.

## Actual behavior
The icon shows
![image](https://user-images.githubusercontent.com/2322095/177626134-9b2692ea-2322-4fff-a3fb-d3391486ee7f.png)
But when I click on it, I get this
![image](https://user-images.githubusercontent.com/2322095/177626308-34a6ef16-2b68-48ce-940b-b37ee53dd753.png)

So I thought.....well maybe I need to serve this via a webserver of some kind. After getting a php web-server up to the directory where things are output, now I just get an empty source file with 2 empty lines.

![image](https://user-images.githubusercontent.com/2322095/177626862-3af98d85-3c1f-4413-9361-c5e92fbf1ade.png)

Do all the source files have to be in the public directory as well?

## Steps to reproduce the problem

1. run `phpdoc` with source option
2. go to documentation page and click on source code icon
3. cry

## Your environment

* Version used: 3.3.1
* Install method: PHAR
* PHP version: 7.4
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu 22.04

**Comment by smileBeda** [comment]
```
                                     
  The "--source" option does not exist.  
                                         

project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [--examples-dir [EXAMPLES-DIR]] [-s|--setting [SETTING]] [--list-settings] [--parseprivate]
```

I struggle with even getting the command working, and this would be one of the most important features to me.

**Comment by n0nag0n** [comment]
Ahh my bad, typo. `--sourcecode`

![image](https://user-images.githubusercontent.com/2322095/177808153-155cf73f-4beb-4231-ae0e-1059d51b68ba.png)

**Comment by mvriel** [comment]
I would need to investigate the actual cause; but `or trying to view from localhost` means that the sourcecode cannot be displayed when you open the documentation using the `file://` scheme in your browser. This is because we show the source code by fetching it using XHR and embedding it there; but browsers block loading through XHR when you open a file using the `file://` scheme.

**Comment by smileBeda** [comment]
Thanks @mvriel - that means that once its fixed, and we would want to run the documentation say on a website A, website A must've the application we are documenting actually located somewhere on its server?

I am also seeing some other things that seem bugs to me (like things  such as `Cp_Plgn_Drctry_Admin` class being split into `Cp\Plgn\Drctry\Cp\Plgn\Drctryadmin` breadcrumbs - this might be due to my unusual syntax, and - I do not want to pollute this thread here with unrelated stuff.

I should just open issue(s) or is there some forum or the likes where we can ask perhaps "beginner" questions?

Thanks!

**Comment by n0nag0n** [comment]
So I just brought up an instance of apache to serve the files on another server (Rocky Linux 8 with apache 2.4 and php-fpm 7.4) and it is serving those source files just fine. Something is up with the localhost stuff I guess....?

**Comment by mvriel** [comment]
> I should just open issue(s) or is there some forum or the likes where we can ask perhaps "beginner" questions?

There is a mailing list, but there are few people responding to these messages; at this moment I can recommend opening an issue. Especially if something doesn't look right. And don't worry about it being beginner questions or not; all of them are valid and to me helpful.

**Comment by mvriel** [comment]
> So I just brought up an instance of apache to serve the files on another server (Rocky Linux 8 with apache 2.4 and php-fpm 7.4) and it is serving those source files just fine. Something is up with the localhost stuff I guess....?

It would seem so! I haven't figured out how to work around this issue yet, but reviewing the error message above. Perhaps that could be more clear on the issue at hand? Another problem is that the software cannot detect if this is the case, the browser errors and returns an empty file..

**Comment by mvriel** [comment]
> Thanks @mvriel - that means that once its fixed, and we would want to run the documentation say on a website A, website A must've the application we are documenting actually located somewhere on its server?

No need. phpDocumentor copies all required files into the build. This is also why this is an optional feature as your source code will be included in the built files and thus accessible. Some proprietary applications do not want that

**Comment by mvriel** [comment]
Given that the issue seems to be a known limitation, I'm going to close this issue. Of course, it would be nice to have an improvement to make this better, at the moment we need to focus our efforts on other locations. This is also in part because I have spent significant time trying to find a workaround but can't justify spending more hours at this moment.

**Comment by n0nag0n** [comment]
I guess then my only ask is if the source code option could be better documented with this limitation in mind. The only way I knew about it was I looked in the default configuration and saw the include-source tag and went from there.

**Comment by mvriel** [comment]
You are right, I am reopening the issue so that this can be picked up on. I am at the moment investigating another issue and thus am not immediately available to include this in the docs

**Comment by n0nag0n** [comment]
I couldn't find any new documentation about the source stuff. Hopefully my last post gives you guys a starting point wherever you decide to put it.

**Comment by mvriel** [comment]
I didn't add documentation yet, but I did hide the feature when viewing using file://. This will at least ensure you get less confused :)

**Comment by n0nag0n** [comment]
That's a great start! Thank you!
