### ISSUE TITLE
Best way to parse complex comments

### ISSUE THREAD

**Issue by smileBeda** [phpDocumentor/phpDocumentor#3250]
I often have complex method comments like the below:
```
/**
	 * TukuToi `[searchtemplate]` ShortCode.
	 *
	 * Outputs the Search Form.</br>
	 * Mandatory to use when adding Search ShortCodes.
	 *
	 * Example usage:
	 * ```
	 * [searchtemplate instance="my_instance" customid="my_id" customclasses="class_one classtwo"]
	 *   // Search ShortCodes here.
	 * [/searchtemplate]
	 * ```</br>
	 * For possible attributes see the Parameters > $atts section below or use the TukuToi ShortCodes GUI.
	 *
	 * @since    2.0.0
	 * @param array  $atts {
	 *      The ShortCode Attributes.
	 *
	 *      @type string    $instance       The Instance used to bind this Search section to a Loop Results Section. Default: ''. Accepts: '', any valid string or number.
	 *      @type string    $customid     ID to use for the Search Form. Default: ''. Accepts: '', valid HTML ID.
	 *      @type string    $customclasses   CSS Classes to use for the Search Form. Default: ''. Accepts: '', valid HTML CSS classes, space delimited.
	 * }
	 * @param mixed  $content   ShortCode enclosed content. TukuToi Search and Filter Search ShortCodes, HTML.
	 * @param string $tag       The Shortcode tag. Value: 'searchtemplate'.
	 */
```

This renders like so in phpdoc:
```
buttons() class-tkt-search-and-filter-shortcodes.php : 682
TukuToi `[buttons]` ShortCode.

public buttons(array<string|int, mixed> $atts[, mixed $content = null ], string $tag) : mixed
Outputs the Buttons for Search Form.
Can only be used inside a [searchtemplate][/searchtemplate] ShortCode.
Can be used to produce Search input as well, apart of Submit and Reset buttons.

Example usage: [buttons label="Submit..." type="submit" customid="my_id" customclasses="class_one classtwo"]
For possible attributes see the Parameters > $atts section below or use the TukuToi ShortCodes GUI.

Parameters

$atts : array<string|int, mixed>
{ The ShortCode Attributes.

 @type string    $label          The Button Label. Default: 'Submit'. Accepts: valid string.
 @type string    $url_param      URL parameter to use. Default: ''. Accepts: valid URL search parameter.
 @type string    $value          The value to pass to the URL parameter 'url_param'. Default: ''. Accepts: valid URL search parameter.
 @type string    $search_by      Query Parameter. Default: ''. Accepts: valid WP Query Parmater.
 @type string    $type           Type of Button. Default: 'submit'. Accepts: 'submit', 'reset', 'button'.
 @type string    $autofocus      Whether to autofocus the button. Only one item on document can be autofocused. Default: ''. Accepts: '', autofocus'.
 @type string    $form           Form ID to submit. Default: ancestor Form. Accepts: valid Form ID.
 @type string    $formtarget     Target of the form. Default: '_self'. Accepts: '_self', '_blank'.
 @type string    $customid       ID to use for the Search Form. Default: ''. Accepts: '', valid HTML ID.
 @type string    $customclasses  CSS Classes to use for the Search Form. Default: ''. Accepts: '', valid HTML CSS classes, space delimited.
}

$content : mixed = null
ShortCode enclosed content. TukuToi Search and Filter Search ShortCodes, HTML.

$tag : string
The Shortcode tag. Value: 'selectsearch'.

Tags 

since
2.0.0
Return values

mixed —
```

I used to use WordPress's `wp parse` command which generates something like this https://developer.wordpress.org/reference/functions/gallery_shortcode/ (see the `attr` section, which is basically a parsed code comment block see example https://github.com/WordPress/wordpress-develop/blob/ac3de7c5b3c6eeeda485e00cc0d94da5b40e023f/src/wp-includes/media.php#L2283)

Any chance that we can achieve the same with phpdoc?
Meaning, some sort of syntax that allows us to:
1. parse "code" in a comment block (like within back-apostrophe or `<code>`)
2. Recognise the `@param array $attr {}` syntax, and parse whatever what's within the `{}` in this case as a sublist of the "parent" @param
3. Generally support markdown ( the three back-apostrophes or else) to print code in comment blocks 

I've added a screenshot of how it looks right now with phpdoc. Not too bad, but I wish there would be some way to better control the `{}` params and code itself as such
I have read about custom templates, but cannot really figure out if, and if then how creating one can help me solve this.

Thank you!

<img width="964" alt="Screenshot 2022-07-09 at 15 54 55" src="https://user-images.githubusercontent.com/11800236/178099068-f70cdaad-0f4f-49ad-b5ac-a0a4412ba50b.png">

**Comment by mvriel** [comment]
> parse "code" in a comment block (like within back-apostrophe or <code>)

The first / opening line (also called the Summary) doesn't support markdown by design. That line is meant to be easily human and machine-readable and be agnostic to formatting.

The Description (the text below the summary and before the tags), and the description with each tag, already supports markdown. If you were to inspect the codeblock that you showed as an example; you'd see it is wrapped in a codeblock. A bit more styling there would probably be helpful :)

> Recognise the @param array $attr {} syntax, and parse whatever what's within the {} in this case as a sublist of the "parent" @param

This is a bit of a debate; there are issues on the backlog to include support for this. At the moment it stalls because of lack of contributors and because, IIRC, there are varying implementations in the wild and we'd need to get a clear reading which would be the preferred implementation. 

The example you are showing above is a notation that stems from the original PSR-5 draft as a proposal. But as far as I can see, userland has adopted a more concise variant that is used by phpstan. So.. I can't really tell you when it would come and what the format will be.

> Generally support markdown ( the three back-apostrophes or else) to print code in comment blocks

**Comment by smileBeda** [comment]
Fair enough, I can workaround it using markdown code delimiters instead of curly {}
Like so:
```
@param array  $atts
	 * ```
	 *      The ShortCode Attributes.
	 *
	 *      @type string    $label          The Button Label. Default: 'Submit'. Accepts: valid string.
	 *      @type string    $url_param      URL parameter to use. Default: ''. Accepts: valid URL search parameter.
	 *      @type string    $value          The value to pass to the URL parameter 'url_param'. Default: ''. Accepts: valid URL search parameter.
	 *      @type string    $search_by      Query Parameter. Default: ''. Accepts: valid WP Query Parmater.
	 *      @type string    $type           Type of Button. Default: 'submit'. Accepts: 'submit', 'reset', 'button'.
	 *      @type string    $autofocus      Whether to autofocus the button. Only one item on document can be autofocused. Default: ''. Accepts: '', autofocus'.
	 *      @type string    $form           Form ID to submit. Default: ancestor Form. Accepts: valid Form ID.
	 *      @type string    $formtarget     Target of the form. Default: '_self'. Accepts: '_self', '_blank'.
	 *      @type string    $customid       ID to use for the Search Form. Default: ''. Accepts: '', valid HTML ID.
	 *      @type string    $customclasses  CSS Classes to use for the Search Form. Default: ''. Accepts: '', valid HTML CSS classes, space delimited.
	 * ```
```

This prints something I can style:
<img width="961" alt="Screenshot 2022-07-09 at 17 11 44" src="https://user-images.githubusercontent.com/11800236/178101330-22c088fb-e2f4-4e21-b7a7-396ba7445279.png">

Thou, it will be difficult to address only _that_ section and not all other `phpdocumentor-description` sections.. thus:

- is there any way to pass a "custom class" or else identifier to particular parts of the @param blocks?
- about custom templating (which I guess is what I will have to venture into), how can I get started with that? For example, lets take a simple thing. how to move the `public buttons(array<string|int, mixed> $atts[, mixed $content = null ], string $tag) : mixed` part _above_ the `TukuToi [buttons] ShortCode.` part? (Screenshot: How to move red part to where blue part is, and blue part to red part?)
Pretty sure that must be some template somewhere that I can edit?
<img width="970" alt="Screenshot 2022-07-09 at 17 17 39" src="https://user-images.githubusercontent.com/11800236/178101511-d3d87ad9-26c3-4966-b5fd-9bc60de7cb33.png">

Thanks!

PS:
I am pretty strongly involved with OS projects, in terms of volunteering, sponsoring, and whatever I can do.
So please let me know if I can help somehow. I am _not_ your "terminal guy_, but I can write PHP pretty well (I make a living off that), I can create websites, web apps, blockchains, documentations, do support... So if you have something I can help with, please feel free to ping me.

**Comment by smileBeda** [comment]
Nevermind, so this is how you create a template:

1. Create a folder in your project `data/templates/my_template`
2. In that folder, to get an easy start, put all of the contents of any of the available templates (for example [`default`](https://github.com/phpDocumentor/phpDocumentor/tree/master/data/templates/default) 
3. Start customising (and good luck there are about 1000 files 🤣 - but for simple changes like mentioned above, it is a pretty quick way to do it

**Comment by mvriel** [comment]
Actually there is a simpler way since phpDocumentor 3.1. But I haven't had time to document it

**Comment by mvriel** [comment]
You can override a specific twig file by creating a `.phpdoc/template` folder and adding overrides for specific twig templates. This way you do not need to create a whole new template

**Comment by mvriel** [comment]
For an example, see how phpDocumentor itself leverages that to change the header and menu: https://github.com/phpDocumentor/phpDocumentor/tree/master/.phpdoc/template
