### ISSUE TITLE
Strange breadcrumbs/package paths generated by documentor

### ISSUE THREAD

**Issue by smileBeda** [phpDocumentor/phpDocumentor#3251]
I have an example file for a class `Tkt_Search_And_Filter_Shortcodes` which on top (file comment) has this 
```
* @package    Tkt_Search_And_Filter
* @subpackage Tkt_Search_And_Filter/public
```

As class comment it features the same.

PHP documentor picks that up as 
```
Tkt_Search_And_Filter_Shortcodes
in package Tkt\Search\And\Filter\Tkt\Search\And\Filterpublic
```
....
I am lost :)

I might understand that phpdocumentor somehow splits `_`, but then where does the last `Filterpublic` come from?
If you need an example, the project is here https://github.com/TukuToi/tukutoi-search-and-filter

I might very well do something wrong with my code documentation, yet I do not see what. 
The way it is now, I end up with a package `Tkt`, another `And`, etc etc, which I never declare.

**Comment by mvriel** [comment]
Hi @smileBeda,

This is a history thing :D The `@package` tag only allows a subset of character and removes some. I would need to look up what exactly. 

But moreover: before there were namespaces in PHP, it was frequently added by using an `@package` like you have now; but there was no standard which character was used as namespace separator. As such, many projects used the `_` or '.' as namespace separator and in phpDocumentor's early days it was decided to use those as separators.

Nowadays, we have the backslash `\` as namespace separator and as such the `@package` tag now considers the dot, underscore and backslash to be namespace separators.

See https://docs.phpdoc.org/guide/references/phpdoc/tags/package.html#package for more information

**Comment by smileBeda** [comment]
Aha. Makes sense so far, I’ve to refactor my code then. Fact is I used package tags Merely as a „Guide for myself“ than as actual namespaces (o don’t use namespace at all)

I’ll go over the code
Thanks!
