### ISSUE TITLE
Implement something to sponsor this project

### ISSUE THREAD

**Issue by smileBeda** [phpDocumentor/phpDocumentor#3252]
I suggest [opencollective](https://opencollective.com)
It allows for ultra transparent donation gathering.

And I certainly would donate to this project - it is just awesome.
There might be issues, every code has some, but in all honesty, I would hate this project to stall or even disappear because of lack of contribution.

Thus, I might not be perfectly able to help programmatically but I certainly would help financially.

I'll start presenting all my code documentation using this tool and credit it so people see how it is useful.

As said, I would strongly suggest you set up a transparent donation system so folks who want can help you (I bet servers are not free for you either, and even if you can just just pay off that with donations it is already a step to maintain it alive).

**Comment by jaapio** [comment]
Thank you very much for this request. When you created this request, we were looking into the options we have to make some sponsor options. We have chosen to use GitHub sponsors in the first place.

I'm not sure yet if it is possible to be as transparent as opencollective is with GitHub sponsors. I hope this will fit your needs for now. And I would be very pleased if you are able to support us. 

Thank you very much for using phpDocumentor, and just this request made my day!

**Comment by jaapio** [comment]
Our sponsor profile is now open for any donations. 

Thanks for your support!

**Comment by smileBeda** [comment]
Added sponsorship of 10USD monthly through my Company [@tukutoi](https://github.com/TukuToi)

**Comment by mvriel** [comment]
Thank you so much @smileBeda; I can't tell you how much that means to us
