### ISSUE TITLE
@package value is not inherited from file-level

### ISSUE THREAD

**Issue by dejudicibus** [phpDocumentor/phpDocumentor#3267]
## Expected behavior
I expect that if I have a @package tag at file level, the tag is applied also to the class inside that file.

## Actual behavior
If the tag is in the file-level doc block, the class is not referenced in generated documentation. 
If I move the @package tag in the class-level doc-block, the class is referenced.

## Steps to reproduce the problem

Try
```
/**
 * My Class
 * 
 * @package        MyProject
 * @subpackage  Classes
 * @filesource	
 *
 */
require_once ABSPATH . 'wp-admin/includes/upgrade.php'; // For dbDelta

/**
 * My Class
 * 
 * This class extend a Singleton pattern, so that there is only one instance.
 */
class MyClass extends Singleton {
   ...
```
The class is NOT referenced.
Try
```
/**
 * My Class
 * 
 * @filesource	
 *
 */
require_once ABSPATH . 'wp-admin/includes/upgrade.php'; // For dbDelta

/**
 * My Class
 * 
 * This class extend a Singleton pattern, so that there is only one instance.
 * @package         MyProject
 * @subpackage   Classes
 */
class MyClass extends Singleton {
   ...
```
The class IS referenced.

## Your environment

phpDocumentor v3.3.1
PHP v7.4.9
WampServer v3.2.7
Windows 10 Pro

**Comment by ashnazg** [comment]
phpDocumentor has required an explicit File level docblock and Package _and_ explicit Class level docblock and Package **for years and years**... it has never behaved on an assumption that a File level Package also applied to a Class in the same file.

This is explicitly defined _and documented_ behavior:

```
If the package is defined in the file-level DocBlock then it only applies to the following elements in the applicable file:

global functions
global constants
global variables
requires and includes
```
https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/package.html#package

Thus, this is not a bug.
