### ISSUE TITLE
phpdoc and phpdoc.dist.xml

### ISSUE THREAD

**Issue by rino1** [phpDocumentor/phpDocumentor#3268]
```
$ cat phpdoc.dist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance
        xmlns=https://www.phpdoc.org/

xsi:noNamespaceSchemaLocation=https://docs.phpdoc.org/latest/phpdoc.xsd
>
    <paths>
        <output>build/api</output>
        <cache>build/cache</cache>
    </paths>
    <version number="3.0.0">
        <api>
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
</phpdocumentor>

$ docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3
Description:
  Parses and transforms the given files to a specified location

Usage:
  project:run [options]
  run
...
```

Why not work (only show help)?

**Comment by rino1** [comment]
nothing?

**Comment by mvriel** [comment]
I just checked it out and in the Dockerfile we run the help command by default; but this interferes in your, valid, use case. I have just issued a PR to remove the default CMD line in our dockerfile. That should fix the issue. As a workaround you can run it using the following:

```
docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3 -v
```

The `-v` will override the default CMD (you can actually use _anything_ there) and then it will pick up on your config file.

Thanks for reporting this and please track https://github.com/phpDocumentor/phpDocumentor/pull/3285 to see when it lands :)
