### ISSUE TITLE
tag @see not work

### ISSUE THREAD

**Issue by rino1** [phpDocumentor/phpDocumentor#3269]
`
$ cat src/Entity.php 
\<?php
class Entity {
    function a(){}
    
    /**
     * @see a
     */
    function b(){}
}
$ docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3 -d src -t docs
[...]
$ firefox docs/classes/Entity.html#method_b
[OUTPUT CLIP: https://pasteboard.co/R1jXAwoHuI1r.png]
`
**a** is not a link.
Why?

**Comment by jaapio** [comment]
because you have to tell phpDocumentor what `a` is and where to find it. 

I think this will work:

```
class Entity {
   function a() {}
   
   /** 
    * @see self::a()
    */
   function b() {}
}
```

**Comment by rino1** [comment]
> perché devi dire cosa phpDocumentor `a` è e dove trovarlo.
> 
> Penso che questo lavoro:
> 
> ```
> class Entity {
>    function a() {}
>    
>    /** 
>     * @see self::a()
>     */
>    function b() {}
> }
> ```

https://pasteboard.co/qFNenPUbEaIi.png

**Comment by mvriel** [comment]
Please see the documentation on the `@see` tag. Though I understand why it seems that it makes no sense, it does :) If you didn't specify context, `@see a` is ambiguous as it may refer to a global function, global constant, constant in the current class, property in the current class, or a method in the current class (and I am ignoring nested anonymous classes right now).

By providing a bit more information, this ambiguity is gone.

I hope this answer provides enough information; as such I will close this issue
