### ISSUE TITLE
Underscores in content results in encoded ID

### ISSUE THREAD

**Issue by smileBeda** [phpDocumentor/phpDocumentor#3272]
This is literally driving me crazy.

I do know PHP Documentor does some assumptions about `_` underscores and basically things will/can go south when any variable, function name or even @package tag has underscores in it.
I found solutions for all cases, but this one is ... just frustrating me.

1. Create a _guide_ (not a PHP Doc block based documentation but a Guide) with .rst files
2. In a .rst file, add something like this:
```
Title Goes here
~~~~~~~~~~~

Some stuff here
```
3. parse that to a html guid
4. Works just fine, the resulting doc will have this HTML:
```
<div class="section" id="title-goes-here">
  <h2>Title Goes here</h2>
  <p>Some stuff here</p>
</div>
```
5. Repeat the same with a title that has _underscores_ in it, like ... a function name `my_cool_function()` 
6. Parse
7. Notice how PHPDocumentor stripped all `_` out of the title
8. Workaround that by putting your title in either single or double back quotes 
9. That avoids the underscores be stripped, but still, the HTML will be like so
```
<div class="section" id="30289u509823740589u289jwforijf9u3h298u24">
  <h2>my_cool_function()</h2>
  <p>Some stuff here</p>
</div>
```

Note how the ID became `30289u509823740589u289jwforijf9u3h298u24`?
That will now also show as such in all TOCs.
Instead of `my_cool_function()` you will get `30289u509823740589u289jwforijf9u3h298u24` as anchor title in the TOCs.

---

I tried working around this by altering the TWIG templates, but as a matter of fact, that is not related to the TWIG template, it is related to something that messes with the `_` in the parsing process. I am not sure what the purpose of this is, and how I can avoid it?
It does not generate beautiful content, and having random numbers (is it encoded somehow) in an URL is also not nice

Analysing this even further, I discovered that the encoded ID of the HTML happens only when you have backticks in the title.
But without backticks.... PHPDocumentor strips the underscores...

**Comment by smileBeda** [comment]
For anyone having this issue, I found a workaround (dirty hack?)

1. In a custom .rst generator, make sure to produce titles for your .rst file like so `thing _with _underscores`
2. Generate your RST (or if you do that manually, well, then manually make sure you use `thing _with _underscores`)
3. Alter the `guides` templates for `.../guides/toc-item.html.twig` and `.../guides/header-title.html.twig` to - using twig - remove the white spaces again:
- in the TOC item template: `{{ tocItem.title|replace({' _': '_'}) }}`
- in the header-title template: `{{ renderNode(node.value)|replace({' _': '_'}) }}`

This will make sure that:
- your TOC table links point to a human readable link (the title of the section)
- your titles in the sections show properly without `_` stripped, and no whitespace of course
-  the section ID is the title of the section instead of a number

Only caveat: You cannot wrap the title in to backticks, as that will automatically encode the section ID. But that is a welcome compromise (for me)

Hope this helps anyone.

**Comment by mvriel** [comment]
I believe @jaapio is reworking the parsing of Sections / Titles. I have pinged him to be aware of this issue and it looks similar / duplicate to https://github.com/phpDocumentor/phpDocumentor/issues/3033

**Comment by jaapio** [comment]
I created a fix for this in the future library for RST handling. it will take a while before this will land into this repo. As the split library needs to be reintegrated into this project. But this has my focus now.

**Comment by jaapio** [comment]
This issue has been fixed by the new integration. If you pick the master branch or our v3 docker tag this is solved. 

Any new release will contain this, fix.
