### ISSUE TITLE
Error parsing nullable arrays in phpdoc

### ISSUE THREAD

**Issue by hemberger** [phpDocumentor/phpDocumentor#3290]
## Expected behavior

When using the shorthand nullable type syntax (`?T`) with an array in phpdoc, e.g.:

```php
/** 
 * @param ?array<string, string> $token
 */
public function setToken(?array $token = null): void { ... }
```
I expected this to result in `array<string, string>|null`.

The shorthand nullable type syntax _does_ work for simple types (e.g. `?int` -> `int|null`), which looks like it was added in v3.0.0 (https://github.com/phpDocumentor/phpDocumentor/issues/1833).

## Actual behavior

```
Unable to parse file "test.php", an error was detected: ?array is not a collection
```

## Your environment

* Version used: 3.3.1
* Install method: downloading the release with curl
* PHP version: 8.1.7
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): 8.1.7-cli-alpine docker image
* Link to project build log: https://github.com/smrealms/smr/runs/7478051130?check_suite_focus=true

EDIT: Confirmed that this issue still exists in the dev version: `phpDocumentor vdev-master@52816d1`

**Comment by mvriel** [comment]
Last I checked the code, types in DocBlocks do not support the `?` shorthand notation. However, I'd need to dive into the TypeResolver library to get a definitive judgment there. The shorthand that you are referring to is with regards to types in signatures.

**Comment by hemberger** [comment]
Thanks for the quick response! I haven't looked at the code, but an empirical test seems to suggest that shorthand nullable type syntax in docblocks is supported for simple types.

Take for example:

```php
/**
 * @param ?int $x Test parameter
 */
function test(?int $x): void {}
```

This results in the following HTML documentation:

![image](https://user-images.githubusercontent.com/846186/180622542-62ec8fb4-074f-4173-b412-b90424fba5ee.png)

**Comment by mvriel** [comment]
Ah, thanks for clarifying that! I haven't touched that code for quite some time due to @jaapio his wonderful work :) I'll classify it as a bug to deal with. My first guess is that this would also be something in the TypeResolver library
