### ISSUE TITLE
Error parsing enum with constants

### ISSUE THREAD

**Issue by hemberger** [phpDocumentor/phpDocumentor#3291]
## Expected behavior

It is legal to define a constant inside an enum. The official PHP documentation gives a simple example of this usage:

```php
enum Size
{
    case Small;
    case Medium;
    case Large;

    public const Huge = self::Large;
}
```
(ref: https://www.php.net/manual/en/language.enumerations.constants.php)

## Actual behavior

It looks like phpDocumentor expects constants to belong only to classes or interfaces:
```
Unable to parse file "test.php", an error was detected: Expected an instance of any of "phpDocumentor\Reflection\Php\Class_", "phpDocumentor\Reflection\Php\Interface_". Got: phpDocumentor\Reflection\Php\Enum_
```

## Your environment

* Version used: phpdoc/phpdoc:latest (phpDocumentor vdev-master@52816d1)
* Install method: Docker

Thank you!

**Comment by mvriel** [comment]
The issue seems to be in https://github.com/phpDocumentor/Reflection/blob/5.x/src/phpDocumentor/Reflection/Php/Factory/ClassConstant.php#L68. In this library it is explicitly checked that the constant only belongs to those. A PR and release on that library is needed to include it in phpDocumentor

**Comment by hemberger** [comment]
Seems like a relatively simple change, thanks for investigating! Are you looking for a volunteer to make the PR? I'm happy to help, though I'd need some guidance on how you'd like it to be tested. Would a new integration test case in `tests/integration/EnumTest.php` be sufficient?

**Comment by mvriel** [comment]
All help is greatly appreciated! I am currently fixing a couple other issues and doing triage (and in all fairness, should go to bed soon 😅 ).

But indeed, a fix in the original file, the integration test and the unit test (https://github.com/phpDocumentor/Reflection/blob/5.x/tests/unit/phpDocumentor/Reflection/Php/Enum_Test.php) would be wonderful!
