### ISSUE TITLE
Aggregated types are not rendered correctly in some cases when using route()

### ISSUE THREAD

**Issue by Mai-Lapyst** [phpDocumentor/phpDocumentor#3323]
The problem occurs when wanting to render methods that have args/return types which contain a class inside an aggregated type which in turn are inside yet another type (like an array),
Example:
```
    /**
     * @param array<string|SomeOtherClass> $p
     */
    public function doSomething3($p) {}
```

## Expected behavior
That class references when using `route('class:short')` are rendered as a link to the class.

## Actual behavior
A class inside aggregated types which in turn are inside yet another type (like an array), are rendered plain as text:
![image](https://user-images.githubusercontent.com/67418776/191878375-89adca73-e244-443b-9a75-8250a5bb0f61.png)

## Steps to reproduce the problem

1. Create the project as mentioned below
2. Run `phpDocumentor.phar run -d ./test-src -t ./out --template="test-tpl"`
3. Optionally start a webserver to serve the docs (i.e. `ruby -run -ehttpd . -p8080`)
4. Open `classes/MyProject-MyKlazz.html` (relative to the output folder / webserver)

## Your environment

* Version used: vdev-master@e5bc3ef
* Install method: git clone & composer install
* PHP version: 8.1.10
* Operating system and version: Arch linux
* Link to your project: [example.zip](https://github.com/phpDocumentor/phpDocumentor/files/9630304/example.zip)

## Code
<details>
<summary>src/MyKlazz.php</summary>

```php
<?php
namespace MyProject;

class MyKlazz {
    /**
     * @param SomeOtherClass $p
     */
    public function doSomething1($p) {}

    /**
     * @param array<SomeOtherClass> $p
     */
    public function doSomething2($p) {}

    /**
     * @param array<string|SomeOtherClass> $p
     */
    public function doSomething3($p) {}
}
```
</details>
<details>
<summary>src/SomeOtherClass.php</summary>

```php
<?php
namespace MyProject;

class SomeOtherClass {

}
```
</details>
<details>
<summary>test-tpl/template.xml</summary>
    
```xml
<?xml version="1.0" encoding="utf-8"?>
<template>
    <name>test-tpl</name>
    <author>Mai Lapyst</author>
    <version>0.1.0</version>
    <copyright></copyright>
    <description></description>
    <parameters></parameters>
    <transformations>
        <transformation writer="twig" query="indexes.classes" source="class.html.twig"/>
    </transformations>
</template>
```
</details>
<details>
<summary>test-tpl/class.html.twig</summary>
    
```twig
{% macro renderType(type) %}
    {{ not type ? "mixed" : type|route('class:short')|join('|')|raw }}
{% endmacro %}

{% macro renderArgs(args) %}
    {% for arg in args %}
        {% if not loop.first %}, {% endif %}
        <span>{{ _self.renderType(arg.type) }} </span>
        <span>{{ arg.name }}</span>
    {% endfor %}
{% endmacro %}

<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <ul>
            {% for method in node.methods %}
                <li>{{ method.name }}({{ _self.renderArgs(method.arguments) }})</li>
            {% endfor %}
        </ul>
    </body>
</html>
```
</details>

**Comment by mvriel** [comment]
I was able to reproduce the issue in our example project using the following nonsensical typehint :)
```
@var array<array-key, Topping|Sauce|list<Topping>>
```

**Comment by Mai-Lapyst** [comment]
I actually have a patch laying around for this, which needs a patched version of phpdocumentor-typeresolver; Will submit both as a draft PR so you guys can take a look at it.

**Comment by mvriel** [comment]
Thanks for the PRs. I'll have a look at it this evening!

**Comment by jaapio** [comment]
This has been solved and will be part of our next release

**Comment by jaapio** [comment]
![image](https://github.com/phpDocumentor/phpDocumentor/assets/1060433/37155351-f7c7-4d4d-81f9-12dd22449192)
