### ISSUE TITLE
Declaring static properties of a class as a single block of code results in incorrect values generation

### ISSUE THREAD

**Issue by mamayadesu** [phpDocumentor/phpDocumentor#3334]
I have the next code:
```php
<?php

namespace MyNamespace;

class MyClass
{
    public static string $Prop1 = "val1", $Prop2 = "val 2", $Prop3 = "val 3";
    // ...
}
```

## Expected behavior
phpDocumentor should generate values according to their class properties, i.e.:
```
public static string $Prop1 = "val1";
```

```
public static string $Prop2 = "val 2";
```

```
public static string $Prop3 = "val 3";
```

## Actual behavior
An error occurs that all class properties that are listed in this block of code have the value of the first property of the class.
```
public static string $Prop1 = "val1";
```

```
public static string $Prop2 = "val1";
```

```
public static string $Prop3 = "val1";
```

## Steps to reproduce the problem

Described above

## Your environment

* Version used: 3.0.0-alpha1
* Install method: PHAR download
* PHP version 7.4.11
* Operating system and version Windows 10
* [Documentation page where this error occurred](http://docs.xrefcore.ru/classes/CliForms-FileSystemDialog-Dialog.html#property_LangClose)
* [Source code](https://github.com/mamayadesu/xRefCoreCompiler/blob/main/src/resources/api_en/CliForms/FileSystemDialog/Dialog.php)

**Comment by mvriel** [comment]
I have been able to reproduce this issue and trace it to a piece of our upstream Reflection library. I have created a PR and as soon as it is merged and there is a release, we can update phpDocumentor and this issue will be fixed.

See https://github.com/phpDocumentor/Reflection/pull/302

**Comment by mvriel** [comment]
I have just released a new version of phpDocumentor/Reflection and bumped the version in phpDocumentor. This means that on master the issue should be solved. If you want to try out the new version, you can check the phar artifact in build https://github.com/phpDocumentor/phpDocumentor/actions/runs/3646047873
