### ISSUE TITLE
Permalink to XSD file no longer works (404 Not found)

### ISSUE THREAD

**Issue by jrfnl** [phpDocumentor/phpDocumentor#3348]
The latest version of the PHPDoc XSD file used to always be available at https://docs.phpdoc.org/latest/phpdoc.xsd
This appears to no longer be the case.

Is there a new permalink for the XSD file ?
And could a redirect be set up from the old permalink to the new one ? Or alternatively, could the old permalink be re-activated again ?

## Expected behavior
The XSD to be present

## Actual behavior
404 Page not found

## Steps to reproduce the problem

1. Try and visit: https://docs.phpdoc.org/latest/phpdoc.xsd

## Your environment

Typically, this link would be used in the `phpdoc.dist.xml` file header, like so:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
    configVersion="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://www.phpdoc.org"
    xsi:noNamespaceSchemaLocation="https://docs.phpdoc.org/latest/phpdoc.xsd"
>
    ...
</phpdocumentor>
```

The XSD being in a predictable location is also relevant for projects which validate their XML configuration files in CI.

**Comment by mvriel** [comment]
Should be fixed in the commit that it on its way to master; I'll double check in the morning if everything is a-ok :)

**Comment by jrfnl** [comment]
Thanks @mvriel !

**Comment by mvriel** [comment]
Just got up and got to confirm it, the link to the XSD works again :)
