### ISSUE TITLE
Back-to-top arrow in guides still points to the default documentation page

### ISSUE THREAD

**Issue by michielvaneerd** [phpDocumentor/phpDocumentor#3350]
If you look at a guide page for the documentation for this project, for example https://docs.phpdoc.org/3.0/guide/getting-started/what-is-a-docblock.html and you click on the "back to top" arrow in the right bottom corner, you go to the default documentation page and not the current guide-page.

Is there a way to keep it on the current page?

**Comment by mvriel** [comment]
Nice find! I have issued a couple of PRs in the past few days where I found more of these surprises and added Cypress tests to verify it; but I think I missed this one. Surely needs to be fixed

**Comment by mvriel** [comment]
PR opened to fix the issue, it is a small fix so I will merge it as soon as the pipelines are green and I have come around to it
