### ISSUE TITLE
 Unable to parse file: Traits can only be used in class or trait

### ISSUE THREAD

**Issue by iguojun** [phpDocumentor/phpDocumentor#3360]
- PHP 8.1.12
- Laravel 9.39.0
- phpDocumentor v3.3.1

When running phpDocumentor, I got the error message:
> Unable to parse file "app/Enums/FailureRank.php", an error was detected: Traits can only be used in class or trait

But I checked the PHP Manual at https://www.php.net/manual/en/language.enumerations.traits.php,
It says:
> Enumerations may leverage traits, which will behave the same as on classes. The caveat is that traits used in an enum must not contain properties. They may only include methods and static methods. A trait with properties will result in a fatal error.

There maybe something wrong I think.

**Comment by mvriel** [comment]
There is a validation upstream in our Reflection library that causes this issue, I have made a PR for that (https://github.com/phpDocumentor/Reflection/pull/301) and once it is released we can update phpDocumentor with it and very that the information is actually rendered in the output

**Comment by mvriel** [comment]
I have just released a new version of phpDocumentor/Reflection and bumped the version in phpDocumentor. This means that on master the issue should be solved. If you want to try out the new version, you can check the phar artifact in build https://github.com/phpDocumentor/phpDocumentor/actions/runs/3646047873
