### ISSUE TITLE
HTML br Tags Handled Correctly But Show up in Error Report

### ISSUE THREAD

**Issue by oleibman** [phpDocumentor/phpDocumentor#3378]
See https://phpoffice.github.io/PhpSpreadsheet/reports/errors.html. The formatting of GammaBase (https://phpoffice.github.io/PhpSpreadsheet/classes/PhpOffice-PhpSpreadsheet-Calculation-Statistical-Distributions-GammaBase.html) is flawless. So I am left to wonder why this member shows up in the error report. Removing the `<br />` tags eliminates the error report, but, of course, causes changes in formatting. Changing to `<br>` does not eliminate the error report, nor does removing all the breaks and surrounding the lines with `<pre><\pre>`.

## Expected behavior

GammaBase should not show up in error report. No change to the actual formatting is required.

## Actual behavior

GammaBase shows up in error report.

## Steps to reproduce the problem

1. Documentation is created as part of new release. But I have also downloaded v3.0.0 to my machine and run it there with the same results.
2.
3.

## Your environment

* Version used: 3.0.0
* Install method phar
* PHP version all
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Windows 10
* Link to your project: see above
* Attach code that is involved
* ...

**Comment by mvriel** [comment]
I am investigating why it complains about the author tag, I can reproduce it locally so I hope to have results soon. 

I did notice the location of the DocBlock (https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Calculation/Statistical/Distributions/GammaBase.php#L124) is not with the function it documents but attached to the constants above it? This is not the cause of the issue, but it may cause another anomaly in your documentation, so I wanted to make you aware of it

**Comment by mvriel** [comment]
The error is correct, though there is room for improvement regarding feedback. The `@author` tag does not support a description (see: https://docs.phpdoc.org/guide/references/phpdoc/tags/author.html#author) and has strict validation on its contents. 

This means that for this to work, I recommend moving the information into the description of the DocBlock, or adding an `@link` (https://docs.phpdoc.org/guide/references/phpdoc/tags/link.html#link) tag to the source material and applying the description there.

**Comment by oleibman** [comment]
@mvriel Thank you for the feedback. I will move the DocBlock before the function, and move the information in question from the author tag to the DocBlock description.
