### ISSUE TITLE
Inherited tags should not generate errors

### ISSUE THREAD

**Issue by hschletz** [phpDocumentor/phpDocumentor#338]
To prevent duplicating docblocks for overridden methods, I just use /*\* {@inheritdoc} */ for these. This works fine (the parent's method's doc shows up in the output for the overridden method, including @param output), but for each argument an error "Argument $foo is missing from the Docblock of bar()" is generated. It would be very helpful to suppress the message for missing but inherited tags.

**Comment by xGouley** [comment]
Today with the last version 2.8.5, Error is always here...

**Comment by NicoVIII** [comment]
I think this issue is still an issue, I noticed this behaviour as well.
