### ISSUE TITLE
Links inside a note are not parsed properly

### ISSUE THREAD

**Issue by stof** [phpDocumentor/phpDocumentor#3389]
## Expected behavior

Content of the `.. note::` directive should be rendered

## Actual behavior

We see the raw rST content there.

## Steps to reproduce the problem

1. Go on https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/param.html#effects-in-phpdocumentor
2. Look at phpstan or psalm links inside the note

## Your environment

Whatever was used to build the phpdoc.org website

**Comment by stof** [comment]
Looking at the HTML, it looks like notes are treated as code blocks, which might actually be the actual bug (or a misuse of the directive in the whole documentation of the project)

**Comment by jaapio** [comment]
This issue has been fixed by the new integration. If you pick the master branch or our v3 docker tag this is solved.

Any new release will contain this, fix.
