### ISSUE TITLE
Cannot install "3.3.*" using composer.

### ISSUE THREAD

**Issue by deepeloper** [phpDocumentor/phpDocumentor#3405]
## Expected behavior
phpDocumentor will be installed.

## Steps to reproduce the problem
1. "composer.json":
```json
{
    "minimum-stability": "dev",
    "config": {
        "platform": {
            "php": "7.4"
        }
    },
    "require-dev": {
        "phpdocumentor/phpdocumentor": "3.3.*"
    }
}
```
`composer update` outputs `phpdocumentor/phpdocumentor[v3.3.0, ..., v3.3.1] require phpdocumentor/guides-markdown *@dev -> could not be found in any version, there may be a typo in the package name.`

2. "composer.json":
```json 
{
    "minimum-stability": "dev",
    "config": {
        "platform": {
            "php": "7.4"
        }
    },
    "repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/phpDocumentor/guides-markdown"
        }
    ],
    "require-dev": {
        "phpdocumentor/phpdocumentor": "3.3.*"
    }
}
```
`composer update` outputs `league/uri[6.8.0, ..., 6.x-dev] require php ^8.1 -> your php version (7.4; overridden via config.platform, actual: 7.4.33) does not satisfy that requirement.`

## Environment
* Version used: 3.3.*
* Install method: Composer 2.4.4
* PHP 7.4.33
* Operating system: Windows 10
* My project: https://github.com/deepeloper/pdo-debugging

**Comment by jaapio** [comment]
We do not recommend using composer to install phpdocumentor. If you still prefer composer have a look at https://github.com/phpDocumentor/shim
