### ISSUE TITLE
Broken link on Inline Tags page

### ISSUE THREAD

**Issue by dregad** [phpDocumentor/phpDocumentor#3416]
## Expected behavior
Working link to tags page per [doc source](https://github.com/phpDocumentor/phpDocumentor/blame/master/docs/references/phpdoc/inline-tags/index.rst#L13).

## Actual behavior
![image](https://user-images.githubusercontent.com/449891/209120728-d13b0c52-70f4-4442-8f25-8e1aadfd102f.png)

## Steps to reproduce the problem

1. Go to https://docs.phpdoc.org/3.0/guide/references/phpdoc/inline-tags/index.html

## Your environment

N/A

**Comment by jaapio** [comment]
Thanks for reporting, I pushed an update, should be resolved now.
