### ISSUE TITLE
Slew of deprecation warnings running phar version of phpdoc

### ISSUE THREAD

**Issue by dan-sherwin** [phpDocumentor/phpDocumentor#3429]
When running phpdoc, I am getting a slew of deprecation warnings, but then phpdoc runs fine.  There are no errors and it does complete the documentation run.  It just has a mess of these deprecation warnings.  Im using an example of "--help" just to simplify, but I get the warnings no matter what the parameters are.

Command:  phpDocumentor.phar --help

## Expected behavior
Display the help documentation is all

## Steps to reproduce the problem
1. Install
2. phpDocumentor.phar --help

## Your environment
phpDocumentor v3.3.1
MacBook Air M1
Ventura 13.1
PHP 8.1.8

## Actual behavior - Deprecation errors and then it runs.
PHP Deprecated:  Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/RequirementCollection.php on line 15
PHP Stack trace:
PHP   1. {main}() /Users/dsherwin/tmp/phpDocumentor.phar:0
PHP   2. require() /Users/dsherwin/tmp/phpDocumentor.phar:12
PHP   3. HumbugBox380\KevinGH\RequirementChecker\Checker::checkRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/bin/check-requirements.php:10
PHP   4. HumbugBox380\KevinGH\RequirementChecker\Checker::retrieveRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:13
PHP   5. Composer\Autoload\ClassLoader->loadClass($class = 'HumbugBox380\\KevinGH\\RequirementChecker\\RequirementCollection') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:82
PHP   6. Composer\Autoload\includeFile($file = 'phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/../../src/RequirementCollection.php') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:322
PHP   7. include() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:444

Deprecated: Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/RequirementCollection.php on line 15

Call Stack:
    0.0566   25272672   1. {main}() /Users/dsherwin/tmp/phpDocumentor.phar:0
    0.0566   25267696   2. require('phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/bin/check-requirements.php') /Users/dsherwin/tmp/phpDocumentor.phar:12
    0.0571   25349384   3. HumbugBox380\KevinGH\RequirementChecker\Checker::checkRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/bin/check-requirements.php:10
    0.0571   25349384   4. HumbugBox380\KevinGH\RequirementChecker\Checker::retrieveRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:13
    0.0571   25360880   5. Composer\Autoload\ClassLoader->loadClass($class = 'HumbugBox380\\KevinGH\\RequirementChecker\\RequirementCollection') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:82
    0.0571   25360880   6. Composer\Autoload\includeFile($file = 'phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/../../src/RequirementCollection.php') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:322
    0.0571   25367648   7. include('phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/RequirementCollection.php') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:444

PHP Deprecated:  Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/RequirementCollection.php on line 19
PHP Stack trace:
PHP   1. {main}() /Users/dsherwin/tmp/phpDocumentor.phar:0
PHP   2. require() /Users/dsherwin/tmp/phpDocumentor.phar:12
PHP   3. HumbugBox380\KevinGH\RequirementChecker\Checker::checkRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/bin/check-requirements.php:10
PHP   4. HumbugBox380\KevinGH\RequirementChecker\Checker::retrieveRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:13
PHP   5. Composer\Autoload\ClassLoader->loadClass($class = 'HumbugBox380\\KevinGH\\RequirementChecker\\RequirementCollection') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:82
PHP   6. Composer\Autoload\includeFile($file = 'phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/../../src/RequirementCollection.php') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:322
PHP   7. include() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:444

Deprecated: Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/RequirementCollection.php on line 19

Call Stack:
    0.0566   25272672   1. {main}() /Users/dsherwin/tmp/phpDocumentor.phar:0
    0.0566   25267696   2. require('phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/bin/check-requirements.php') /Users/dsherwin/tmp/phpDocumentor.phar:12
    0.0571   25349384   3. HumbugBox380\KevinGH\RequirementChecker\Checker::checkRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/bin/check-requirements.php:10
    0.0571   25349384   4. HumbugBox380\KevinGH\RequirementChecker\Checker::retrieveRequirements() phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:13
    0.0571   25360880   5. Composer\Autoload\ClassLoader->loadClass($class = 'HumbugBox380\\KevinGH\\RequirementChecker\\RequirementCollection') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/Checker.php:82
    0.0571   25360880   6. Composer\Autoload\includeFile($file = 'phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/../../src/RequirementCollection.php') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:322
    0.0571   25367648   7. include('phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/src/RequirementCollection.php') phar:///Users/dsherwin/tmp/phpDocumentor.phar/.box/vendor/composer/ClassLoader.php:444

.....(about 20-30 more of these)

Description:
  Parses and transforms the given files to a specified location

Usage:
  project:run [options]
  run

Options:
  -t, --target[=TARGET]                          Path where to store the generated output
      --cache-folder[=CACHE-FOLDER]              Path where to store the cache files
  -f, --filename[=FILENAME]                      File to parse, glob patterns are supported. Provide multiple options of this type to add
                                                 multiple files. (multiple values allowed)
  -d, --directory[=DIRECTORY]                    directory to parse, glob patterns are supported. Provide multiple options of this type to add
                                                 multiple directories. (multiple values allowed)
      --encoding[=ENCODING]                      encoding to be used to interpret source files with
      --extensions[=EXTENSIONS]                  Provide multiple options of this type to add multiple extensions. default is php (multiple values allowed)
  -i, --ignore[=IGNORE]                          File(s) and directories (relative to the source-code directory) that will be ignored. Glob patterns are supported. Add multiple options of this type of add more ignore patterns (multiple values allowed)
      --ignore-tags[=IGNORE-TAGS]                Tag that will be ignored, defaults to none. package, subpackage and ignore may not be ignored. Add multiple options of this type to ignore multiple tags. (multiple values allowed)
      --hidden                                   Use this option to tell phpDocumentor to parse files and directories that begin with a period (.), by default these are ignored
      --ignore-symlinks                          Ignore symlinks to other files or directories, default is on
  -m, --markers[=MARKERS]                        Comma-separated list of markers/tags to filter (multiple values allowed)
      --title[=TITLE]                            Sets the title for this project; default is the phpDocumentor logo
      --force                                    Forces a full build of the documentation, does not increment existing documentation
      --validate                                 Validates every processed file using PHP Lint, costs a lot of performance
      --visibility[=VISIBILITY]                  Specifies the parse visibility that should be displayed in the documentation. Add multiple options of
                                                 this type to specify multiple levels.("public,protected") (multiple values allowed)
      --defaultpackagename[=DEFAULTPACKAGENAME]  Name to use for the default package.
      --sourcecode                               Whether to include syntax highlighted source code
      --template[=TEMPLATE]                      Name of the template to use (optional) (multiple values allowed)
      --examples-dir[=EXAMPLES-DIR]              Directory to seacher for example files referenced by @example tags
  -s, --setting[=SETTING]                        Provide custom setting(s) as "key=value", run again with --list-settings for a list (multiple values allowed)
      --list-settings                            Returns a list of available settings
      --parseprivate                             Whether to parse DocBlocks marked with @internal tag
  -h, --help                                     Display help for the given command. When no command is given display help for the list command
  -q, --quiet                                    Do not output any message
  -V, --version                                  Display this application version
      --ansi|--no-ansi                           Force (or disable --no-ansi) ANSI output
  -n, --no-interaction                           Do not ask any interactive question
  -c, --config[=CONFIG]                          Location of a custom configuration file
      --log[=LOG]                                Log file to write to
  -e, --env=ENV                                  The Environment name. [default: "prod"]
      --no-debug                                 Switch off debug mode.
  -v|vv|vvv, --verbose                           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
                  phpDocumentor creates documentation from PHP source files. The simplest way
                  to use it is:

                      $ phpdoc run -d [directory to parse] -t [output directory]

                  This will parse every file ending with .php in <directory
                  to parse> and then output a HTML site containing easily readable documentation
                  in <output directory>.

                  phpDocumentor will try to look for a phpdoc.dist.xml or phpdoc.xml file in your
                  current working directory and use that to override the default settings if
                  present. In the configuration file can you specify the same settings (and
                  more) as the command line provides.

                  Other commands
                  In addition to this command phpDocumentor also supports additional commands:

                  Available commands:
                    help
                    list
                    run
                  project
                    project:run

                  You can get a more detailed listing of the commands using the list
                  command and get help by prepending the word help to the command
                  name.

**Comment by jaapio** [comment]
Thanks for reporting this, we addressed this issue in v3.4.0
