### ISSUE TITLE
How are informational pages being created?

### ISSUE THREAD

**Issue by StephanMeijer** [phpDocumentor/phpDocumentor#3455]
How are pages such as these created withing phpDocumentor?

https://docs.phpdoc.org/3.0/guide/getting-started/installing.html

**Comment by mvriel** [comment]
At the moment, the "guides" feature is still considered experimental. So please be mindful that bugs could occur.

To use this feature you need to use a configuration file. You could use the one we have for our own project as an example: https://github.com/phpDocumentor/phpDocumentor/blob/master/phpdoc.dist.xml

The most important bits there are the "guide" element (https://github.com/phpDocumentor/phpDocumentor/blob/master/phpdoc.dist.xml#L37) and that the corresponding feature flag is enabled (https://github.com/phpDocumentor/phpDocumentor/blob/master/phpdoc.dist.xml#L44).

In addition, rendering of the guides is only supported by the default template. To be honest, I have no clue what output you would get if you were to use another :)

After that, you need an `index.rst` (like this: https://github.com/phpDocumentor/phpDocumentor/blob/master/docs/index.rst) in a docs folder. phpDocumentor will start parsing that document and walk through other references documents to build the rest of the guides.

In the future we will have documentation supporting this feature. Thank you for your interest and if you run into any issues. Be sure to let us know
