### ISSUE TITLE
Semicolon in comment breaks the parser.

### ISSUE THREAD

**Issue by lance-at-pfplogistics** [phpDocumentor/phpDocumentor#3460]
This breaks...

/**
 * Export locations to a CSV file.
 *
 * @property-read   array $active_columns;
 * @property-read   string[] $dbFields      The fields we want to export.
 */
class SLP_Power_Locations_Export {}

This works...

/**
 * Export locations to a CSV file.
 *
 * @property-read   array $active_columns
 * @property-read   string[] $dbFields      The fields we want to export.
 */
class SLP_Power_Locations_Export

## Expected behavior

An errant semicolon on a property description should not crash the entire documentor run.

## Actual behavior

  5/22 [======>---------------------]  22%04:22:21 CRITICAL  [console] An error occurred while using the console. Message: "Call to a member function getFile() on null" ["exception" => Error { …},"message" => "Call to a member function getFile() on null"]

In PropertyDescriptor.php line 118:
                                               
  Call to a member function getFile() on null  

## Steps to reproduce the problem

1. Add a semicolon to a property description
2. Run the documentor tool (via Docker, but it probably happens on all installs)

## Your environment

* Version used: 3 
* Install method: Docker
* PHP version: 8
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): MacOS (latest)
* ...

**Comment by jaapio** [comment]
I can confirm this is still an issue in the current master branch. 

We need to fix this somehow.
