### ISSUE TITLE
How do I correctly define an argument of the type array and its properties?

### ISSUE THREAD

**Issue by Timbuktu1982** [phpDocumentor/phpDocumentor#3476]
Hi there,
i have not found any useful information on my question.

Situation:
```
/**
 * [Description for testFunction]
 *
 * @param   string  $argument1
 * @param   array   $options
 *
 * @return  void
 */
function testFunction(string $argument1 = "", array $options)
{
	// simple definition of defaults
	$options["property1"] = $options["property1"] ?? "defaultValueForProperty1";
	$options["property2"] = $options["property2"] ?? "defaultValueForProperty2";
	$options["property3"] = $options["property3"] ?? "defaultValueForProperty3";
}
```

**2 Questions at the Moment:** 
How i document the default for $argument1 correctly?
How i document the available properties (type, name, default, description) for $options correctly?

For the second question was my first idea (but i thinks its not working correctly):
```
/**
 * Description for testFunction
 *
 * @param   string  $argument1
 * @param   array   $options{
 *  property1:  ?string     defaultValueForProperty1    Description for defaultValueForProperty1.
 *  property2:  ?string     defaultValueForProperty2    Description for defaultValueForProperty2.
 *  property3:  ?string     defaultValueForProperty2    Description for defaultValueForProperty3.
 * }
 *
 * @return  void
 */
function testFunction(string $argument1 = "", array $options)
{
	// simple definition of defaults
	$options["property1"] = $options["property1"] ?? "defaultValueForProperty1";
	$options["property2"] = $options["property2"] ?? "defaultValueForProperty2";
	$options["property3"] = $options["property3"] ?? "defaultValueForProperty1";
}
```
Result:
![image](https://user-images.githubusercontent.com/47846931/225278271-8cff0274-4d85-4ee4-a646-0d0b358a41c5.png)

Thank you so much!

**Comment by jaapio** [comment]
What you want to define is called `ArrayShapes` 

phpDocumentor does not have support for this yet, but other tools in the eco-system are already supporting it. 
https://phpstan.org/writing-php-code/phpdoc-types#array-shapes

phpDocumentor's next version does have support for array shapes.

**Comment by Timbuktu1982** [comment]
Hi Jaapio. Thank you for your response. Have a good start in the new week...
