### ISSUE TITLE
`--ignore-symlinks=off` does not work via CLI

### ISSUE THREAD

**Issue by matzeeable** [phpDocumentor/phpDocumentor#3494]
## Expected behavior
I can follow symlinks via `phpdoc --ignore-symlinks=off`

## Steps to reproduce the problem

Run `phpdoc --ignore-symlinks=off` and getting the following error:

```
  The "--ignore-symlinks" option does not accept a value. 
```

But in `README.md` the option should be available:

https://github.com/phpDocumentor/phpDocumentor/blob/49e48dcc13532b93ac94a9323e55b0e926d3c948/docs/guides/running-phpdocumentor.rst#L100-L103

## Your environment

* Version used: v3.3.1
* Install method: `wget https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar && chmod +x phpDocumentor.phar && sudo mv phpDocumentor.phar /usr/local/bin/phpdoc`
* PHP version: `PHP 7.4.33 (cli) (built: Feb 14 2023 18:01:29) ( NTS )`
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu 20.04

**Comment by jaapio** [comment]
Thanks for reporting this, I created a PR to address this issue. 

For now, I recommend you use a configuration file, future versions will have this feature properly implemented with the new option flag `--no-ignore-symlinks`
