### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array

### ISSUE THREAD

**Issue by brunolimadevelopment** [phpDocumentor/phpDocumentor#3499]
## Expected behavior

After I have installed phpDocumentor I can use the phpdoc command to generate my documentation.

## Actual behavior

In my-project I run: vendor/bin/phpdoc -d path_of_project -t path_root_project

 PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/bruno/Desktop/server/plugin/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:170

## Steps to reproduce the problem

1. Global Instaled phpDocumentation by phive 
2. In my-project I run vendor/bin/phpdoc command

## Your environment

* Version used: 3.0.0-
* Install method: phive
* PHP version: 8.0.28
* Operating system and version: Linux PopOs
* Link to your project: https://github.com/brunolimadevelopment/server
* Attach code that is involved
* ...

**Comment by jaapio** [comment]
please update to the latest version, this has been fixed before.
