### ISSUE TITLE
Inline @see ignored in summary line

### ISSUE THREAD

**Issue by Xymph** [phpDocumentor/phpDocumentor#3501]
An inline @see in the first line of a docblock, i.e. the summary line, is not linked.

Sample cases:
https://github.com/hamstar/Wikimate/blob/master/Wikimate.php#L779 (& L786)
https://github.com/hamstar/Wikimate/blob/master/Wikimate.php#L1332

## Expected behavior
Apply the link.

Alternatively, if that is really impossible, [document](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/see.html) that inline @see cannot be used in summary line.
But that would be frustrating as I don't want to unnecessarily balloon those docblocks with a description section.

## Actual behavior
The summary line is rendered as plain text. E.g. in the above case:
`Use section indexes as keys in return array of {@see self::getAllSections()}`
`Alias of {@see WikiPage::setSection()} specifically for creating new sections.`

## Steps to reproduce the problem

phpDocumentor.phar run -v --title=Wikimate -d . -i vendor/ --sourcecode -t <path_to_my_private_site> -s graphs.enabled=true

## Your environment

* Version used: 3.3.1
* Install method: downloaded PHAR
* PHP version: 7.4+
* Operating system and version: Ubuntu 22.04
* Link to your project: https://github.com/hamstar/Wikimate

**Comment by mvriel** [comment]
The summary does not support formatting nor using inline tags, you can find the docs mentioning this here: https://docs.phpdoc.org/guide/guides/docblocks.html#summary

> Summaries are plain and simple, they cannot contain formatting or inline tags

**Comment by Xymph** [comment]
Oh, bummer. But thanks for the pointer.
