### ISSUE TITLE
URGENT: Unable to install 3.3.1 release because package dependencies

### ISSUE THREAD

**Issue by aprokopenko** [phpDocumentor/phpDocumentor#3505]
If you try to install phpdocumentor as a dependency from 3.3.1 you will get composer error:
- phpdocumentor/phpdocumentor[v3.3.1-rc, ..., v3.3.1] require league/uri ~6.3.0
- phpdocumentor/guides dev-main requires league/uri ^6.5

`phpdocumentor/guides dev-main` package has the only one branch and no tags. this is rediculous.

`phpdocumentor/phpdocumentor` is also not match the requirements, because it requires missing "json-path" package. 

My app is crashing after updating to PHP 8.1 and even if you have an update it can't be downloaded (((

## Expected behavior
I expected to download dependency by composer without any issues.

## Actual behavior
I can't install your package at all.

## Steps to reproduce the problem

1. Create new project with composer
2. Add dependency "phpdocumentor/phpdocumentor": "^3.3.1"
3. Run composer install

## Your environment

* Version used: 3.3.1, dev-master, 3.3.0, 3.2.0
* Install method: Composer dependency
* PHP version: 8.2.3
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Docker image php-fpm bullseye 8.2.3
* Link to your project: NDA

**Comment by aprokopenko** [comment]
Btw, before that the version 3.1.2 is installed with composer. I also has symfony console dependency in my composer and I don't have any deprecated warnings when I run something. When I use phar version - I have tons of deprecated messages from different packages :(

**Comment by jaapio** [comment]
Thanks for your report. 

The problem you are facing has multiple sides. First of all phpDocumentor does not support php 8.2 yet. If it works, it will throw a ton of depreciation messages. We are simply not ready yet. 

Second issue you are facing is that phpDocumentor is a application with a large number of dependencies. Thos will conflict with your code. If you want to install phpDocumentor as a composer package, please check phpDocumentor/shim. This is a phar install that will not conflict with your code.

**Comment by aprokopenko** [comment]
I managed to launch phar package with creating my own spl_autoload, which loads phar with native PHP class and then require files from phar directly on requests.
Actually 3.1.* is installed fine with composer and works under PHP 8.2 (however I scanned code without PHP 8.2 features).

Unfortunately, using the latest phpDocumentor didn't resolved my problem. We moved our application to PHP 8.2 and we use phpDocumentor classes to generate our own IDE helper files, because after that the main source code is encrypting. And one of our packages fails to read class definitions. I though 3.3.1 will works, but it doesn't too (

Btw, most of the deprecated warnings from your phar goes from outdated symfony packages (that's why I wrote my own autoloader to skip symfony packages from your phar). Maybe you can use newer versions? (Because when I install 3.1.* - composer install fresh symfony dependencies and they don't have these warnings)

Thanks for your link to `phpDocumentor/shim` - I will try that in future, when you make PHP 8.2 support.

Btw, do you have any plans about PHP 8.2?
