### ISSUE TITLE
(Guides) :php:namespace:`Some\NameSpace` generates invalid url (404)

### ISSUE THREAD

**Issue by axel37** [phpDocumentor/phpDocumentor#3513]
Using the following syntax (as shown in [the docs](https://docs.phpdoc.org/3.0/guide/hand-written-docs/references.html)) generates an invalid url :

```rst
:php:namespace:`Some\Namespace`
```

## Expected behavior

I am currently writing [hand-written documentation](https://docs.phpdoc.org/3.0/guide/hand-written-docs/index.html#hand-written-documentation) in rst files for my project. 

I need to link to a namespace, which I can access by browsing to this url : `(project root)/docs/build/namespaces/app-entity.html`

![working webpage showing auto-generated namespace documentation](https://github.com/phpDocumentor/phpDocumentor/assets/11683059/25e3f3ae-cf81-405c-b83f-0cef22fda87b)

[The docs](https://docs.phpdoc.org/3.0/guide/hand-written-docs/references.html) provide a snipped said to link to a namespace, which I use like so :

```rst
:php:namespace:`App\Entity`
```

However, the generated url is wrong : `/docs/build/classes/App-Entity.html`.

## Actual behavior

Using the code shown in the docs, **the generated url is wrong and produces a 404** :

![http error 404](https://github.com/phpDocumentor/phpDocumentor/assets/11683059/bc3bb7dd-c19d-4b9c-9187-8a7d90b00ea8)

I can spot two differences :
- Generated path points towards `/classes` when correct url is at `/namespaces`
- File name capitalization is different

*Note : No errors are produced in the terminal when generating documentation :*
```
phpDocumentor v3.3.1

Parsing files
 143/143 [============================] 100%
Applying transformations (can take a while)
 21/21 [============================] 100%
All done in 4 seconds!

```

## Steps to reproduce the problem

1. Create a hand-written rst guide
2. Follow documentation by writing `:php:namespace:` followed by some namespace in your application
3. Generate the docs and click on the generated link, which leads to a 4040

## Your environment

* Version used: 3.3.1
* Install method : phar
* PHP version : 8.1.2
* Operating system and version : Ubuntu 22.0.4.2
* Link to your project : (none, project is private)

**Comment by jaapio** [comment]
This has been fixed in v3.4
