### ISSUE TITLE
Disable application cache with `APP_CACHE_DIR` and `APP_LOG_DIR` ?

### ISSUE THREAD

**Issue by drupol** [phpDocumentor/phpDocumentor#3517]
Hello,

I'm in the process of integrating `phpDocumentor` into Nix. While a detailed explanation of how Nix functions isn't necessary for this discussion, don't hesitate to ask any questions in the thread if this is not the case, I'll be glad to answer them.

When `phpDocumentor` is installed using Nix, the files are placed into an immutable (read-only) store. This results in all files and directories of the application being read-only.

As `phpDocumentor` is a Symfony-based application, it necessitates the creation of a `var/` directory to store cache when running.

Users can modify the cache directory by altering the `APP_CACHE_DIR` environment variable, and the log directory by changing the `APP_LOG_DIR` variable.

I've attempted to run `phpDocumentor` while adjusting the location of these variables. However, it persistently defaults to using `var/`.

This make sense since it is hardcoded in [`kernel.php`](https://github.com/phpDocumentor/phpDocumentor/blob/master/src/phpDocumentor/Kernel.php#L67).

In the default Symfony [kernel](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L107), those environment variables are not ignored.

I guess adding a very simple condition should fix the issue.

## Expected behavior

The application should use `APP_CACHE_DIR` and `APP_CACHE_LOG`.

## Actual behavior

The application keeps writing in its own `var/` directory and ignore `APP_CACHE_DIR` and `APP_CACHE_LOG`.

## Steps to reproduce the problem

You can test by yourself by doing:

```
APP_CACHE_DIR=/tmp/foo/cache APP_LOG_DIR=/tmp/foo/log ./bin/phpdoc
```

## Your environment

Linux

* Version used: 3.3.1
* Install method: git clone
* PHP version: 8.1
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): NixOS 23.05

**Comment by jaapio** [comment]
Thanks for reporting this, I think it would be wise to chose a name that will not conflict with other user settings. So `PHPDOC_CACHE_DIR` and `PHPDOC_LOG_DIR` this is in line with the existing `PHPDOC_ENV` variable. 

Thanks for your contribution!

**Comment by drupol** [comment]
Right, I will fix this right now.

**Comment by drupol** [comment]
Just to clarify, APP_CACHE_DIR and APP_LOG_DIR are the environment variables specifically set for Symfony.

In my humble opinion, I have reservations about potential conflicts with other variables. Do you really think that other Symfony apps have such conflicts ?

Opting to use the default environment variables might be a wiser choice for future application upgrades. By sticking with the defaults that are already present in the higher versions of the kernel, we can minimize the complexities during upgrades and maintain closer alignment with Symfony's default configuration.

What are your thoughts on this?

**Comment by drupol** [comment]
After a discussion on Slack we came to the conclusion to use `APP_CACHE_DIR` and `APP_LOG_DIR`.
