### ISSUE TITLE
Unable to parse readonly classes

### ISSUE THREAD

**Issue by levkp** [phpDocumentor/phpDocumentor#3525]
I filed this as bug report and not feature request because the project website says "Supports the latest features that PHP has to offer."

## Expected behavior

The class in question is parsed and appears on the generated website.

## Actual behavior

When parsing TestReadonlyClass.php, I get 

`ALERT [app] Unable to parse file "Namespace/To/TestReadonlyClass.php", an error was detected: Syntax error, unexpected T_READONLY on line 12`

And the documentation in that class are not shown on the generated website.

## Steps to reproduce the problem

1. Create any readonly class, or copy mine below
2. Run phpDocumentor

## Your environment

* Version used: 3.3.1
* Install method: PHAR from website
* PHP version: 8.2.7
* Operating system and version: Ubuntu 22.04
* Link to your project: -
* Attach code that is involved: 

Here's my test class:

```php
<?php

namespace Namespace\To\TestReadonlyClass;

/**
 * Trying to document this class
 */
readonly class TestReadonlyClass { }
```

My actual readonly class has many more docblocks on class level and on attributes, but I figured that doesn't make a difference since I was receiving the same error on this test class.

**Comment by jaapio** [comment]
This will be added in the next release: https://github.com/phpDocumentor/phpDocumentor/pull/3362
