### ISSUE TITLE
The phpDocumentor directory structure generation function does not work as expected

### ISSUE THREAD

**Issue by charlesgetup** [phpDocumentor/phpDocumentor#3532]
I have added `<folder>` tag in `<version>` and `<output>` tag in `<api>`, but none of the folders are created. And the `<output>` in `<guide>` is generated in root folder, messed up with APIs. Please correct me if my understanding is wrong.

## Expected behavior

My expected directory structure should like the following,
**{root doc dir}/version/api/{api doc content}**
**{root doc dir}/version/guide/{guide doc content}**

## Actual behavior

Now the output file structure is like below.
**{root doc dir}/version/api/{api doc content}**
**{root doc dir}/version/api/guide/{guide doc content}** (guide folder is inside api and no separate api folder created.)
See more details in the problem replication.

## Steps to reproduce the problem

1. Here is my configuration.
```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor
        configVersion="3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.phpdoc.org"
        xsi:noNamespaceSchemaLocation="data/xsd/phpdoc.xsd"
>
    <title>API Document</title>
    <paths>
        <output>storage/framework/docs/php</output>
        <cache>.phpdoc</cache>
    </paths>
    <version number="1.0.0">
        <folder>1.0.0</folder> <!-- This <folder> tag is not working as expect -->
        <api>
            <source dsn=".">
                <path>.</path>
            </source>
            <output>api</output> <!-- This <output> tag is not working as expect -->
            <ignore hidden="true" symlinks="true">
                <path>tests/**/*</path>
                <path>build/**/*</path>
                <path>storage/**/*</path>
                <path>vendor/**/*</path>
            </ignore>
            <extensions>
                <extension>php</extension>
            </extensions>
            <!--ignore-tags>
                <ignore-tag>template</ignore-tag>
                <ignore-tag>template-extends</ignore-tag>
                <ignore-tag>template-implements</ignore-tag>
                <ignore-tag>extends</ignore-tag>
                <ignore-tag>implements</ignore-tag>
            </ignore-tags-->
            <default-package-name>Application</default-package-name>
        </api>
        <guide>
            <source dsn=".">
                <path>docs</path>
            </source>
            <output>guide</output> <!-- This <output> tag is not working as expect -->
        </guide>
    </version>
    <setting name="guides.enabled" value="true"/>
    <setting name="graphs.enabled" value="true"/>
    <template name="default" />
</phpdocumentor>
```
2. Run `phpDocumentor run`
3. And the API Doc content is generated directly under `storage/framework/docs/php`. No version (1.0.0) folder created, no api folder created. The guide folder is created as `storage/framework/docs/php/guide`. Now the system file structure is like below.
```
storage/framework/docs/php/{api doc content}
storage/framework/docs/php/guide/{guide doc content}
```
4. What I expected based on this configuration is as following,
```
storage/framework/docs/php/1.0.0/api/{api doc content}
storage/framework/docs/php/1.0.0/guide/{guide doc content}
```

## Your environment

- Version used: v3.3.1
- Install method: Downloaded the phar file from GitHub
- PHP version: 8.1.18
- Operating system and version (e.g. Ubuntu 20.04, Windows 10): alpine3.17 (The project has been built based on this docker image, FROM php:8.1.18-alpine3.17 AS base)
- Link to your project: Project has not launched yet.
- Attach code that is involved: 

Any help is appreciated. Thanks.

**Comment by jaapio** [comment]
Unfortunately you are fully correct. Right now the paths do not work correctly with phpDocumentor. You are getting it right that it should work this way... but the internals of phpDocumentor are not supporting this right now. We are working towards this. Guides are still in a experimental stage, so we will break them at some point to fix this behavior.  

Adding features to phpDocumentor is taking a lot of time due the age of the project. We (mostly just me) are working hard to get things done. But we have very limited time to get the full job done. 

I'm sorry for this inconvenience.

**Comment by charlesgetup** [comment]
Now I understand. Thank you for the response, @jaapio .

I will use the current file structure for now.

Thank you for sharing this great project and maintaining it.

**Comment by charlesgetup** [comment]
Now I understand. Thank you for the response, @jaapio .

I will use the current file structure for now.

Thank you for sharing this great project and maintaining it.
