### ISSUE TITLE
It is not working on my system!

### ISSUE THREAD

**Issue by ericruga** [phpDocumentor/phpDocumentor#3535]
I'm not being able to use phpDocumentor on my laptop. I'm receiving a warning and 2 errors on the output.

[v3.3.1]
PHP 8.2.8
macOs Monterey 12.3.1

iTerm:

cd /Applications/XAMPP/xamppfiles/htdocs
php phpDocumentor.phar run -d /Applications/XAMPP/xamppfiles/htdocs/ex-vehicles-phpdocumentor -t /Applications/XAMPP/xamppfiles/htdocs/mi-primer-documentor

Output:

PHP Deprecated:  Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/.box/src/RequirementCollection.php on line 15

Deprecated: Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/.box/src/RequirementCollection.php on line 15
PHP Deprecated:  Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/.box/src/RequirementCollection.php on line 19

Deprecated: Return type of HumbugBox380\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/.box/src/RequirementCollection.php on line 19
PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/ParameterBag.php on line 205

Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/ParameterBag.php on line 205
PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\ParameterBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/ParameterBag.php on line 215

Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/ParameterBag.php on line 215
PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/HeaderBag.php on line 255

Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/HeaderBag.php on line 255
PHP Deprecated:  Return type of Symfony\Component\HttpFoundation\HeaderBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/HeaderBag.php on line 265

Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/http-foundation/HeaderBag.php on line 265
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/console/Helper/HelperSet.php on line 94

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Applications/XAMPP/xamppfiles/htdocs/phpDocumentor.phar/vendor/symfony/console/Helper/HelperSet.php on line 94

<img width="898" alt="output-error" src="https://github.com/phpDocumentor/phpDocumentor/assets/104991905/8a1a4e62-d6da-49e6-bbde-fdea4e93b5b7">

**Comment by jaapio** [comment]
Please try the new release, this might help to fix these issues.
