### ISSUE TITLE
Table of content doesn't come with "deprecated" class name

### ISSUE THREAD

**Issue by gaxweb** [phpDocumentor/phpDocumentor#3543]
# Feature request

In the actual description part of deprecated items, there's a HTML class name of `-deprecated` applied, which by default comes with a CSS rule that causes the name to appear crossed-out.

I'd like that HTML class to also be applied inside the table of contents block, so I can have a line-through there as well. You don't need to ship it with the actual CSS, if you don't want to.

I'm using v3.3.1.

**Comment by jaapio** [comment]
We addressed this in the new v3.5.1 release.
