### ISSUE TITLE
Template color is not applied

### ISSUE THREAD

**Issue by gaxweb** [phpDocumentor/phpDocumentor#3544]
## Expected behavior

The colors in the default template should change.

## Actual behavior

They're still lime green.

## Steps to reproduce the problem

1. Add `template.color` setting to XML config file or as command line argument as described [in the docs](https://docs.phpdoc.org/3.0/guide/features/theming/changing-the-color.html#changing-the-color).
2. Delete previously generated files
3. Generate docs again, using the config file

## Your environment

* Version used: 3.3.1
* Install method: PHAR from Github
* PHP version: 8.2.8
* Operating system and version: Fedora 38

**Comment by jaapio** [comment]
This feature is introduced in phpdoc v3.4 as we are shipping docker images constantly the documentation was already updated before the release. 

Thanks for reaching out to us, feel free to reopen this issue when the new version does not solve the issue.
