### ISSUE TITLE
File-level docblocks sometimes get ignored

### ISSUE THREAD

**Issue by zerocrates** [phpDocumentor/phpDocumentor#355]
Given a source file like this:

``` php
/**
 * @copyright blah blah blah
 * @license blah blah blah
 */

/**
 * Class short description
 *
 * @package whatever
 */
class ...
```

DocBlox 0.18.1 complains: "No page-level DocBlock was found in file." The generated documentation doesn't contain license or copyright data for that file.

But, if I simply add a `@package` tag to the file-level docblock, there's no warning, and the data for the file appears as it should.

There's nothing in the DocBlox documentation that leads me to believe the `@package` tag is required anywhere, much less in file-level blocks. For the common one-class-per-file pattern, that extra `@package` tag is at best just a duplication of the class' package, and at worst different but irrelevant.

**Comment by ve3** [comment]
In version 3.0.0-alpha.3 seems to be not working.

https://github.com/Rundiz/simple-cache/blob/version3/src/SimpleCache.php

I cannot generate @license at file level.
Even with  this code still not.

```
<?php
/**
 * Simple Cache.
 *
 * License: MIT
 * @package SimpleCache
 * @license http://opensource.org/licenses/MIT MIT
 */


namespace Rundiz\SimpleCache;


/**
 * Rundiz SimpleCache
 * 
 * @since 3.0
 * @version 3.0 
 */
class SimpleCache
{


    const VERSION = '3.0';


}
```
