### ISSUE TITLE
Phar doesn't work after 3.3.1

### ISSUE THREAD

**Issue by hermzz** [phpDocumentor/phpDocumentor#3562]
Running the phpDocumentor phar worked fine for me up to 3.3.1 but it stopped working for 3.4.0. This cropped up initially in a gitlab pipeline, it had worked fine on Aug 15 but it stopped working Aug 16. Nothing in the pipeline environment changed between runs. I was also able to replicate the issue on my personal machine.

## Expected behavior

Running the phpDocumentor phar file should work.

```
$ curl -L https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar > phpdoc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 22.0M  100 22.0M    0     0  19.2M      0  0:00:01  0:00:01 --:--:-- 23.8M
$ chmod +x phpdoc
$ ./phpdoc
phpDocumentor v3.3.1

Parsing files
 129/129 [============================] 100%
Applying transformations (can take a while)
 4/4 [============================] 100%
All done in 1 seconds!
```

## Actual behavior

The phpDocumentor phar complains about `Failed to open stream: phar error: no directory in "phar:///[redacted]/phpdoc/bin/phpdoc"`

```
$ curl -L https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.4.0/phpDocumentor.phar > phpdoc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.4M  100 14.4M    0     0  9093k      0  0:00:01  0:00:01 --:--:-- 13.5M
$ chmod +x phpdoc
$ ./phpdoc
PHP Warning:  require(phar:///[redacted]/phpdoc/bin/phpdoc): Failed to open stream: phar error: no directory in "phar:///[redacted]/phpdoc/bin/phpdoc", must have at least phar:///[redacted]/phpdoc/bin/phpdoc/ for root directory (always use full p
ath to a new phar) in /[redacted]/phpdoc on line 10
PHP Fatal error:  Uncaught Error: Failed opening required 'phar:///[redacted]/phpdoc/bin/phpdoc' (include_path='.:') in [redacted]/phpdoc:10
Stack trace:
#0 {main}
  thrown in /[redacted]/phpdoc on line 10
```

## Steps to reproduce the problem

1. Download phar
2. Set executable flag
3. Run the phar file

## Your environment

* Version used: 3.4.0
* Install method: phar
* PHP version: 8.2.9 and 8.1.14
* Operating system and version: Arch Linux and Ubuntu 20.04.5 LTS

**Comment by jaapio** [comment]
I think the problem you are facing is caused by the fact the new release is a zipped phar file to reduce the size of the package. When I download the file using your curl command I get the same error however when I use the original file file it still works. 

It's unclear to me right now why this happens, I will investigate this.

**Comment by hermzz** [comment]
Interesting! Symlink or renaming to `phpDoc.zip` works.

**Comment by Moonomo** [comment]
> Making a symlink does work, that might help you to solve your issue with to much impact.

It isn't working on end. 🤦🏼 

My environment:
- Version used: 3.4.0
- Install method: phar
- PHP version: 7.4.0
- Operating system and version: MacOS Ventura 13.4.1
- Device: Apple MackBook Air with M1 chip 

Version  3.3.1 works just fine.

**Comment by jaapio** [comment]
Do you get an error?

**Comment by Moonomo** [comment]
@jaapio right, it's failing because of the PHP 7.4. Thanks for the confirmation.

> PhpDocumentor requires PHP 7.4 or higher to run

Looks like docs need to be updated accordingly.

**Comment by jakzal** [comment]
`phive` installation is broken in the same way.

**Comment by jaapio** [comment]
> Looks like docs need to be updated accordingly. 
Thanks I will update them. 

>phive installation is broken in the same way.
That's sad... I still haven't found an solution for this.

**Comment by jrfnl** [comment]
Another report here - this breaks automated workflows using `setup-php` to install the PHAR file (using PHP 8.1).

```
Run phpDocumentor -n
PHP Warning:  require(phar:///usr/local/bin/phpDocumentor/bin/phpdoc): Failed to open stream: phar error: no directory in "phar:///usr/local/bin/phpDocumentor/bin/phpdoc", must have at least phar:///usr/local/bin/phpDocumentor/bin/phpdoc/ for root directory (always use full path to a new phar) in /usr/local/bin/phpDocumentor on line 10

PHP Fatal error:  Uncaught Error: Failed opening required 'phar:///usr/local/bin/phpDocumentor/bin/phpdoc' (include_path='.:/usr/share/php') in /usr/local/bin/phpDocumentor:10
Stack trace:
Warning: require(phar:///usr/local/bin/phpDocumentor/bin/phpdoc): Failed to open stream: phar error: no directory in "phar:///usr/local/bin/phpDocumentor/bin/phpdoc", must have at least phar:///usr/local/bin/phpDocumentor/bin/phpdoc/ for root directory (always use full path to a new phar) in /usr/local/bin/phpDocumentor on line 10
#0 {main}

  thrown in /usr/local/bin/phpDocumentor on line 10
Fatal error: Uncaught Error: Failed opening required 'phar:///usr/local/bin/phpDocumentor/bin/phpdoc' (include_path='.:/usr/share/php') in /usr/local/bin/phpDocumentor:10
Stack trace:
#0 {main}
  thrown in /usr/local/bin/phpDocumentor on line 10
```

Source: https://github.com/PHPCSStandards/PHPCSUtils/actions/runs/5971668670/job/16201054407

**Comment by jaapio** [comment]
I finally found something... not yet the solution though... it seems to be related to the new stub file included in our phar.

**Comment by jaapio** [comment]
ok, it turns out that php's phar does not support all filenames, so I had to introduce an alias name to make sure the bootstrap works as expected. This alias is some kind of internal reference to the current phar. 

`phar://phpdocumentor.phar` is a valid file path... while `phar:://phpdoc` isn't.

**Comment by jaapio** [comment]
v3.4.1 willl be available within minutes. This should fix your issue. 

Thanks for all the reports!

**Comment by jrfnl** [comment]
@jaapio Thank you! I'll restart the workflows and will report back.

**Comment by jrfnl** [comment]
Doc generation build is passing again!

P.S.: you may want to update this sentence in the intro for the 3.4.0 release changelog to make it clear support for 8.0 has also been dropped (that's now hidden away further down in the changelog)

> General changes
>
> In this release we upgraded to Symfony 6 and PHP 7 support has been droppped completely. We added support for php 8.2.
Interally we have restructured the pipelines to prepare for multi version support in the future.

**Comment by jakzal** [comment]
I'm still getting an error with phive on Docker:

```
Notice: require(): zlib: data error in /tools/.phive/phars/phpdocumentor-3.4.1.phar on line 11

Warning: require(phar://phpdocumentor.phar/bin/phpdoc): Failed to open stream: phar error: internal corruption of phar "/tools/.phive/phars/phpdocumentor-3.4.1.phar" (actual filesize mismatch on file "bin/phpdoc") in /tools/.phive/phars/phpdocumentor-3.4.1.phar on line 11

Fatal error: Uncaught Error: Failed opening required 'phar://phpdocumentor.phar/bin/phpdoc' (include_path='.:/usr/local/lib/php') in /tools/.phive/phars/phpdocumentor-3.4.1.phar:11
Stack trace:
#0 {main}
  thrown in /tools/.phive/phars/phpdocumentor-3.4.1.phar on line 11
```

<img width="1508" alt="image" src="https://github.com/phpDocumentor/phpDocumentor/assets/190447/6ed53c3f-9266-4853-8573-9ff2a4e82861">

Interestingly, phpDocumentor works when image is being built, but not when I run it on the built image. Perhaps a docker issue.

**Comment by jaapio** [comment]
Do you have the zip extension installed in php?

**Comment by jakzal** [comment]
Yes. I'm not expecting you to look into this btw. 

Looking into the phar, most of PHP files are empty.

<img width="1013" alt="image" src="https://github.com/phpDocumentor/phpDocumentor/assets/190447/ddbe6581-4da1-46a6-8c3b-f5fa12c50503">

**Comment by jakzal** [comment]
I can reproduce the problem now.

1. Start a PHP Docker container

    ```
    docker run -it --rm jakzal/phpqa:alpine sh
    ```

2. Install phpDocumentor with phar

    ```
    phive --no-progress --home /tools/.phive install \
        --trust-gpg-keys 8AC0BAA79732DD42 phpDocumentor \
        -t /tools/.phive/tmp/f474e60df5620536af2224cbc21a1668 \
        && mv /tools/.phive/tmp/f474e60df5620536af2224cbc21a1668/* /tools/phpDocumentor
    ```

3. Run phpDocumentor (works fine)

    ```
    /tools/phpDocumentor
    ```

5. Run phpDocumentor again (phar is now corrupted)


    ```
    /tools/phpDocumentor
    ```

<img width="1896" alt="image" src="https://github.com/phpDocumentor/phpDocumentor/assets/190447/aaea8f65-a0ae-4687-ae5a-af06673ef61d">

**Comment by dharmann** [comment]
Hi@all, I'm facing a similar problem, but only the second time I run the phar. 

## My environment
* Version used: 3.4.1 
* Install method: phar
* PHP version: 8.1.2
* Operating system and version: Ubuntu Linux 22.04.3 LTS
* I've the zlib extension installed and working
* I'm running the phar as normal user. 

## Steps to reproduce the problem:
FYI: I'm working into **/tmp** directory.

1. Download phar 
   `$ wget https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.4.1/phpDocumentor.phar`
4. Set executable flag
   `$ chmod +x phpDocumentor.phar`
5. Run the phar file
   `$ ./phpDocumentor help ` (_help_ command, for instance)

After these steps. from the second time I launch the phar onwards:
 `$ ./phpDocumentor help `

I obtain the following result:
> PHP Notice:  require(): zlib: data error in /tmp/phpDocumentor.phar on line 11
> PHP Warning:  require(phar://phpdocumentor.phar/bin/phpdoc): Failed to open stream: phar error: internal corruption of phar "/tmp/phpDocumentor.phar" (actual filesize mismatch on file "bin/phpdoc") in /tmp/phpDocumentor.phar on line 11
> PHP Fatal error:  Uncaught Error: Failed opening required 'phar://phpdocumentor.phar/bin/phpdoc' (include_path='.:/usr/share/php') in /tmp/phpDocumentor.phar:11
> Stack trace:
> #0 {main}
>   thrown in /tmp/phpDocumentor.phar on line 11

Additionally I've extracted the phar before and after running it and seen that in the second extraction there are missing files. One for all `phar://phpDocumentor.phar/bin/phpdoc`

**Comment by jaapio** [comment]
I created a new issue, please continue there, as this issue was different.
