### ISSUE TITLE
First line of a docblock ("summary") does not parse inline tags

### ISSUE THREAD

**Issue by bshaffer** [phpDocumentor/phpDocumentor#3583]
When running the XML template, the first line of any docblock is considered the "summary", and is passed in as a `string`. All other parts of the docblock are considered the "description", and are passed in as a `DocBlock\Description`. 

The latter contains the bodyTemplate logic which parses tags and resolves xref paths. The former does not. 

This means that a docblock for a function like this will not resolve the `@see` reference:

```php
/**
 * This tag {@see Baz} does NOT resolve the xref.
 */
public function query()
```

...while a docblock for a function like this _will_ resolve the `@see` reference:

```php
/**
 * Query function.
 * 
 * This tag {@see Baz} will resolve the xref.
 */
public function query()
```

## Expected behavior
The first line of a function's phpdoc should still resolve tags.

## Actual behavior
The first line of a function's phpdoc does not resolve tags.

## Steps to reproduce the problem

Create the following class file and run `phpdoc` with the XML tempalte (`phpdoc --template xml`):

```php
namespace Bar;

class Foo
{
    /**
     * This tag {@see Baz} does not resolve the xref.
     *
     * But tag {@see Baz} does.
     */
    public function foo()
    {
    }
}
```
This will generate the following xml:

```xml
<docblock line="12">
    <description>This tag {@see Baz} does not resolve the xref.</description>
    <long-description>But tag {@see \Bar\Baz} does.</long-description>
</docblock>
```

Ideally, both tags would be resolved.

## Solution

This seems to be Working As Designed, given that it's rendered separately as `description` and `long-description` in the XML template, and as `DocBlock::getSummary()` and `DocBlock::getDescription()` (respectively) in `phpDocumentor\Reflection\DocBlock`. However, if it's desirable to have this render tags, we could use the existing `phpDocumentor\Reflection\DocBlock\Description` class for the "summary" as well, OR we could create our own Summary class. However, since this is used in more than just the XML templates, I am not sure the best way to proceed. This seems like behavior we'd universally want to fix, but there might be an important reason that the "summary" does not parse any tags. 

## Your environment

* Version used: 3.4.1
* Install method: docker
* PHP version: 8.2.0
* Operating system and version: MacOSX 13.5.2

**Comment by jaapio** [comment]
Thanks for your report. 

The summary is a plain text only field by design. I think I would like to keep it that way, because a lot of tools are relaying in this behavior. IDE's see the summary as a plain text value.  I don't know the origin of this implementation, but it has been as is for more than 10 years, if not longer. In an attempt to standardize docblocks this was written:

> A Summary MUST contain an abstract of the "Structural Element" defining the purpose. It is RECOMMENDED for Summaries to span a single line or at most two, but not more than that.
>
>A Summary MUST end with two sequential line breaks, unless it is the only content in the PHPDoc.
>
>If a Description is provided, then it MUST be preceded by a Summary. Otherwise the Description will be considered the Summary, until the end of the Summary is reached.

>Because a Summary is comparable to a chapter title, it is beneficial to use as little formatting as possible. As such, contrary to the Description (see next chapter), no recommendation is done to support a mark-up language. It is explicitly left up to the implementing application whether it wants to support this or not.

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#51-summary 

Our own website states:
>Summary
>
> The summary is used to give an impression of the function of the documented element. This can be used in overviews to allow the user to skim the documentation in search of the required template.

> Summaries should always end in either a full stop, or 2 consecutive new lines. If it is not closed like this then any description will be considered as part of the summary.

> Summaries shall be plain text. Unlike other text elements in DocBlocks Markdown is not supported, nor are tags.
https://docs.phpdoc.org/guide/references/phpdoc/basic-syntax.html#summary

@ashnazg can you please give your opinion on this?

**Comment by bshaffer** [comment]
Thank you for your response! This is clear then, that we should omit `{@see}` links in our summaries. One thing that is confusing to me as well is if we use absolute paths instead, this solution will also work (although it's possibly discouraged).

**Comment by jaapio** [comment]
Could you provide an example for that? I'm not understanding what you try to explain

**Comment by bshaffer** [comment]
Yes!
For the `xml` template, if you include an inline `@see` tag, it will resolve the reference in the context of the file. In other words, it resolves relative classnames to the current namespace or imported classname FQSEN. This is, AFAIK, the only thing it does. So if I just use absolute FQSENs in the summary for inline `@see` tags, I could get around this limitation.

**Comment by bshaffer** [comment]
Closing as WAD
