### ISSUE TITLE
Documentation issue in Changing the color page

### ISSUE THREAD

**Issue by Cartman34** [phpDocumentor/phpDocumentor#3584]
We could see a documentation issue accessing the page https://docs.phpdoc.org/3.0/guide/features/theming/changing-the-color.html
The code of Configuration section it out of the box.
![image](https://github.com/phpDocumentor/phpDocumentor/assets/375425/c605a61d-7b3f-4300-8169-18e7f03ddd47)

I found this reference if it could help
https://github.com/phpDocumentor/phpDocumentor/blob/8b2bec0a4f9d4989374e6dbc1bbdeee99eacbda6/docs/features/theming/changing-the-color.rst?plain=1#L26

**Comment by jaapio** [comment]
Thanks for reporting this, the issue has been solved.
