### ISSUE TITLE
Generating guides error with v3.4.2 on php 8.2

### ISSUE THREAD

**Issue by Gandhi11** [phpDocumentor/phpDocumentor#3596]
Since the version 3.4.2 we are stating to get this Fatal Error when applying transformations

```
PHP Fatal error:  Uncaught TypeError: phpDocumentor\Guides\Handlers\RenderCommand::__construct(): Argument #3 ($documentIterator) must be of type Traversable|array, League\Flysystem\Filesystem given, called in phar:///home/jenkins/workspace/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/RenderGuide.php on line 98 and defined in phar:///home/jenkins/workspace/phpDocumentor.phar/vendor/phpdocumentor/guides/src/Handlers/RenderCommand.php:17
```

## Expected behavior
No Fatal error should be triggered

## Steps to reproduce the problem

1. Download latest .phar  - `wget https://phpdoc.org/phpDocumentor.phar`
2. run `php phpDocumentor.phar --force` with guides.enabled=true

## Your environment

* Version used: 3.4.2
* Install method: .phar
* PHP version: 8.2
* Operating system and version: Ubuntu 20.04

**Comment by jaapio** [comment]
I'm sorry, I missed a file in my latest commit, was to much in a rush. 

fix is pushed I will create a new release tonight
