### ISSUE TITLE
Nested Functions Cause Parsing Error

### ISSUE THREAD

**Issue by AntumDeluge** [phpDocumentor/phpDocumentor#3599]
## Expected behavior

As PHP supports nested functions, I would expect that phpDocumentor would either ignore or be able to parse & document them.

## Actual behavior

Error message `Unable to parse file "test.php", an error was detected: Expected an instance of phpDocumentor\Reflection\Php\File. Got: phpDocumentor\Reflection\Php\Function_` & file is not documented.

## Steps to reproduce the problem

1. Create a PHP script with a global function or class method containing a nested function
2. Execute phpDocumentor on script
3. Check output for error

## Your environment

* Version used: 3.4.3
* Install method: [.phar download](https://www.phpdoc.org/phpDocumentor.phar), chmod & rename to "phpdoc"
* PHP version: 8.1.2
* Operating system and version: Ubuntu 22.04.3
* Attach code that is involved

Global function without nested function example (`test.php`):
```php
<?php

function foo() {
  echo "Hello";
}

?>
```

Result:
```
$ phpdoc run -f test.php
phpDocumentor v3.4.3

Parsing files
 1/1 [============================] 100%
Applying transformations (can take a while)

All done in 1 seconds!
```

Global function with nested function example (`test.php`):
```php
<?php

function foo() {
  echo "Hello";
  function bar() {
    echo " world!";
  }
}

?>
```

Result:
```
$ phpdoc run -f test.php
phpDocumentor v3.4.3

Parsing files
 1/1 [============================] 100%[alert]   Unable to parse file "test.php", an error was detected: Expected an instance of phpDocumentor\Reflection\Php\File. Got: phpDocumentor\Reflection\Php\Function_                                                                                                                                                                              

Applying transformations (can take a while)

All done in 0 seconds!
```

Class method with nested function example (`test.php`):
```php
<?php

class Foo {
  public function foo() {
    echo "Hello";
    function bar() {
      echo " world!";
    }
  }
}

?>
```

Result:
```
$ phpdoc run -f test.php
phpDocumentor v3.4.3

Parsing files
 1/1 [============================] 100%[alert]   Unable to parse file "test.php", an error was detected: Expected an instance of phpDocumentor\Reflection\Php\File. Got: phpDocumentor\Reflection\Php\Method                                                                                                                                                                                 

Applying transformations (can take a while)

All done in 0 seconds!
```

**Comment by jaapio** [comment]
This is a known issue, and already fixed, but there is no phar release available yet. 

I'm working on some other bugfixes before I will create a new release. 

See: https://github.com/phpDocumentor/phpDocumentor/issues/3310
