### ISSUE TITLE
Unexpected package `Application`

### ISSUE THREAD

**Issue by smileBeda** [phpDocumentor/phpDocumentor#3605]
I am getting an unexpected package named `Application`, which of course has zero entries, and scanning my code I def. do never use `@package Application`
Also I found no empty `@package`

Why would the `Application` appear? The only ever file in my app where the word per se appears is the `license.txt`

**Comment by jaapio** [comment]
phpDocumentor is automatically creating a default package named `Application`, if it's empty this is a bug that we should address. There is a feature request somewhere to disable this behavior. We didn't implement this yet. 

If you want to remove the packages from the menu you can overwrite the template for this. 
Please read the docs about this feature: https://docs.phpdoc.org/guide/features/theming/custom-styling.html#replacing-whole-objects-or-components

The template to change is: https://github.com/phpDocumentor/phpDocumentor/blob/master/data/templates/default/components/sidebar.html.twig

**Comment by smileBeda** [comment]
@jaapio I think I resolved it by doing the following:

1. In the config, define a default package name that _matches the topmost package name of your code_. So if for example the code uses package like `MyPack\Subpack`, then pass this in config: `<default-package-name>MyPack</default-package-name>`
2. Make sure _all_ of your code uses the `MyPack` top package (it may use sub package of course). If any code (example: composer autoloader) does not use any, or another package name then exclude it (well I hope people do that anyway in the case of autoloader...) it from the generation with then `ignore` attribute.

That resolved the issue for me. No more `Application` package is generated and the `MyPack` includes as expected all the contents of the application.

I think this can be closed, assuming mis-usage on my end at the begin.
