### ISSUE TITLE
Guide for running phpDocumentor includes wrong examples

### ISSUE THREAD

**Issue by SamsonQuitt** [phpDocumentor/phpDocumentor#3617]
Provided Example in Page "running phpDocumentor" misses a "run"

## Expected behavior
I can use the provided examples in the page because they are correct.

## Actual behavior
The provided examples miss the "run" right after calling phpdoc. This example won't work unless you define a corresponding alias, which is not covered this way in installation.

## Steps to reproduce the problem

1. Go to url: https://docs.phpdoc.org/guide/guides/running-phpdocumentor.html
2. Look at example
3. Example ist wrong

**Comment by neoacevedo** [comment]
I agree. If you run the command as is in the page, you will get an error saying `command "./src" is not defined`.

**Comment by IncubuzzCC** [comment]
It took me a while to figure out that same issue.
What you do is add **`run`** before your options:
`phpdoc run -d path/to/my/project -f path/to/an/additional/file -t path/to/my/output/folder`
I hope this helps...

**Comment by jaapio** [comment]
This will be solved in our next release. We turned phpdoc into a single command application and updated the docs according to that.
