### ISSUE TITLE
PhpDocumentor creating in pdf

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [phpDocumentor/phpDocumentor#3623]
Hi Team,

I have installed php documentor, version im using is phpDocumentor version v2.9.0

php documentor creating in .html file, but i wanted to create in Pdf file for the customer use

i have used some commands but not working => phpdoc -o PDF:default:default -t ./docs -d ./ (not worked)

Can anyone suggest me, how to create php documentor in .pdf file?

Thanks in advance

**Comment by jaapio** [comment]
Hi,

Thanks for your request, phpDocumentor cannot generate PFD files, and I don't think we can ever support that the html we are creating has a complex format that doesn't translate to pdf.

A community contribution would be accepted to - introduce a single page html file template. However I think you will soon hit limitations at memory levels with this.

**Comment by Thejaswini-Rao-U** [comment]
@jaapio , Thanks for the response.

**Comment by Thejaswini-Rao-U** [comment]
@jaapio , Apart from HTML is there any other file type supported for generating php document/manual?

**Comment by jaapio** [comment]
We do support xml, and html
