### ISSUE TITLE
Doesn't document the right inherited method 

### ISSUE THREAD

**Issue by adriendupuis** [phpDocumentor/phpDocumentor#3633]
When there is some cascaded inheritances, the final class might not have the right method signatures.

## Expected behavior

In a cascade of inheritances, when an intermediate class override a base class method, the final class should have the last override in its documentation. 

## Actual behavior

Actually, the final class have an incorrect documentation pretending that it still inherits the base method.

## Steps to reproduce the problem

1. Create three classes into an empty directory in respectively BaseClass.php, InterClass.php and FinalClass.php
  ```php
  <?php
  class BaseClass {
      public function __construct($a)
      {
      }
  }
  ```
  ```php
  <?php
  abstract class InterClass extends BaseClass {
      public function __construct($a, $b)
      {
      }
  }
  ```
  ```php
  <?php
  final class FinalClass extends InterClass {
  }
  ```  
3. Generate documentation:
```shell
curl -LO "https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.4.3/phpDocumentor.phar";
php phpDocumentor.phar;
```
4. Open the documentation index `.phpdoc/build/index.html` in a browser and navigate to `FinalClass` doc page (`.phpdoc/build/classes/FinalClass.html`).
5. Notice that the documented `__construct` is the one from `BaseClass` instead of the one from `InterClass`, the signature is incomplete and a mandatory argument is missing. Trying to use it according to this doc will lead to a "PHP Warning:  Uncaught ArgumentCountError: Too few arguments to function MiddleClass::__construct()".
6. Click on the `__construct` link and notice that it ends on `.phpdoc/build/classes/BaseClass.html#method___construct`.

## Your environment

- macOS Ventura 13.2.1 (22D68)
- PHP 8.2.11 (cli) (built: Sep 28 2023 16:20:53) (NTS)
- phpDocumentor 3.4.3

**Comment by jaapio** [comment]
Thanks for your report, I pushed a fix and it will be available in the next build of our docker image. If you are not using docker it will be part of the next release. 

Your detailed report really helped to find the issue to thank you very much for that!

**Comment by adriendupuis** [comment]
Hi @jaapio
Do you know when a new release will be tagged, and its phar available on https://github.com/phpDocumentor/phpDocumentor/releases?

**Comment by jaapio** [comment]
I was planning to do that after this issue was closed but another urgent bug popped up, that needs to be solved before I can do a new release. I still hope I will be able to do that before the end of this month. But I'm a bit depending on others here .
