### ISSUE TITLE
Xdebug has detected a possible infinite loop - problem with latest, not with 3.4.1

### ISSUE THREAD

**Issue by oleibman** [phpDocumentor/phpDocumentor#3642]
We issued a new release and the documentation was generated without a problem. I believe the install used phpDocumentor 3.4.1 to generate the documentation. I realized that my local version was long out of date, so I downloaded the latest phar version (3.4.3), and this did report a problem (so the problem seems to have been introduced by 3.4.2 or 3.4.3):
```
[alert]   Unable to parse file "PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/FunctionPrefix.php", an error was detected: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
```

## Expected behavior
Produce documentation for all members including FunctionPrefix.php.

## Actual behavior
Documentation is produced for all members except FunctionPrefix.php, which instead outputs the error message above.

## Steps to reproduce the problem

1. php phpDocumentor.phar run -d PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/FunctionPrefix.php -t docs
2.
3.

## Your environment

* Version used: 3.4.3
* Install method: Download phar from your releases page
* PHP version 8.1.26
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Windows 11
* Link to your project: https://github.com/PHPOffice/PhpSpreadsheet
* Attach code that is involved
* ...
[FunctionPrefix.zip](https://github.com/phpDocumentor/phpDocumentor/files/14059131/FunctionPrefix.zip)

**Comment by jaapio** [comment]
We moved away from a cached service container because we are working on support for extensions. I expect this is the causing the issue. 

Raising the value on xdebug will solve this issue as the service container has more nesting than 256 layers.

**Comment by oleibman** [comment]
Sorry to be obtuse - raising what value on xdebug?

**Comment by jaapio** [comment]
https://xdebug.org/docs/all_settings#max_nesting_level 

This is most-likely causing the issue/

**Comment by oleibman** [comment]
Thank you. Before I had received your reply, I tried `php -d xdebug.mode=off ...`, and that eliminated the error. This was needed locally for 3.4.3, but also for 3.4.1 (so my initial report that 3.4.1 was okay was wrong). I will keep your suggestion on nesting level in mind, but, for now, this will do.
