### ISSUE TITLE
Twig v3 support?

### ISSUE THREAD

**Issue by scottw-finao** [phpDocumentor/phpDocumentor#3673]
I'm trying to use opencart v4.0.x and it requires twig v3.3.7 or greater.  This means that out-of-the-gate there is a conflict between phpdocumentor used by many parts of opencart and twig in the opencart storage folder.  I'm not entirely sure how they get around this to create the storage directory and populate the vendor directory within it, but if you try to update/add/modify the composer requirements in storage, it breaks. Hell, if you try to just do a composer update it breaks!

This seems to be because phpdocumentor v3.3.1 used by opencart wants twig 2.0 - 2.16.  I tried seeing if I could update phpdocumentor but then it breaks because it can't find the json-path library anywhere which appears to be included in your composer.json file as a requirement.

**Comment by jaapio** [comment]
Please try to install https://github.com/phpDocumentor/shim this will prevent you from conflicts with outdated libraries in phpDocumentor.

**Comment by scottw-finao** [comment]
This seems to resolve the issue but in opencart, I ended up replacing the require line in composer.json for phpdocumentor with your shim file. So far things seem to be working.
