### ISSUE TITLE
feat: render readthedocs flyout menu for default theme

### ISSUE THREAD

**Issue by jkowalleck** [phpDocumentor/phpDocumentor#3684]
# Template issue/request

## Search Terms

- readthedocs
- rtfd
- readthedocs-embed-flyout

## Problem

When rendering the docs and publishing them to https://readthedocs.com
I don't have usual "flyout menu" visible, or it is rendered incorrectly.

read the details here: https://docs.readthedocs.io/en/stable/flyout-menu.html

dummy project:
- https://github.com/jkowalleck/testing_rtfd/tree/push-prerendered
- rendered as https://jkowalleck-testing-rtfd.readthedocs.io/en/push-prerendered/

## Suggested Solution

Add the needed functionality and styling to the default theme, so the readthedocs menu may be rendered.
Maybe hide the functionality behind an environment variable `READTHEDOCS` -- see https://docs.readthedocs.io/en/stable/reference/environment-variables.html#environment-variable-reference

**Comment by jaapio** [comment]
We do support customizations in our templates via https://docs.phpdoc.org/guide/features/theming/custom-styling.html#replacing-whole-objects-or-components 

I do not see why we would add a special feature for this as the content is really project specific. So I don't think this should be part of phpDocumentor.
