### ISSUE TITLE
Specify PHIVE install GPG keys

### ISSUE THREAD

**Issue by fulldecent** [phpDocumentor/phpDocumentor#3694]
Currently documentation here recommends to install using PHIVE:

https://github.com/phpDocumentor/phpDocumentor/blob/919d5c1ef42a3c74d050e05ce99add6efa87b5a4/README.md?plain=1#L79

And our recommended command is:

https://github.com/phpDocumentor/phpDocumentor/blob/919d5c1ef42a3c74d050e05ce99add6efa87b5a4/README.md?plain=1#L86

PHIVE supports to specify a GPG for security:

https://github.com/phar-io/phive/blob/10e5602f8d8c964bf48bb5c369da8e131c0ab5ae/src/commands/help/help.md?plain=1#L30-L31

I suppose that always using that `--trust-gpg-keys` is best practice. So this issue is to update our documented PHIVE recommended install invocation to include the `--trust-gpg-keys` argument.

And this may require signing the releases of phpDocumentator, whould should be a good thing.

**Comment by jaapio** [comment]
We do ship php documentor with a signature: https://github.com/phpDocumentor/phpDocumentor/releases/tag/v3.4.3 but it has been to long ago for me to remember exactly how this was done :-( 

Besides that since the moment we wrote about phive, I also created: https://github.com/phpDocumentor/shim 
which is a composer package using the signature to verify the downloaded phar. Mayby this helps you a bit?

**Comment by fulldecent** [comment]
Thank you. I have gotten it to install with this key:

8AC0BAA79732DD42

Source: https://github.com/fulldecent/phpdoc/actions/runs/8652882245/workflow#L70

Is that official or a MITM key?

**Comment by jaapio** [comment]
Yes, you can find our public key here: https://keys.openpgp.org/search?q=info%40phpdoc.org

or fetch it with `gpg --recv-key 8AC0BAA79732DD42 `  This will add the key to your trusted keys to phive can validate.

**Comment by fulldecent** [comment]
Thank you, got it.

Added improved install instruction at https://github.com/phpDocumentor/phpDocumentor/pull/3699

**Comment by alexkuc** [comment]
@jaapio 

While `README.md` was updated, the website with the documentation was not.

https://docs.phpdoc.org/3.0/guide/getting-started/installing.html#installation

If you scroll to phive installation it does _not_ mention public key to use.
