### ISSUE TITLE
Doesn't document the right inherited method

### ISSUE THREAD

**Issue by smaddock** [phpDocumentor/phpDocumentor#3706]
Follow-up to #3633. Commit 635e8d3c broke inheritance in a new way.

## Expected behavior
Child class methods should override parent class methods that they inherit in the documentation.

## Actual behavior
Documentation is inconsistent in which class method is documented.

## Steps to reproduce the problem

Follow the same steps in #3633:

- BaseClass is documented correctly
- InterClass is documented correctly
- FinalClass should show InterClass documentation, but shows BaseClass

Now follow the same steps in #3633, but run phpDocumentor/bin/phpdoc from commit 635e8d3c.

- BaseClass is documented correctly
- InterClass should show its own documentation, but shows BaseClass
- FinalClass is documented correctly

Modify FinalClass.php to be:
```php
<?php
final class FinalClass extends InterClass {
    public function __construct($a, $b, $c)
    {
    }
}
```

Using release v3.4.3:

- BaseClass is documented correctly
- InterClass is documented correctly
- FinalClass is documented correctly

Using commit 635e8d3c:

- BaseClass is documented correctly
- InterClass should show its own documentation, but shows BaseClass
- FinalClass should show its own documentation, but shows InterClass

## Your environment

- macOS Sonoma 14.4.1 (23E224)
- PHP 8.3.6 (cli) (built: Apr 10 2024 14:21:20) (NTS)
- phpDocumentor master+635e8d3

**Comment by jaapio** [comment]
Thanks for this report, it was really helpful when debugging this issue.
