### ISSUE TITLE
Version 3.5.0 fails with "No arguments expected, got 'run'"

### ISSUE THREAD

**Issue by mrbase** [phpDocumentor/phpDocumentor#3725]
Just downloaded the latest phar package and tried to generate our docs with the new version.

We run it with the `-d` and `-t` switches.

```bash
php8.2 phpDocumentor.phar run -d /path/to/source -t /path/to/target
```

Results in:

`No arguments expected, got "run".`

## Steps to reproduce the problem

1. Download latest phar `wget https://phpdoc.org/phpDocumentor.phar`
2. Run

## Your environment

* Version used: 3.5.0
* Install method: phar, downloaded from phpdoc.org
* PHP version: 8.2
* Operating system: Ubuntu 22.04.4

**Comment by jaapio** [comment]
Thanks for your report, you can omit the run command as a workaround. 

We need to have a look at how to solve this regression.

**Comment by mrbase** [comment]
Tried without `run` and it works fine - only thing now is a PHP Warning.

```
PHP Warning: Array to string conversion in phar:///phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig/LinkRenderer/CallableAdapter.php on line 64
```
