### ISSUE TITLE
Add syntax for typing tuples in `@return array` values

### ISSUE THREAD

**Issue by matronator** [phpDocumentor/phpDocumentor#3727]
# Feature request

If a function or method returns a tuple (i.e.: `return [$value, $other]`) there's currently no way (to my knowledge) to specify that in the `@return` tag. Please add a support for typing out tuples. It might look something like this for example:

```php
/**
 * @return array<int, string>
**/
function hello(): array
```

**Comment by jaapio** [comment]
I think you can solve this by using array shapes.

https://blog.jetbrains.com/phpstorm/2022/02/phpstorm-2022-1-eap-3/

**Comment by matronator** [comment]
Not using PHPStorm, but VSCode.

**Comment by jaapio** [comment]
Array shapes are not invented by phpstorm, but they were introduced by psalm a static analyzer. Today they are supported by many other tools like phpDocumentor. 
 
I don't know about vs-code but they should add support for it,  as it will not go away any more.
