### ISSUE TITLE
 how i can create uml with plantum

### ISSUE THREAD

**Issue by vahidalvandi** [phpDocumentor/phpDocumentor#3730]
i cant send this question in discussions . how i can create uml with plantum ?

**Comment by jaapio** [comment]
My first question is why you cannot post this question in discussions? Is it not working for you?

To answer your question, as far as I get it. We do support plantuml diagrams in our guides documents.  Like here: https://github.com/phpDocumentor/phpDocumentor/blob/master/docs/internals/flow.rst#introduction 

Right now we do not support uml in docblocks.

**Comment by vahidalvandi** [comment]
No I can't sent question

**Comment by jaapio** [comment]
I provided an example, didn't get any other responses. So I think this was clear
