### ISSUE TITLE
Document the `@final` annotation

### ISSUE THREAD

**Issue by nicolas-grekas** [phpDocumentor/phpDocumentor#3737]
In Symfony, we use this annotation quite extensively - and Doctrine does also.

There are two use cases :
- when used without any comment, this is done to express that the class is final, but this final is intentionally not enforced so that technical use cases can still extend the class (think lazy proxies, like EntityManager's class)
- when used with a comment it reads as `@final since Symfony 6.4`, and obviously this means "don't extend me, I'm final, but for BC you can still extend me until the next major"

It'd be great to document these practice outside of the Symfony ecosystem. I think this use of `@final` is addressing a generic problem.

**Comment by jaapio** [comment]
@nicolas-grekas I added a proposal for the description of this tag. I would like to invite you to leave any comments in the pr if you want to improve the text to clarify somethings.

**Comment by jaapio** [comment]
@ashnazg do you think we should add a pr for this on PSR-19?
