### ISSUE TITLE
Unclosed anchors in properties sidebar

### ISSUE THREAD

**Issue by Xymph** [phpDocumentor/phpDocumentor#3741]
In the properties section of a class sidebar, `<a href...>` elements are left open.

## Expected behavior

Close `<a>` elements correctly.
Entries in the constants and methods sections are already closed.

## Actual behavior

Source code excerpt:
```
<li class="phpdocumentor-on-this-page-section__title">Properties</li>
                <li>
                    <ul class="phpdocumentor-list -clean">
                                                    <li class=""><a href="classes/Wikimate.html#property_api">$api</li>
                                                    <li class=""><a href="classes/Wikimate.html#property_data">$data</li>
[...]
                                            </ul>
                </li>
```

In v3.5.0 between the property and the `</li>`, there was another unclosed `<a href>`. Removing that was good, a closing `</a>` is better. :)

## Your environment

* Version used: 3.5.2
* Install method: downloaded PHAR
* PHP version: 8.3
* Operating system and version: Ubuntu 22.04
* Link to your project: https://github.com/hamstar/Wikimate

**Comment by jrfnl** [comment]
Came here to report the same ;-) (and some more, but that's one off my list)

**Comment by jaapio** [comment]
Thanks for raising this issue, it will be part of our next release and is directly fixed in our docker image.

**Comment by jrfnl** [comment]
Thanks @jaapio!
