### ISSUE TITLE
Images in guides broken

### ISSUE THREAD

**Issue by dmjohnsson23** [phpDocumentor/phpDocumentor#3746]
When generating a guide, any images included in the guide have an invalid link, and do not display correctly in the rendered HTML.

## Steps to reproduce the problem

I have the following directory structure (cut down to the relevant bits for brevity):
```
+-- docs
    +-- manual
        +-- framework
            +-- index.rst
            +-- forms.rst
            +-- form_flowchart.png
```

`forms.rst` contains the following block:

```rst
.. figure:: form_flowchart.png
    
    Forms flowchart
```

Which results in the following HTML being rendered on `/guide/framework/forms.html`:

```html
<figure>
    <img src="guide/guide/docs/manual/framework/form_flowchart.png">
    <figcaption>
        <p>Forms flowchart</p>
    </figcaption>
</figure>
```
The link is not valid. However, if I manually edit the image source to `"guide/docs/manual/framework/form_flowchart.png"` (removing the duplicate "guide/") the image displays as expected.

## Your environment

* Version used: v3.5.2
* Install method: phar
* PHP version: PHP 8.1.28
* Operating system and version: Ubuntu 22.04.4 LTS

**Comment by jaapio** [comment]
Thanks for reporting this, this is definitely a bug that we need to address

**Comment by jaapio** [comment]
I pushed a fix for this issue. Once this final checks by our pipelines are done I will create a release.
