### ISSUE TITLE
Guides : Large code-blocks create horizontal overflow

### ISSUE THREAD

**Issue by axel37** [phpDocumentor/phpDocumentor#3748]
## Expected behavior

Code blocks with long lines should be scrollable (= scrollbar inside the code block).

For instance, Github's code block are scrollable :

```rst
.. code-block:: bash
    curl "https://some-very-long-url-that-might-be-too-large-to-display-all-at-once.com/github-makes-it-scrollable-without-overflowing-the-whole-page"
```

## Actual behavior

When the code block's content are too large to fit on the screen, the whole page overflows horizontally.

Here's an example from the [official phpDocumentor documentation](https://docs.phpdoc.org/3.0/guide/references/configuration.html) : as shown in the following screenshot, you can't see the whole page unless you scroll to the right.

![A documentation page with an horizontal scrollbar, revealing that some content is hidden](https://github.com/user-attachments/assets/b405886c-1c8a-4ce2-8efa-7107eae4a2d8)

## Steps to reproduce the problem

1. Inside a guide  (`.rst` file), create `.. code-block::` containing long lines
2. Observe the generated page that overflows horizontally

## Your environment

* Version used : `phpDocumentor 3.4.2-v3.5.2+1876139`
* Install method : **Docker** (`docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3`)
* PHP version : *Bundled in docker image ?*
* Operating system and version : Fedora 40 (GNU/Linux)
* Link to your project : None / Private

**Comment by jaapio** [comment]
Thanks for your report, this will be fixed in our unstable docker image and part of a next release.
