### ISSUE TITLE
Fatal Error, Applying Transforms

### ISSUE THREAD

**Issue by ecsproull** [phpDocumentor/phpDocumentor#3749]
Warning: I'm not totally new to Linux but might as well be. It's been about 25 years since I used it last.

Setup, I'm running $ php phpDocumentor.phar run -d /mnt/c/SignUps -t docs/signups -c /mnt/c/SignUps/phpdoc.dist.xml from WSL. I've tested my setup on a smaller project, and it worked fine. For this project I've tried it with and without a phpdoc.dist.xml and continue to get the same error.

PHP 8.1.2-1ubuntu2.18 (cli) (built: Jun 14 2024 15:52:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.18, Copyright (c), by Zend Technologies

phardoc.dist.xml
        ```
 <?xml version="1.0" encoding="UTF-8" ?>
        <phpdocumentor
                configVersion="3"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns="https://www.phpdoc.org"
                xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/phpDocumentor/phpDocumentor/master/data/xsd/phpdoc.xsd">
            <paths>
                <output>build/api</output>
                <cache>build/cache</cache>
            </paths>
            <version number="3.0.0">
                <api>
                    <source dsn=".">
                        <path>class-signupsplugin.php</path>
                        <path>includes/*</path>
                    </source>
                </api>
            </version>
        </phpdocumentor>
```

I also tried limiting it to just the one file by omitting the includes path, but it still parses 132 files. That is a different problem but if you can tell me how to limit the project there is a possibility I could narrow down the problem.

Any tips on how to debug this issue would be greatly appreciated. Can something like xDebug be ran on this package? Is there a debug mode or error file that I've failed to find?

Parsing files
 132/132 [============================] 100%
Applying transformations (can take a while)
PHP Fatal error:  Uncaught ValueError: The arguments array must contain 2 items, 0 given in phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig/Extension.php:450
Stack trace:
#0 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig/Extension.php(450): vsprintf()
#1 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(40): phpDocumentor\Transformer\Writer\Twig\Extension->renderDescription()
#2 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2dfc749d42f5f65cddf225cb4cf55302->doDisplay()
#3 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#4 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#5 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Extension/CoreExtension.php(1290): Twig\Template->render()
#6 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(149): twig_include()
#7 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ecd76b7d67ab727fd060ee5e46c8954f->doDisplay()
#8 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#9 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#10 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Extension/CoreExtension.php(1290): Twig\Template->render()
#11 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(120): twig_include()
#12 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d92af64a8ee5b66f40775efab0885802->doDisplay()
#13 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#14 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(72): Twig\Template->display()
#15 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0c5d4433b3bfc1b154a84202c7a979bc->doDisplay()
#16 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#17 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#18 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Extension/CoreExtension.php(1290): Twig\Template->render()
#19 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(74): twig_include()
#20 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(182): __TwigTemplate_c9d52ecb24933977c2e30c22d6d0d3bc->block_content()
#21 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(90): Twig\Template->displayBlock()
#22 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8a84e69f1b4208748647d836549fd7e1->doDisplay()
#23 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#24 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(41): Twig\Template->display()
#25 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_85f5475fd71ba65d38be6f4b251b45e1->doDisplay()
#26 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#27 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(43): Twig\Template->display()
#28 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c9d52ecb24933977c2e30c22d6d0d3bc->doDisplay()
#29 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#30 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#31 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#32 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#33 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig.php(249): Twig\Environment->render()
#34 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig.php(212): phpDocumentor\Transformer\Writer\Twig->transformNode()
#35 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig.php(165): phpDocumentor\Transformer\Writer\Twig->transformNodeCollection()
#36 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Transformer.php(235): phpDocumentor\Transformer\Writer\Twig->transform()
#37 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Transformer.php(199): phpDocumentor\Transformer\Transformer->applyTransformation()
#38 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Transformer.php(124): phpDocumentor\Transformer\Transformer->transform()
#39 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/Transform.php(94): phpDocumentor\Transformer\Transformer->execute()
#40 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/TimedStageDecorator.php(40): phpDocumentor\Pipeline\Stage\Transform->__invoke()
#41 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php(11): phpDocumentor\Pipeline\Stage\TimedStageDecorator->__invoke()
#42 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(34): League\Pipeline\FingersCrossedProcessor->process()
#43 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(39): League\Pipeline\Pipeline->process()
#44 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Pipeline/Stage/TimedStageDecorator.php(40): League\Pipeline\Pipeline->__invoke()
#45 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/league/pipeline/src/FingersCrossedProcessor.php(11): phpDocumentor\Pipeline\Stage\TimedStageDecorator->__invoke()
#46 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(34): League\Pipeline\FingersCrossedProcessor->process()
#47 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/league/pipeline/src/Pipeline.php(39): League\Pipeline\Pipeline->process()
#48 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Console/Command/Project/RunCommand.php(273): League\Pipeline\Pipeline->__invoke()
#49 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/symfony/console/Command/Command.php(326): phpDocumentor\Console\Command\Project\RunCommand->execute()
#50 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#51 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#52 phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Console/Application.php(78): Symfony\Component\Console\Application->doRun()
#53 phar:///home/ecsproull/phive/phpDocumentor.phar/vendor/symfony/console/Application.php(175): phpDocumentor\Console\Application->doRun()
#54 phar:///home/ecsproull/phive/phpDocumentor.phar/bin/phpdoc(13): Symfony\Component\Console\Application->run()
#55 /home/ecsproull/phive/phpDocumentor.phar(11): require('...')
#56 {main}
  thrown in phar:///home/ecsproull/phive/phpDocumentor.phar/src/phpDocumentor/Transformer/Writer/Twig/Extension.php on line 450

**Comment by ecsproull** [comment]
I used the -v to see that the entire directory including the Vendor directory was being parsed. Then I realized that I was using a config file but still providing a root directory on the command line. I removed that and also removed the output directory from the command line and just used the phpdoc.dist.xml config file. Once it was just aimed at the code I cared about it worked great!

Trimming it to: php phpDocumentor.phar run -c /mnt/c/SignUps/phpdoc.dist.xml was all that was needed. Really awesome tool!

**Comment by jaapio** [comment]
Thanks for reaching out. This error has been reported before and we tried to solve it. In most cases it's very hard to find the cause. It's mostly and invalid docblock or some obscure definition that isn't supported somewhere in your vendor directory. I will wait for a report that gives me a more clear report to address this.

I'm glad you like the tool. Thanks!
