### ISSUE TITLE
Parse error in twig stops doc generation

### ISSUE THREAD

**Issue by sdonnet** [phpDocumentor/phpDocumentor#3752]
## Expected behavior
Expecting doc generation, after code was parsed

## Actual behavior

Phar stops to work with error :

PHP Parse error:  syntax error, unexpected token ":" in phar:///usr/local/bin/phpDocumentor/vendor/twig/twig/src/Environment.php(418) : eval()'d code on line 54

## Steps to reproduce the problem

1. Server : Ubuntu 20.04 LTS, PHP 8.4
2. Latest phpDocumentor.phar installed
3. phpdoc.dist.xml, at my web folder root, totally standart
4. cd <web-root>
5. php /usr/local/bin/phpDocumentor.phar -d .

## Your environment

* Version used: **vv3.5.3**
* Install method
* **Download "PHAR"**
* PHP version : **PHP 8.4.0alpha2**
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): **Ubuntu 20.04.6 LTS**
* Link to your project:
* Attach code that is involved
* ...

**Comment by sdonnet** [comment]
Hum, 

Seems relative to php version. I install php 8.3 (8.3.9), instead of 8.4 (alpha!) and phpDocumentor works fine.

**Comment by jaapio** [comment]
We didn't test with php 8.4 yet. Most of our dependencies are not ready yet. So this is too early to test with 8.4
