### ISSUE TITLE
Getting 404 downloading from https://phpdoc.org/phpDocumentor.phar

### ISSUE THREAD

**Issue by jaredhendrickson13** [phpDocumentor/phpDocumentor#3768]
Trying to download the .phar file from phpdoc.org results in a 404.

## Expected behavior

A successful download of the latest .phar.

## Actual behavior

A 404 Not Found error is being returned:

```
% wget https://phpdoc.org/phpDocumentor.phar
--2024-09-14 19:58:24--  https://phpdoc.org/phpDocumentor.phar
Resolving phpdoc.org (phpdoc.org)... 172.67.191.115, 104.21.60.41
Connecting to phpdoc.org (phpdoc.org)|172.67.191.115|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-09-14 19:58:25 ERROR 404: Not Found.
```

## Steps to reproduce the problem

1. Run `wget https://phpdoc.org/phpDocumentor.phar` like stated in the documentation.
2. See the resulting 404 Not Found error.

Alternatively, you can reproduce the 404 in a browser too: https://phpdoc.org/phpDocumentor.phar

## Your environment

* Version used: N/A
* Install method: PHAR
* PHP version: N/A
* Operating system and version: macOS 14.6.1 and Ubuntu Server 22.04
* Link to your project: N/A
* Attach code that is involved: N/A

**Comment by jaapio** [comment]
Thanks for your report, I forgot to add a redirect for the phar files in our new site setup. I did add it again so it should be working as before.

**Comment by jaredhendrickson13** [comment]
Looks like everything's working as expected again. Thanks for the quick response!
