### ISSUE TITLE
Error in base URL

### ISSUE THREAD

**Issue by natanfelles** [phpDocumentor/phpDocumentor#3780]
Hello! I found a problem with the base URL while searching through the documentation.

## Expected behavior

URLs are expected to work in search results.

## Actual behavior

URLs are broken on the `index.html` page search results.

## Steps to reproduce the problem

1. To reproduce the problem, please follow the instructions below:

```
mkdir phpdoc-test
cd phpdoc-test/
git clone git@github.com:aplus-framework/http-client.git .
wget https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.5.3/phpDocumentor.phar
chmod +x phpDocumentor.phar
./phpDocumentor.phar
```

2. Open the file `build/docs/index.html` in the browser.

3. Search by `req`.

4. Move your mouse over the search result links.

5. Note that the links are broken, as in the example below:

`/index.htmlclasses/Framework-HTTP-Client-Request.html`

6. Note that `/index.htmlclasses` are stuck together.

7. The correct thing would be for the link to not have the index.html file, as in the example below:

`/classes/Framework-HTTP-Client-Request.html`

8. I noticed this happens only when we search on the `/index.html` page.

9. My solution is to edit the `layout.html.twig` file like this:

```twig
{% set baseUrl %}{{ renderBaseUrlHeader() }}{% endset %}
{% if baseUrl %}{{ baseUrl }}{% else %}<base href="./">{% endif %}
```

10. I believe that `{{ renderBaseUrlHeader() }}` could already contain the `<base href="./">` snippet by default.

Thank you very much!

## Your environment

* Version used: 3.5.3
* Install method: phar
* PHP version: 8.3
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): Ubuntu 22.04

**Comment by jaapio** [comment]
Thanks for your extensive report. I applied your fix by changing the twig function.
