### ISSUE TITLE
Syntax error when trying to create documentation

### ISSUE THREAD

**Issue by lcsqlpete** [phpDocumentor/phpDocumentor#3822]
I am running phpDocumentor like this:
~/phpDocumentor.phar -f myfile.php

## Expected behavior
Documentation to be created in a subfolder of the directory

## Actual behavior
I get this error message.
PHP Parse error:  syntax error, unexpected 'ClassLoader' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in phar:///Users/Dad/phpDocumentor.phar/src/phpDocumentor/AutoloaderLocator.php on line 29

## Steps to reproduce the problem

1. run the command in Terminal ~/phpDocumentor.phar -f myfile.php

## Your environment
 I don't know the phpDocumentor version since it always fails with this error

I downloaded the PHAR file on 11/18/2024 and installed it in my working directory
 PHP version is 7.2.21
MacOS 10.15.7

**Comment by jaapio** [comment]
Hi, thanks for your issue report. 

phpDocumentor needs php 8.1 or higher to run.
