### ISSUE TITLE
Handling third party code

### ISSUE THREAD

**Issue by robocoder** [phpDocumentor/phpDocumentor#394]
Currently, in my Sf2 project, I have included <directory>../vendor/symfony/src</directory> and  <directory>../vendor/doctrine/lib/Doctrine</directory> in my phpdoc configuration to resolve inherited methods where the parent class (or interface) is defined in a third-party library.  The parse stage is under 3 minutes, but the transformation is closer to 10 minutes.

I would like to propose alternate handling for code identified as third party:
- separate structure.xml (perhaps an attribute on the <directory> element could provide a hint?)
- transformation stage could skip 3rd party code unless the structure.xml has changed or --force is used

Thoughts?

Possibly related issues: #234, #364

**Comment by mvriel** [comment]
Performance should be far better in phpDocumentor 3 with the default template; closing this
