### ISSUE TITLE
Remember List View option

### ISSUE THREAD

**Issue by GaryJones** [phpDocumentor/phpDocumentor#409]
phpDocumentor 2.0.0.a1, Responsive template 1.0.0
Chrome, local filesystem (so no Ajax)

The list view (whether to show descriptions with functions / methods or not) is not persistent across page reloads (at least when there's no Ajax loading of content).

**Comment by mvriel** [comment]
Closing this issue as a no-fix; we have abandoned the complete TOC trees in the sidebar as, for larger projects, it increased rendering time and file size significantly; and in terms of UX did more harm than good
