### ISSUE TITLE
@method tag's function arguments do not accept the use of default parameters 

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#526]
As mentioned here: https://github.com/phpDocumentor/phpDocumentor2/issues/379

The accepted signatures should be improved in `/src/phpDocumentor/Plugin/Core/Parser/DocBlock/Tag/Definition/Method.php` and documented in the @method tag's specific documentation

**Comment by jaapio** [comment]
Needs specification update first.

**Comment by mvriel** [comment]
This functions partially; for some odd reason the default value is only shown when a typehint is added to the magic method's parameter

**Comment by mvriel** [comment]
Specs mention that no support is needed and noone commented on this issue since; I am closing it as a won't fix
