### ISSUE TITLE
Support for enumerated options fro properties and method arguments

### ISSUE THREAD

**Issue by MarkBaker** [phpDocumentor/phpDocumentor#557]
PHPDocumentor doesn't support listing of enumerated values for a property or for a method argument. I suggest that this would be a useful addition to doc blocks;

``` php
/*
 * Object State
 *
 * @var string
 * @options=["open", "closed", "pending"] 
 **/ 
private $_state;
```

``` php
/**
 * Set Object State
 *
 * @param string $plotType
 * @options=["open", "closed", "pending"] 
 **/
public function setPlotType($plotType = '') {
    ...
}
```

While @options might not be the best tag to use, or this syntax could be simplified (and might need modification if the list of options was to be a list of valid constant values), it seems to me that it would be a useful addition to the doc block because the alternative is documenting it in the general block comments. A formal syntax of some description would simplify this and provide a standardised display of the valid options

**Comment by GameCharmer** [comment]
Hello.  It's been a year or so since the last comment.  Are there any plans for incorporating something like this?

**Comment by mikedfunk** [comment]
+1

**Comment by freshfelicio** [comment]
why not combine it with the syntax for union types? You can already use `true` and `false` as type, so why not other scalars values? Examples:

     @return array|false Array on success, false on failure

     @var 'open'|'closed'|'pending' $status

     @return 1|0|-1 One if greater, zero if equal, minus one if smaller

**Comment by vikingmaster** [comment]
Any ideas when this will be implemented?
Java supports enumeration types, XML also supports for validation, we see enumeration every day - it's a part of our lives. Choose an item from dropdown list, use radio inputs - it's all the same.

In PHP frameworks dependency injectors use strings for registering modules, relations are also accessed via strings sometimes. There are so many uses, when a simple raw string is used nowadays as a parameter. It's year 2016, why on earth everything is so limiting, when we are able to create very complex systems?

It's simple as that, in PHPStorm the following scenario would be handy:
1. Type: `$object->do('`
2. A dropdown with options is open, navigate with key arrows:
                         ['create'] @return Model
                   ->   ['save']    @return bool
                         ['delete']  @return bool
3. Press enter and get result: `$object->do('save');`

**Comment by DannyvdSluijs** [comment]
@mvriel I came across this issue on CodeTriage as this issue was almost over 2 years old. And it seems to me that time has proven the issue to be not that desired that anyone in the OSS community started working on it (or any alternatives)

I know there is no native support for enumerations available in PHP (or even planned to be; currently there is an [RFC](https://wiki.php.net/rfc/enum?rev=1480969445) in draft since '15). Alternatively there is the [SPL Enum](http://php.net/manual/en/class.splenum.php) offering a close to native approach.

In addition the examples in the opening post could be upgraded to use objects (implementing a enum type using one of the available [libraries](https://github.com/myclabs/php-enum) ) to avoid having a string type as function parameter. 

Most importantly having an `@options` might look like a solution to the problem but it will not enforce any type checking in the PHP runtime, giving a false sense of code quality, whereas an object oriented approach together with type hinting will. And as a bonus effect it can reduce duplication if the same enumeration is used more than one time.

IMHO the issue can be closed, that said the remark of @felixfbecker [125731809](https://github.com/phpDocumentor/phpDocumentor2/issues/557#issuecomment-125731809) seems like a more natural approach which is still very close to the current @param and @return annotations. Still would not fixes the type checking as opposed of the enum object.

**Comment by jaapio** [comment]
Before closing this issue I want to make @ashnazg aware of this question. If this is not added to the psr-5 standard phpdocumentor will not support this. 

Moving this to our psr-5 project.

**Comment by numediaweb** [comment]
Six years later.. Any progress on this issue?

**Comment by jaapio** [comment]
Asking is answering the question...

**Comment by numediaweb** [comment]
In [PSR-5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#713-param) it is possible to specify elements types for an Array:
```
/**
 * Initializes this class with the given options.
 *
 * @param array $options {
 *     @var bool   $required Whether this element is required
 *     @var string $label    The display name for this element
 * }
 */
public function __construct(array $options = array())
{
    <...>
}
```

**Comment by anurbol** [comment]
PHPDocumentor definitely should support this. PHP apps may become very complex, there are already many things we have to memorize, no need to keep memorizing possible string argument values for tens/hundreds of functions. psr-5 has an abandoned status anyway, so there is no reason to wait for it to be released.

**Comment by jaapio** [comment]
It doesn't our team is preparing to pick up the discussion on psr-5 again.

**Comment by anurbol** [comment]
@jaapio that's a good news! I think many people just gave up on this (desired, but not a critical), but they still hoping for it to be implemented

**Comment by ashnazg** [comment]
I'm very unconvinced on this one.  Making a class be your enumerator object seems to me to be the correct approach, both in code and in documenting things.  This approach is already supported, and has been back into 1.x.

PHP allowing this behavior (without a proper Enum object) is one of its tradeoffs, and I don't think we can make a doc-only construct for every occasion where "I only want to use strings in my code, but I want my docs to look like these are strict typed thingamabobs".

**Comment by anurbol** [comment]
These type of issues are the reason why I have gave up with PHP after 11 years and moved to node.js + Typescript. PHP is moving too slow for 2018

**Comment by gareth-ib** [comment]
wow this is a really long time to not do this feature...
If PHP implemented RFC types this would be built in... but they still haven't decided on a good way to do that, so it would be nice if PHPDoc could at least support the idea.

Some sort of concept that would potentially be forward compatible with RFC types being added to php when the figure it out?

```php
    /**
     * @var objectConstants|\Path\To\ClassHoldingStrings
     */
    public $stringFromConstants;
```

**Comment by gareth-ib** [comment]
yeah I agree there shouldn't be hacks added into phpdoc.. but there must be some sort of concept that can logically solve this concept of needing a param to be a restricted list string, somehow

**Comment by Roy-Orbison** [comment]
So now that it's PSR-19 any chance of something sane being suggested to the FIG by someone who can?

I really like the type addendum style, but with `|` for consistency with other PHPDoc conventions:

```
@param string{'open'|'closed'|'pending'} $plotType
```

**Comment by AmirrezaNasiri** [comment]
Hi guys, any update on this? 🤐

**Comment by JakeQZ** [comment]
> @JakeQZ referenced this issue 2 hours ago
> Psalm #778

The referenced comment is not properly linked by GitHub (from a large PR and not easy to find o/w), the relevant link is https://github.com/MyIntervals/emogrifier/pull/778#discussion_r331766607

**Comment by barbu110** [comment]
Anything on this yet?

**Comment by mvriel** [comment]
@ashnazg is this currently in PSR-5/PSR-19? Does this require action?
