### ISSUE TITLE
New screen showing usage information for @global

### ISSUE THREAD

**Issue by gms8994** [phpDocumentor/phpDocumentor#580]
We're trying to get away from using global's in our code. But we want to make sure that their use is documented first. If we could have a screen that would show us everywhere an @global is used, it would be amazingly helpful.

**Comment by mvriel** [comment]
`@global` is as of yet unsupported by phpDocumentor 2 or 3 (https://github.com/phpDocumentor/phpDocumentor/issues/99); but implementing it has a very low priority. That also means this screen cannot be implemented now. I cannot keep this issue open in good faith; so I am closing it as I do not see this implemented anytime soon
