### ISSUE TITLE
Class Inheritance diagram only takes notice of namespaces, not packages

### ISSUE THREAD

**Issue by PandyLegend** [phpDocumentor/phpDocumentor#588]
As discussed in IRC, the class inheritance diagram at the moment only takes notice of namespaces. It would be useful if it could take notice of packages, subpackages etc. aswell.

**Comment by mvriel** [comment]
I have moved this request to our wishlist project (https://github.com/orgs/phpDocumentor/projects/8) so that it doesn't show up in the issue tracker anymore. Although the request is valid and would be helpful; I do not see this happening anytime soon due to priorities and availability.
