### ISSUE TITLE
reST (Restructured Text) Template

### ISSUE THREAD

**Issue by KingCrunch** [phpDocumentor/phpDocumentor#601]
Would allow to integrate the resulting API directly into the documentation (without "style break" or whatever designers call it). Seems, that many uses readthedocs.org in the meanwhile and I guess they would like it :)

**Comment by kaystrobach** [comment]
@kingcrunch where have you put it?

**Comment by mvriel** [comment]
For phpDocumentor 3.1, we have planned to release the functionality to include handwritten documentation using RestructuredText. The inverse, a template that will render the API Documentation as RestructuredText documents is not planned. 

As such, this issue need not be open for longer
