### ISSUE TITLE
Issues with function arguments passed by reference in the generated structure.xml

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#614]
Hello. I'm using phpDocumentor2 to generate structure.xml and then I'm using the xml to render the api myself using php. I found some issues:

xpath("//function/argument/type") doesn't have a "@by_reference" argument

xpath('//function/docblock/tag[@name="param"]/type') has a "@by_reference" argument but it is always false. In any case this is not the appropriate place to check if the argument is by reference because a "type" is not "by reference", function argument is "by reference" whatever the type.

I haven't checked if by_reference works for the @return tag but again this is not the right place.

Regards,
bobef

**Comment by jaapio** [comment]
structure.xml has been reimplemented. Should be fixed by now.
