### ISSUE TITLE
Issue with @see tags in structure.xml

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#616]
Hi. The problem is if you have see tag like this

<code>
@see http://google.com description
</code>

it will become like this in structure.xml

<code>
&lt;tag name="see" description="\global\http://google.com" refers="\global\http://google.com"&gt;
</code>

1) \global\ is always added. This is wrong even on types, because there is no "\global", the global namespace is called "\"
2) Links are not recognized from types
3) Description is not recognized

Regards,
bobef

**Comment by jaapio** [comment]
We have been rebuilding the structure.xml in v3 this item is solved. And can be closed.
