### ISSUE TITLE
Issue with @deprecated tag in structure.xml

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#617]
I'm not sure this is an issue actually or it is meant to be parsed at another level, but the @deprecated tag is not parsed as described in the docs.

<code>
@deprecated 0.9 something happend
</code>

becomes in structure.xml

<code>
&lt;tag name="deprecated" description="0.9 something happend"&gt;
</code>

The version number is not separated from the description.

Regards,
bobef

**Comment by jaapio** [comment]
We have been rebuilding the structure.xml in v3 this item is solved. And can be closed.
