### ISSUE TITLE
Incomplete doc for writing custom templates

### ISSUE THREAD

**Issue by benkeen** [phpDocumentor/phpDocumentor#688]
The documentation for the "Template Designers" section is incomplete. 

The quick-start guide page explains how to generate a skeleton template to allow customization of the branding, but not how to call the template by the phpdoc command to actually create the doc. Page:
http://www.phpdoc.org/docs/latest/for-template-builders/getting-started/quick-start.html

From following instructions elsewhere, the most likely command seems to be this:

```
phpdoc --template=/path/to/customtemplate/ -d /path/to/php/source/files -t /path/to/generated/content/
```

But I get the following error.

[phpDocumentor\Transformer\Exception]  
The source path does not exist: /path/to/Transformer/../../../data/templates/customtemplate/js  

Would it be possible to add that information to that page? 

Thanks!

**Comment by mvriel** [comment]
With the release of phpDocumentor 3, we have revised the templating system. After this issue has been made a new version of this page was released; we are working on a new one. As this is documented in a project; I am closing this issue
