### ISSUE TITLE
Regex (or wildcards) for @properties and @methods

### ISSUE THREAD

**Issue by pocesar** [phpDocumentor/phpDocumentor#689]
Sometimes it's really useful to have a way to place wildcards in properties, because since `__get` and `__call` are "magic", it's common to use modifiers to existing properties, like `_as_something` like `_as_json`, `_as_array`, `_as_int`. `field_as_array` for example will return an object as an associative array, so in the Docblock, it would be written as 

``` php
/**
 * @property ORM $field_as_(array|json|int)
 */
```

or

``` php
/**
 * @property ORM $*_as_(array|json|int)
 */
```

that works for multiple fields

**Comment by dynasource** [comment]
+1

**Comment by CC007** [comment]
Is there any conclusive spec for wildcard (or regex) @method PHPDoc? As previously stated it is very handy to use for ORM related functions, like the ones from PHPActiveRecord. I have a lot of `Model::find_by_some_column_name` in my code and it would be much neater in the PHPDoc if you didn't have to write them all out.

**Comment by xiaohuilam** [comment]
I think it's time to support it at this age.
