### ISSUE TITLE
Minor PSR Issues

### ISSUE THREAD

**Issue by GaryJones** [phpDocumentor/phpDocumentor#725]
- No mention of `@static` tag (presumed deprecated?)
- (6.1): "In addition to the inherited descriptions and tags as defined in this chapter's root MUST a class or interface inherit the following tags:"  
  should be:  
  In addition to the inherited descriptions and tags as defined in this chapter's root, a class or interface MUST inherit the following tags:
- (7.4): "The format of the description if governed by the"  
  should be:  
  "The format of the description is governed by the"
- (Appendix A): "...same way as the 'static' keyword keyword (not..."  
  should be:  
  "...same way as the 'static' keyword (not..."

**Comment by mvriel** [comment]
Issues related to the PSR should be reported to the FIG mailing list; the current workgroup does not use this issue tracker anymore

**Comment by mvriel** [comment]
@ashnazg is this something you can do something with?

**Comment by ashnazg** [comment]
Those are minor English corrections, that I long ago tackled in the transition of the docs into 5/19.
