### ISSUE TITLE
Do not deprecate @category

### ISSUE THREAD

**Issue by tobiastom** [phpDocumentor/phpDocumentor#758]
I would like to encourage you to keep the `@category` tag and use it inside the default template.

I use the `@package Project \ Sub-section` already, but having at least a second categorization like `@category Controller`, `@category Model` or `@category Import` seems to be an excellent idea to group items by source.

With only the `@package` tag this would not be possible.

**Comment by jcrben** [comment]
@category isn't as semantically clear as @tag to me, as in my mind a thing generally only has one category. Tagging is a common and well-understood feature, so @tag makes sense. Agree with @mrviel.

**Comment by jaapio** [comment]
Looking at the age of this ticket and the number of changes that have affected the way people are writing php today I do not think there is a proper use case for this tag anymore.
