### ISSUE TITLE
Have phpDocumentor fix @param tags in existing code

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#780]
This is a request by @MarkBaker sent in via Twitter: https://twitter.com/Mark_Baker/status/315035003903950848

At the moment phpDocumentor does not support the altering of existing code to improve code quality but this would of course not be impossible given that it has access to the source code and line numbers.

> At this moment in time the phpDocumentor team focuses its efforts on fixing bugs and the generation of documentation, although this feature is wanted we probably do not get around to implementing this functionality within a short timespan. Contributions are of course welcomed and will help with this effort

**Comment by jaapio** [comment]
There are already tools with can do this, and I do not see this happen very soon.
