### ISSUE TITLE
Should project:run be avoiding private scope by default?

### ISSUE THREAD

**Issue by bkuhl** [phpDocumentor/phpDocumentor#782]
I'm working on documentation for the command line parameters for project:run.  There's a parameter called `--parseprivate` which I'm unsure is working correctly.  the impression I get is that private properties and methods are not parsed by default, but including this flag will ensure they get parsed.

In my experience I'm noticing that it appears to always be generating docs for private items whether this flag is there or not.

Is this intended functionality?

**Comment by mvriel** [comment]
This has been resolved since
