### ISSUE TITLE
standard folder for images or other static assets to copy into the doc

### ISSUE THREAD

**Issue by dbu** [phpDocumentor/phpDocumentor#785]
it would be nice to be able to specify a folder that contains static assets (mostly images but maybe downloadable sample files or whatever) that is copied automatically, so that the doc can include images.
much like javadoc does with the `doc-files` folder (maybe make the folder name configurable): http://download.java.net/jdk8/docs/technotes/tools/solaris/javadoc.html#unprocessed

**Comment by mvriel** [comment]
With the release of phpDocumentor 3, we have introduced a `.phpdoc` folder in your project with which you can include your own asset and template files. Unfortunately, we still need to better document this; but the feature exists now
