### ISSUE TITLE
Template Generation: Define source template to extend

### ISSUE THREAD

**Issue by bkuhl** [phpDocumentor/phpDocumentor#788]
Currently the documentation to generate a template reads:

`template:generate [-t|--target="..."] [--name="..."] [-a|--author[="..."]] [--given-version[="..."]] [--force]`

I'm trying to extend the Responsive template only to change what's displayed on the dashboard.  Is there a way to use this command to specify that I would like to extend the "responsive" template.

**Comment by jaapio** [comment]
Command has been removed in v3
