### ISSUE TITLE
Cache folders are being generated in the output folder

### ISSUE THREAD

**Issue by zackkatz** [phpDocumentor/phpDocumentor#890]
Cache folders are being generated in the output folder. This wasn't happening with earlier releases, and I believe it is a bug.

OSX 10.8 Mountain Lion; phpDoc 2.0.0b4

![phpDoc cache folders](https://f.cloud.github.com/assets/870979/681575/0a677d66-d9b5-11e2-914f-6437d48dff4a.png)

**Comment by ValeriiVasyliev** [comment]
My full command 

> phpdoc -d PROJECT_DIR -t DOCS_DIR --ignore "*/dir1/*,*/dir2/*"  --cache-folder CACHE_DIR

use option "--cache-folder CACHE_DIR"
