### ISSUE TITLE
page-level docblocks not appearing in output (procedural code)

### ISSUE THREAD

**Issue by ursbraem** [phpDocumentor/phpDocumentor#910]
I am exploring phpdoc for documenting a rather procedural, non-namespaced project. 

Although I add the @package tag to page-level docblocks, their content (author, description etc) is not visible in the generated documentation. I see no filenames or page-level documentation at all. Just namespaces, packages, classes, methods etc.

Is that intended or not?

There are no errors when generating the documentation. I don't think it's related to #695.

Also, I've noticed that a page like output/packages/inc/file.php.html just lists the one class contained in that file (to which I've assigned the package name file.php). But there are some more free-floating functions in that file, and so I would have expected to see them on the page for that package. But they don't show up there, just on output/packages/default.html

This is not stackoverflow, I know, but I would very much appreciate a few hints, thanks a bunch!

**Comment by p4d** [comment]
Same issue here, trying to display page-level docblocks in a procedural style code..
Even if i place a namespace and comment on it this "first" comment of the page never displays in the resulting HTML..

**Comment by mvriel** [comment]
This issue has been fixed in phpDocumentor 3's nightly build. Unfortunately, this issue was resolved in phpDocumentor 3's internals but missed in the template when we released phpDocumentor 3.0. So the next release (3.0.1 or 3.1) will fix this
