### ISSUE TITLE
@uses and @throws aren't resolving resource names

### ISSUE THREAD

**Issue by slifty** [phpDocumentor/phpDocumentor#920]
Apologies if this isn't proper protocol.

I'm facing an issue with @uses and @throws where the resource is not appearing in the documentation, but the description is.

For example:

This DocBlock:

```
/**
 * Constructs the object and loads data.
 * 
 * This constructor invokes the gatherData and populates the object's instance variables.
 *
 * @uses gatherData() to load in the data associated with this object.
 * @uses load() to populate the data gathered.
 * @param integer $itemId Is the item being loaded.
 */
```

Yields this output:

![example](https://f.cloud.github.com/assets/208884/756950/f730b674-e65a-11e2-820a-a76987f2ea95.png)

Which has no mention of the methods being used.  Just the descriptions provided.

Please note that gatherData() and load() are both methods of the class in question.  I have also tried specifying the class explicitly using ClassName::gatherData() and face the same problem.

I can't figure out if I'm misusing the tool, or if it is an error in the code itself.

Note: I posted this as a StackOverflow question as well (http://stackoverflow.com/questions/17504923/uses-and-throws-arent-resolving-in-phpdocumentor)

**Comment by Erutan409** [comment]
@slifty Were you able to make any headway on this issue?

**Comment by slifty** [comment]
Unfortunately I think I got completely uprooted from the project that was
using the tool; sorry for flaking!

**Comment by Erutan409** [comment]
@slifty No worries.  Thanks for replying back!

**Comment by WesselHof** [comment]
@slifty @mvriel Is there any news on this issue? I love to use phpDocumentor for my projects, but missing the links in uses and used-by a lot. Some info is appreciated.
Thanks!!

**Comment by Ga68** [comment]
Hi all. Following up on this one as it'd be fantastic to see it fixed.

**Comment by mbed67** [comment]
I'm fixing the @see tags currently, but afterwards I will have a look at this issue.

**Comment by filips123** [comment]
@boenrobot @mvriel @mbed67 Is there any update? This issue is over 5 years old! Does this work in phpDoc v3?

**Comment by jaapio** [comment]
Asking here is answering the question. No updates.
It might work already in phpdoc v3 but nobody checked it, and provided feedback here.

**Comment by dsone** [comment]
Doesn't seem to work still. I am no expert in phpDocumentor, but taking this manual for example and current v3: https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.see.pkg.html
Even with those example I do not get any links generated.

Also tried the latest docs: https://docs.phpdoc.org/latest/references/phpdoc/tags/see.html
Even with the full url I do not get a link generated. "Documentation of Foo" is displayed, though.

Full url with _uses_ does work. But using double colon as in https://docs.phpdoc.org/latest/references/phpdoc/tags/uses.html described does not generate a lin but text is displayed.

**Comment by alien999999999** [comment]
I see links in uses for @uses Class::method() <description> ; and they work; but no used-by tag.

{@see Class::property} inlines seem to work, but not in the first line, only in the description.
