### ISSUE TITLE
Incorrect CSS / JS paths

### ISSUE THREAD

**Issue by raphaeltm** [phpDocumentor/phpDocumentor#941]
Using phpDocumentor version 2.0.0b7

I run

```
phpdoc run -d ./ -t ../documentation_directory
```

I browse to the documentation directory.

Everything in the root directory looks fine.

Anything outside of it is just text (no styling, no javascript).

For example, clicking on the "Global()" link under NAMESPACES, sends me to,

```
http://localhost/documentation_directory/namespaces/default.html
```

but upon inspection, the CSS and JavaScript paths still point to

```
js/jquery-1.7.1.min.js
css/template.css
etc...
```

instead of the correct paths (../css/template.css etc...)

**Comment by pitylee** [comment]
So many years past the problem still persists, but I solved with the ugly workaround of running the above command after generation:

`sed -i -e 's@<head>@<head><base href="/docs/">@g' /var/www/html/public/docs/index.html`
