### ISSUE TITLE
Should @method augment inherited methods

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#943]
@cweiske pointed out the following scenario:

Given the code http://p.cweiske.de/49, he wanted to show in FooResponse's DocBlock what the correct return type would be. The best solution we could come up with was to have an @method call augment the inherited definifion.

Research should be done to see whether it is feasable and if so, implement it

**Comment by jaapio** [comment]
Closing as this is just a discussion between maintainers. I didn't see any linked issues so I assume this isn't requested anymore after 11 years./
