### ISSUE TITLE
{@inheritdoc} not working with interfaces

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#949]
In issue #389 the user @rrehbeindoi reported:

```
This issue appears to have come back. The sample class B ends up with a literal "{@inheritdoc}" rather then interface I's documentation.
```

Apparently a regression error has crept in which must be fixed

**Comment by robertmain** [comment]
I'm having this issue just now. I'm trying to implement the `CacheItemInterface` interface from PSR-6. If I use `{@inheritdoc}` it just prints the string literal under the method...
