### ISSUE TITLE
error report shows missing summary for inherited class functions

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor#986]
The error report complains about missing summaries for inherited class functions although the generated documentation does what one would expect:
use the parent class' function docbloc for the child class' function if none can be found there.

Example:

abstract class Foo {
         /**
         \* name of this foo.
     \* @var String
     */
         protected $name;
}
class Bar extends Foo {
         protected $name = "thisfoobar";
}

will generate the same summary and var documentation for both classes.
But the error report still shows errors for all classes that extend Foo like Bar does above.

Showing these in the Error report is not only misleading, but also clutters up the report and makes it harder to find real issues.

**Comment by mvriel** [comment]
Validtion has been removed in phpDocumentor 3 as it was to complex to maintain and with the changing times regarding typehints a lot less relevant. With phpDocumentor we are pivoting, so this issue is closed
