### ISSUE TITLE
Add support for @global

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor#99]
Support should be added for @global as described in http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.global.pkg.html

This is actually a tricky one and the documentation above should perhaps be rewritten to a more business rule-ish form.

**Comment by dregad** [comment]
Hello @mvriel and @toxalot, any news on this issue (no pressure, just asking...) ? Thanks !

**Comment by mvriel** [comment]
Hello @dregad! Unfortunately I have no news. We have been focussing almost all our efforts on phpDocumentor3 and as such have had to reduce the time that we could spare for phpDocumentor 2.

**Comment by mvriel** [comment]
Moved this onto our 'Wishlist' project board as a note so that it would not show up as an issue in our tracker. We are doing this for feature requests we cannot complete in a short timespan and which does not have a high priority to make sure the issue listing reflects work that we want to pick up now.

As for the reason why this was not done yet:

This is not a trivial issue since the Parser we built does not track state; to fix this; we'd need to do open-heart surgery on these parts of phpDocumentor and we do not feel that the time and effort needed for this weigh up.

I apologize if this inconveniences some, we, unfortunately, have to make choices with the small team that we have.

**Comment by dregad** [comment]
OK @mvriel I understand. Anyway as you can imagine, after nearly 6 years I learned to live without this feature, and I must admit kind of gave up all hope of ever seeing this implemented :wink: 

A link to this _'Wishlist' project board_ would be nice, as I'm not quite sure what you're referring to...
